In [80]:
# ============================================================
# Imports
# ============================================================

# Standard library
import os
import re
import copy
import time
import random
import shutil
from pathlib import Path
from collections import Counter, defaultdict

# Data handling
import numpy as np
import pandas as pd
import joblib

# Image handling / visualization
from PIL import Image
import pillow_heif
import matplotlib.pyplot as plt
import seaborn as sns

# Scikit-learn metrics
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
)

# PyTorch
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from torchvision import datasets, models
import torchvision.transforms.v2 as v2
from torch.utils.data import (
    DataLoader,
    Subset,
    ConcatDataset,
)

# Environment configuration
from dotenv import load_dotenv


# Enable HEIF/HEIC/AVIF image support
pillow_heif.register_heif_opener()

print("=== Environment Info ===")
print(f"OS: {os.name}")
print(f"Python version: {os.sys.version}")
print(f"PyTorch version: {torch.__version__}")
print(f"Torchvision version: {torchvision.__version__}")
print(f"Numpy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")
print(f"Matplotlib version: {plt.matplotlib.__version__}")
print(f"Seaborn version: {sns.__version__}")

if torch.backends.mps.is_available():
    print("Apple GPU (MPS) available: Yes")
else:
    print("Apple GPU (MPS) available: No")

=== Environment Info ===
OS: posix
Python version: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ]
PyTorch version: 2.5.1
Torchvision version: 0.20.1
Numpy version: 1.26.4
Pandas version: 2.2.2
Matplotlib version: 3.9.2
Seaborn version: 0.13.2
Apple GPU (MPS) available: Yes

In [4]:
# ============================================================
# Project / Dataset Paths
# ============================================================

from dotenv import load_dotenv

# Permanent private configuration
CONFIG_FILE = Path.home() / ".wadidegla.env"

if not CONFIG_FILE.exists():
    raise FileNotFoundError(
        "Local WadiDegla configuration file was not found."
    )

load_dotenv(CONFIG_FILE)

# Wadi Degla dataset
DATA_DIR = Path(os.environ["WADIDEGLA_DATA_DIR"])
TRAIN_DIR = DATA_DIR / "Train"
VAL_DIR = DATA_DIR / "Validation"

# External web dataset
WEB_DATA_DIR = Path(os.environ["WEB_DATA_DIR"])

# Experimental workspace
WORKSPACE_DIR = Path(os.environ["WADIDEGLA_WORKSPACE_DIR"])


if not DATA_DIR.exists():
    raise FileNotFoundError(
        "The configured WadiDegla dataset directory does not exist."
    )

if not WEB_DATA_DIR.exists():
    raise FileNotFoundError(
        "The configured external web dataset directory does not exist."
    )

if not WORKSPACE_DIR.exists():
    raise FileNotFoundError(
        "The configured WadiDegla experimental workspace directory does not exist."
    )

print("WadiDegla dataset configuration loaded successfully.")
print("External web dataset configuration loaded successfully.")
print("WadiDegla experimental workspace configuration loaded successfully.")

WadiDegla dataset configuration loaded successfully.
External web dataset configuration loaded successfully.
WadiDegla experimental workspace configuration loaded successfully.

# <center>**Utility Functions for Model Training & Evaluation**</center>

## **1. Compute Class Weights**

In [5]:
def compute_class_weights(dataset, method="inverse_frequency", normalize=False):
    """
    Compute class weights based on the chosen method, with optional normalization.

    Args:
        dataset: A dataset object with a 'targets' attribute containing class labels.
        method (str): Method for computing class weights. Options:
            - "inverse_frequency": total_samples / count
            - "balanced": total_samples / (count * num_classes)
            - "sqrt_inverse": 1 / np.sqrt(count)
            - "scaled_sqrt_inverse": (1 / np.sqrt(count)) * 100
        normalize (bool): If True, rescale weights so that their mean = 1.

    Returns:
        torch.Tensor: Class weights tensor on the appropriate device.
    """
    # Compute class frequencies
    class_counts = Counter(dataset.targets)
    total_samples = sum(class_counts.values())
    num_classes = len(class_counts)

    # Select weight calculation method
    if method == "inverse_frequency":
        class_weights = {cls: total_samples / count for cls, count in class_counts.items()}
    elif method == "balanced":
        class_weights = {cls: total_samples / (count * num_classes) for cls, count in class_counts.items()}
    elif method == "sqrt_inverse":
        class_weights = {cls: 1 / np.sqrt(count) for cls, count in class_counts.items()}
    elif method == "scaled_sqrt_inverse":
        class_weights = {cls: (1 / np.sqrt(count)) * 100 for cls, count in class_counts.items()}
    else:
        raise ValueError("Invalid method. Choose from 'inverse_frequency', 'balanced', 'sqrt_inverse', 'scaled_sqrt_inverse'.")

    # Convert to tensor
    class_weights_tensor = torch.tensor([class_weights[i] for i in range(num_classes)], dtype=torch.float32)

    #  Normalize weights to have an average of 1.0 → divide by mean 
    if normalize:
        class_weights_tensor = class_weights_tensor / class_weights_tensor.mean()

    # Move weights to MPS (Apple GPU) if available
    device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
    return class_weights_tensor.to(device)

## **2. Candidate Models Configuration**

### **1. mobilenet_v2**

In [8]:
def summarize_mobilenetv2_blocks(model: nn.Module):
    """
    Summarize blocks in a MobileNetV2 model.
    
    Returns:
        pd.DataFrame: block-level summary with counts, percentages, and cumulative stats.
    """

    # ---- Collect blocks: features + classifier ----
    blocks = []
    if hasattr(model, "features"):
        for i, block in enumerate(model.features):
            blocks.append((f"{block.__class__.__name__}_{i+1}", block, "features"))
    if hasattr(model, "classifier"):
        blocks.append((f"{model.classifier.__class__.__name__}", model.classifier, "classifier"))

    # ---- Helper functions ----
    def count_layers(module: nn.Module):
        # Count atomic submodules (ignore containers)
        return sum(1 for m in module.modules() if not isinstance(m, nn.Sequential))

    def count_params(module: nn.Module):
        return sum(p.numel() for p in module.parameters())

    def count_trainable_params(module: nn.Module):
        return sum(p.numel() for p in module.parameters() if p.requires_grad)

    # ---- Build dataframe rows ----
    rows = []
    for order, (name, block, module_name) in enumerate(blocks, 1):
        n_layers = count_layers(block)
        n_params = count_params(block)
        n_trainable = count_trainable_params(block)
        rows.append({
            "Block": name,
            "Order": order,
            "Module": module_name,
            "Layers (#)": n_layers,
            "Params (#)": n_params,
            "Trainable Params (#)": n_trainable,
        })

    df = pd.DataFrame(rows)

    # ---- Totals for whole model ----
    total_layers_model = df["Layers (#)"].sum()
    total_params_model = df["Params (#)"].sum()
    total_trainable_params_model = df["Trainable Params (#)"].sum()

    # Per-model percentages
    df["% Layers (Model)"] = df["Layers (#)"] / total_layers_model * 100
    df["% Params (Model)"] = df["Params (#)"] / total_params_model * 100
    df["% Trainable Params (Model)"] = df["Trainable Params (#)"] / total_params_model * 100

    # Accumulative (start from deepest → reverse order)
    df["Cumulative Layers (Model)"] = df["Layers (#)"][::-1].cumsum()[::-1]
    df["Cumulative % Layers (Model)"] = df["Cumulative Layers (Model)"] / total_layers_model * 100
    df["Cumulative Params (Model)"] = df["Params (#)"][::-1].cumsum()[::-1]
    df["Cumulative % Params (Model)"] = df["Cumulative Params (Model)"] / total_params_model * 100
    # ---- Per-module stats ----
    module_stats = []
    for module_name in df["Module"].unique():
        sub = df[df["Module"] == module_name]
        total_layers_mod = sub["Layers (#)"].sum()
        total_params_mod = sub["Params (#)"].sum()
        total_trainable_mod = sub["Trainable Params (#)"].sum()
        for idx in sub.index:
            module_stats.append({
                "Layers (Module %)": df.loc[idx, "Layers (#)"] / total_layers_mod * 100,
                "Params (Module %)": df.loc[idx, "Params (#)"] / total_params_mod * 100,
                "Trainable Params (Module %)": df.loc[idx, "Trainable Params (#)"] / total_trainable_mod * 100 if total_trainable_mod > 0 else 0,
                "Cumulative Layers (Module)": sub["Layers (#)"][::-1].cumsum()[::-1].loc[idx],
                "Cumulative % Layers (Module)": sub["Layers (#)"][::-1].cumsum()[::-1].loc[idx] / total_layers_mod * 100,
                "Cumulative Params (Module)": sub["Params (#)"][::-1].cumsum()[::-1].loc[idx],
                "Cumulative % Params (Module)": sub["Params (#)"][::-1].cumsum()[::-1].loc[idx] / total_params_mod * 100,
            })
    module_df = pd.DataFrame(module_stats, index=df.index)

    # Combine
    df = pd.concat([df, module_df], axis=1)

    return df

## 3. Model Training

In [9]:
def train_model(model, train_loader, criterion, optimizer, class_names, epoch_num=1, log_interval=100):
    start_time = time.time()  # Start tracking time
    device = torch.device("cuda" if torch.cuda.is_available() else "mps")  # Use GPU if available on Mac

    # Dictionary to store per-class metrics
    class_metrics = defaultdict(lambda: {"correct": 0, "total": 0, "y_true": [], "y_pred": []})

    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    epoch_start_time = time.time()  # Track epoch time

    for batch_idx, (images, labels) in enumerate(train_loader, 1):  # Start index from 1
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        # Compute accuracy
        _, predicted = outputs.max(1)
        correct += (predicted == labels).sum().item()
        total += labels.size(0)
        accuracy = 100 * correct / total

        # Store predictions for per-class metrics
        for label, pred in zip(labels.cpu().numpy(), predicted.cpu().numpy()):
            class_metrics[label]["correct"] += (label == pred)
            class_metrics[label]["total"] += 1
            class_metrics[label]["y_true"].append(label)
            class_metrics[label]["y_pred"].append(pred)

        # Print loss and accuracy every 100 batches
        if batch_idx % log_interval == 0:
            elapsed_time = (time.time() - start_time)/60
            print(f"Epoch {epoch_num}, Batch {batch_idx}, Loss: {running_loss/batch_idx:.4f}, "
                  f"Accuracy: {accuracy:.2f}%, Time Passed: {elapsed_time:.2f}m")

    epoch_time = (time.time() - epoch_start_time)/60
    print(f"Epoch {epoch_num} Completed - Average Loss: {running_loss/len(train_loader):.4f}, "
          f"Accuracy: {accuracy:.2f}%, Epoch Time: {epoch_time:.2f}m")
    overall_accuracy = 100 * correct / total

    total_time = (time.time() - start_time)/60
    print(f"Training Complete Epoch {epoch_num} - Total Time: {total_time:.2f}m")

    # Calculate per-class accuracy, precision, recall, and F1-score
    all_y_true = []
    all_y_pred = []
    
    for class_idx in sorted(class_metrics.keys()):
        all_y_true.extend(class_metrics[class_idx]["y_true"])
        all_y_pred.extend(class_metrics[class_idx]["y_pred"])
    
    # Compute per-class precision, recall, and F1-score
    unique_classes = sorted(set(all_y_true))  # Get all unique classes
    per_class_metrics = {
        "precision": precision_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0),
        "recall": recall_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0),
        "f1_score": f1_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0)
    }

    # Store per-class results in alignment with unique_classes
    class_results = []
    for class_idx in unique_classes:
        class_results.append([
            class_names[class_idx],
            per_class_metrics["precision"][unique_classes.index(class_idx)]*100,
            per_class_metrics["recall"][unique_classes.index(class_idx)]*100,
            per_class_metrics["f1_score"][unique_classes.index(class_idx)]*100
        ])

    # Create a DataFrame with per-class accuracy, precision, recall, and F1-score
    df_results = pd.DataFrame(class_results, columns=["Species", "Precision", "Recall", "F1-score"])

    # Append overall metrics (Macro) as the last row
    macro_precision = per_class_metrics["precision"].mean()*100
    macro_recall = per_class_metrics["recall"].mean()*100
    macro_f1 = per_class_metrics["f1_score"].mean()*100

    df_results.loc[len(df_results)] = ["Average Performance (Macro)", macro_precision, macro_recall, macro_f1]

    df_results['Epoch'] = epoch_num
    avg_loss = running_loss / len(train_loader)

    return {
    'model': model,
    'optimizer': optimizer,
    'metrics_df': df_results,
    'overall_accuracy': overall_accuracy,
    'total_loss': running_loss,
    'avg_loss': avg_loss,
    'epoch_time': epoch_time
            }

## 4. Model Evaluation

In [10]:
def evaluate_model(model, val_loader, criterion, class_names, epoch_num=1, log_interval=100):
    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "mps")
    
    start_time = time.time()  # Track evaluation time

    # Dictionary to store per-class metrics
    class_metrics = defaultdict(lambda: {"correct": 0, "total": 0, "y_true": [], "y_pred": []})
    all_y_true = []
    all_y_pred = []
    correct = 0
    total = 0
    running_loss = 0.0

    with torch.no_grad():
        for batch_idx, (images, labels) in enumerate(val_loader, 1):  # Start index from 1
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)

            # Compute loss
            loss = criterion(outputs, labels)
            running_loss += loss.item()
            
            _, preds = torch.max(outputs, 1)

            all_y_true.extend(labels.cpu().numpy())
            all_y_pred.extend(preds.cpu().numpy())

            # Compute accuracy
            correct += (preds == labels).sum().item()
            total += labels.size(0)
            accuracy = 100 * correct / total

            # Store per-class metrics
            for label, pred in zip(labels.cpu().numpy(), preds.cpu().numpy()):
                class_metrics[label]["correct"] += (label == pred)
                class_metrics[label]["total"] += 1
                class_metrics[label]["y_true"].append(label)
                class_metrics[label]["y_pred"].append(pred)

            # Print progress every 100 batches
            if batch_idx % log_interval == 0:
                elapsed_time = (time.time() - start_time)/60
                avg_loss = running_loss / batch_idx
                print(f"Batch {batch_idx}, Loss: {avg_loss:.4f}, "
                      f"Accuracy: {accuracy:.2f}%, Time Passed: {elapsed_time:.2f}m")

    total_time = (time.time() - start_time)/60
    avg_loss = running_loss / len(val_loader)
    print(f"Evaluation Complete - Loss: {avg_loss:.4f}, Accuracy: {accuracy:.2f}%, Total Time: {total_time:.2f}m")
    overall_accuracy = 100 * correct / total

    # Compute per-class accuracy
    class_results = []
    for class_idx in sorted(class_metrics.keys()):
        metrics = class_metrics[class_idx]
        class_results.append([class_names[class_idx]])

    # Compute per-class precision, recall, and F1-score
    unique_classes = sorted(set(all_y_true))  # Get all unique classes
    per_class_metrics = {
        "precision": precision_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0),
        "recall": recall_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0),
        "f1_score": f1_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0)
    }

    # Store per-class metrics
    for idx, class_label in enumerate(unique_classes):
        class_results[idx].extend([
            per_class_metrics["precision"][idx],
            per_class_metrics["recall"][idx],
            per_class_metrics["f1_score"][idx]
        ])

    # Create a DataFrame with per-class accuracy, precision, recall, and F1-score
    df_results = pd.DataFrame(class_results, columns=["Species", "Precision", "Recall", "F1-score"])

    # Append overall metrics (Macro) as the last row
    macro_precision = per_class_metrics["precision"].mean()
    macro_recall = per_class_metrics["recall"].mean()
    macro_f1 = per_class_metrics["f1_score"].mean()

    df_results.loc[len(df_results)] = ["Average Performance (Macro)", macro_precision, macro_recall, macro_f1]

    df_results['Epoch'] = epoch_num
    return {
    'metrics_df': df_results,
    'overall_accuracy': overall_accuracy,
    'avg_loss': avg_loss,
    'epoch_time': total_time
            }

## 5. Create performance summary

> **Legacy terminology note:** The column name `Train & Test` is retained from the historical implementation. In Phase 2, the relevant WadiDegla subset is the **validation set**, not an independent test set.

In [11]:
def create_performance_summary(df, micro_accuracy, avg_loss, model_name, train_val, class_weights, time_taken, epoch):
    # Extract macro metrics from the last row
    
    macro_row = df[df['Species'] == 'Average Performance (Macro)']
    precision_macro = macro_row['Precision'].values[0]
    recall_macro = macro_row['Recall'].values[0]
    f1_macro = macro_row['F1-score'].values[0]


    # Exclude the last row to analyze per-class accuracies
    class_accuracies = df[df['Species'] != 'Average Performance (Macro)'].copy()

    # Identify best and worst class based on accuracy
    best_class = class_accuracies.loc[class_accuracies['F1-score'].idxmax(), 'Species']
    worst_class = class_accuracies.loc[class_accuracies['F1-score'].idxmin(), 'Species']

    # Compute the median accuracy and find the nearest class
    median_f1_macro = class_accuracies['F1-score'].median()
    class_accuracies['Abs_Diff'] = (class_accuracies['F1-score'] - median_f1_macro).abs()
    median_class = class_accuracies.loc[class_accuracies['Abs_Diff'].idxmin(), 'Species']

    # Compute the number of classes above micro and macro accuracy averages
    num_classes_above_f1_macro_avg = (class_accuracies['F1-score'] > f1_macro).sum()
    num_classes_above_f1_macro_median = (class_accuracies['F1-score'] > median_f1_macro).sum()

    # Create the final summary DataFrame
    performance_summary = pd.DataFrame({
        "Model": [model_name],
        "Train & Test": [train_val],
        "Accuracy (micro)": [micro_accuracy],
        "Precision (macro)": [precision_macro],
        "Recall (macro)": [recall_macro],
        "F1 (macro)": [f1_macro],
        "Loss": [avg_loss],
        "Class_weights": [class_weights],
        "Best_class": [best_class],
        "Median_class": [median_class],
        "Worst_class": [worst_class],
        "num_classes_above_f1_macro_avg": [num_classes_above_f1_macro_avg],
        "num_classes_above_f1_macro_median": [num_classes_above_f1_macro_median],
        "Time Taken (mins)": [time_taken],
        "Epoch": [epoch]
    })


    return performance_summary

## 6. Model Training & Evaluation Loop

In [12]:
def train_and_evaluate_model(
    model: nn.Module,
    train_loader,
    val_loader,
    criterion,
    optimizer,
    class_names,
    start_epoch: int,
    end_epoch: int,
    model_name: str,
    save_dir: str,
    class_weights: str,
    log_interval: int,
    evaluate = True
):
    """
    Train and evaluate a model, storing per-epoch metrics, summaries, and states.

    Returns:
        dict: {
            'epoch_states': {epoch_num: {'model_state': ..., 'optimizer_state': ..., 'train_metrics': ..., 'val_metrics': ...}},
            'train_results_df': pd.DataFrame,
            'train_summary_df': pd.DataFrame,
            'val_results_df': pd.DataFrame,
            'val_summary_df': pd.DataFrame
        }
    """
    device = torch.device("mps")
    model.to(device)  # Move model to MPS

    # Initialize storage
    epoch_states = {}
    train_results_list, train_summary_list = [], []
    val_results_list, val_summary_list = [], []


    for epoch in range(start_epoch, end_epoch + 1):
        print(f"\n🚀 Epoch {epoch} - Training Started...\n")
        
        # ---- Training ----
        training_result = train_model(
            model, train_loader, criterion, optimizer, class_names, epoch_num=epoch, log_interval=log_interval
        )
        train_summary = create_performance_summary(
            training_result['metrics_df'],
            training_result['overall_accuracy'],
            training_result['avg_loss'],
            model_name=model_name,
            train_val='Train',
            class_weights=class_weights,
            time_taken=training_result['epoch_time'],
            epoch = epoch
        )
        
        train_results_list.append(training_result['metrics_df'])
        train_summary_list.append(train_summary)
        if evaluate:

            print(f"\n✅ Epoch {epoch} - Training Completed. Starting Evaluation...\n")
    
            # ---- Validation ----
            val_result = evaluate_model(
                model, val_loader, criterion, class_names, epoch_num=epoch, log_interval=log_interval
            )
            val_summary = create_performance_summary(
                val_result['metrics_df'],
                val_result['overall_accuracy'],
                val_result['avg_loss'],
                model_name=model_name,
                train_val='Validation',
                class_weights=class_weights,
                time_taken=val_result['epoch_time'],
                epoch = epoch
            )
    
            val_results_list.append(val_result['metrics_df'])
            val_summary_list.append(val_summary)
            print(f"\n📊 Epoch {epoch} - Evaluation Completed.\n")

        else:
            print(f"\n✅ Epoch {epoch} - Training Completed (No Evaluation).\n")

        # ---- Save model + optimizer state for this epoch ----
        epoch_states[epoch] = {
            'model_state_dict': copy.deepcopy(model.state_dict()),
            'optimizer_state_dict': copy.deepcopy(optimizer.state_dict())
        }

        

    # ---- Combine DataFrames ----
    train_results_df = pd.concat(train_results_list, ignore_index=True)
    train_summary_df = pd.concat(train_summary_list, ignore_index=True)
    if evaluate:
        val_results_df = pd.concat(val_results_list, ignore_index=True)
        val_summary_df = pd.concat(val_summary_list, ignore_index=True)

    else:
        val_results_df, val_summary_df = None, None

    # Optionally save to CSV (you can remove if not needed)
    train_results_df.to_csv(f"{save_dir}/{model_name}_train_results{start_epoch}_{end_epoch}.csv", index=False)
    train_summary_df.to_csv(f"{save_dir}/{model_name}_train_summary{start_epoch}_{end_epoch}.csv", index=False)
    if evaluate:
        val_results_df.to_csv(f"{save_dir}/{model_name}_val_results{start_epoch}_{end_epoch}.csv", index=False)
        val_summary_df.to_csv(f"{save_dir}/{model_name}_val_summary{start_epoch}_{end_epoch}.csv", index=False)

    return epoch_states, {
        'train_results_df': train_results_df,
        'train_summary_df': train_summary_df,
        'val_results_df': val_results_df,
        'val_summary_df': val_summary_df
    }

## **7. Testing Model Generalization on Web Images from data dir or data loader**

> **Terminology note:** In this notebook, references to "testing" on web images denote external web evaluation during model development. The web data do not constitute an independent test set.

In [13]:
def evaluate_models_on_directory(models_dict, data_dir, class_names,
                                 display_images=False, particular_model=None, Minimum=None):
    """
    Evaluate multiple models on a directory of plant images organized by class subfolders.
    Each class folder may contain multiple subfolders (e.g., collection dates).

    Args:
        models_dict (dict): {model_name: model}
        data_dir (str): path to directory with subdirs (each subdir = class, contains subsubdirs of images)
        class_names (list): list of class names
        display_images (bool): whether to display predictions with matplotlib
        particular_model (str, optional): evaluate only this specific model name
        Minimum (int, optional): skip models with epoch number < Minimum

    Returns:
        results_df (pd.DataFrame): predictions per image
        metrics_df (pd.DataFrame): per-class precision, recall, f1 for each model
    """

    # Transform (same as validation)
    transform = v2.Compose([
        v2.ToImage(),
        v2.Resize(256),
        v2.CenterCrop(224),
        v2.ToDtype(torch.float32, scale=True),
        v2.Normalize(mean=[0.485, 0.456, 0.406],
                     std=[0.229, 0.224, 0.225])
    ])

    # Storage for all results
    records = []
    metrics_df = pd.DataFrame(columns=["model_name", "plant_species", "precision", "recall", "f1_score"])

    # Iterate over models
    for model_name, model in models_dict.items():
        if particular_model and model_name != particular_model:
            continue

        # Historical optional argument:
        # `Minimum` was retained from an earlier implementation but was not used in the
        # reported Phase 2 workflow. Therefore, the results reported in this study do
        # not depend on the epoch-filtering logic associated with this argument.

        if Minimum and int(model_name[6:8]) < Minimum:
            continue

        device = torch.device("cuda" if torch.cuda.is_available() else "mps")
        model.to(device)
        model.eval()

        all_y_true = []
        all_y_pred = []

        # Walk through dataset
        for class_folder in os.listdir(data_dir):
            class_path = os.path.join(data_dir, class_folder)
            if not os.path.isdir(class_path):
                continue

            # Walk through subfolders inside each class folder
            for root, _, files in os.walk(class_path):
                for img_file in files:
                    if not img_file.lower().endswith(('.png', '.jpg', '.jpeg', '.avif')):
                        continue

                    img_path = os.path.join(root, img_file)

                    # Load and preprocess image
                    image = Image.open(img_path).convert("RGB")
                    input_tensor = transform(image).unsqueeze(0).to(device)

                    # Predict
                    with torch.no_grad():
                        output = model(input_tensor)
                    probs = torch.nn.functional.softmax(output[0], dim=0)
                    confidence, pred_idx = torch.max(probs, 0)

                    predicted_class = class_names[pred_idx.item()]
                    actual_class = class_folder  # main folder name = true label
                    confidence_value = confidence.item() * 100

                    # 🔹 Confidence for the true (actual) class:
                    actual_idx = class_names.index(actual_class)
                    true_confidence_value = probs[actual_idx].item() * 100
                    
                    # Save record
                    records.append({
                        "model_name": model_name,
                        "image_path": img_path,
                        "actual_plant": actual_class,
                        "predicted_plant": predicted_class,
                        "confidence_predicted": confidence_value,
                        "confidence_actual": true_confidence_value
                    })

                    all_y_true.append(class_names.index(actual_class))
                    all_y_pred.append(pred_idx.item())

                    # Optional display
                    if display_images:
                        plt.figure(figsize=(6, 5))
                        plt.imshow(np.array(image))
                        plt.title(f"Actual: {actual_class}\nPredicted: {predicted_class} "
                                  f"({confidence_value:.2f}%)\nEpoch num: {model_name[-2:]}")
                        plt.axis("off")
                        plt.show()

        # Compute per-class metrics
        unique_classes = sorted(set(all_y_true))
        precisions = precision_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0)
        recalls = recall_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0)
        f1s = f1_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0)

        metrics_data = []
        for i, class_idx in enumerate(unique_classes):
            metrics_data.append([
                model_name,
                class_names[class_idx],
                precisions[i],
                recalls[i],
                f1s[i]
            ])

        # Add macro averages
        metrics_data.append([
            model_name,
            "Average Performance (Macro)",
            precisions.mean(),
            recalls.mean(),
            f1s.mean()
        ])

        # Merge metrics
        metrics_df = pd.concat([metrics_df,
                                pd.DataFrame(metrics_data,
                                             columns=["model_name", "plant_species", "precision", "recall", "f1_score"])],
                               ignore_index=True)

    # Final DataFrame for predictions
    results_df = pd.DataFrame(records)

    return results_df, metrics_df

In [16]:
# --- Step 1: Count how many models classified each image correctly ---
def compute_correct_counts(df):
    """
    Compute how many models classified each image correctly,
    total number of models, and the correct ratio.
    """
    correct_counts = (
        df.assign(correct=df['actual_plant'] == df['predicted_plant'])
        .groupby('image_path')['correct']
        .sum()
        .rename('times_correctly_classified')
        .reset_index()
    )

    total_models = df['model_name'].nunique()
    correct_counts['total_models'] = total_models
    correct_counts['correct_ratio'] = correct_counts['times_correctly_classified'] / total_models

    return correct_counts


# --- Step 2: Compute within-model grades ---
def compute_within_model_grades(df):
    df['within_model_grade'] = df.groupby(['model_name', 'actual_plant'])['confidence_actual'] \
                                 .rank(method='dense', ascending=False)
    return df

# --- Step 3: Compute across-model grades ---
def compute_across_model_grades(df):
    mean_conf = df.groupby(['image_path', 'actual_plant'])['confidence_actual'].mean().reset_index()
    mean_conf.rename(columns={'confidence_actual': 'mean_confidence_actual'}, inplace=True)
    mean_conf['across_models_grade'] = mean_conf.groupby('actual_plant')['mean_confidence_actual'] \
                                                .rank(method='dense', ascending=False)
    return df.merge(mean_conf, on=['image_path', 'actual_plant'], how='left')



def assign_percentile(x):
    """
    Assign percentile rank category like 'Top 10%', 'Top 20%', ..., 'Top 100%'.
    Lower percentile number = higher confidence.
    """
    percentile = x.rank(pct=True, ascending=False)
    bins = np.linspace(0, 1, 11)
    labels = [f"Top {int(i*10)}%" for i in range(1, 11)]  # ascending order now
    return pd.cut(percentile, bins=bins, labels=labels, include_lowest=True, right=True)

# --- Step 5: Apply percentile rankings (only for misclassified images) ---
def compute_percentiles(df):
    """
    Compute percentile ranks (within misclassified images only)
    and create a summary column showing both the percentile category
    and how many times each image was correctly classified.
    """
    df = df.copy()

    # Filter misclassified subset (never correctly classified by any model)
    misclassified = df[df['times_correctly_classified'] == 0].copy()

    if misclassified.empty:
        print("✅ No misclassified images (times_correctly_classified == 0) found — skipping percentiles.")
        df['percentile_within_model'] = np.nan
        df['percentile_across_models'] = np.nan
        df['classification_summary'] = (
            "Correctly classified "
            + df['times_correctly_classified'].astype(str)
            + " time(s)"
        )
        return df

    # Compute percentiles within misclassified subset only
    misclassified['percentile_within_model'] = misclassified.groupby(['model_name', 'actual_plant'])['confidence_actual'] \
        .transform(assign_percentile)

    misclassified['percentile_across_models'] = misclassified.groupby('actual_plant')['mean_confidence_actual'] \
        .transform(assign_percentile)

    # Merge back so only misclassified rows have percentiles
    df = df.merge(
        misclassified[['image_path', 'model_name', 'percentile_within_model', 'percentile_across_models']],
        on=['image_path', 'model_name'],
        how='left',
        suffixes=('', '_misclassified')
    )

    # --- New combined summary column ---
    df['classification_summary'] = np.where(
        df['times_correctly_classified'] == 0,
        "Misclassified - Across: " + df['percentile_across_models'].astype(str),
        "Correctly classified " + df['times_correctly_classified'].astype(str) + " time(s)"
    )

    return df




def grade_confidences(results_df):
    """
    Modular pipeline to grade results_df images based on confidence_actual within and across models,
    assign percentile ranks, and record how many models classified each image correctly.

    Adds:
        - within_model_grade
        - across_models_grade
        - mean_confidence_actual
        - percentile_within_model
        - percentile_across_models
        - times_correctly_classified
        - total_models
        - correct_ratio
        - percentile_within_misclassified
    """

    # Step 1 — Compute how many times each image is correctly classified across models
    correct_counts = compute_correct_counts(results_df)
    results_df = results_df.merge(correct_counts, on='image_path', how='left')

    # Step 2 — Compute within-model grading (based on confidence_actual, etc.)
    results_df = compute_within_model_grades(results_df)

    # Step 3 — Compute across-model grading
    results_df = compute_across_model_grades(results_df)

    # Step 4 — Compute percentiles across all data (within and across models)
    results_df = compute_percentiles(results_df)
    
    return results_df

In [17]:
def organize_images_by_performance_group(
    results_df,
    base_output_dir,
    summary_column='classification_summary',
    copy=True
):
    """
    Organize images into 4 main performance-based groups:
        correctly_classified/
        top_30_misclassified/
        mid_30_70_misclassified/
        lowest_30_misclassified/

    Each group contains:
        ClassName / classification_summary / source_name / image.jpg

    Args:
        results_df (pd.DataFrame): Must include ['image_path', 'actual_plant', summary_column]
        base_output_dir (str): Root output directory
        summary_column (str): Column containing summary text (e.g., "Top 10%", "Correctly classified 2 time(s)")
        copy (bool): If True, copy images; if False, move them
    """

    assert summary_column in results_df.columns, f"Column '{summary_column}' not found."

    def categorize(summary_value):
        """Categorize based on classification summary text."""
        text = str(summary_value).lower()
        if "correctly" in text:
            return "correctly_classified"
        match = re.search(r"top\s*(\d+)", text)
        if match:
            rank = int(match.group(1))
            if rank <= 30:
                return "top_30_misclassified"
            elif 30 < rank <= 70:
                return "mid_30_70_misclassified"
            else:
                return "lowest_30_misclassified"
        # fallback if not recognized
        return "unclassified"

    for _, row in results_df.iterrows():
        src_path = row["image_path"]
        class_name = str(row["actual_plant"])
        summary_value = str(row[summary_column])

        if not os.path.exists(src_path):
            print(f"⚠️ Missing file: {src_path}")
            continue

        # Determine category (main folder)
        category = categorize(summary_value)

        # Clean up summary folder name (avoid illegal chars)
        safe_summary = summary_value.replace("/", "-").replace(":", "").replace("*", "-").replace("?", "")
        source_name = os.path.basename(os.path.dirname(src_path))

        # Build final destination path
        dest_dir = os.path.join(base_output_dir, category, class_name, safe_summary, source_name)
        os.makedirs(dest_dir, exist_ok=True)
        dest_path = os.path.join(dest_dir, os.path.basename(src_path))

        try:
            if copy:
                shutil.copy2(src_path, dest_path)
            else:
                shutil.move(src_path, dest_path)
        except Exception as e:
            print(f"❌ Error handling {src_path}: {e}")

    print(f"✅ Images organized into performance groups under: {base_output_dir.name}")

In [21]:
def set_seed(seed: int, deterministic: bool = True):
    """
    Initialize all RNG seeds for reproducibility on Apple Silicon M1.
    Optimized for MPS backend.

    Returns:
        start_rng_state (dict): RNG states captured immediately after seeding.
        generator (torch.Generator): Torch generator initialized with the same seed.
    """
    os.environ['PYTHONHASHSEED'] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.backends.mps.is_available():
        torch.mps.manual_seed(seed)
    if deterministic:
        torch.use_deterministic_algorithms(True)

    generator = torch.Generator()
    generator.manual_seed(seed)

    rng_state = {
        'seed': seed,
        'rng_python': random.getstate(),
        'rng_numpy': np.random.get_state(),
        'rng_torch': torch.get_rng_state(),
        'rng_torch_mps': torch.mps.get_rng_state() if torch.backends.mps.is_available() else None,
        'deterministic': deterministic,
        'generator_state': generator.get_state()
    }
    print(f"✅ Random seed set to {seed} (MPS available: {torch.backends.mps.is_available()})")
    return rng_state, generator

In [22]:
def get_rng_state(seed: int, generator: torch.Generator, deterministic: bool = True):
    """
    Capture the CURRENT RNG states for Python, NumPy, and PyTorch (CPU + MPS if available).

    Returns:
        (dict, torch.Generator): RNG state dict and the generator.
    """
    rng_state = {
        'seed': seed,
        'rng_python': random.getstate(),
        'rng_numpy': np.random.get_state(),
        'rng_torch': torch.get_rng_state(),
        'rng_torch_mps': torch.mps.get_rng_state() if torch.backends.mps.is_available() else None,
        'deterministic': deterministic,
        'generator_state': generator.get_state()
    }
    return rng_state, generator

In [23]:
def manage_rng_state(path: str, mode: str, seed: int = None, generator: torch.Generator = None, deterministic: bool = True):
    """
    Save or load RNG state for Python, NumPy, and PyTorch (CPU + MPS).

    Returns:
        (dict, torch.Generator): RNG state dict and the generator.
    """
    if mode == 'load':
        rng_state = joblib.load(path)

        random.setstate(rng_state['rng_python'])
        np.random.set_state(rng_state['rng_numpy'])
        torch.set_rng_state(rng_state['rng_torch'])
        if torch.backends.mps.is_available() and rng_state.get('rng_torch_mps') is not None:
            torch.mps.set_rng_state(rng_state['rng_torch_mps'])
        torch.use_deterministic_algorithms(rng_state.get('deterministic', False))

        generator = torch.Generator()
        if 'generator_state' in rng_state:
            generator.set_state(rng_state['generator_state'])
        elif seed is not None:
            generator.manual_seed(seed)

        print(f"✅ RNG state loaded from {path}")
        return rng_state, generator

    elif mode == 'save':
        if generator is None:
            generator = torch.Generator().manual_seed(seed)
        rng_state, generator = get_rng_state(seed, generator, deterministic)
        joblib.dump(rng_state, path)
        print(f"✅ RNG state saved to {path}")
        return rng_state, generator

    else:
        raise ValueError("mode must be either 'save' or 'load'")

In [24]:
def setup_reproducibility(start_fresh: bool = False,
                          seed: int = None,
                          deterministic: bool = True,
                          continue_run: bool = False,
                          path: str = None,
                          mode: str = None,
                          generator: torch.Generator = None):
    """
    Wrapper for reproducibility setup:
      - Optionally set RNG seeds.
      - Optionally save/load RNG states.

    Returns:
        (dict, torch.Generator)
    """
    if start_fresh:
        if seed is None:
            raise ValueError("`seed` must be provided when start_fresh=True.")
        return set_seed(seed=seed, deterministic=deterministic)

    if continue_run:
        if path is None or mode is None:
            raise ValueError("Both `path` and `mode` must be provided when continue_run=True.")
        return manage_rng_state(path=path, mode=mode, seed=seed, generator=generator, deterministic=deterministic)

In [25]:
def build_train_transform(
    crop_type="random",
    scale=(0.2, 1.0),
    crop_size=224,
    ratio=(0.75, 1.33),
    color_jitter=True,
    jitter_prob=0.8,
    always_jitter=False,
    hflip_prob=0.5,
    vflip_prob=0.2,
    rotate_prob=0.5,
    rotation_degrees=(-90, 90),
    brightness=(0.7, 1.3),
    contrast=(0.85, 1.3),
    saturation=(0.7, 1.3),
    hue=(-0.0278, 0.0278),
    mean=None,
    std=None,
    normalize=True
):
    """
    Build a training transform pipeline with customizable augmentations.
    ...
    """
    mean = mean or [0.485, 0.456, 0.406]
    std = std or [0.229, 0.224, 0.225]
    
    # Stage 1: Input Preparation & Spatial Augmentations
    transforms_list = [v2.ToImage()]

    if crop_type == "random":
        transforms_list.append(
            v2.RandomResizedCrop(
                size=(crop_size, crop_size),
                scale=scale,
                ratio=ratio,
                antialias=True
            )
        )
    elif crop_type == "center":
        transforms_list.extend([
            v2.Resize(256),
            v2.CenterCrop(crop_size)
        ])
    else:
        raise ValueError(f"Unknown crop_type: {crop_type}. Use 'random' or 'center'")

    transforms_list.extend([
        v2.RandomHorizontalFlip(p=hflip_prob),
        v2.RandomVerticalFlip(p=vflip_prob),
        v2.RandomApply([
            v2.RandomRotation(degrees=rotation_degrees, interpolation=v2.InterpolationMode.BILINEAR)
        ], p=rotate_prob)
    ])

    # Stage 2: Color Operations
    transforms_list.append(v2.ToDtype(torch.float32, scale=True)) # Convert to [0,1] float32

    if color_jitter:
        jitter = v2.ColorJitter(
            brightness=brightness, contrast=contrast,
            saturation=saturation, hue=hue
        )
        transforms_list.append(jitter if always_jitter else v2.RandomApply([jitter], p=jitter_prob)) # Apply color jitter jitter_prob of the time, identity (1 - jitter_prob)

    # Stage 3: Normalization (CRUCIAL for training)
    if normalize:
        transforms_list.append(v2.Normalize(mean=mean, std=std))

    return v2.Compose(transforms_list)

In [26]:
def evaluate_on_three_sets(
    model,
    dict_subset,          # {'Web Top 30': web_top_30_dataset}
    dict_all_web,         # {'All Web Data': web_dataset}
    list_diff_dicts,      # list of dicts, each has one dataset
    transform,
    model_name: str,
    criterion,
    class_names,
    epoch_num,
    log_interval=100,
    batch_size=32,
    num_workers=4
):
    """
    Evaluates model on:
      1. Subset (used in training)
      2. Full web dataset
      3. Each remaining dataset individually
      4. Concatenated remaining datasets
    """

    # Extract keys and datasets
    subset_label, subset_dataset = next(iter(dict_subset.items()))
    all_label, all_dataset = next(iter(dict_all_web.items()))
    subset_dataset.transform = transform
    all_dataset.transform = transform
    

    # Prepare the individual remaining datasets and their names
    remaining_datasets_info = []
    for d in list_diff_dicts:
        label, ds = next(iter(d.items()))
        ds.transform = transform
        remaining_datasets_info.append((ds, label))

    # Concat all remaining datasets together
    concat_remaining = ConcatDataset([ds for ds, _ in remaining_datasets_info])

    # Collect all datasets for evaluation
    datasets_info = [
        (subset_dataset, f"{subset_label} (used in training)"),
        (all_dataset, all_label),
        *remaining_datasets_info,
        (concat_remaining, "Concatenated Remaining Web Data (unseen)")
    ]

    all_results, all_metrics = [], []

    for dataset_obj, dataset_label in datasets_info:
        print(f"\n🔹 Starting evaluation for: {dataset_label}")

        loader = DataLoader(dataset_obj, batch_size=batch_size, shuffle=False, num_workers=num_workers)

        results = evaluate_model(
            model=model,
            val_loader=loader,
            criterion=criterion,
            class_names=class_names,
            epoch_num=epoch_num,
            log_interval=log_interval
        )

        df_results = results['metrics_df'].copy()
        overall_acc = results['overall_accuracy']
        avg_loss = results['avg_loss']
        total_time = results['epoch_time']

        # Add metadata
        df_results.insert(0, "Model", model_name)
        df_results.insert(1, "Dataset", dataset_label)
        all_results.append(df_results)

        # Add summary row
        avg_row = df_results[df_results["Species"] == "Average Performance (Macro)"].copy()
        if not avg_row.empty:
            avg_row = avg_row.iloc[0]
            df_metrics = pd.DataFrame([{
                "Model": model_name,
                "Dataset": dataset_label,
                "Precision": avg_row["Precision"],
                "Recall": avg_row["Recall"],
                "F1-score": avg_row["F1-score"],
                "Epoch": avg_row["Epoch"],
                "overall_accuracy": overall_acc,
                "avg_loss": avg_loss,
                "total_time": total_time
            }])
            all_metrics.append(df_metrics)

    # Combine results
    df_all_results = pd.concat(all_results, ignore_index=True)
    df_metrics_summary = pd.concat(all_metrics, ignore_index=True)

    return df_all_results, df_metrics_summary

# Data Splitting

## External Web Evaluation and Performance Stratification

In [29]:
val_dataset = datasets.ImageFolder(
    root=DATA_DIR / "Validation"  # Path to the validation directory
)

In [30]:
training_states = joblib.load(WORKSPACE_DIR /
                              "Phase 1/mobilenetv2/training_states/training_states_121_130.pkl")

In [31]:
training_states.keys()

dict_keys([121, 122, 123, 124, 125, 126, 127, 128, 129, 130])

In [33]:
model_dict = {}
for i in training_states.keys():
    mobilenet = models.mobilenet_v2(weights=None, num_classes=len(val_dataset.classes)) 
    device = torch.device("mps") 
    mobilenet.to(device)
    mobilenet.load_state_dict(training_states[i]["model_state_dict"])
    model_dict[f'mobilenet_{i}'] = mobilenet

del training_states

In [34]:
model_dict.keys()

dict_keys(['mobilenet_121', 'mobilenet_122', 'mobilenet_123', 'mobilenet_124', 'mobilenet_125', 'mobilenet_126', 'mobilenet_127', 'mobilenet_128', 'mobilenet_129', 'mobilenet_130'])

In [36]:
results_eval_121_130, metrics_eval_121_130 = evaluate_models_on_directory(model_dict,WEB_DATA_DIR, val_dataset.classes)

/var/folders/r9/013lqpnn2cj0hh05j71mb64h0000gn/T/ipykernel_3211/2602539206.py:129: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  metrics_df = pd.concat([metrics_df,

In [37]:
metrics_eval_121_130[metrics_eval_121_130['plant_species']=='Average Performance (Macro)']

        model_name                plant_species  precision    recall  f1_score
32   mobilenet_121  Average Performance (Macro)   0.339878  0.205261  0.215530
65   mobilenet_122  Average Performance (Macro)   0.334349  0.202834  0.213842
98   mobilenet_123  Average Performance (Macro)   0.341831  0.212546  0.221690
131  mobilenet_124  Average Performance (Macro)   0.337915  0.217832  0.225721
164  mobilenet_125  Average Performance (Macro)   0.331406  0.212019  0.220501
197  mobilenet_126  Average Performance (Macro)   0.338396  0.221390  0.231105
230  mobilenet_127  Average Performance (Macro)   0.338710  0.226754  0.234675
263  mobilenet_128  Average Performance (Macro)   0.344508  0.215790  0.227614
296  mobilenet_129  Average Performance (Macro)   0.337081  0.214902  0.223560
329  mobilenet_130  Average Performance (Macro)   0.345338  0.214199  0.223350

In [38]:
graded_summary = grade_confidences(results_eval_121_130)

In [70]:
graded_summary.loc[:, graded_summary.columns != "image_path"]

,model_name,actual_plant,predicted_plant,confidence_predicted,confidence_actual,times_correctly_classified,total_models,correct_ratio,within_model_grade,mean_confidence_actual,across_models_grade,percentile_within_model,percentile_across_models,classification_summary
0,mobilenet_121,Ephedra alata Decne.,others,99.785680,0.000235,0,10,0.0,21.0,0.000351,21.0,Top 70%,Top 70%,Misclassified - Across: Top 70%
1,mobilenet_121,Ephedra alata Decne.,others,98.704344,0.000090,0,10,0.0,23.0,0.000234,22.0,Top 80%,Top 70%,Misclassified - Across: Top 70%
2,mobilenet_121,Ephedra alata Decne.,Tamarix nilotica (Ehrenb.) Bunge,75.536013,0.000004,0,10,0.0,24.0,0.000019,24.0,Top 80%,Top 80%,Misclassified - Across: Top 80%
3,mobilenet_121,Ephedra alata Decne.,others,49.295691,1.589664,0,10,0.0,9.0,1.909910,9.0,Top 10%,Top 10%,Misclassified - Across: Top 10%
4,mobilenet_121,Ephedra alata Decne.,others,68.113470,0.000097,0,10,0.0,22.0,0.000176,23.0,Top 70%,Top 80%,Misclassified - Across: Top 80%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58145,mobilenet_130,Salsola imbricata Forssk.,Ochradenus baccatus Delile,68.567693,0.612048,0,10,0.0,109.0,0.433660,131.0,Top 20%,Top 20%,Misclassified - Across: Top 20%
58146,mobilenet_130,Salsola imbricata Forssk.,others,30.679718,15.259188,1,10,0.1,45.0,19.566176,46.0,NaN,NaN,Correctly classified 1 time(s)
58147,mobilenet_130,Salsola imbricata Forssk.,Zygophyllum arabicum (L.) Christenh. & Byng,92.336100,0.000029,0,10,0.0,327.0,0.000081,340.0,Top 70%,Top 70%,Misclassified - Across: Top 70%
58148,mobilenet_130,Salsola imbricata Forssk.,Cebatha pendula (J.R.Forst. & G.Forst.) Kuntze,37.720597,0.000001,0,10,0.0,391.0,0.000003,388.0,Top 90%,Top 90%,Misclassified - Across: Top 90%
58149,mobilenet_130,Salsola imbricata Forssk.,Lycium shawii Roem. & Schult.,46.874788,0.000013,0,10,0.0,346.0,0.000051,349.0,Top 80%,Top 80%,Misclassified - Across: Top 80%

In [44]:
graded_summary.to_csv('graded_summary_121_130/graded_summary_121_130.csv')

In [52]:
categorized_web_dir = WEB_DATA_DIR.parent / "categorized_121_130"

In [54]:
organize_images_by_performance_group(graded_summary, categorized_web_dir)

✅ Images organized into performance groups under: categorized_121_130

# **<center>Fine Tuning</center>**

In [49]:
seeds = [42, 1234, 2025]

In [50]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[1])

✅ Random seed set to 1234 (MPS available: True)

In [51]:
# Validation/evaluation transforms (no augmentation)
val_transform = v2.Compose([
    v2.ToImage(),
    # Resize the image so its shorter side is 256 pixels, preserving aspect ratio (i.e., the proportion between width and height stays the same)
    v2.Resize(256),
    # Extract a 224x224 patch from the center of the resized image
    v2.CenterCrop(224),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

In [52]:
# Create FullDataset object.
categorized_web_dir = WEB_DATA_DIR.parent / "categorized_121_130"
Web_correctly_classified = categorized_web_dir / "correctly_classified"
Web_lowest_30_misclassified = categorized_web_dir / "lowest_30_misclassified"
Web_mid_30_70_misclassified = categorized_web_dir / "mid_30_70_misclassified"
Web_top_30_misclassified = categorized_web_dir / "top_30_misclassified"
BATCH_SIZE = 32

In [53]:
train_dataset = datasets.ImageFolder(
    root=TRAIN_DIR
)

val_dataset = datasets.ImageFolder(
    root=VAL_DIR
)

web_dataset = datasets.ImageFolder(
    root=WEB_DATA_DIR
)


web_correctly_classified_dataset = datasets.ImageFolder(
    root=Web_correctly_classified
)


web_lowest_30_dataset = datasets.ImageFolder(
    root=Web_lowest_30_misclassified
)


web_mid_30_70_dataset = datasets.ImageFolder(
    root=Web_mid_30_70_misclassified
)


web_top_30_dataset = datasets.ImageFolder(
    root=Web_top_30_misclassified
)

print(f'train_dataset: {len(train_dataset)}')
print(f'val_dataset: {len(val_dataset)}')
print(f'web_dataset: {len(web_dataset)}')
print(f'web_correctly_classified_dataset: {len(web_correctly_classified_dataset)}')
print(f'web_lowest_30_dataset: {len(web_lowest_30_dataset)}')
print(f'web_mid_30_70_dataset: {len(web_mid_30_70_dataset)}')
print(f'web_top_30_dataset: {len(web_top_30_dataset)}')

train_dataset: 17364
val_dataset: 5200
web_dataset: 5815
web_correctly_classified_dataset: 1815
web_lowest_30_dataset: 1202
web_mid_30_70_dataset: 1599
web_top_30_dataset: 1199

In [54]:
strong_train_transform = build_train_transform(
    scale=(0.08, 1.0),
    jitter_prob=1.0,
    always_jitter=True,
    vflip_prob=0.5,
    rotate_prob=0.7,
    rotation_degrees=(-180, 180),
    normalize=False
                     )
extra_aug = v2.RandomApply([
    v2.GaussianBlur(kernel_size=3, sigma=(0.1, 2.0)),
    v2.RandomPerspective(distortion_scale=0.3, p=1.0),
    v2.RandomErasing(p=0.5, scale=(0.02, 0.2), ratio=(0.3, 3.3))
], p=0.5)

new_train_transform = v2.Compose([
    strong_train_transform,
    extra_aug,
    v2.Normalize(mean=[0.485, 0.456, 0.406],
                 std=[0.229, 0.224, 0.225])
])

In [55]:
train_dataset.transform = new_train_transform  
web_lowest_30_dataset.transform = new_train_transform
web_top_30_dataset.transform = new_train_transform
val_dataset.transform = val_transform

In [61]:
full_web_lowest_30_dataset = ConcatDataset([train_dataset, web_lowest_30_dataset])
full_web_top_30_dataset = ConcatDataset([train_dataset, web_top_30_dataset])

print(f'full_web_lowest_30_dataset: {len(full_web_lowest_30_dataset)}')
print(f'full_web_top_30_dataset: {len(full_web_top_30_dataset)}')

full_web_lowest_30_dataset: 18566
full_web_top_30_dataset: 18563

In [63]:
full_web_lowest_30_loader = DataLoader(
    full_web_lowest_30_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,             # shuffle ensures different order each epoch
    num_workers=4,            # safer on macOS, avoids multiprocessing issues
    pin_memory=True,      
    generator=generator       # ensures reproducible shuffling
)


full_web_top_30_loader = DataLoader(
    full_web_top_30_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,             # shuffle ensures different order each epoch
    num_workers=4,            # safer on macOS, avoids multiprocessing issues
    pin_memory=True,     
    generator=generator       # ensures reproducible shuffling
)


val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,            # no need to shuffle validation
    num_workers=4,            # same note for macOS
    pin_memory=True,
    generator=generator
)

## full_web_top_30_dataset

In [66]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[1])

✅ Random seed set to 1234 (MPS available: True)

In [65]:
training_states = joblib.load(WORKSPACE_DIR /
                              "Phase 1/mobilenetv2/training_states/training_states_121_130.pkl")

mobilenetv2_stageF_top_30 = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes)) 
device = torch.device("mps") 
mobilenetv2_stageF_top_30.to(device)
mobilenetv2_stageF_top_30.load_state_dict(training_states[127]["model_state_dict"])
del training_states
df_summary = summarize_mobilenetv2_blocks(mobilenetv2_stageF_top_30)
df_summary

,Block,Order,Module,Layers (#),Params (#),Trainable Params (#),% Layers (Model),% Params (Model),% Trainable Params (Model),Cumulative Layers (Model),Cumulative % Layers (Model),Cumulative Params (Model),Cumulative % Params (Model),Layers (Module %),Params (Module %),Trainable Params (Module %),Cumulative Layers (Module),Cumulative % Layers (Module),Cumulative Params (Module),Cumulative % Params (Module)
0,Conv2dNormActivation_1,1,features,3,928,928,1.898734,0.040951,0.040951,158,100.000000,2266145,100.000000,1.923077,0.041729,0.041729,156,100.000000,2223872,100.000000
1,InvertedResidual_2,2,features,6,896,896,3.797468,0.039539,0.039539,155,98.101266,2265217,99.959049,3.846154,0.040290,0.040290,153,98.076923,2222944,99.958271
2,InvertedResidual_3,3,features,9,5136,5136,5.696203,0.226640,0.226640,149,94.303797,2264321,99.919511,5.769231,0.230949,0.230949,147,94.230769,2222048,99.917981
3,InvertedResidual_4,4,features,9,8832,8832,5.696203,0.389737,0.389737,140,88.607595,2259185,99.692870,5.769231,0.397145,0.397145,138,88.461538,2216912,99.687032
4,InvertedResidual_5,5,features,9,10000,10000,5.696203,0.441278,0.441278,131,82.911392,2250353,99.303134,5.769231,0.449666,0.449666,129,82.692308,2208080,99.289887
5,InvertedResidual_6,6,features,9,14848,14848,5.696203,0.655210,0.655210,122,77.215190,2240353,98.861856,5.769231,0.667664,0.667664,120,76.923077,2198080,98.840221
6,InvertedResidual_7,7,features,9,14848,14848,5.696203,0.655210,0.655210,113,71.518987,2225505,98.206646,5.769231,0.667664,0.667664,111,71.153846,2183232,98.172557
7,InvertedResidual_8,8,features,9,21056,21056,5.696203,0.929155,0.929155,104,65.822785,2210657,97.551436,5.769231,0.946817,0.946817,102,65.384615,2168384,97.504892
8,InvertedResidual_9,9,features,9,54272,54272,5.696203,2.394904,2.394904,95,60.126582,2189601,96.622281,5.769231,2.440428,2.440428,93,59.615385,2147328,96.558075
9,InvertedResidual_10,10,features,9,54272,54272,5.696203,2.394904,2.394904,86,54.430380,2135329,94.227377,5.769231,2.440428,2.440428,84,53.846154,2093056,94.117647
10,InvertedResidual_11,11,features,9,54272,54272,5.696203,2.394904,2.394904,77,48.734177,2081057,91.832473,5.769231,2.440428,2.440428,75,48.076923,2038784,91.677219
11,InvertedResidual_12,12,features,9,66624,66624,5.696203,2.939971,2.939971,68,43.037975,2026785,89.437569,5.769231,2.995856,2.995856,66,42.307692,1984512,89.236791
12,InvertedResidual_13,13,features,9,118272,118272,5.696203,5.219084,5.219084,59,37.341772,1960161,86.497598,5.769231,5.318292,5.318292,57,36.538462,1917888,86.240935
13,InvertedResidual_14,14,features,9,118272,118272,5.696203,5.219084,5.219084,50,31.645570,1841889,81.278515,5.769231,5.318292,5.318292,48,30.769231,1799616,80.922643
14,InvertedResidual_15,15,features,9,155264,155264,5.696203,6.851459,6.851459,41,25.949367,1723617,76.059431,5.769231,6.981697,6.981697,39,25.000000,1681344,75.604351
15,InvertedResidual_16,16,features,9,320000,320000,5.696203,14.120897,14.120897,32,20.253165,1568353,69.207972,5.769231,14.389317,14.389317,30,19.230769,1526080,68.622655
16,InvertedResidual_17,17,features,9,320000,320000,5.696203,14.120897,14.120897,23,14.556962,1248353,55.087075,5.769231,14.389317,14.389317,21,13.461538,1206080,54.233337
17,InvertedResidual_18,18,features,9,473920,473920,5.696203,20.913048,20.913048,14,8.860759,928353,40.966178,5.769231,21.310579,21.310579,12,7.692308,886080,39.844020
18,Conv2dNormActivation_19,19,features,3,412160,412160,1.898734,18.187715,18.187715,5,3.164557,454433,20.053130,1.923077,18.533441,18.533441,3,1.923077,412160,18.533441
19,Sequential,20,classifier,2,42273,42273,1.265823,1.865415,1.865415,2,1.265823,42273,1.865415,100.000000,100.000000,100.000000,2,100.000000,42273,100.000000

### the following method divide the other class weights by 2

In [98]:
norm_sqrt_inv_weights_train = compute_class_weights(train_dataset, method="sqrt_inverse", normalize=True)
norm_sqrt_inv_weights_train_top_30 = compute_class_weights(web_top_30_dataset, method="sqrt_inverse", normalize=True)   
norm_sqrt_inv_weights_train_top_30[-1] = 0 # handel other class

In [99]:
norm_sqrt_inv_weights = (norm_sqrt_inv_weights_train + (2*norm_sqrt_inv_weights_train_top_30))/2

In [100]:
norm_sqrt_inv_weights

tensor([1.0938, 1.1379, 1.5019, 1.2137, 1.1484, 1.2588, 1.5647, 1.8985, 2.4456,
        1.0494, 1.6496, 2.0818, 1.0580, 0.9910, 1.0173, 1.4435, 2.7015, 1.5595,
        1.1196, 0.9252, 0.9630, 1.5881, 1.1269, 0.8456, 1.2772, 1.0728, 1.4412,
        1.1018, 0.8796, 1.2396, 1.7300, 2.5961, 0.4783], device='mps:0')

In [101]:
norm_sqrt_inv_criterion = nn.CrossEntropyLoss(weight=norm_sqrt_inv_weights)

In [ ]:
stageF_optimizer = torch.optim.AdamW(mobilenetv2_stageF_top_30.parameters(), lr=1e-5,
                            weight_decay=1e-4, betas=(0.9, 0.999))

In [42]:
start_epoch = 128
end_epoch = 140
start_epoch, end_epoch

(128, 140)

In [43]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_top_30, full_web_top_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_top_30', save_dir = 'Training outputs',
                         class_weights='norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 128 - Training Started...

Epoch 128, Batch 100, Loss: 0.6012, Accuracy: 86.66%, Time Passed: 3.57m
Epoch 128, Batch 200, Loss: 0.5890, Accuracy: 86.59%, Time Passed: 7.11m
Epoch 128, Batch 300, Loss: 0.5908, Accuracy: 86.76%, Time Passed: 10.74m
Epoch 128, Batch 400, Loss: 0.5675, Accuracy: 87.01%, Time Passed: 14.57m
Epoch 128, Batch 500, Loss: 0.5503, Accuracy: 87.29%, Time Passed: 18.34m
Epoch 128 Completed - Average Loss: 0.5459, Accuracy: 87.32%, Epoch Time: 21.30m
Training Complete Epoch 128 - Total Time: 21.30m

✅ Epoch 128 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7834, Accuracy: 80.19%, Time Passed: 4.44m
Evaluation Complete - Loss: 0.7482, Accuracy: 82.53%, Total Time: 8.12m

📊 Epoch 128 - Evaluation Completed.


🚀 Epoch 129 - Training Started...

Epoch 129, Batch 100, Loss: 0.4194, Accuracy: 88.59%, Time Passed: 4.36m
Epoch 129, Batch 200, Loss: 0.4345, Accuracy: 88.25%, Time Passed: 8.91m
Epoch 129, Batch 300, Loss: 0.4361, Accuracy: 88.29%, Time Passed: 13.55m
Epoch 129, Batch 400, Loss: 0.4402, Accuracy: 88.34%, Time Passed: 18.51m
Epoch 129, Batch 500, Loss: 0.4371, Accuracy: 88.41%, Time Passed: 23.31m
Epoch 129 Completed - Average Loss: 0.4317, Accuracy: 88.55%, Epoch Time: 27.39m
Training Complete Epoch 129 - Total Time: 27.39m

✅ Epoch 129 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7521, Accuracy: 80.47%, Time Passed: 5.00m
Evaluation Complete - Loss: 0.7355, Accuracy: 82.50%, Total Time: 9.30m

📊 Epoch 129 - Evaluation Completed.


🚀 Epoch 130 - Training Started...

Epoch 130, Batch 100, Loss: 0.3821, Accuracy: 89.22%, Time Passed: 5.39m
Epoch 130, Batch 200, Loss: 0.3868, Accuracy: 89.27%, Time Passed: 10.50m
Epoch 130, Batch 300, Loss: 0.3919, Accuracy: 89.08%, Time Passed: 15.61m
Epoch 130, Batch 400, Loss: 0.3892, Accuracy: 89.10%, Time Passed: 20.84m
Epoch 130, Batch 500, Loss: 0.3926, Accuracy: 89.01%, Time Passed: 26.08m
Epoch 130 Completed - Average Loss: 0.3913, Accuracy: 89.04%, Epoch Time: 29.78m
Training Complete Epoch 130 - Total Time: 29.78m

✅ Epoch 130 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7499, Accuracy: 80.66%, Time Passed: 4.43m
Evaluation Complete - Loss: 0.7311, Accuracy: 82.76%, Total Time: 7.66m

📊 Epoch 130 - Evaluation Completed.


🚀 Epoch 131 - Training Started...

Epoch 131, Batch 100, Loss: 0.3386, Accuracy: 90.38%, Time Passed: 3.72m
Epoch 131, Batch 200, Loss: 0.3354, Accuracy: 90.19%, Time Passed: 7.51m
Epoch 131, Batch 300, Loss: 0.3378, Accuracy: 90.20%, Time Passed: 11.24m
Epoch 131, Batch 400, Loss: 0.3497, Accuracy: 89.87%, Time Passed: 14.94m
Epoch 131, Batch 500, Loss: 0.3555, Accuracy: 89.72%, Time Passed: 18.70m
Epoch 131 Completed - Average Loss: 0.3571, Accuracy: 89.73%, Epoch Time: 21.61m
Training Complete Epoch 131 - Total Time: 21.61m

✅ Epoch 131 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7074, Accuracy: 81.47%, Time Passed: 4.14m
Evaluation Complete - Loss: 0.6660, Accuracy: 83.84%, Total Time: 7.20m

📊 Epoch 131 - Evaluation Completed.


🚀 Epoch 132 - Training Started...

Epoch 132, Batch 100, Loss: 0.3282, Accuracy: 89.78%, Time Passed: 3.61m
Epoch 132, Batch 200, Loss: 0.3304, Accuracy: 90.25%, Time Passed: 7.23m
Epoch 132, Batch 300, Loss: 0.3313, Accuracy: 90.30%, Time Passed: 10.81m
Epoch 132, Batch 400, Loss: 0.3334, Accuracy: 90.30%, Time Passed: 14.52m
Epoch 132, Batch 500, Loss: 0.3463, Accuracy: 89.89%, Time Passed: 18.50m
Epoch 132 Completed - Average Loss: 0.3440, Accuracy: 89.96%, Epoch Time: 21.51m
Training Complete Epoch 132 - Total Time: 21.51m

✅ Epoch 132 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7195, Accuracy: 80.38%, Time Passed: 4.35m
Evaluation Complete - Loss: 0.6842, Accuracy: 83.39%, Total Time: 7.86m

📊 Epoch 132 - Evaluation Completed.


🚀 Epoch 133 - Training Started...

Epoch 133, Batch 100, Loss: 0.3504, Accuracy: 90.06%, Time Passed: 4.11m
Epoch 133, Batch 200, Loss: 0.3469, Accuracy: 90.23%, Time Passed: 8.33m
Epoch 133, Batch 300, Loss: 0.3405, Accuracy: 90.25%, Time Passed: 12.59m
Epoch 133, Batch 400, Loss: 0.3229, Accuracy: 90.72%, Time Passed: 16.81m
Epoch 133, Batch 500, Loss: 0.3225, Accuracy: 90.67%, Time Passed: 21.07m
Epoch 133 Completed - Average Loss: 0.3274, Accuracy: 90.47%, Epoch Time: 24.17m
Training Complete Epoch 133 - Total Time: 24.17m

✅ Epoch 133 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6556, Accuracy: 82.06%, Time Passed: 4.49m
Evaluation Complete - Loss: 0.6421, Accuracy: 84.06%, Total Time: 7.90m

📊 Epoch 133 - Evaluation Completed.


🚀 Epoch 134 - Training Started...

Epoch 134, Batch 100, Loss: 0.3338, Accuracy: 90.62%, Time Passed: 4.15m
Epoch 134, Batch 200, Loss: 0.3268, Accuracy: 90.34%, Time Passed: 8.83m
Epoch 134, Batch 300, Loss: 0.3244, Accuracy: 90.27%, Time Passed: 13.55m
Epoch 134, Batch 400, Loss: 0.3188, Accuracy: 90.54%, Time Passed: 18.15m
Epoch 134, Batch 500, Loss: 0.3136, Accuracy: 90.76%, Time Passed: 22.72m
Epoch 134 Completed - Average Loss: 0.3137, Accuracy: 90.70%, Epoch Time: 25.69m
Training Complete Epoch 134 - Total Time: 25.69m

✅ Epoch 134 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7097, Accuracy: 80.97%, Time Passed: 4.35m
Evaluation Complete - Loss: 0.6730, Accuracy: 83.65%, Total Time: 7.77m

📊 Epoch 134 - Evaluation Completed.


🚀 Epoch 135 - Training Started...

Epoch 135, Batch 100, Loss: 0.3104, Accuracy: 90.91%, Time Passed: 4.03m
Epoch 135, Batch 200, Loss: 0.3199, Accuracy: 90.53%, Time Passed: 8.09m
Epoch 135, Batch 300, Loss: 0.3090, Accuracy: 90.78%, Time Passed: 12.14m
Epoch 135, Batch 400, Loss: 0.3061, Accuracy: 90.73%, Time Passed: 16.12m
Epoch 135, Batch 500, Loss: 0.3022, Accuracy: 90.73%, Time Passed: 20.22m
Epoch 135 Completed - Average Loss: 0.3025, Accuracy: 90.74%, Epoch Time: 23.22m
Training Complete Epoch 135 - Total Time: 23.22m

✅ Epoch 135 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6309, Accuracy: 83.38%, Time Passed: 4.43m
Evaluation Complete - Loss: 0.6166, Accuracy: 85.27%, Total Time: 7.78m

📊 Epoch 135 - Evaluation Completed.


🚀 Epoch 136 - Training Started...

Epoch 136, Batch 100, Loss: 0.3052, Accuracy: 90.66%, Time Passed: 3.71m
Epoch 136, Batch 200, Loss: 0.3035, Accuracy: 90.58%, Time Passed: 7.27m
Epoch 136, Batch 300, Loss: 0.3013, Accuracy: 90.61%, Time Passed: 10.83m
Epoch 136, Batch 400, Loss: 0.3008, Accuracy: 90.69%, Time Passed: 14.47m
Epoch 136, Batch 500, Loss: 0.3023, Accuracy: 90.69%, Time Passed: 18.19m
Epoch 136 Completed - Average Loss: 0.2985, Accuracy: 90.80%, Epoch Time: 21.21m
Training Complete Epoch 136 - Total Time: 21.21m

✅ Epoch 136 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6643, Accuracy: 81.47%, Time Passed: 4.32m
Evaluation Complete - Loss: 0.6273, Accuracy: 84.26%, Total Time: 7.79m

📊 Epoch 136 - Evaluation Completed.


🚀 Epoch 137 - Training Started...

Epoch 137, Batch 100, Loss: 0.2881, Accuracy: 91.69%, Time Passed: 4.18m
Epoch 137, Batch 200, Loss: 0.2817, Accuracy: 91.53%, Time Passed: 8.63m
Epoch 137, Batch 300, Loss: 0.2825, Accuracy: 91.36%, Time Passed: 12.80m
Epoch 137, Batch 400, Loss: 0.2829, Accuracy: 91.33%, Time Passed: 17.07m
Epoch 137, Batch 500, Loss: 0.2818, Accuracy: 91.39%, Time Passed: 21.27m
Epoch 137 Completed - Average Loss: 0.2827, Accuracy: 91.38%, Epoch Time: 24.26m
Training Complete Epoch 137 - Total Time: 24.26m

✅ Epoch 137 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6647, Accuracy: 81.72%, Time Passed: 4.44m
Evaluation Complete - Loss: 0.6202, Accuracy: 84.47%, Total Time: 7.91m

📊 Epoch 137 - Evaluation Completed.


🚀 Epoch 138 - Training Started...

Epoch 138, Batch 100, Loss: 0.2757, Accuracy: 91.28%, Time Passed: 5.06m
Epoch 138, Batch 200, Loss: 0.2671, Accuracy: 91.36%, Time Passed: 10.48m
Epoch 138, Batch 300, Loss: 0.2687, Accuracy: 91.34%, Time Passed: 16.11m
Epoch 138, Batch 400, Loss: 0.2652, Accuracy: 91.41%, Time Passed: 21.54m
Epoch 138, Batch 500, Loss: 0.2662, Accuracy: 91.49%, Time Passed: 27.14m
Epoch 138 Completed - Average Loss: 0.2662, Accuracy: 91.57%, Epoch Time: 31.25m
Training Complete Epoch 138 - Total Time: 31.25m

✅ Epoch 138 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6359, Accuracy: 82.34%, Time Passed: 5.69m
Evaluation Complete - Loss: 0.6102, Accuracy: 84.69%, Total Time: 10.02m

📊 Epoch 138 - Evaluation Completed.


🚀 Epoch 139 - Training Started...

Epoch 139, Batch 100, Loss: 0.2621, Accuracy: 91.34%, Time Passed: 5.98m
Epoch 139, Batch 200, Loss: 0.2674, Accuracy: 91.30%, Time Passed: 11.35m
Epoch 139, Batch 300, Loss: 0.2746, Accuracy: 91.09%, Time Passed: 16.56m
Epoch 139, Batch 400, Loss: 0.2779, Accuracy: 91.27%, Time Passed: 21.40m
Epoch 139, Batch 500, Loss: 0.2817, Accuracy: 91.18%, Time Passed: 25.24m
Epoch 139 Completed - Average Loss: 0.2769, Accuracy: 91.34%, Epoch Time: 28.15m
Training Complete Epoch 139 - Total Time: 28.15m

✅ Epoch 139 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6092, Accuracy: 82.94%, Time Passed: 4.27m
Evaluation Complete - Loss: 0.6070, Accuracy: 84.86%, Total Time: 7.65m

📊 Epoch 139 - Evaluation Completed.


🚀 Epoch 140 - Training Started...

Epoch 140, Batch 100, Loss: 0.2596, Accuracy: 91.97%, Time Passed: 4.42m
Epoch 140, Batch 200, Loss: 0.2580, Accuracy: 92.11%, Time Passed: 8.50m
Epoch 140, Batch 300, Loss: 0.2597, Accuracy: 91.97%, Time Passed: 12.67m
Epoch 140, Batch 400, Loss: 0.2599, Accuracy: 92.03%, Time Passed: 16.95m
Epoch 140, Batch 500, Loss: 0.2636, Accuracy: 91.89%, Time Passed: 21.36m
Epoch 140 Completed - Average Loss: 0.2642, Accuracy: 91.84%, Epoch Time: 24.59m
Training Complete Epoch 140 - Total Time: 24.59m

✅ Epoch 140 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6091, Accuracy: 83.16%, Time Passed: 4.31m
Evaluation Complete - Loss: 0.5958, Accuracy: 85.03%, Total Time: 7.65m

📊 Epoch 140 - Evaluation Completed.

In [44]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_top_30_{start_epoch}_{end_epoch}.pkl')

In [45]:
del training_states

### **Continue Training**

In [102]:
state, generator = setup_reproducibility(continue_run=True, path="Training outputs/rng_state_140.pkl", mode="load")

✅ RNG state loaded from Training outputs/rng_state_140.pkl

> **Output-organization note:** Training outputs were initially generated in the main `Training outputs/` directory and were subsequently organized manually into dedicated subdirectories such as `training_states/`, `top_val_results/`, and `lowest_val_results/`. These paths therefore reflect the organized archive structure rather than a different training procedure.

In [103]:
training_states = joblib.load('Training outputs/training_states_top_30_128_140.pkl')

# Recreate the optimizer with the same settings as before
stageF_optimizer = torch.optim.AdamW(mobilenetv2_stageF_top_30.parameters(), lr=1e-5,
                            weight_decay=1e-4, betas=(0.9, 0.999))

# Load the saved optimizer state
stageF_optimizer.load_state_dict(training_states[140]["optimizer_state_dict"])
del training_states

In [104]:
start_epoch = 141
end_epoch = 150
start_epoch, end_epoch

(141, 150)

In [71]:
val_res = evaluate_model(mobilenetv2_stageF_top_30, val_loader, norm_sqrt_inv_criterion, train_dataset.classes, epoch_num=1, log_interval=100)

python(40604) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40606) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40608) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40610) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.6091, Accuracy: 83.16%, Time Passed: 3.49m
Evaluation Complete - Loss: 0.5958, Accuracy: 85.03%, Total Time: 6.55m

In [105]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_top_30, full_web_top_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_top_30', save_dir = 'Training outputs',
                         class_weights='norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 141 - Training Started...

python(40782) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40784) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40787) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40789) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 141, Batch 100, Loss: 0.2433, Accuracy: 91.66%, Time Passed: 4.58m
Epoch 141, Batch 200, Loss: 0.2445, Accuracy: 91.86%, Time Passed: 8.83m
Epoch 141, Batch 300, Loss: 0.2625, Accuracy: 91.54%, Time Passed: 13.37m
Epoch 141, Batch 400, Loss: 0.2600, Accuracy: 91.77%, Time Passed: 18.03m
Epoch 141, Batch 500, Loss: 0.2651, Accuracy: 91.54%, Time Passed: 22.52m
Epoch 141 Completed - Average Loss: 0.2656, Accuracy: 91.53%, Epoch Time: 25.98m
Training Complete Epoch 141 - Total Time: 25.98m

✅ Epoch 141 - Training Completed. Starting Evaluation...

python(41167) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41169) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41171) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41173) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5728, Accuracy: 84.69%, Time Passed: 4.06m
Evaluation Complete - Loss: 0.5728, Accuracy: 86.01%, Total Time: 7.37m

📊 Epoch 141 - Evaluation Completed.


🚀 Epoch 142 - Training Started...

python(41203) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41207) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41210) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41212) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 142, Batch 100, Loss: 0.2858, Accuracy: 91.03%, Time Passed: 4.43m
Epoch 142, Batch 200, Loss: 0.2644, Accuracy: 91.86%, Time Passed: 8.90m
Epoch 142, Batch 300, Loss: 0.2617, Accuracy: 91.75%, Time Passed: 13.35m
Epoch 142, Batch 400, Loss: 0.2592, Accuracy: 91.85%, Time Passed: 17.90m
Epoch 142, Batch 500, Loss: 0.2589, Accuracy: 91.86%, Time Passed: 22.30m
Epoch 142 Completed - Average Loss: 0.2583, Accuracy: 91.99%, Epoch Time: 25.78m
Training Complete Epoch 142 - Total Time: 25.78m

✅ Epoch 142 - Training Completed. Starting Evaluation...

python(41385) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41392) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41395) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41399) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5980, Accuracy: 83.81%, Time Passed: 4.36m
Evaluation Complete - Loss: 0.5821, Accuracy: 85.49%, Total Time: 7.57m

📊 Epoch 142 - Evaluation Completed.


🚀 Epoch 143 - Training Started...

python(41447) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41449) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41453) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41455) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 143, Batch 100, Loss: 0.2721, Accuracy: 91.16%, Time Passed: 5.28m
Epoch 143, Batch 200, Loss: 0.2620, Accuracy: 91.52%, Time Passed: 11.89m
Epoch 143, Batch 300, Loss: 0.2569, Accuracy: 91.79%, Time Passed: 17.24m
Epoch 143, Batch 400, Loss: 0.2581, Accuracy: 91.66%, Time Passed: 22.53m
Epoch 143, Batch 500, Loss: 0.2512, Accuracy: 91.89%, Time Passed: 27.11m
Epoch 143 Completed - Average Loss: 0.2508, Accuracy: 91.92%, Epoch Time: 31.06m
Training Complete Epoch 143 - Total Time: 31.06m

✅ Epoch 143 - Training Completed. Starting Evaluation...

python(41987) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41989) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41991) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(41993) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.6188, Accuracy: 83.25%, Time Passed: 4.13m
Evaluation Complete - Loss: 0.5985, Accuracy: 85.16%, Total Time: 7.48m

📊 Epoch 143 - Evaluation Completed.


🚀 Epoch 144 - Training Started...

python(42074) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(42077) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(42080) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(42083) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 144, Batch 100, Loss: 0.2558, Accuracy: 91.59%, Time Passed: 5.24m
Epoch 144, Batch 200, Loss: 0.2647, Accuracy: 91.70%, Time Passed: 10.71m
Epoch 144, Batch 300, Loss: 0.2618, Accuracy: 91.72%, Time Passed: 15.15m
Epoch 144, Batch 400, Loss: 0.2577, Accuracy: 91.80%, Time Passed: 20.11m
Epoch 144, Batch 500, Loss: 0.2568, Accuracy: 91.93%, Time Passed: 24.69m
Epoch 144 Completed - Average Loss: 0.2555, Accuracy: 91.98%, Epoch Time: 28.18m
Training Complete Epoch 144 - Total Time: 28.18m

✅ Epoch 144 - Training Completed. Starting Evaluation...

python(42398) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(42400) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(42402) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(42404) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5931, Accuracy: 83.97%, Time Passed: 4.07m
Evaluation Complete - Loss: 0.5780, Accuracy: 85.75%, Total Time: 7.34m

📊 Epoch 144 - Evaluation Completed.


🚀 Epoch 145 - Training Started...

python(42493) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(42495) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(42497) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(42500) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 145, Batch 100, Loss: 0.2322, Accuracy: 92.66%, Time Passed: 6.19m
Epoch 145, Batch 200, Loss: 0.2435, Accuracy: 92.30%, Time Passed: 12.89m
Epoch 145, Batch 300, Loss: 0.2384, Accuracy: 92.27%, Time Passed: 19.55m
Epoch 145, Batch 400, Loss: 0.2402, Accuracy: 92.31%, Time Passed: 24.27m
Epoch 145, Batch 500, Loss: 0.2391, Accuracy: 92.26%, Time Passed: 28.73m
Epoch 145 Completed - Average Loss: 0.2391, Accuracy: 92.26%, Epoch Time: 32.00m
Training Complete Epoch 145 - Total Time: 32.00m

✅ Epoch 145 - Training Completed. Starting Evaluation...

python(43100) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43102) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43104) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43106) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5981, Accuracy: 83.41%, Time Passed: 4.02m
Evaluation Complete - Loss: 0.5701, Accuracy: 85.32%, Total Time: 7.31m

📊 Epoch 145 - Evaluation Completed.


🚀 Epoch 146 - Training Started...

python(43131) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43133) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43135) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43137) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 146, Batch 100, Loss: 0.2317, Accuracy: 92.34%, Time Passed: 4.62m
Epoch 146, Batch 200, Loss: 0.2459, Accuracy: 92.19%, Time Passed: 8.91m
Epoch 146, Batch 300, Loss: 0.2491, Accuracy: 92.26%, Time Passed: 13.43m
Epoch 146, Batch 400, Loss: 0.2480, Accuracy: 92.15%, Time Passed: 17.82m
Epoch 146, Batch 500, Loss: 0.2486, Accuracy: 92.19%, Time Passed: 22.16m
Epoch 146 Completed - Average Loss: 0.2478, Accuracy: 92.16%, Epoch Time: 25.43m
Training Complete Epoch 146 - Total Time: 25.44m

✅ Epoch 146 - Training Completed. Starting Evaluation...

python(43384) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43386) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43388) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43390) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.6060, Accuracy: 83.28%, Time Passed: 3.99m
Evaluation Complete - Loss: 0.5820, Accuracy: 85.27%, Total Time: 7.17m

📊 Epoch 146 - Evaluation Completed.


🚀 Epoch 147 - Training Started...

python(43406) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43408) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43410) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43412) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 147, Batch 100, Loss: 0.2397, Accuracy: 92.47%, Time Passed: 5.38m
Epoch 147, Batch 200, Loss: 0.2309, Accuracy: 92.41%, Time Passed: 11.45m
Epoch 147, Batch 300, Loss: 0.2368, Accuracy: 92.34%, Time Passed: 16.93m
Epoch 147, Batch 400, Loss: 0.2352, Accuracy: 92.35%, Time Passed: 21.56m
Epoch 147, Batch 500, Loss: 0.2329, Accuracy: 92.33%, Time Passed: 26.36m
Epoch 147 Completed - Average Loss: 0.2349, Accuracy: 92.28%, Epoch Time: 30.02m
Training Complete Epoch 147 - Total Time: 30.02m

✅ Epoch 147 - Training Completed. Starting Evaluation...

python(43837) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43842) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43844) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43846) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5661, Accuracy: 84.50%, Time Passed: 4.10m
Evaluation Complete - Loss: 0.5734, Accuracy: 85.68%, Total Time: 7.26m

📊 Epoch 147 - Evaluation Completed.


🚀 Epoch 148 - Training Started...

python(43879) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43881) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43883) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43885) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 148, Batch 100, Loss: 0.2213, Accuracy: 93.00%, Time Passed: 5.24m
Epoch 148, Batch 200, Loss: 0.2251, Accuracy: 92.81%, Time Passed: 9.77m
Epoch 148, Batch 300, Loss: 0.2301, Accuracy: 92.62%, Time Passed: 14.12m
Epoch 148, Batch 400, Loss: 0.2370, Accuracy: 92.30%, Time Passed: 18.68m
Epoch 148, Batch 500, Loss: 0.2438, Accuracy: 92.14%, Time Passed: 23.24m
Epoch 148 Completed - Average Loss: 0.2416, Accuracy: 92.28%, Epoch Time: 26.74m
Training Complete Epoch 148 - Total Time: 26.74m

✅ Epoch 148 - Training Completed. Starting Evaluation...

python(44115) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44118) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44120) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44123) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5757, Accuracy: 83.84%, Time Passed: 4.04m
Evaluation Complete - Loss: 0.5404, Accuracy: 85.99%, Total Time: 7.25m

📊 Epoch 148 - Evaluation Completed.


🚀 Epoch 149 - Training Started...

python(44174) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44176) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44178) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44180) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 149, Batch 100, Loss: 0.2447, Accuracy: 92.25%, Time Passed: 5.10m
Epoch 149, Batch 200, Loss: 0.2353, Accuracy: 92.59%, Time Passed: 9.84m
Epoch 149, Batch 300, Loss: 0.2270, Accuracy: 92.70%, Time Passed: 14.64m
Epoch 149, Batch 400, Loss: 0.2235, Accuracy: 92.81%, Time Passed: 19.21m
Epoch 149, Batch 500, Loss: 0.2268, Accuracy: 92.78%, Time Passed: 23.63m
Epoch 149 Completed - Average Loss: 0.2280, Accuracy: 92.73%, Epoch Time: 27.92m
Training Complete Epoch 149 - Total Time: 27.92m

✅ Epoch 149 - Training Completed. Starting Evaluation...

python(44559) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44561) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44566) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44568) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5378, Accuracy: 85.50%, Time Passed: 4.08m
Evaluation Complete - Loss: 0.5525, Accuracy: 86.27%, Total Time: 7.44m

📊 Epoch 149 - Evaluation Completed.


🚀 Epoch 150 - Training Started...

python(44618) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44620) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44622) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44624) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 150, Batch 100, Loss: 0.2303, Accuracy: 92.81%, Time Passed: 4.88m
Epoch 150, Batch 200, Loss: 0.2339, Accuracy: 92.70%, Time Passed: 9.16m
Epoch 150, Batch 300, Loss: 0.2366, Accuracy: 92.51%, Time Passed: 13.86m
Epoch 150, Batch 400, Loss: 0.2354, Accuracy: 92.59%, Time Passed: 18.48m
Epoch 150, Batch 500, Loss: 0.2360, Accuracy: 92.62%, Time Passed: 24.04m
Epoch 150 Completed - Average Loss: 0.2328, Accuracy: 92.64%, Epoch Time: 27.80m
Training Complete Epoch 150 - Total Time: 27.80m

✅ Epoch 150 - Training Completed. Starting Evaluation...

python(44931) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44934) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44936) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44939) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5659, Accuracy: 84.19%, Time Passed: 4.17m
Evaluation Complete - Loss: 0.5565, Accuracy: 85.79%, Total Time: 7.70m

📊 Epoch 150 - Evaluation Completed.

In [107]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_top_30_{start_epoch}_{end_epoch}.pkl')

In [108]:
del training_states

In [109]:
state, generator = setup_reproducibility(continue_run=True, path="Training outputs/rng_state_150.pkl", mode="save", seed=seeds[1], generator=generator)

✅ RNG state saved to Training outputs/rng_state_150.pkl

In [49]:
training_states = joblib.load("Training outputs/training_states_top_30_141_150.pkl"
)
mobilenetv2_stageF_top_30 = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes)) 
device = torch.device("mps") 
mobilenetv2_stageF_top_30.to(device)
mobilenetv2_stageF_top_30.load_state_dict(training_states[150]["model_state_dict"])
del training_states

norm_sqrt_inv_weights_train = compute_class_weights(train_dataset, method="sqrt_inverse", normalize=True)
norm_sqrt_inv_weights_train_top_30 = compute_class_weights(web_top_30_dataset, method="sqrt_inverse", normalize=True)   
norm_sqrt_inv_weights_train_top_30[-1] = 0 # handel other class
norm_sqrt_inv_weights = (norm_sqrt_inv_weights_train + (2*norm_sqrt_inv_weights_train_top_30))/2
norm_sqrt_inv_criterion = nn.CrossEntropyLoss(weight=norm_sqrt_inv_weights)

web_datasets_dict_list = [{'All Web Data': web_dataset},
 {'Web Correctly Classified': web_correctly_classified_dataset},
 {'Web Top 30': web_top_30_dataset}, 
 {'Web Mid_30_70': web_mid_30_70_dataset},
 {'Web Lowest 30': web_lowest_30_dataset}
]

> **Evaluation-set note:** The label `unseen` is retained from the historical code. It means that these web images were not used for training the current branch; however, they belong to the broader web pool previously used for performance stratification and should not be interpreted as an independent unseen test set.

In [50]:
top_30_all_results, top_30_metrics_summary = evaluate_on_three_sets(
    mobilenetv2_stageF_top_30,
    web_datasets_dict_list[2],          # {'Web Top 30': web_top_30_dataset}
    web_datasets_dict_list[0],         # {'All Web Data': web_dataset}
    [d for i, d in enumerate(web_datasets_dict_list) if i not in (0, 2)],      # list of dicts, each has one dataset
    val_transform,
    "mobilenetv2_stageF_top_30",
    norm_sqrt_inv_criterion,
    train_dataset.classes,
    epoch_num=150,
    log_interval=100,
    batch_size=32,
    num_workers=4
)

🔹 Starting evaluation for: Web Top 30 (used in training)
Evaluation Complete - Loss: 0.5333, Accuracy: 80.08%, Total Time: 0.55m

🔹 Starting evaluation for: All Web Data
Batch 100, Loss: 2.0355, Accuracy: 56.38%, Time Passed: 0.37m
Evaluation Complete - Loss: 2.1240, Accuracy: 58.32%, Total Time: 0.93m

🔹 Starting evaluation for: Web Correctly Classified
Evaluation Complete - Loss: 9.4798, Accuracy: 31.02%, Total Time: 0.60m

🔹 Starting evaluation for: Web Mid_30_70
Evaluation Complete - Loss: 2.4290, Accuracy: 41.38%, Total Time: 0.58m

🔹 Starting evaluation for: Web Lowest 30
Evaluation Complete - Loss: 5.9142, Accuracy: 16.71%, Total Time: 0.55m

🔹 Starting evaluation for: Concatenated Remaining Web Data (unseen)
Batch 100, Loss: 6.4583, Accuracy: 35.25%, Time Passed: 0.37m
Evaluation Complete - Loss: 6.1220, Accuracy: 30.88%, Total Time: 0.84m

In [78]:
## Note on legacy filenames
## Some historical output filenames use the term test. These files contain external web evaluation results and do not represent an independent test set.

In [141]:
top_30_all_results.to_csv("Training outputs/top_30_web_test_150_results.csv", index=False)
top_30_metrics_summary.to_csv("Training outputs/top_30_web_test_150_metrics.csv", index=False)

### Continue training

In [100]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[2])

✅ Random seed set to 2025 (MPS available: True)

In [101]:
training_states = joblib.load("Training outputs/training_states_top_30_141_150.pkl")
mobilenetv2_stageF_top_30 = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes)) 
device = torch.device("mps") 
mobilenetv2_stageF_top_30.to(device)
mobilenetv2_stageF_top_30.load_state_dict(training_states[150]["model_state_dict"])
del training_states

In [146]:
norm_sqrt_inv_weights_train = compute_class_weights(train_dataset, method="sqrt_inverse", normalize=True)
norm_sqrt_inv_weights_train_top_30 = compute_class_weights(web_top_30_dataset, method="sqrt_inverse", normalize=True)   
norm_sqrt_inv_weights_train_top_30[-1] = 0 # handel other class
norm_sqrt_inv_weights = (norm_sqrt_inv_weights_train + (2*norm_sqrt_inv_weights_train_top_30))/2

top_30_val_results141_150 = pd.read_csv("Training outputs/mobilenetv2_stageF_top_30_val_results141_150.csv")

# Step 1: get the subset dataframe
df = top_30_val_results141_150[
    (top_30_val_results141_150['Species'] != "Average Performance (Macro)") &
    (top_30_val_results141_150['Epoch'] == 150)
].copy()

# Step 2: build a mapping from species to recall multiplier
def get_multiplier(recall):
    if recall < 0.6:
        return 10
    elif recall < 0.7:
        return 8
    elif recall < 0.8:
        return 6
    elif recall < 0.9:
        return 4
    elif recall < 1:
        return 2
    else:
        return 1

df['Multiplier'] = df['Recall'].apply(get_multiplier)

# Step 3: make sure class order matches your dataset order
species_to_multiplier = dict(zip(df['Species'], df['Multiplier']))

# Step 4: apply the multipliers to your weight vector
adjusted_weights = norm_sqrt_inv_weights.clone() if hasattr(norm_sqrt_inv_weights, 'clone') else np.copy(norm_sqrt_inv_weights)

for idx, class_name in enumerate(train_dataset.classes):
    if class_name in species_to_multiplier:
        adjusted_weights[idx] *= species_to_multiplier[class_name]

In [147]:
df

,Species,Precision,Recall,F1-score,Epoch,Multiplier
306,Anabasis articulata (Forssk.) Moq.,0.861111,1.000000,0.925373,150,1
307,Anabasis setifera Moq.,0.897590,0.752525,0.818681,150,6
308,Atriplex halimus L.,0.688202,0.871886,0.769231,150,4
309,Calotropis procera,0.960526,0.901235,0.929936,150,2
310,Capparis spinosa L.,0.947761,0.894366,0.920290,150,4
311,Cebatha pendula (J.R.Forst. & G.Forst.) Kuntze,0.931373,0.791667,0.855856,150,6
312,Cenchrus divisus,0.977273,0.988506,0.982857,150,2
313,Deverra tortuosa (Desf.) DC.,0.802326,0.985714,0.884615,150,2
314,Deverra triradiata Hochst. ex Boiss.,0.704225,1.000000,0.826446,150,1
315,Diplotaxis harra (Forssk.) Boiss.,0.890511,0.897059,0.893773,150,4
316,Echinops glaberrimus DC.,0.815574,0.975490,0.888393,150,2
317,Ephedra alata Decne.,0.861538,0.823529,0.842105,150,4
318,Farsetia aegyptia Turra,0.892857,0.675676,0.769231,150,8
319,Gymnocarpos decander Forssk.,0.862319,0.922481,0.891386,150,2
320,Haloxylon salicornicum (Moq.) Bunge ex Boiss.,0.810811,0.882353,0.845070,150,4
321,Heliotropium arbainense Fresen.,0.959391,0.917476,0.937965,150,2
322,Iphiona mucronata (Forssk.) Asch. & Schweinf.,0.967742,1.000000,0.983607,150,1
323,Limonium pruinosum (L.) Chaz.,0.855263,0.730337,0.787879,150,6
324,Lycium shawii Roem. & Schult.,0.824324,0.653571,0.729084,150,8
325,Nitraria retusa (Forssk.) Asch.,0.761745,0.722930,0.741830,150,6
326,Ochradenus baccatus Delile,0.935547,0.961847,0.948515,150,2
327,Peganum harmala L.,0.733333,1.000000,0.846154,150,1
328,Rumex vesicarius L.,0.955056,1.000000,0.977011,150,1
329,Salsola imbricata Forssk.,0.945946,1.000000,0.972222,150,1
330,Stachys aegyptiaca Pers.,0.709677,1.000000,0.830189,150,1
331,Suaeda aegyptiaca (Hasselq.) Zohary,0.792683,0.977444,0.875421,150,2
332,Tamarix nilotica (Ehrenb.) Bunge,0.877729,0.628125,0.732240,150,8
333,Trichodesma africanum (L.) Sm.,0.828571,0.520958,0.639706,150,10
334,Zilla spinosa (L.) Prantl,0.905512,1.000000,0.950413,150,1
335,Zygophyllum arabicum (L.) Christenh. & Byng,0.880952,0.992337,0.933333,150,2
336,Zygophyllum coccineum,0.834123,0.907216,0.869136,150,2
337,Zygophyllum molle (Delile) Christenh. & Byng,0.957627,0.991228,0.974138,150,2
338,others,1.000000,0.830000,0.907104,150,4

In [148]:
adjusted_weights, norm_sqrt_inv_weights

(tensor([ 1.0938,  6.8274,  6.0075,  2.4275,  4.5935,  7.5528,  3.1295,  3.7970,
          2.4456,  4.1975,  3.2993,  8.3270,  8.4638,  1.9820,  4.0691,  2.8870,
          2.7015,  9.3570,  8.9568,  5.5509,  1.9259,  1.5881,  1.1269,  0.8456,
          1.2772,  2.1456, 11.5294, 11.0180,  0.8796,  2.4793,  3.4599,  5.1923,
          1.9130], device='mps:0'),
 tensor([1.0938, 1.1379, 1.5019, 1.2137, 1.1484, 1.2588, 1.5647, 1.8985, 2.4456,
         1.0494, 1.6496, 2.0818, 1.0580, 0.9910, 1.0173, 1.4435, 2.7015, 1.5595,
         1.1196, 0.9252, 0.9630, 1.5881, 1.1269, 0.8456, 1.2772, 1.0728, 1.4412,
         1.1018, 0.8796, 1.2396, 1.7300, 2.5961, 0.4783], device='mps:0'))

In [149]:
norm_sqrt_inv_criterion = nn.CrossEntropyLoss(weight=adjusted_weights)
stageF_optimizer = torch.optim.AdamW(mobilenetv2_stageF_top_30.parameters(), lr=1e-5,
                            weight_decay=1e-4, betas=(0.9, 0.999))

In [106]:
start_epoch = 151
end_epoch = 155
start_epoch, end_epoch

(151, 155)

In [107]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_top_30, full_web_top_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_top_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 151 - Training Started...

Epoch 151, Batch 100, Loss: 0.2451, Accuracy: 92.22%, Time Passed: 3.75m
Epoch 151, Batch 200, Loss: 0.2274, Accuracy: 92.53%, Time Passed: 7.74m
Epoch 151, Batch 300, Loss: 0.2188, Accuracy: 92.69%, Time Passed: 11.52m
Epoch 151, Batch 400, Loss: 0.2180, Accuracy: 92.68%, Time Passed: 15.44m
Epoch 151, Batch 500, Loss: 0.2147, Accuracy: 92.73%, Time Passed: 19.20m
Epoch 151 Completed - Average Loss: 0.2141, Accuracy: 92.69%, Epoch Time: 21.88m
Training Complete Epoch 151 - Total Time: 21.88m

✅ Epoch 151 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5198, Accuracy: 85.91%, Time Passed: 3.95m
Evaluation Complete - Loss: 0.5439, Accuracy: 86.79%, Total Time: 7.11m

📊 Epoch 151 - Evaluation Completed.


🚀 Epoch 152 - Training Started...

Epoch 152, Batch 100, Loss: 0.2054, Accuracy: 92.69%, Time Passed: 3.57m
Epoch 152, Batch 200, Loss: 0.1949, Accuracy: 92.38%, Time Passed: 7.24m
Epoch 152, Batch 300, Loss: 0.1920, Accuracy: 92.59%, Time Passed: 10.89m
Epoch 152, Batch 400, Loss: 0.1961, Accuracy: 92.39%, Time Passed: 14.59m
Epoch 152, Batch 500, Loss: 0.1938, Accuracy: 92.46%, Time Passed: 18.47m
Epoch 152 Completed - Average Loss: 0.1908, Accuracy: 92.47%, Epoch Time: 21.38m
Training Complete Epoch 152 - Total Time: 21.38m

✅ Epoch 152 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5147, Accuracy: 85.69%, Time Passed: 4.61m
Evaluation Complete - Loss: 0.5048, Accuracy: 86.96%, Total Time: 8.26m

📊 Epoch 152 - Evaluation Completed.


🚀 Epoch 153 - Training Started...

Epoch 153, Batch 100, Loss: 0.2003, Accuracy: 92.34%, Time Passed: 4.95m
Epoch 153, Batch 200, Loss: 0.2063, Accuracy: 92.12%, Time Passed: 10.26m
Epoch 153, Batch 300, Loss: 0.2037, Accuracy: 92.19%, Time Passed: 16.46m
Epoch 153, Batch 400, Loss: 0.1934, Accuracy: 92.52%, Time Passed: 22.21m
Epoch 153, Batch 500, Loss: 0.1937, Accuracy: 92.43%, Time Passed: 27.77m
Epoch 153 Completed - Average Loss: 0.1946, Accuracy: 92.35%, Epoch Time: 31.80m
Training Complete Epoch 153 - Total Time: 31.80m

✅ Epoch 153 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4782, Accuracy: 86.16%, Time Passed: 5.24m
Evaluation Complete - Loss: 0.4837, Accuracy: 87.13%, Total Time: 9.22m

📊 Epoch 153 - Evaluation Completed.


🚀 Epoch 154 - Training Started...

Epoch 154, Batch 100, Loss: 0.1883, Accuracy: 92.72%, Time Passed: 4.82m
Epoch 154, Batch 200, Loss: 0.2030, Accuracy: 92.42%, Time Passed: 9.79m
Epoch 154, Batch 300, Loss: 0.1984, Accuracy: 92.52%, Time Passed: 14.85m
Epoch 154, Batch 400, Loss: 0.1944, Accuracy: 92.63%, Time Passed: 19.83m
Epoch 154, Batch 500, Loss: 0.1947, Accuracy: 92.71%, Time Passed: 24.93m
Epoch 154 Completed - Average Loss: 0.1941, Accuracy: 92.57%, Epoch Time: 28.72m
Training Complete Epoch 154 - Total Time: 28.72m

✅ Epoch 154 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5096, Accuracy: 86.00%, Time Passed: 4.33m
Evaluation Complete - Loss: 0.5052, Accuracy: 87.09%, Total Time: 7.59m

📊 Epoch 154 - Evaluation Completed.


🚀 Epoch 155 - Training Started...

Epoch 155, Batch 100, Loss: 0.1836, Accuracy: 92.28%, Time Passed: 3.82m
Epoch 155, Batch 200, Loss: 0.1897, Accuracy: 92.42%, Time Passed: 7.56m
Epoch 155, Batch 300, Loss: 0.1936, Accuracy: 92.19%, Time Passed: 11.33m
Epoch 155, Batch 400, Loss: 0.1877, Accuracy: 92.30%, Time Passed: 15.08m
Epoch 155, Batch 500, Loss: 0.1905, Accuracy: 92.29%, Time Passed: 18.90m
Epoch 155 Completed - Average Loss: 0.1895, Accuracy: 92.40%, Epoch Time: 21.68m
Training Complete Epoch 155 - Total Time: 21.68m

✅ Epoch 155 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4704, Accuracy: 86.97%, Time Passed: 4.19m
Evaluation Complete - Loss: 0.4945, Accuracy: 87.59%, Total Time: 7.51m

📊 Epoch 155 - Evaluation Completed.

In [110]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_top_30_{start_epoch}_{end_epoch}.pkl')

In [139]:
top_30_all_results_155, top_30_metrics_summary_155 = evaluate_on_three_sets(
    mobilenetv2_stageF_top_30,
    web_datasets_dict_list[2],          # {'Web Top 30': web_top_30_dataset}
    web_datasets_dict_list[0],         # {'All Web Data': web_dataset}
    [d for i, d in enumerate(web_datasets_dict_list) if i not in (0, 2)],      # list of dicts, each has one dataset
    val_transform,
    "mobilenetv2_stageF_top_30",
    norm_sqrt_inv_criterion,
    train_dataset.classes,
    epoch_num=155,
    log_interval=100,
    batch_size=32,
    num_workers=4
)

🔹 Starting evaluation for: Web Top 30 (used in training)

python(10356) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10358) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10360) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10362) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Evaluation Complete - Loss: 0.5421, Accuracy: 80.00%, Total Time: 0.69m

🔹 Starting evaluation for: All Web Data

python(10405) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10407) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10409) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10411) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 2.0106, Accuracy: 57.47%, Time Passed: 0.46m
Evaluation Complete - Loss: 2.2323, Accuracy: 56.89%, Total Time: 1.04m

🔹 Starting evaluation for: Web Correctly Classified

python(10420) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10422) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10424) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10426) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Evaluation Complete - Loss: 9.5093, Accuracy: 31.40%, Total Time: 0.67m

🔹 Starting evaluation for: Web Mid_30_70

python(10440) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10442) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10444) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10447) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Evaluation Complete - Loss: 2.5768, Accuracy: 37.75%, Total Time: 0.68m

🔹 Starting evaluation for: Web Lowest 30

python(10467) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10469) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10471) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10476) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Evaluation Complete - Loss: 6.2854, Accuracy: 12.64%, Total Time: 0.64m

🔹 Starting evaluation for: Concatenated Remaining Web Data (unseen)

python(10496) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10499) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10501) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10503) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 6.5327, Accuracy: 33.84%, Time Passed: 0.53m
Evaluation Complete - Loss: 6.2519, Accuracy: 28.71%, Total Time: 1.01m

In [142]:
top_30_all_results_155.to_csv("Training outputs/top_30_web_test_155_results.csv", index=False)
top_30_metrics_summary_155.to_csv("Training outputs/top_30_web_test_155_metrics.csv", index=False)

In [150]:
val_res = evaluate_model(mobilenetv2_stageF_top_30, val_loader, norm_sqrt_inv_criterion, train_dataset.classes, epoch_num=155, log_interval=100)

python(10820) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10822) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10824) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10826) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4704, Accuracy: 86.97%, Time Passed: 5.75m
Evaluation Complete - Loss: 0.4945, Accuracy: 87.59%, Total Time: 9.85m

In [151]:
start_epoch = 156
end_epoch = 160
start_epoch, end_epoch

(156, 160)

In [152]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_top_30, full_web_top_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_top_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 156 - Training Started...

python(10913) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10916) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10918) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(10920) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 156, Batch 100, Loss: 0.1983, Accuracy: 92.44%, Time Passed: 6.93m
Epoch 156, Batch 200, Loss: 0.1813, Accuracy: 92.95%, Time Passed: 15.27m
Epoch 156, Batch 300, Loss: 0.1817, Accuracy: 92.89%, Time Passed: 28.35m
Epoch 156, Batch 400, Loss: 0.1778, Accuracy: 92.83%, Time Passed: 36.50m
Epoch 156, Batch 500, Loss: 0.1760, Accuracy: 92.86%, Time Passed: 42.62m
Epoch 156 Completed - Average Loss: 0.1784, Accuracy: 92.79%, Epoch Time: 46.08m
Training Complete Epoch 156 - Total Time: 46.08m

✅ Epoch 156 - Training Completed. Starting Evaluation...

python(11965) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(11968) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(11970) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(11972) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4829, Accuracy: 86.91%, Time Passed: 4.25m
Evaluation Complete - Loss: 0.5030, Accuracy: 87.43%, Total Time: 7.83m

📊 Epoch 156 - Evaluation Completed.


🚀 Epoch 157 - Training Started...

python(12002) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12004) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12006) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12011) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 157, Batch 100, Loss: 0.1597, Accuracy: 93.12%, Time Passed: 5.41m
Epoch 157, Batch 200, Loss: 0.1729, Accuracy: 92.67%, Time Passed: 10.57m
Epoch 157, Batch 300, Loss: 0.1887, Accuracy: 92.48%, Time Passed: 15.64m
Epoch 157, Batch 400, Loss: 0.1921, Accuracy: 92.41%, Time Passed: 20.21m
Epoch 157, Batch 500, Loss: 0.1908, Accuracy: 92.39%, Time Passed: 25.04m
Epoch 157 Completed - Average Loss: 0.1897, Accuracy: 92.46%, Epoch Time: 28.57m
Training Complete Epoch 157 - Total Time: 28.57m

✅ Epoch 157 - Training Completed. Starting Evaluation...

python(12427) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12429) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12433) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12435) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4711, Accuracy: 86.88%, Time Passed: 4.34m
Evaluation Complete - Loss: 0.4998, Accuracy: 87.31%, Total Time: 8.04m

📊 Epoch 157 - Evaluation Completed.


🚀 Epoch 158 - Training Started...

python(12481) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12498) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12501) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12503) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 158, Batch 100, Loss: 0.1976, Accuracy: 92.25%, Time Passed: 5.14m
Epoch 158, Batch 200, Loss: 0.2085, Accuracy: 92.09%, Time Passed: 9.64m
Epoch 158, Batch 300, Loss: 0.1906, Accuracy: 92.61%, Time Passed: 14.33m
Epoch 158, Batch 400, Loss: 0.1928, Accuracy: 92.45%, Time Passed: 19.64m
Epoch 158, Batch 500, Loss: 0.1889, Accuracy: 92.46%, Time Passed: 24.36m
Epoch 158 Completed - Average Loss: 0.1870, Accuracy: 92.54%, Epoch Time: 27.58m
Training Complete Epoch 158 - Total Time: 27.58m

✅ Epoch 158 - Training Completed. Starting Evaluation...

python(12821) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12823) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12826) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12829) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4667, Accuracy: 86.97%, Time Passed: 4.78m
Evaluation Complete - Loss: 0.4741, Accuracy: 87.59%, Total Time: 8.87m

📊 Epoch 158 - Evaluation Completed.


🚀 Epoch 159 - Training Started...

python(12904) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12907) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12912) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(12916) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 159, Batch 100, Loss: 0.1725, Accuracy: 92.78%, Time Passed: 6.02m
Epoch 159, Batch 200, Loss: 0.1751, Accuracy: 92.69%, Time Passed: 11.24m
Epoch 159, Batch 300, Loss: 0.1812, Accuracy: 92.78%, Time Passed: 16.20m
Epoch 159, Batch 400, Loss: 0.1804, Accuracy: 92.77%, Time Passed: 21.17m
Epoch 159, Batch 500, Loss: 0.1814, Accuracy: 92.78%, Time Passed: 26.12m
Epoch 159 Completed - Average Loss: 0.1825, Accuracy: 92.66%, Epoch Time: 29.78m
Training Complete Epoch 159 - Total Time: 29.78m

✅ Epoch 159 - Training Completed. Starting Evaluation...

python(13326) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(13328) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(13330) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(13332) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4711, Accuracy: 86.72%, Time Passed: 4.56m
Evaluation Complete - Loss: 0.4798, Accuracy: 87.56%, Total Time: 8.17m

📊 Epoch 159 - Evaluation Completed.


🚀 Epoch 160 - Training Started...

python(13360) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(13362) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(13364) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(13366) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 160, Batch 100, Loss: 0.1915, Accuracy: 92.53%, Time Passed: 5.46m
Epoch 160, Batch 200, Loss: 0.1821, Accuracy: 92.84%, Time Passed: 10.73m
Epoch 160, Batch 300, Loss: 0.1871, Accuracy: 92.60%, Time Passed: 15.61m
Epoch 160, Batch 400, Loss: 0.1866, Accuracy: 92.45%, Time Passed: 21.08m
Epoch 160, Batch 500, Loss: 0.1885, Accuracy: 92.35%, Time Passed: 26.01m
Epoch 160 Completed - Average Loss: 0.1867, Accuracy: 92.44%, Epoch Time: 29.83m
Training Complete Epoch 160 - Total Time: 29.83m

✅ Epoch 160 - Training Completed. Starting Evaluation...

python(13953) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(13955) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(13958) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(13961) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4707, Accuracy: 86.78%, Time Passed: 4.88m
Evaluation Complete - Loss: 0.4880, Accuracy: 87.44%, Total Time: 8.80m

📊 Epoch 160 - Evaluation Completed.

In [153]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_top_30_{start_epoch}_{end_epoch}.pkl')

### Continue training

In [57]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[0])

✅ Random seed set to 42 (MPS available: True)

In [58]:
training_states = joblib.load("Training outputs/training_states_top_30_156_160.pkl")
mobilenetv2_stageF_top_30 = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes)) 
device = torch.device("mps") 
mobilenetv2_stageF_top_30.to(device)
mobilenetv2_stageF_top_30.load_state_dict(training_states[160]["model_state_dict"])
del training_states

- **Note on validation-output organization**
- Validation CSV files generated during training were subsequently organized manually into the top_val_results/ and lowest_val_results/ subdirectories. These - paths therefore refer to the organized output structure rather than the original save location.

In [146]:
norm_sqrt_inv_weights_train = compute_class_weights(train_dataset, method="sqrt_inverse", normalize=True)
norm_sqrt_inv_weights_train_top_30 = compute_class_weights(web_top_30_dataset, method="sqrt_inverse", normalize=True)   
norm_sqrt_inv_weights_train_top_30[-1] = 0 # handel other class
norm_sqrt_inv_weights = (norm_sqrt_inv_weights_train + (2*norm_sqrt_inv_weights_train_top_30))/2

top_30_val_results156_160 = pd.read_csv("Training outputs/top_val_results/mobilenetv2_stageF_top_30_val_results156_160.csv")

# Step 1: get the subset dataframe
df = top_30_val_results156_160[
    (top_30_val_results156_160['Species'] != "Average Performance (Macro)") &
    (top_30_val_results156_160['Epoch'] == 160)
].copy()

# Step 2: build a mapping from species to recall multiplier
def get_multiplier(recall):
    if recall < 0.6:
        return 10
    elif recall < 0.7:
        return 8
    elif recall < 0.8:
        return 6
    elif recall < 0.9:
        return 4
    elif recall < 1:
        return 2
    else:
        return 1

df['Multiplier'] = df['Recall'].apply(get_multiplier)

# Step 3: make sure class order matches your dataset order
species_to_multiplier = dict(zip(df['Species'], df['Multiplier']))

# Step 4: apply the multipliers to your weight vector
adjusted_weights = norm_sqrt_inv_weights.clone() if hasattr(norm_sqrt_inv_weights, 'clone') else np.copy(norm_sqrt_inv_weights)

for idx, class_name in enumerate(train_dataset.classes):
    if class_name in species_to_multiplier:
        adjusted_weights[idx] *= species_to_multiplier[class_name]

In [60]:
df

,Species,Precision,Recall,F1-score,Epoch,Multiplier
136,Anabasis articulata (Forssk.) Moq.,0.953125,0.983871,0.968254,160,2
137,Anabasis setifera Moq.,0.881720,0.828283,0.854167,160,4
138,Atriplex halimus L.,0.753994,0.839858,0.794613,160,4
139,Calotropis procera,0.961039,0.913580,0.936709,160,2
140,Capparis spinosa L.,0.961240,0.873239,0.915129,160,4
141,Cebatha pendula (J.R.Forst. & G.Forst.) Kuntze,0.921569,0.783333,0.846847,160,6
142,Cenchrus divisus,0.988636,1.000000,0.994286,160,1
143,Deverra tortuosa (Desf.) DC.,0.777778,1.000000,0.875000,160,1
144,Deverra triradiata Hochst. ex Boiss.,0.859649,0.980000,0.915888,160,2
145,Diplotaxis harra (Forssk.) Boiss.,0.808917,0.933824,0.866894,160,2
146,Echinops glaberrimus DC.,0.843049,0.921569,0.880562,160,2
147,Ephedra alata Decne.,0.844749,0.906863,0.874704,160,2
148,Farsetia aegyptia Turra,0.865854,0.767568,0.813754,160,6
149,Gymnocarpos decander Forssk.,0.859155,0.945736,0.900369,160,2
150,Haloxylon salicornicum (Moq.) Bunge ex Boiss.,0.806122,0.929412,0.863388,160,2
151,Heliotropium arbainense Fresen.,0.994624,0.898058,0.943878,160,4
152,Iphiona mucronata (Forssk.) Asch. & Schweinf.,0.983607,1.000000,0.991736,160,1
153,Limonium pruinosum (L.) Chaz.,0.904110,0.741573,0.814815,160,6
154,Lycium shawii Roem. & Schult.,0.785156,0.717857,0.750000,160,6
155,Nitraria retusa (Forssk.) Asch.,0.803175,0.805732,0.804452,160,4
156,Ochradenus baccatus Delile,0.925287,0.969880,0.947059,160,2
157,Peganum harmala L.,0.733333,1.000000,0.846154,160,1
158,Rumex vesicarius L.,0.955056,1.000000,0.977011,160,1
159,Salsola imbricata Forssk.,0.972222,1.000000,0.985915,160,1
160,Stachys aegyptiaca Pers.,0.868421,1.000000,0.929577,160,1
161,Suaeda aegyptiaca (Hasselq.) Zohary,0.881119,0.947368,0.913043,160,2
162,Tamarix nilotica (Ehrenb.) Bunge,0.901786,0.631250,0.742647,160,8
163,Trichodesma africanum (L.) Sm.,0.865385,0.538922,0.664207,160,10
164,Zilla spinosa (L.) Prantl,0.934959,1.000000,0.966387,160,1
165,Zygophyllum arabicum (L.) Christenh. & Byng,0.888889,0.980843,0.932605,160,2
166,Zygophyllum coccineum,0.786026,0.927835,0.851064,160,2
167,Zygophyllum molle (Delile) Christenh. & Byng,0.982609,0.991228,0.986900,160,2
168,others,0.977011,0.850000,0.909091,160,4

In [147]:
adjusted_weights, norm_sqrt_inv_weights

(tensor([ 2.1876,  4.5516,  6.0075,  2.4275,  4.5935,  7.5528,  1.5647,  1.8985,
          4.8911,  2.0988,  3.2993,  4.1635,  6.3478,  1.9820,  2.0345,  5.7740,
          2.7015,  9.3570,  6.7176,  3.7006,  1.9259,  1.5881,  1.1269,  0.8456,
          1.2772,  2.1456, 11.5294, 11.0180,  0.8796,  2.4793,  3.4599,  5.1923,
          1.9130], device='mps:0'),
 tensor([1.0938, 1.1379, 1.5019, 1.2137, 1.1484, 1.2588, 1.5647, 1.8985, 2.4456,
         1.0494, 1.6496, 2.0818, 1.0580, 0.9910, 1.0173, 1.4435, 2.7015, 1.5595,
         1.1196, 0.9252, 0.9630, 1.5881, 1.1269, 0.8456, 1.2772, 1.0728, 1.4412,
         1.1018, 0.8796, 1.2396, 1.7300, 2.5961, 0.4783], device='mps:0'))

In [148]:
norm_sqrt_inv_criterion = nn.CrossEntropyLoss(weight=adjusted_weights)
stageF_optimizer = torch.optim.AdamW(mobilenetv2_stageF_top_30.parameters(), lr=1e-5,
                            weight_decay=1e-4, betas=(0.9, 0.999))

In [63]:
start_epoch = 161
end_epoch = 180
start_epoch, end_epoch

(161, 180)

In [64]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_top_30, full_web_top_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_top_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 161 - Training Started...

Epoch 161, Batch 100, Loss: 0.1827, Accuracy: 92.44%, Time Passed: 3.84m
Epoch 161, Batch 200, Loss: 0.1880, Accuracy: 92.20%, Time Passed: 7.65m
Epoch 161, Batch 300, Loss: 0.1812, Accuracy: 92.46%, Time Passed: 11.22m
Epoch 161, Batch 400, Loss: 0.1819, Accuracy: 92.34%, Time Passed: 14.87m
Epoch 161, Batch 500, Loss: 0.1781, Accuracy: 92.58%, Time Passed: 18.64m
Epoch 161 Completed - Average Loss: 0.1777, Accuracy: 92.70%, Epoch Time: 21.53m
Training Complete Epoch 161 - Total Time: 21.53m

✅ Epoch 161 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4824, Accuracy: 86.84%, Time Passed: 4.33m
Evaluation Complete - Loss: 0.5045, Accuracy: 87.33%, Total Time: 7.51m

📊 Epoch 161 - Evaluation Completed.


🚀 Epoch 162 - Training Started...

Epoch 162, Batch 100, Loss: 0.1700, Accuracy: 93.84%, Time Passed: 3.79m
Epoch 162, Batch 200, Loss: 0.1707, Accuracy: 93.38%, Time Passed: 7.34m
Epoch 162, Batch 300, Loss: 0.1707, Accuracy: 93.18%, Time Passed: 11.01m
Epoch 162, Batch 400, Loss: 0.1694, Accuracy: 93.09%, Time Passed: 14.75m
Epoch 162, Batch 500, Loss: 0.1704, Accuracy: 93.12%, Time Passed: 18.26m
Epoch 162 Completed - Average Loss: 0.1714, Accuracy: 93.07%, Epoch Time: 21.05m
Training Complete Epoch 162 - Total Time: 21.05m

✅ Epoch 162 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4699, Accuracy: 86.94%, Time Passed: 4.16m
Evaluation Complete - Loss: 0.4776, Accuracy: 87.65%, Total Time: 7.50m

📊 Epoch 162 - Evaluation Completed.


🚀 Epoch 163 - Training Started...

Epoch 163, Batch 100, Loss: 0.1870, Accuracy: 92.62%, Time Passed: 3.59m
Epoch 163, Batch 200, Loss: 0.1855, Accuracy: 92.69%, Time Passed: 7.29m
Epoch 163, Batch 300, Loss: 0.1777, Accuracy: 92.75%, Time Passed: 10.91m
Epoch 163, Batch 400, Loss: 0.1819, Accuracy: 92.71%, Time Passed: 14.61m
Epoch 163, Batch 500, Loss: 0.1742, Accuracy: 93.03%, Time Passed: 18.19m
Epoch 163 Completed - Average Loss: 0.1712, Accuracy: 93.13%, Epoch Time: 20.83m
Training Complete Epoch 163 - Total Time: 20.83m

✅ Epoch 163 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4629, Accuracy: 87.22%, Time Passed: 4.07m
Evaluation Complete - Loss: 0.4916, Accuracy: 87.72%, Total Time: 7.32m

📊 Epoch 163 - Evaluation Completed.


🚀 Epoch 164 - Training Started...

Epoch 164, Batch 100, Loss: 0.1654, Accuracy: 93.25%, Time Passed: 3.66m
Epoch 164, Batch 200, Loss: 0.1640, Accuracy: 93.19%, Time Passed: 7.29m
Epoch 164, Batch 300, Loss: 0.1743, Accuracy: 93.02%, Time Passed: 10.93m
Epoch 164, Batch 400, Loss: 0.1744, Accuracy: 92.97%, Time Passed: 14.53m
Epoch 164, Batch 500, Loss: 0.1752, Accuracy: 92.96%, Time Passed: 18.07m
Epoch 164 Completed - Average Loss: 0.1736, Accuracy: 93.01%, Epoch Time: 20.61m
Training Complete Epoch 164 - Total Time: 20.61m

✅ Epoch 164 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4796, Accuracy: 86.59%, Time Passed: 3.96m
Evaluation Complete - Loss: 0.4818, Accuracy: 87.56%, Total Time: 7.10m

📊 Epoch 164 - Evaluation Completed.


🚀 Epoch 165 - Training Started...

Epoch 165, Batch 100, Loss: 0.1704, Accuracy: 93.09%, Time Passed: 3.49m
Epoch 165, Batch 200, Loss: 0.1754, Accuracy: 93.05%, Time Passed: 7.04m
Epoch 165, Batch 300, Loss: 0.1722, Accuracy: 93.28%, Time Passed: 10.59m
Epoch 165, Batch 400, Loss: 0.1681, Accuracy: 93.36%, Time Passed: 14.12m
Epoch 165, Batch 500, Loss: 0.1667, Accuracy: 93.36%, Time Passed: 17.60m
Epoch 165 Completed - Average Loss: 0.1681, Accuracy: 93.26%, Epoch Time: 20.19m
Training Complete Epoch 165 - Total Time: 20.19m

✅ Epoch 165 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4788, Accuracy: 86.91%, Time Passed: 3.90m
Evaluation Complete - Loss: 0.4837, Accuracy: 87.61%, Total Time: 6.97m

📊 Epoch 165 - Evaluation Completed.


🚀 Epoch 166 - Training Started...

Epoch 166, Batch 100, Loss: 0.1597, Accuracy: 93.28%, Time Passed: 3.49m
Epoch 166, Batch 200, Loss: 0.1677, Accuracy: 92.91%, Time Passed: 7.01m
Epoch 166, Batch 300, Loss: 0.1698, Accuracy: 92.91%, Time Passed: 10.51m
Epoch 166, Batch 400, Loss: 0.1698, Accuracy: 93.00%, Time Passed: 14.01m
Epoch 166, Batch 500, Loss: 0.1660, Accuracy: 93.14%, Time Passed: 17.63m
Epoch 166 Completed - Average Loss: 0.1682, Accuracy: 93.00%, Epoch Time: 20.23m
Training Complete Epoch 166 - Total Time: 20.23m

✅ Epoch 166 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4990, Accuracy: 86.03%, Time Passed: 3.87m
Evaluation Complete - Loss: 0.5063, Accuracy: 87.09%, Total Time: 6.99m

📊 Epoch 166 - Evaluation Completed.


🚀 Epoch 167 - Training Started...

Epoch 167, Batch 100, Loss: 0.1912, Accuracy: 92.88%, Time Passed: 3.45m
Epoch 167, Batch 200, Loss: 0.1808, Accuracy: 92.94%, Time Passed: 6.92m
Epoch 167, Batch 300, Loss: 0.1728, Accuracy: 93.16%, Time Passed: 10.51m
Epoch 167, Batch 400, Loss: 0.1753, Accuracy: 92.98%, Time Passed: 13.96m
Epoch 167, Batch 500, Loss: 0.1743, Accuracy: 92.94%, Time Passed: 17.44m
Epoch 167 Completed - Average Loss: 0.1725, Accuracy: 93.02%, Epoch Time: 20.07m
Training Complete Epoch 167 - Total Time: 20.07m

✅ Epoch 167 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4771, Accuracy: 87.09%, Time Passed: 3.87m
Evaluation Complete - Loss: 0.4532, Accuracy: 88.04%, Total Time: 6.94m

📊 Epoch 167 - Evaluation Completed.


🚀 Epoch 168 - Training Started...

Epoch 168, Batch 100, Loss: 0.1763, Accuracy: 92.31%, Time Passed: 3.94m
Epoch 168, Batch 200, Loss: 0.1684, Accuracy: 92.84%, Time Passed: 7.78m
Epoch 168, Batch 300, Loss: 0.1641, Accuracy: 93.21%, Time Passed: 11.80m
Epoch 168, Batch 400, Loss: 0.1644, Accuracy: 93.24%, Time Passed: 15.79m
Epoch 168, Batch 500, Loss: 0.1646, Accuracy: 93.22%, Time Passed: 19.69m
Epoch 168 Completed - Average Loss: 0.1649, Accuracy: 93.25%, Epoch Time: 22.60m
Training Complete Epoch 168 - Total Time: 22.60m

✅ Epoch 168 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4716, Accuracy: 86.94%, Time Passed: 3.90m
Evaluation Complete - Loss: 0.4571, Accuracy: 87.85%, Total Time: 7.03m

📊 Epoch 168 - Evaluation Completed.


🚀 Epoch 169 - Training Started...

Epoch 169, Batch 100, Loss: 0.1780, Accuracy: 92.75%, Time Passed: 3.97m
Epoch 169, Batch 200, Loss: 0.1737, Accuracy: 92.75%, Time Passed: 7.85m
Epoch 169, Batch 300, Loss: 0.1662, Accuracy: 93.21%, Time Passed: 11.92m
Epoch 169, Batch 400, Loss: 0.1604, Accuracy: 93.39%, Time Passed: 15.92m
Epoch 169, Batch 500, Loss: 0.1647, Accuracy: 93.16%, Time Passed: 19.96m
Epoch 169 Completed - Average Loss: 0.1659, Accuracy: 93.14%, Epoch Time: 22.86m
Training Complete Epoch 169 - Total Time: 22.86m

✅ Epoch 169 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4591, Accuracy: 87.88%, Time Passed: 3.87m
Evaluation Complete - Loss: 0.4560, Accuracy: 88.36%, Total Time: 6.96m

📊 Epoch 169 - Evaluation Completed.


🚀 Epoch 170 - Training Started...

Epoch 170, Batch 100, Loss: 0.1861, Accuracy: 92.81%, Time Passed: 3.97m
Epoch 170, Batch 200, Loss: 0.1762, Accuracy: 93.20%, Time Passed: 7.81m
Epoch 170, Batch 300, Loss: 0.1662, Accuracy: 93.39%, Time Passed: 11.72m
Epoch 170, Batch 400, Loss: 0.1646, Accuracy: 93.35%, Time Passed: 15.68m
Epoch 170, Batch 500, Loss: 0.1619, Accuracy: 93.39%, Time Passed: 19.60m
Epoch 170 Completed - Average Loss: 0.1583, Accuracy: 93.47%, Epoch Time: 22.52m
Training Complete Epoch 170 - Total Time: 22.52m

✅ Epoch 170 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4469, Accuracy: 87.44%, Time Passed: 3.93m
Evaluation Complete - Loss: 0.4618, Accuracy: 87.82%, Total Time: 7.07m

📊 Epoch 170 - Evaluation Completed.


🚀 Epoch 171 - Training Started...

Epoch 171, Batch 100, Loss: 0.1742, Accuracy: 92.84%, Time Passed: 4.06m
Epoch 171, Batch 200, Loss: 0.1669, Accuracy: 93.08%, Time Passed: 8.00m
Epoch 171, Batch 300, Loss: 0.1594, Accuracy: 93.27%, Time Passed: 12.02m
Epoch 171, Batch 400, Loss: 0.1626, Accuracy: 93.27%, Time Passed: 15.96m
Epoch 171, Batch 500, Loss: 0.1596, Accuracy: 93.39%, Time Passed: 19.99m
Epoch 171 Completed - Average Loss: 0.1586, Accuracy: 93.35%, Epoch Time: 23.08m
Training Complete Epoch 171 - Total Time: 23.08m

✅ Epoch 171 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4508, Accuracy: 87.78%, Time Passed: 3.90m
Evaluation Complete - Loss: 0.4867, Accuracy: 87.69%, Total Time: 7.00m

📊 Epoch 171 - Evaluation Completed.


🚀 Epoch 172 - Training Started...

Epoch 172, Batch 100, Loss: 0.1975, Accuracy: 92.19%, Time Passed: 4.07m
Epoch 172, Batch 200, Loss: 0.1768, Accuracy: 93.08%, Time Passed: 8.23m
Epoch 172, Batch 300, Loss: 0.1708, Accuracy: 93.11%, Time Passed: 12.38m
Epoch 172, Batch 400, Loss: 0.1703, Accuracy: 93.03%, Time Passed: 16.48m
Epoch 172, Batch 500, Loss: 0.1676, Accuracy: 93.09%, Time Passed: 20.75m
Epoch 172 Completed - Average Loss: 0.1630, Accuracy: 93.29%, Epoch Time: 23.89m
Training Complete Epoch 172 - Total Time: 23.89m

✅ Epoch 172 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4400, Accuracy: 87.81%, Time Passed: 4.19m
Evaluation Complete - Loss: 0.4379, Accuracy: 88.47%, Total Time: 7.40m

📊 Epoch 172 - Evaluation Completed.


🚀 Epoch 173 - Training Started...

Epoch 173, Batch 100, Loss: 0.1675, Accuracy: 92.94%, Time Passed: 4.02m
Epoch 173, Batch 200, Loss: 0.1527, Accuracy: 93.31%, Time Passed: 8.01m
Epoch 173, Batch 300, Loss: 0.1518, Accuracy: 93.44%, Time Passed: 12.09m
Epoch 173, Batch 400, Loss: 0.1543, Accuracy: 93.30%, Time Passed: 16.10m
Epoch 173, Batch 500, Loss: 0.1568, Accuracy: 93.17%, Time Passed: 20.12m
Epoch 173 Completed - Average Loss: 0.1556, Accuracy: 93.24%, Epoch Time: 23.33m
Training Complete Epoch 173 - Total Time: 23.33m

✅ Epoch 173 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4378, Accuracy: 88.00%, Time Passed: 4.13m
Evaluation Complete - Loss: 0.4470, Accuracy: 88.41%, Total Time: 7.46m

📊 Epoch 173 - Evaluation Completed.


🚀 Epoch 174 - Training Started...

Epoch 174, Batch 100, Loss: 0.1613, Accuracy: 93.12%, Time Passed: 4.10m
Epoch 174, Batch 200, Loss: 0.1571, Accuracy: 93.55%, Time Passed: 8.41m
Epoch 174, Batch 300, Loss: 0.1566, Accuracy: 93.39%, Time Passed: 12.60m
Epoch 174, Batch 400, Loss: 0.1562, Accuracy: 93.39%, Time Passed: 16.92m
Epoch 174, Batch 500, Loss: 0.1616, Accuracy: 93.33%, Time Passed: 21.10m
Epoch 174 Completed - Average Loss: 0.1598, Accuracy: 93.41%, Epoch Time: 24.23m
Training Complete Epoch 174 - Total Time: 24.23m

✅ Epoch 174 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4457, Accuracy: 88.12%, Time Passed: 4.18m
Evaluation Complete - Loss: 0.4524, Accuracy: 88.54%, Total Time: 7.53m

📊 Epoch 174 - Evaluation Completed.


🚀 Epoch 175 - Training Started...

Epoch 175, Batch 100, Loss: 0.1385, Accuracy: 93.84%, Time Passed: 3.98m
Epoch 175, Batch 200, Loss: 0.1460, Accuracy: 93.92%, Time Passed: 8.05m
Epoch 175, Batch 300, Loss: 0.1483, Accuracy: 93.86%, Time Passed: 12.32m
Epoch 175, Batch 400, Loss: 0.1497, Accuracy: 93.63%, Time Passed: 16.43m
Epoch 175, Batch 500, Loss: 0.1515, Accuracy: 93.64%, Time Passed: 20.46m
Epoch 175 Completed - Average Loss: 0.1503, Accuracy: 93.68%, Epoch Time: 23.45m
Training Complete Epoch 175 - Total Time: 23.45m

✅ Epoch 175 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4474, Accuracy: 87.75%, Time Passed: 4.20m
Evaluation Complete - Loss: 0.4312, Accuracy: 88.45%, Total Time: 7.47m

📊 Epoch 175 - Evaluation Completed.


🚀 Epoch 176 - Training Started...

Epoch 176, Batch 100, Loss: 0.1542, Accuracy: 93.59%, Time Passed: 3.91m
Epoch 176, Batch 200, Loss: 0.1487, Accuracy: 93.59%, Time Passed: 7.90m
Epoch 176, Batch 300, Loss: 0.1538, Accuracy: 93.69%, Time Passed: 12.14m
Epoch 176, Batch 400, Loss: 0.1514, Accuracy: 93.64%, Time Passed: 16.47m
Epoch 176, Batch 500, Loss: 0.1549, Accuracy: 93.62%, Time Passed: 20.46m
Epoch 176 Completed - Average Loss: 0.1541, Accuracy: 93.64%, Epoch Time: 23.39m
Training Complete Epoch 176 - Total Time: 23.39m

✅ Epoch 176 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4769, Accuracy: 87.03%, Time Passed: 4.26m
Evaluation Complete - Loss: 0.4525, Accuracy: 88.02%, Total Time: 7.64m

📊 Epoch 176 - Evaluation Completed.


🚀 Epoch 177 - Training Started...

Epoch 177, Batch 100, Loss: 0.1619, Accuracy: 93.22%, Time Passed: 4.00m
Epoch 177, Batch 200, Loss: 0.1487, Accuracy: 93.66%, Time Passed: 7.97m
Epoch 177, Batch 300, Loss: 0.1485, Accuracy: 93.53%, Time Passed: 11.95m
Epoch 177, Batch 400, Loss: 0.1520, Accuracy: 93.41%, Time Passed: 15.93m
Epoch 177, Batch 500, Loss: 0.1514, Accuracy: 93.51%, Time Passed: 19.97m
Epoch 177 Completed - Average Loss: 0.1493, Accuracy: 93.60%, Epoch Time: 22.92m
Training Complete Epoch 177 - Total Time: 22.92m

✅ Epoch 177 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4809, Accuracy: 86.72%, Time Passed: 4.22m
Evaluation Complete - Loss: 0.4840, Accuracy: 87.61%, Total Time: 7.52m

📊 Epoch 177 - Evaluation Completed.


🚀 Epoch 178 - Training Started...

Epoch 178, Batch 100, Loss: 0.1898, Accuracy: 92.03%, Time Passed: 4.10m
Epoch 178, Batch 200, Loss: 0.1704, Accuracy: 92.91%, Time Passed: 8.04m
Epoch 178, Batch 300, Loss: 0.1670, Accuracy: 93.23%, Time Passed: 12.05m
Epoch 178, Batch 400, Loss: 0.1641, Accuracy: 93.30%, Time Passed: 16.44m
Epoch 178, Batch 500, Loss: 0.1612, Accuracy: 93.47%, Time Passed: 20.73m
Epoch 178 Completed - Average Loss: 0.1617, Accuracy: 93.39%, Epoch Time: 23.76m
Training Complete Epoch 178 - Total Time: 23.76m

✅ Epoch 178 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4692, Accuracy: 87.38%, Time Passed: 4.19m
Evaluation Complete - Loss: 0.4596, Accuracy: 88.00%, Total Time: 7.62m

📊 Epoch 178 - Evaluation Completed.


🚀 Epoch 179 - Training Started...

Epoch 179, Batch 100, Loss: 0.1443, Accuracy: 94.47%, Time Passed: 4.02m
Epoch 179, Batch 200, Loss: 0.1481, Accuracy: 94.00%, Time Passed: 8.04m
Epoch 179, Batch 300, Loss: 0.1517, Accuracy: 93.85%, Time Passed: 12.19m
Epoch 179, Batch 400, Loss: 0.1479, Accuracy: 93.95%, Time Passed: 16.33m
Epoch 179, Batch 500, Loss: 0.1525, Accuracy: 93.88%, Time Passed: 20.44m
Epoch 179 Completed - Average Loss: 0.1536, Accuracy: 93.93%, Epoch Time: 23.38m
Training Complete Epoch 179 - Total Time: 23.38m

✅ Epoch 179 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4778, Accuracy: 87.34%, Time Passed: 4.21m
Evaluation Complete - Loss: 0.4876, Accuracy: 87.78%, Total Time: 7.56m

📊 Epoch 179 - Evaluation Completed.


🚀 Epoch 180 - Training Started...

Epoch 180, Batch 100, Loss: 0.1450, Accuracy: 94.03%, Time Passed: 4.11m
Epoch 180, Batch 200, Loss: 0.1520, Accuracy: 93.86%, Time Passed: 8.02m
Epoch 180, Batch 300, Loss: 0.1459, Accuracy: 93.84%, Time Passed: 11.98m
Epoch 180, Batch 400, Loss: 0.1447, Accuracy: 93.84%, Time Passed: 15.97m
Epoch 180, Batch 500, Loss: 0.1474, Accuracy: 93.73%, Time Passed: 20.38m
Epoch 180 Completed - Average Loss: 0.1466, Accuracy: 93.74%, Epoch Time: 23.45m
Training Complete Epoch 180 - Total Time: 23.45m

✅ Epoch 180 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5012, Accuracy: 86.97%, Time Passed: 4.29m
Evaluation Complete - Loss: 0.4814, Accuracy: 87.76%, Total Time: 7.81m

📊 Epoch 180 - Evaluation Completed.

In [66]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_top_30_{start_epoch}_{end_epoch}.pkl')

In [72]:
web_datasets_dict_list = [{'All Web Data': web_dataset},
 {'Web Correctly Classified': web_correctly_classified_dataset},
 {'Web Top 30': web_top_30_dataset}, 
 {'Web Mid_30_70': web_mid_30_70_dataset},
 {'Web Lowest 30': web_lowest_30_dataset}
]
top_30_all_results_180, top_30_metrics_summary_180 = evaluate_on_three_sets(
    mobilenetv2_stageF_top_30,
    web_datasets_dict_list[2],          # {'Web Top 30': web_top_30_dataset}
    web_datasets_dict_list[0],         # {'All Web Data': web_dataset}
    [d for i, d in enumerate(web_datasets_dict_list) if i not in (0, 2)],      # list of dicts, each has one dataset
    val_transform,
    "mobilenetv2_stageF_top_30",
    norm_sqrt_inv_criterion,
    train_dataset.classes,
    epoch_num=180,
    log_interval=100,
    batch_size=32,
    num_workers=4
)

🔹 Starting evaluation for: Web Top 30 (used in training)
Evaluation Complete - Loss: 0.2998, Accuracy: 89.75%, Total Time: 0.74m

🔹 Starting evaluation for: All Web Data
Batch 100, Loss: 1.7287, Accuracy: 63.28%, Time Passed: 0.41m
Evaluation Complete - Loss: 1.9914, Accuracy: 62.07%, Total Time: 0.99m

🔹 Starting evaluation for: Web Correctly Classified
Evaluation Complete - Loss: 9.8288, Accuracy: 31.13%, Total Time: 0.64m

🔹 Starting evaluation for: Web Mid_30_70
Evaluation Complete - Loss: 2.2675, Accuracy: 45.62%, Total Time: 0.64m

🔹 Starting evaluation for: Web Lowest 30
Evaluation Complete - Loss: 5.7182, Accuracy: 17.46%, Total Time: 0.58m

🔹 Starting evaluation for: Concatenated Remaining Web Data (unseen)
Batch 100, Loss: 6.5728, Accuracy: 37.12%, Time Passed: 0.40m
Evaluation Complete - Loss: 6.1378, Accuracy: 32.59%, Total Time: 0.87m

In [73]:
top_30_all_results_180.to_csv("Training outputs/top_30_web_test_180_results.csv", index=False)
top_30_metrics_summary_180.to_csv("Training outputs/top_30_web_test_180_metrics.csv", index=False)

### New Method

In [50]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[2])

✅ Random seed set to 2025 (MPS available: True)

In [51]:
training_states = joblib.load("Training outputs/training_states/training_states_top_30_161_180.pkl")
mobilenetv2_stageF_top_30 = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes)) 
device = torch.device("mps") 
mobilenetv2_stageF_top_30.to(device)
mobilenetv2_stageF_top_30.load_state_dict(training_states[180]["model_state_dict"])
del training_states

In [52]:
default_train_transform = build_train_transform(crop_type="random", scale=(0.2, 1.0))
train_dataset.transform = default_train_transform  
web_top_30_dataset.transform = default_train_transform
val_dataset.transform = val_transform  
full_web_top_30_dataset = ConcatDataset([train_dataset, web_top_30_dataset])
train_dataset.transform

Compose(
      ToImage()
      RandomResizedCrop(size=(224, 224), scale=(0.2, 1.0), ratio=(0.75, 1.33), interpolation=InterpolationMode.BILINEAR, antialias=True)
      RandomHorizontalFlip(p=0.5)
      RandomVerticalFlip(p=0.2)
      RandomApply(    RandomRotation(degrees=[-90.0, 90.0], interpolation=InterpolationMode.BILINEAR, expand=False, fill=0))
      ToDtype(scale=True)
      RandomApply(    ColorJitter(brightness=(0.7, 1.3), contrast=(0.85, 1.3), saturation=(0.7, 1.3), hue=(-0.0278, 0.0278)))
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], inplace=False)
)

In [53]:
full_web_top_30_loader = DataLoader(
    full_web_top_30_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,             # shuffle ensures different order each epoch
    num_workers=4,            # safer on macOS, avoids multiprocessing issues
    pin_memory=True,      
    generator=generator       # ensures reproducible shuffling
)

In [54]:
norm_sqrt_inv_weights_train = compute_class_weights(train_dataset, method="sqrt_inverse", normalize=True)
norm_sqrt_inv_weights_train_top_30 = compute_class_weights(web_top_30_dataset, method="sqrt_inverse", normalize=True)   
norm_sqrt_inv_weights_train_top_30[-1] = 0 # handel other class
norm_sqrt_inv_weights = (norm_sqrt_inv_weights_train + (2*norm_sqrt_inv_weights_train_top_30))/2

In [55]:
top_30_val_results161_180 = pd.read_csv("Training outputs/top_val_results/mobilenetv2_stageF_top_30_val_results161_180.csv")

# Step 1: get the subset dataframe
df = top_30_val_results161_180[
    (top_30_val_results161_180['Species'] != "Average Performance (Macro)") &
    (top_30_val_results161_180['Epoch'] == 180)
].copy()

# Step 2: build a mapping from species to recall multiplier
def get_multiplier(recall):
    if recall < 0.6:
        return 10
    elif recall < 0.7:
        return 8
    elif recall < 0.8:
        return 6
    elif recall < 0.9:
        return 4
    elif recall < 1:
        return 2
    else:
        return 1

df['Multiplier'] = df['Recall'].apply(get_multiplier)

# Step 3: make sure class order matches your dataset order
species_to_multiplier = dict(zip(df['Species'], df['Multiplier']))

# Step 4: apply the multipliers to your weight vector
adjusted_weights = norm_sqrt_inv_weights.clone() if hasattr(norm_sqrt_inv_weights, 'clone') else np.copy(norm_sqrt_inv_weights)

for idx, class_name in enumerate(train_dataset.classes):
    if class_name in species_to_multiplier:
        adjusted_weights[idx] *= species_to_multiplier[class_name]

In [56]:
df

,Species,Precision,Recall,F1-score,Epoch,Multiplier
646,Anabasis articulata (Forssk.) Moq.,0.976000,0.983871,0.979920,180,2
647,Anabasis setifera Moq.,0.867403,0.792929,0.828496,180,6
648,Atriplex halimus L.,0.732938,0.879004,0.799353,180,4
649,Calotropis procera,0.961538,0.925926,0.943396,180,2
650,Capparis spinosa L.,0.947761,0.894366,0.920290,180,4
651,Cebatha pendula (J.R.Forst. & G.Forst.) Kuntze,0.857143,0.950000,0.901186,180,2
652,Cenchrus divisus,1.000000,0.977011,0.988372,180,2
653,Deverra tortuosa (Desf.) DC.,0.827160,0.957143,0.887417,180,2
654,Deverra triradiata Hochst. ex Boiss.,0.746269,1.000000,0.854701,180,1
655,Diplotaxis harra (Forssk.) Boiss.,0.903704,0.897059,0.900369,180,4
656,Echinops glaberrimus DC.,0.871560,0.931373,0.900474,180,2
657,Ephedra alata Decne.,0.941799,0.872549,0.905852,180,4
658,Farsetia aegyptia Turra,0.918919,0.735135,0.816817,180,6
659,Gymnocarpos decander Forssk.,0.906250,0.899225,0.902724,180,4
660,Haloxylon salicornicum (Moq.) Bunge ex Boiss.,0.788177,0.941176,0.857909,180,2
661,Heliotropium arbainense Fresen.,0.955665,0.941748,0.948655,180,2
662,Iphiona mucronata (Forssk.) Asch. & Schweinf.,1.000000,1.000000,1.000000,180,1
663,Limonium pruinosum (L.) Chaz.,0.907895,0.775281,0.836364,180,6
664,Lycium shawii Roem. & Schult.,0.875000,0.700000,0.777778,180,6
665,Nitraria retusa (Forssk.) Asch.,0.773292,0.792994,0.783019,180,6
666,Ochradenus baccatus Delile,0.926357,0.959839,0.942801,180,2
667,Peganum harmala L.,0.846154,1.000000,0.916667,180,1
668,Rumex vesicarius L.,1.000000,1.000000,1.000000,180,1
669,Salsola imbricata Forssk.,0.990566,1.000000,0.995261,180,1
670,Stachys aegyptiaca Pers.,0.804878,1.000000,0.891892,180,1
671,Suaeda aegyptiaca (Hasselq.) Zohary,0.841060,0.954887,0.894366,180,2
672,Tamarix nilotica (Ehrenb.) Bunge,0.889362,0.653125,0.753153,180,8
673,Trichodesma africanum (L.) Sm.,0.816667,0.586826,0.682927,180,10
674,Zilla spinosa (L.) Prantl,0.898438,1.000000,0.946502,180,1
675,Zygophyllum arabicum (L.) Christenh. & Byng,0.885813,0.980843,0.930909,180,2
676,Zygophyllum coccineum,0.792035,0.922680,0.852381,180,2
677,Zygophyllum molle (Delile) Christenh. & Byng,0.982456,0.982456,0.982456,180,2
678,others,0.966292,0.860000,0.910053,180,4

In [60]:
adjusted_weights, norm_sqrt_inv_weights

(tensor([ 2.1876,  6.8274,  6.0075,  2.4275,  4.5935,  2.5176,  3.1295,  3.7970,
          2.4456,  4.1975,  3.2993,  8.3270,  6.3478,  3.9639,  2.0345,  2.8870,
          2.7015,  9.3570,  6.7176,  5.5509,  1.9259,  1.5881,  1.1269,  0.8456,
          1.2772,  2.1456, 11.5294, 11.0180,  0.8796,  2.4793,  3.4599,  5.1923,
          1.9130], device='mps:0'),
 tensor([1.0938, 1.1379, 1.5019, 1.2137, 1.1484, 1.2588, 1.5647, 1.8985, 2.4456,
         1.0494, 1.6496, 2.0818, 1.0580, 0.9910, 1.0173, 1.4435, 2.7015, 1.5595,
         1.1196, 0.9252, 0.9630, 1.5881, 1.1269, 0.8456, 1.2772, 1.0728, 1.4412,
         1.1018, 0.8796, 1.2396, 1.7300, 2.5961, 0.4783], device='mps:0'))

In [61]:
norm_sqrt_inv_criterion = nn.CrossEntropyLoss(weight=adjusted_weights)
stageF_optimizer = torch.optim.AdamW(mobilenetv2_stageF_top_30.parameters(), lr=1e-5,
                            weight_decay=1e-4, betas=(0.9, 0.999))

In [62]:
start_epoch = 181
end_epoch = 195

In [63]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_top_30, full_web_top_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_top_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 181 - Training Started...

Epoch 181, Batch 100, Loss: 0.0874, Accuracy: 96.47%, Time Passed: 3.66m
Epoch 181, Batch 200, Loss: 0.0903, Accuracy: 96.20%, Time Passed: 7.33m
Epoch 181, Batch 300, Loss: 0.0870, Accuracy: 96.27%, Time Passed: 11.18m
Epoch 181, Batch 400, Loss: 0.0897, Accuracy: 96.12%, Time Passed: 15.20m
Epoch 181, Batch 500, Loss: 0.0903, Accuracy: 96.01%, Time Passed: 19.13m
Epoch 181 Completed - Average Loss: 0.0891, Accuracy: 96.04%, Epoch Time: 21.93m
Training Complete Epoch 181 - Total Time: 21.93m

✅ Epoch 181 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4968, Accuracy: 87.03%, Time Passed: 4.00m
Evaluation Complete - Loss: 0.4756, Accuracy: 87.97%, Total Time: 7.25m

📊 Epoch 181 - Evaluation Completed.


🚀 Epoch 182 - Training Started...

Epoch 182, Batch 100, Loss: 0.0932, Accuracy: 95.81%, Time Passed: 4.09m
Epoch 182, Batch 200, Loss: 0.0861, Accuracy: 96.14%, Time Passed: 7.96m
Epoch 182, Batch 300, Loss: 0.0856, Accuracy: 96.22%, Time Passed: 12.49m
Epoch 182, Batch 400, Loss: 0.0813, Accuracy: 96.36%, Time Passed: 16.35m
Epoch 182, Batch 500, Loss: 0.0806, Accuracy: 96.36%, Time Passed: 20.37m
Epoch 182 Completed - Average Loss: 0.0795, Accuracy: 96.44%, Epoch Time: 23.15m
Training Complete Epoch 182 - Total Time: 23.16m

✅ Epoch 182 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4871, Accuracy: 87.25%, Time Passed: 4.12m
Evaluation Complete - Loss: 0.4682, Accuracy: 88.19%, Total Time: 7.60m

📊 Epoch 182 - Evaluation Completed.


🚀 Epoch 183 - Training Started...

Epoch 183, Batch 100, Loss: 0.0826, Accuracy: 96.12%, Time Passed: 4.38m
Epoch 183, Batch 200, Loss: 0.0830, Accuracy: 96.20%, Time Passed: 8.65m
Epoch 183, Batch 300, Loss: 0.0795, Accuracy: 96.38%, Time Passed: 13.36m
Epoch 183, Batch 400, Loss: 0.0774, Accuracy: 96.41%, Time Passed: 17.15m
Epoch 183, Batch 500, Loss: 0.0777, Accuracy: 96.39%, Time Passed: 20.82m
Epoch 183 Completed - Average Loss: 0.0762, Accuracy: 96.48%, Epoch Time: 23.86m
Training Complete Epoch 183 - Total Time: 23.86m

✅ Epoch 183 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4792, Accuracy: 87.41%, Time Passed: 4.20m
Evaluation Complete - Loss: 0.4751, Accuracy: 88.13%, Total Time: 7.55m

📊 Epoch 183 - Evaluation Completed.


🚀 Epoch 184 - Training Started...

Epoch 184, Batch 100, Loss: 0.0740, Accuracy: 96.62%, Time Passed: 3.99m
Epoch 184, Batch 200, Loss: 0.0789, Accuracy: 96.59%, Time Passed: 7.93m
Epoch 184, Batch 300, Loss: 0.0784, Accuracy: 96.38%, Time Passed: 11.80m
Epoch 184, Batch 400, Loss: 0.0752, Accuracy: 96.52%, Time Passed: 15.69m
Epoch 184, Batch 500, Loss: 0.0767, Accuracy: 96.58%, Time Passed: 19.39m
Epoch 184 Completed - Average Loss: 0.0752, Accuracy: 96.63%, Epoch Time: 22.09m
Training Complete Epoch 184 - Total Time: 22.09m

✅ Epoch 184 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5001, Accuracy: 87.41%, Time Passed: 3.95m
Evaluation Complete - Loss: 0.4685, Accuracy: 88.37%, Total Time: 7.15m

📊 Epoch 184 - Evaluation Completed.


🚀 Epoch 185 - Training Started...

Epoch 185, Batch 100, Loss: 0.0697, Accuracy: 96.50%, Time Passed: 3.75m
Epoch 185, Batch 200, Loss: 0.0662, Accuracy: 96.59%, Time Passed: 7.51m
Epoch 185, Batch 300, Loss: 0.0705, Accuracy: 96.55%, Time Passed: 11.33m
Epoch 185, Batch 400, Loss: 0.0664, Accuracy: 96.77%, Time Passed: 15.22m
Epoch 185, Batch 500, Loss: 0.0667, Accuracy: 96.74%, Time Passed: 18.95m
Epoch 185 Completed - Average Loss: 0.0667, Accuracy: 96.78%, Epoch Time: 21.81m
Training Complete Epoch 185 - Total Time: 21.81m

✅ Epoch 185 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4850, Accuracy: 87.62%, Time Passed: 4.10m
Evaluation Complete - Loss: 0.4747, Accuracy: 88.24%, Total Time: 7.45m

📊 Epoch 185 - Evaluation Completed.


🚀 Epoch 186 - Training Started...

Epoch 186, Batch 100, Loss: 0.0680, Accuracy: 96.84%, Time Passed: 3.83m
Epoch 186, Batch 200, Loss: 0.0638, Accuracy: 97.23%, Time Passed: 7.65m
Epoch 186, Batch 300, Loss: 0.0678, Accuracy: 97.05%, Time Passed: 11.66m
Epoch 186, Batch 400, Loss: 0.0643, Accuracy: 97.04%, Time Passed: 15.47m
Epoch 186, Batch 500, Loss: 0.0687, Accuracy: 96.88%, Time Passed: 19.27m
Epoch 186 Completed - Average Loss: 0.0692, Accuracy: 96.86%, Epoch Time: 22.10m
Training Complete Epoch 186 - Total Time: 22.10m

✅ Epoch 186 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4648, Accuracy: 87.69%, Time Passed: 4.14m
Evaluation Complete - Loss: 0.4566, Accuracy: 88.37%, Total Time: 7.43m

📊 Epoch 186 - Evaluation Completed.


🚀 Epoch 187 - Training Started...

Epoch 187, Batch 100, Loss: 0.0773, Accuracy: 96.50%, Time Passed: 3.76m
Epoch 187, Batch 200, Loss: 0.0692, Accuracy: 96.80%, Time Passed: 7.63m
Epoch 187, Batch 300, Loss: 0.0683, Accuracy: 96.86%, Time Passed: 11.80m
Epoch 187, Batch 400, Loss: 0.0703, Accuracy: 96.71%, Time Passed: 15.83m
Epoch 187, Batch 500, Loss: 0.0691, Accuracy: 96.72%, Time Passed: 19.70m
Epoch 187 Completed - Average Loss: 0.0700, Accuracy: 96.67%, Epoch Time: 22.56m
Training Complete Epoch 187 - Total Time: 22.56m

✅ Epoch 187 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4905, Accuracy: 86.84%, Time Passed: 4.38m
Evaluation Complete - Loss: 0.4653, Accuracy: 87.74%, Total Time: 7.66m

📊 Epoch 187 - Evaluation Completed.


🚀 Epoch 188 - Training Started...

Epoch 188, Batch 100, Loss: 0.0691, Accuracy: 96.81%, Time Passed: 3.95m
Epoch 188, Batch 200, Loss: 0.0665, Accuracy: 96.64%, Time Passed: 7.78m
Epoch 188, Batch 300, Loss: 0.0692, Accuracy: 96.66%, Time Passed: 11.57m
Epoch 188, Batch 400, Loss: 0.0740, Accuracy: 96.56%, Time Passed: 15.46m
Epoch 188, Batch 500, Loss: 0.0727, Accuracy: 96.67%, Time Passed: 19.14m
Epoch 188 Completed - Average Loss: 0.0717, Accuracy: 96.70%, Epoch Time: 21.94m
Training Complete Epoch 188 - Total Time: 21.94m

✅ Epoch 188 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4632, Accuracy: 87.97%, Time Passed: 4.22m
Evaluation Complete - Loss: 0.4548, Accuracy: 88.36%, Total Time: 7.57m

📊 Epoch 188 - Evaluation Completed.


🚀 Epoch 189 - Training Started...

Epoch 189, Batch 100, Loss: 0.0654, Accuracy: 96.56%, Time Passed: 4.20m
Epoch 189, Batch 200, Loss: 0.0627, Accuracy: 96.83%, Time Passed: 8.13m
Epoch 189, Batch 300, Loss: 0.0633, Accuracy: 96.99%, Time Passed: 12.15m
Epoch 189, Batch 400, Loss: 0.0671, Accuracy: 96.82%, Time Passed: 15.96m
Epoch 189, Batch 500, Loss: 0.0653, Accuracy: 96.88%, Time Passed: 19.94m
Epoch 189 Completed - Average Loss: 0.0675, Accuracy: 96.87%, Epoch Time: 23.01m
Training Complete Epoch 189 - Total Time: 23.01m

✅ Epoch 189 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4543, Accuracy: 88.06%, Time Passed: 4.08m
Evaluation Complete - Loss: 0.4497, Accuracy: 88.50%, Total Time: 7.23m

📊 Epoch 189 - Evaluation Completed.


🚀 Epoch 190 - Training Started...

Epoch 190, Batch 100, Loss: 0.0630, Accuracy: 97.22%, Time Passed: 3.70m
Epoch 190, Batch 200, Loss: 0.0626, Accuracy: 97.36%, Time Passed: 7.69m
Epoch 190, Batch 300, Loss: 0.0610, Accuracy: 97.33%, Time Passed: 11.52m
Epoch 190, Batch 400, Loss: 0.0619, Accuracy: 97.25%, Time Passed: 15.46m
Epoch 190, Batch 500, Loss: 0.0632, Accuracy: 97.11%, Time Passed: 19.50m
Epoch 190 Completed - Average Loss: 0.0634, Accuracy: 97.17%, Epoch Time: 22.46m
Training Complete Epoch 190 - Total Time: 22.46m

✅ Epoch 190 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4884, Accuracy: 87.09%, Time Passed: 4.16m
Evaluation Complete - Loss: 0.4807, Accuracy: 87.95%, Total Time: 7.69m

📊 Epoch 190 - Evaluation Completed.


🚀 Epoch 191 - Training Started...

Epoch 191, Batch 100, Loss: 0.0594, Accuracy: 97.31%, Time Passed: 4.03m
Epoch 191, Batch 200, Loss: 0.0637, Accuracy: 97.05%, Time Passed: 7.80m
Epoch 191, Batch 300, Loss: 0.0661, Accuracy: 97.04%, Time Passed: 11.66m
Epoch 191, Batch 400, Loss: 0.0630, Accuracy: 97.13%, Time Passed: 15.89m
Epoch 191, Batch 500, Loss: 0.0639, Accuracy: 97.08%, Time Passed: 19.97m
Epoch 191 Completed - Average Loss: 0.0631, Accuracy: 97.10%, Epoch Time: 22.79m
Training Complete Epoch 191 - Total Time: 22.79m

✅ Epoch 191 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4906, Accuracy: 86.56%, Time Passed: 4.15m
Evaluation Complete - Loss: 0.4686, Accuracy: 87.65%, Total Time: 7.45m

📊 Epoch 191 - Evaluation Completed.


🚀 Epoch 192 - Training Started...

Epoch 192, Batch 100, Loss: 0.0652, Accuracy: 97.28%, Time Passed: 3.86m
Epoch 192, Batch 200, Loss: 0.0649, Accuracy: 97.22%, Time Passed: 7.77m
Epoch 192, Batch 300, Loss: 0.0680, Accuracy: 97.00%, Time Passed: 11.92m
Epoch 192, Batch 400, Loss: 0.0654, Accuracy: 97.15%, Time Passed: 16.33m
Epoch 192, Batch 500, Loss: 0.0630, Accuracy: 97.19%, Time Passed: 20.52m
Epoch 192 Completed - Average Loss: 0.0612, Accuracy: 97.23%, Epoch Time: 23.36m
Training Complete Epoch 192 - Total Time: 23.36m

✅ Epoch 192 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4526, Accuracy: 87.97%, Time Passed: 4.18m
Evaluation Complete - Loss: 0.4450, Accuracy: 88.41%, Total Time: 7.47m

📊 Epoch 192 - Evaluation Completed.


🚀 Epoch 193 - Training Started...

Epoch 193, Batch 100, Loss: 0.0467, Accuracy: 97.62%, Time Passed: 3.86m
Epoch 193, Batch 200, Loss: 0.0493, Accuracy: 97.67%, Time Passed: 7.57m
Epoch 193, Batch 300, Loss: 0.0486, Accuracy: 97.55%, Time Passed: 11.55m
Epoch 193, Batch 400, Loss: 0.0526, Accuracy: 97.34%, Time Passed: 15.49m
Epoch 193, Batch 500, Loss: 0.0537, Accuracy: 97.30%, Time Passed: 19.40m
Epoch 193 Completed - Average Loss: 0.0537, Accuracy: 97.30%, Epoch Time: 22.28m
Training Complete Epoch 193 - Total Time: 22.28m

✅ Epoch 193 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4702, Accuracy: 87.09%, Time Passed: 4.15m
Evaluation Complete - Loss: 0.4528, Accuracy: 88.19%, Total Time: 7.50m

📊 Epoch 193 - Evaluation Completed.


🚀 Epoch 194 - Training Started...

Epoch 194, Batch 100, Loss: 0.0487, Accuracy: 97.44%, Time Passed: 3.94m
Epoch 194, Batch 200, Loss: 0.0563, Accuracy: 97.41%, Time Passed: 8.27m
Epoch 194, Batch 300, Loss: 0.0572, Accuracy: 97.42%, Time Passed: 12.69m
Epoch 194, Batch 400, Loss: 0.0586, Accuracy: 97.30%, Time Passed: 16.62m
Epoch 194, Batch 500, Loss: 0.0605, Accuracy: 97.22%, Time Passed: 20.54m
Epoch 194 Completed - Average Loss: 0.0603, Accuracy: 97.25%, Epoch Time: 23.36m
Training Complete Epoch 194 - Total Time: 23.36m

✅ Epoch 194 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4759, Accuracy: 86.97%, Time Passed: 4.14m
Evaluation Complete - Loss: 0.4630, Accuracy: 87.95%, Total Time: 7.39m

📊 Epoch 194 - Evaluation Completed.


🚀 Epoch 195 - Training Started...

Epoch 195, Batch 100, Loss: 0.0507, Accuracy: 97.59%, Time Passed: 3.79m
Epoch 195, Batch 200, Loss: 0.0581, Accuracy: 97.38%, Time Passed: 7.50m
Epoch 195, Batch 300, Loss: 0.0609, Accuracy: 97.22%, Time Passed: 11.25m
Epoch 195, Batch 400, Loss: 0.0613, Accuracy: 97.23%, Time Passed: 15.06m
Epoch 195, Batch 500, Loss: 0.0614, Accuracy: 97.19%, Time Passed: 18.73m
Epoch 195 Completed - Average Loss: 0.0616, Accuracy: 97.17%, Epoch Time: 21.57m
Training Complete Epoch 195 - Total Time: 21.57m

✅ Epoch 195 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4650, Accuracy: 88.00%, Time Passed: 4.20m
Evaluation Complete - Loss: 0.4550, Accuracy: 88.82%, Total Time: 7.48m

📊 Epoch 195 - Evaluation Completed.

In [64]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_top_30_{start_epoch}_{end_epoch}.pkl')

In [65]:
del training_states

In [66]:
start_epoch = 196
end_epoch = 210

In [67]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_top_30, full_web_top_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_top_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 196 - Training Started...

Epoch 196, Batch 100, Loss: 0.0605, Accuracy: 97.31%, Time Passed: 3.41m
Epoch 196, Batch 200, Loss: 0.0620, Accuracy: 97.20%, Time Passed: 6.85m
Epoch 196, Batch 300, Loss: 0.0577, Accuracy: 97.43%, Time Passed: 10.69m
Epoch 196, Batch 400, Loss: 0.0589, Accuracy: 97.33%, Time Passed: 14.26m
Epoch 196, Batch 500, Loss: 0.0598, Accuracy: 97.22%, Time Passed: 17.79m
Epoch 196 Completed - Average Loss: 0.0580, Accuracy: 97.29%, Epoch Time: 20.45m
Training Complete Epoch 196 - Total Time: 20.45m

✅ Epoch 196 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4599, Accuracy: 88.12%, Time Passed: 3.92m
Evaluation Complete - Loss: 0.4403, Accuracy: 88.78%, Total Time: 7.00m

📊 Epoch 196 - Evaluation Completed.


🚀 Epoch 197 - Training Started...

Epoch 197, Batch 100, Loss: 0.0527, Accuracy: 97.41%, Time Passed: 3.57m
Epoch 197, Batch 200, Loss: 0.0578, Accuracy: 97.27%, Time Passed: 7.26m
Epoch 197, Batch 300, Loss: 0.0578, Accuracy: 97.33%, Time Passed: 11.34m
Epoch 197, Batch 400, Loss: 0.0558, Accuracy: 97.38%, Time Passed: 15.19m
Epoch 197, Batch 500, Loss: 0.0567, Accuracy: 97.23%, Time Passed: 18.99m
Epoch 197 Completed - Average Loss: 0.0590, Accuracy: 97.18%, Epoch Time: 21.74m
Training Complete Epoch 197 - Total Time: 21.74m

✅ Epoch 197 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4605, Accuracy: 87.44%, Time Passed: 4.14m
Evaluation Complete - Loss: 0.4401, Accuracy: 88.28%, Total Time: 7.39m

📊 Epoch 197 - Evaluation Completed.


🚀 Epoch 198 - Training Started...

Epoch 198, Batch 100, Loss: 0.0463, Accuracy: 97.78%, Time Passed: 3.82m
Epoch 198, Batch 200, Loss: 0.0502, Accuracy: 97.52%, Time Passed: 7.63m
Epoch 198, Batch 300, Loss: 0.0494, Accuracy: 97.55%, Time Passed: 11.44m
Epoch 198, Batch 400, Loss: 0.0531, Accuracy: 97.49%, Time Passed: 15.29m
Epoch 198, Batch 500, Loss: 0.0542, Accuracy: 97.46%, Time Passed: 19.30m
Epoch 198 Completed - Average Loss: 0.0551, Accuracy: 97.43%, Epoch Time: 22.33m
Training Complete Epoch 198 - Total Time: 22.33m

✅ Epoch 198 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4414, Accuracy: 88.28%, Time Passed: 4.15m
Evaluation Complete - Loss: 0.4255, Accuracy: 89.06%, Total Time: 7.39m

📊 Epoch 198 - Evaluation Completed.


🚀 Epoch 199 - Training Started...

Epoch 199, Batch 100, Loss: 0.0652, Accuracy: 97.06%, Time Passed: 3.90m
Epoch 199, Batch 200, Loss: 0.0666, Accuracy: 97.16%, Time Passed: 7.98m
Epoch 199, Batch 300, Loss: 0.0618, Accuracy: 97.27%, Time Passed: 12.02m
Epoch 199, Batch 400, Loss: 0.0629, Accuracy: 97.25%, Time Passed: 16.03m
Epoch 199, Batch 500, Loss: 0.0595, Accuracy: 97.30%, Time Passed: 19.97m
Epoch 199 Completed - Average Loss: 0.0580, Accuracy: 97.40%, Epoch Time: 22.95m
Training Complete Epoch 199 - Total Time: 22.95m

✅ Epoch 199 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4333, Accuracy: 88.88%, Time Passed: 4.12m
Evaluation Complete - Loss: 0.4169, Accuracy: 89.42%, Total Time: 7.34m

📊 Epoch 199 - Evaluation Completed.


🚀 Epoch 200 - Training Started...

Epoch 200, Batch 100, Loss: 0.0504, Accuracy: 97.00%, Time Passed: 3.80m
Epoch 200, Batch 200, Loss: 0.0536, Accuracy: 97.16%, Time Passed: 7.57m
Epoch 200, Batch 300, Loss: 0.0509, Accuracy: 97.34%, Time Passed: 11.38m
Epoch 200, Batch 400, Loss: 0.0526, Accuracy: 97.34%, Time Passed: 15.08m
Epoch 200, Batch 500, Loss: 0.0528, Accuracy: 97.38%, Time Passed: 19.04m
Epoch 200 Completed - Average Loss: 0.0537, Accuracy: 97.35%, Epoch Time: 21.89m
Training Complete Epoch 200 - Total Time: 21.89m

✅ Epoch 200 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4365, Accuracy: 88.59%, Time Passed: 4.05m
Evaluation Complete - Loss: 0.4468, Accuracy: 88.88%, Total Time: 7.27m

📊 Epoch 200 - Evaluation Completed.


🚀 Epoch 201 - Training Started...

Epoch 201, Batch 100, Loss: 0.0512, Accuracy: 97.31%, Time Passed: 4.60m
Epoch 201, Batch 200, Loss: 0.0523, Accuracy: 97.34%, Time Passed: 9.15m
Epoch 201, Batch 300, Loss: 0.0551, Accuracy: 97.28%, Time Passed: 13.71m
Epoch 201, Batch 400, Loss: 0.0545, Accuracy: 97.41%, Time Passed: 18.22m
Epoch 201, Batch 500, Loss: 0.0543, Accuracy: 97.38%, Time Passed: 22.61m
Epoch 201 Completed - Average Loss: 0.0527, Accuracy: 97.45%, Epoch Time: 25.87m
Training Complete Epoch 201 - Total Time: 25.87m

✅ Epoch 201 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4885, Accuracy: 87.59%, Time Passed: 4.11m
Evaluation Complete - Loss: 0.4902, Accuracy: 88.00%, Total Time: 7.43m

📊 Epoch 201 - Evaluation Completed.


🚀 Epoch 202 - Training Started...

Epoch 202, Batch 100, Loss: 0.0479, Accuracy: 97.66%, Time Passed: 4.68m
Epoch 202, Batch 200, Loss: 0.0480, Accuracy: 97.58%, Time Passed: 9.16m
Epoch 202, Batch 300, Loss: 0.0491, Accuracy: 97.60%, Time Passed: 13.73m
Epoch 202, Batch 400, Loss: 0.0489, Accuracy: 97.58%, Time Passed: 18.19m
Epoch 202, Batch 500, Loss: 0.0492, Accuracy: 97.64%, Time Passed: 22.59m
Epoch 202 Completed - Average Loss: 0.0492, Accuracy: 97.63%, Epoch Time: 25.87m
Training Complete Epoch 202 - Total Time: 25.87m

✅ Epoch 202 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4473, Accuracy: 88.19%, Time Passed: 4.05m
Evaluation Complete - Loss: 0.4334, Accuracy: 89.10%, Total Time: 7.25m

📊 Epoch 202 - Evaluation Completed.


🚀 Epoch 203 - Training Started...

Epoch 203, Batch 100, Loss: 0.0577, Accuracy: 97.50%, Time Passed: 4.44m
Epoch 203, Batch 200, Loss: 0.0546, Accuracy: 97.50%, Time Passed: 8.92m
Epoch 203, Batch 300, Loss: 0.0568, Accuracy: 97.41%, Time Passed: 13.24m
Epoch 203, Batch 400, Loss: 0.0580, Accuracy: 97.32%, Time Passed: 17.60m
Epoch 203, Batch 500, Loss: 0.0559, Accuracy: 97.36%, Time Passed: 22.30m
Epoch 203 Completed - Average Loss: 0.0563, Accuracy: 97.38%, Epoch Time: 25.68m
Training Complete Epoch 203 - Total Time: 25.68m

✅ Epoch 203 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4559, Accuracy: 88.03%, Time Passed: 4.28m
Evaluation Complete - Loss: 0.4410, Accuracy: 88.88%, Total Time: 7.64m

📊 Epoch 203 - Evaluation Completed.


🚀 Epoch 204 - Training Started...

Epoch 204, Batch 100, Loss: 0.0530, Accuracy: 97.50%, Time Passed: 4.52m
Epoch 204, Batch 200, Loss: 0.0557, Accuracy: 97.20%, Time Passed: 9.06m
Epoch 204, Batch 300, Loss: 0.0550, Accuracy: 97.30%, Time Passed: 13.69m
Epoch 204, Batch 400, Loss: 0.0558, Accuracy: 97.27%, Time Passed: 18.39m
Epoch 204, Batch 500, Loss: 0.0540, Accuracy: 97.36%, Time Passed: 22.74m
Epoch 204 Completed - Average Loss: 0.0540, Accuracy: 97.40%, Epoch Time: 26.10m
Training Complete Epoch 204 - Total Time: 26.10m

✅ Epoch 204 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4541, Accuracy: 88.44%, Time Passed: 4.14m
Evaluation Complete - Loss: 0.4421, Accuracy: 89.10%, Total Time: 7.33m

📊 Epoch 204 - Evaluation Completed.


🚀 Epoch 205 - Training Started...

Epoch 205, Batch 100, Loss: 0.0535, Accuracy: 97.53%, Time Passed: 4.53m
Epoch 205, Batch 200, Loss: 0.0488, Accuracy: 97.70%, Time Passed: 9.01m
Epoch 205, Batch 300, Loss: 0.0485, Accuracy: 97.71%, Time Passed: 13.50m
Epoch 205, Batch 400, Loss: 0.0489, Accuracy: 97.63%, Time Passed: 18.08m
Epoch 205, Batch 500, Loss: 0.0501, Accuracy: 97.53%, Time Passed: 22.76m
Epoch 205 Completed - Average Loss: 0.0498, Accuracy: 97.54%, Epoch Time: 26.13m
Training Complete Epoch 205 - Total Time: 26.13m

✅ Epoch 205 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4697, Accuracy: 88.44%, Time Passed: 4.38m
Evaluation Complete - Loss: 0.4780, Accuracy: 88.69%, Total Time: 7.94m

📊 Epoch 205 - Evaluation Completed.


🚀 Epoch 206 - Training Started...

Epoch 206, Batch 100, Loss: 0.0522, Accuracy: 97.66%, Time Passed: 4.84m
Epoch 206, Batch 200, Loss: 0.0509, Accuracy: 97.70%, Time Passed: 9.50m
Epoch 206, Batch 300, Loss: 0.0488, Accuracy: 97.69%, Time Passed: 14.12m
Epoch 206, Batch 400, Loss: 0.0488, Accuracy: 97.73%, Time Passed: 18.78m
Epoch 206, Batch 500, Loss: 0.0499, Accuracy: 97.62%, Time Passed: 23.52m
Epoch 206 Completed - Average Loss: 0.0508, Accuracy: 97.56%, Epoch Time: 26.84m
Training Complete Epoch 206 - Total Time: 26.84m

✅ Epoch 206 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4627, Accuracy: 88.00%, Time Passed: 4.51m
Evaluation Complete - Loss: 0.4588, Accuracy: 88.58%, Total Time: 8.08m

📊 Epoch 206 - Evaluation Completed.


🚀 Epoch 207 - Training Started...

Epoch 207, Batch 100, Loss: 0.0459, Accuracy: 97.94%, Time Passed: 4.69m
Epoch 207, Batch 200, Loss: 0.0460, Accuracy: 97.77%, Time Passed: 9.37m
Epoch 207, Batch 300, Loss: 0.0457, Accuracy: 97.76%, Time Passed: 14.07m
Epoch 207, Batch 400, Loss: 0.0456, Accuracy: 97.80%, Time Passed: 18.69m
Epoch 207, Batch 500, Loss: 0.0477, Accuracy: 97.68%, Time Passed: 23.29m
Epoch 207 Completed - Average Loss: 0.0492, Accuracy: 97.59%, Epoch Time: 26.64m
Training Complete Epoch 207 - Total Time: 26.64m

✅ Epoch 207 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4611, Accuracy: 88.03%, Time Passed: 4.45m
Evaluation Complete - Loss: 0.4568, Accuracy: 88.69%, Total Time: 8.08m

📊 Epoch 207 - Evaluation Completed.


🚀 Epoch 208 - Training Started...

Epoch 208, Batch 100, Loss: 0.0501, Accuracy: 97.38%, Time Passed: 4.65m
Epoch 208, Batch 200, Loss: 0.0442, Accuracy: 97.75%, Time Passed: 9.37m
Epoch 208, Batch 300, Loss: 0.0461, Accuracy: 97.64%, Time Passed: 13.96m
Epoch 208, Batch 400, Loss: 0.0450, Accuracy: 97.73%, Time Passed: 18.76m
Epoch 208, Batch 500, Loss: 0.0456, Accuracy: 97.78%, Time Passed: 23.38m
Epoch 208 Completed - Average Loss: 0.0445, Accuracy: 97.86%, Epoch Time: 27.13m
Training Complete Epoch 208 - Total Time: 27.13m

✅ Epoch 208 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4782, Accuracy: 87.91%, Time Passed: 4.43m
Evaluation Complete - Loss: 0.4693, Accuracy: 88.56%, Total Time: 8.03m

📊 Epoch 208 - Evaluation Completed.


🚀 Epoch 209 - Training Started...

Epoch 209, Batch 100, Loss: 0.0489, Accuracy: 97.59%, Time Passed: 4.77m
Epoch 209, Batch 200, Loss: 0.0505, Accuracy: 97.55%, Time Passed: 9.51m
Epoch 209, Batch 300, Loss: 0.0493, Accuracy: 97.53%, Time Passed: 14.18m
Epoch 209, Batch 400, Loss: 0.0467, Accuracy: 97.66%, Time Passed: 18.80m
Epoch 209, Batch 500, Loss: 0.0472, Accuracy: 97.67%, Time Passed: 23.89m
Epoch 209 Completed - Average Loss: 0.0486, Accuracy: 97.64%, Epoch Time: 27.38m
Training Complete Epoch 209 - Total Time: 27.38m

✅ Epoch 209 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4551, Accuracy: 88.19%, Time Passed: 4.49m
Evaluation Complete - Loss: 0.4459, Accuracy: 88.60%, Total Time: 8.08m

📊 Epoch 209 - Evaluation Completed.


🚀 Epoch 210 - Training Started...

Epoch 210, Batch 100, Loss: 0.0454, Accuracy: 97.84%, Time Passed: 4.71m
Epoch 210, Batch 200, Loss: 0.0461, Accuracy: 97.78%, Time Passed: 9.57m
Epoch 210, Batch 300, Loss: 0.0464, Accuracy: 97.51%, Time Passed: 14.86m
Epoch 210, Batch 400, Loss: 0.0489, Accuracy: 97.53%, Time Passed: 19.72m
Epoch 210, Batch 500, Loss: 0.0504, Accuracy: 97.48%, Time Passed: 24.37m
Epoch 210 Completed - Average Loss: 0.0497, Accuracy: 97.54%, Epoch Time: 27.73m
Training Complete Epoch 210 - Total Time: 27.73m

✅ Epoch 210 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4694, Accuracy: 87.56%, Time Passed: 4.39m
Evaluation Complete - Loss: 0.4544, Accuracy: 88.49%, Total Time: 7.89m

📊 Epoch 210 - Evaluation Completed.

In [69]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_top_30_{start_epoch}_{end_epoch}.pkl')

In [70]:
del training_states

In [71]:
start_epoch = 211
end_epoch = 220

In [72]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_top_30, full_web_top_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_top_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 211 - Training Started...

Epoch 211, Batch 100, Loss: 0.0448, Accuracy: 97.31%, Time Passed: 4.09m
Epoch 211, Batch 200, Loss: 0.0439, Accuracy: 97.39%, Time Passed: 8.78m
Epoch 211, Batch 300, Loss: 0.0455, Accuracy: 97.49%, Time Passed: 13.21m
Epoch 211, Batch 400, Loss: 0.0462, Accuracy: 97.51%, Time Passed: 17.90m
Epoch 211, Batch 500, Loss: 0.0469, Accuracy: 97.53%, Time Passed: 22.54m
Epoch 211 Completed - Average Loss: 0.0461, Accuracy: 97.55%, Epoch Time: 25.96m
Training Complete Epoch 211 - Total Time: 25.96m

✅ Epoch 211 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4568, Accuracy: 87.94%, Time Passed: 4.28m
Evaluation Complete - Loss: 0.4410, Accuracy: 88.80%, Total Time: 7.78m

📊 Epoch 211 - Evaluation Completed.


🚀 Epoch 212 - Training Started...

Epoch 212, Batch 100, Loss: 0.0412, Accuracy: 97.94%, Time Passed: 6.89m
Epoch 212, Batch 200, Loss: 0.0478, Accuracy: 97.77%, Time Passed: 13.73m
Epoch 212, Batch 300, Loss: 0.0493, Accuracy: 97.75%, Time Passed: 21.52m
Epoch 212, Batch 400, Loss: 0.0501, Accuracy: 97.70%, Time Passed: 28.83m
Epoch 212, Batch 500, Loss: 0.0474, Accuracy: 97.71%, Time Passed: 36.74m
Epoch 212 Completed - Average Loss: 0.0488, Accuracy: 97.68%, Epoch Time: 42.67m
Training Complete Epoch 212 - Total Time: 42.67m

✅ Epoch 212 - Training Completed. Starting Evaluation...

python(43374) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43376) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43378) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43380) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4639, Accuracy: 87.41%, Time Passed: 4.22m
Evaluation Complete - Loss: 0.4282, Accuracy: 88.91%, Total Time: 7.48m

📊 Epoch 212 - Evaluation Completed.


🚀 Epoch 213 - Training Started...

python(43439) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43441) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43443) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43445) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 213, Batch 100, Loss: 0.0396, Accuracy: 98.22%, Time Passed: 5.25m
Epoch 213, Batch 200, Loss: 0.0489, Accuracy: 97.86%, Time Passed: 10.70m
Epoch 213, Batch 300, Loss: 0.0499, Accuracy: 97.80%, Time Passed: 15.96m
Epoch 213, Batch 400, Loss: 0.0487, Accuracy: 97.75%, Time Passed: 20.59m
Epoch 213, Batch 500, Loss: 0.0476, Accuracy: 97.78%, Time Passed: 25.08m
Epoch 213 Completed - Average Loss: 0.0475, Accuracy: 97.78%, Epoch Time: 28.14m
Training Complete Epoch 213 - Total Time: 28.14m

✅ Epoch 213 - Training Completed. Starting Evaluation...

python(44013) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44016) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44019) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44022) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4650, Accuracy: 87.56%, Time Passed: 4.07m
Evaluation Complete - Loss: 0.4355, Accuracy: 88.69%, Total Time: 7.25m

📊 Epoch 213 - Evaluation Completed.


🚀 Epoch 214 - Training Started...

python(44045) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44047) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44049) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(44051) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 214, Batch 100, Loss: 0.0467, Accuracy: 97.56%, Time Passed: 5.25m
Epoch 214, Batch 200, Loss: 0.0448, Accuracy: 97.70%, Time Passed: 9.56m
Epoch 214, Batch 300, Loss: 0.0456, Accuracy: 97.80%, Time Passed: 19.09m
Epoch 214, Batch 400, Loss: 0.0455, Accuracy: 97.78%, Time Passed: 26.94m
Epoch 214, Batch 500, Loss: 0.0467, Accuracy: 97.79%, Time Passed: 35.42m
Epoch 214 Completed - Average Loss: 0.0471, Accuracy: 97.76%, Epoch Time: 39.65m
Training Complete Epoch 214 - Total Time: 39.65m

✅ Epoch 214 - Training Completed. Starting Evaluation...

python(45385) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(45387) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(45390) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(45392) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4711, Accuracy: 87.66%, Time Passed: 4.15m
Evaluation Complete - Loss: 0.4436, Accuracy: 88.63%, Total Time: 7.45m

📊 Epoch 214 - Evaluation Completed.


🚀 Epoch 215 - Training Started...

python(45442) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(45444) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(45446) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(45448) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 215, Batch 100, Loss: 0.0416, Accuracy: 98.06%, Time Passed: 5.08m
Epoch 215, Batch 200, Loss: 0.0452, Accuracy: 97.92%, Time Passed: 10.90m
Epoch 215, Batch 300, Loss: 0.0474, Accuracy: 97.84%, Time Passed: 16.95m
Epoch 215, Batch 400, Loss: 0.0456, Accuracy: 97.86%, Time Passed: 23.26m
Epoch 215, Batch 500, Loss: 0.0460, Accuracy: 97.84%, Time Passed: 28.23m
Epoch 215 Completed - Average Loss: 0.0464, Accuracy: 97.81%, Epoch Time: 31.48m
Training Complete Epoch 215 - Total Time: 31.48m

✅ Epoch 215 - Training Completed. Starting Evaluation...

python(46917) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(46919) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(46921) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(46923) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4539, Accuracy: 88.09%, Time Passed: 3.97m
Evaluation Complete - Loss: 0.4255, Accuracy: 89.38%, Total Time: 7.22m

📊 Epoch 215 - Evaluation Completed.


🚀 Epoch 216 - Training Started...

python(46949) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(46951) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(46953) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(46956) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 216, Batch 100, Loss: 0.0381, Accuracy: 98.09%, Time Passed: 4.34m
Epoch 216, Batch 200, Loss: 0.0410, Accuracy: 98.03%, Time Passed: 8.67m
Epoch 216, Batch 300, Loss: 0.0443, Accuracy: 97.84%, Time Passed: 13.06m
Epoch 216, Batch 400, Loss: 0.0454, Accuracy: 97.83%, Time Passed: 17.50m
Epoch 216, Batch 500, Loss: 0.0458, Accuracy: 97.80%, Time Passed: 21.91m
Epoch 216 Completed - Average Loss: 0.0459, Accuracy: 97.80%, Epoch Time: 25.06m
Training Complete Epoch 216 - Total Time: 25.06m

✅ Epoch 216 - Training Completed. Starting Evaluation...

python(47047) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47049) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47051) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47054) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4585, Accuracy: 88.00%, Time Passed: 3.99m
Evaluation Complete - Loss: 0.4439, Accuracy: 88.78%, Total Time: 7.28m

📊 Epoch 216 - Evaluation Completed.


🚀 Epoch 217 - Training Started...

python(47077) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47079) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47081) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47083) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 217, Batch 100, Loss: 0.0402, Accuracy: 97.97%, Time Passed: 5.30m
Epoch 217, Batch 200, Loss: 0.0405, Accuracy: 98.03%, Time Passed: 10.02m
Epoch 217, Batch 300, Loss: 0.0428, Accuracy: 97.94%, Time Passed: 14.75m
Epoch 217, Batch 400, Loss: 0.0412, Accuracy: 97.99%, Time Passed: 19.11m
Epoch 217, Batch 500, Loss: 0.0417, Accuracy: 97.92%, Time Passed: 23.53m
Epoch 217 Completed - Average Loss: 0.0420, Accuracy: 97.91%, Epoch Time: 26.88m
Training Complete Epoch 217 - Total Time: 26.88m

✅ Epoch 217 - Training Completed. Starting Evaluation...

python(47329) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47331) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47333) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47335) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4732, Accuracy: 87.31%, Time Passed: 4.09m
Evaluation Complete - Loss: 0.4573, Accuracy: 88.39%, Total Time: 7.44m

📊 Epoch 217 - Evaluation Completed.


🚀 Epoch 218 - Training Started...

python(47378) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47380) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47382) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47384) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 218, Batch 100, Loss: 0.0502, Accuracy: 97.78%, Time Passed: 4.84m
Epoch 218, Batch 200, Loss: 0.0449, Accuracy: 97.80%, Time Passed: 9.29m
Epoch 218, Batch 300, Loss: 0.0459, Accuracy: 97.77%, Time Passed: 13.84m
Epoch 218, Batch 400, Loss: 0.0469, Accuracy: 97.72%, Time Passed: 18.29m
Epoch 218, Batch 500, Loss: 0.0459, Accuracy: 97.73%, Time Passed: 22.73m
Epoch 218 Completed - Average Loss: 0.0456, Accuracy: 97.74%, Epoch Time: 25.87m
Training Complete Epoch 218 - Total Time: 25.87m

✅ Epoch 218 - Training Completed. Starting Evaluation...

python(47477) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47479) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47481) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47483) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4762, Accuracy: 88.12%, Time Passed: 4.09m
Evaluation Complete - Loss: 0.4497, Accuracy: 88.88%, Total Time: 7.29m

📊 Epoch 218 - Evaluation Completed.


🚀 Epoch 219 - Training Started...

python(47509) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47511) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47513) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47515) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 219, Batch 100, Loss: 0.0379, Accuracy: 97.84%, Time Passed: 4.45m
Epoch 219, Batch 200, Loss: 0.0400, Accuracy: 97.88%, Time Passed: 8.97m
Epoch 219, Batch 300, Loss: 0.0377, Accuracy: 97.97%, Time Passed: 13.39m
Epoch 219, Batch 400, Loss: 0.0404, Accuracy: 97.94%, Time Passed: 17.68m
Epoch 219, Batch 500, Loss: 0.0415, Accuracy: 97.90%, Time Passed: 21.95m
Epoch 219 Completed - Average Loss: 0.0403, Accuracy: 97.92%, Epoch Time: 25.18m
Training Complete Epoch 219 - Total Time: 25.18m

✅ Epoch 219 - Training Completed. Starting Evaluation...

python(47611) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47614) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47617) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47620) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4472, Accuracy: 88.44%, Time Passed: 4.13m
Evaluation Complete - Loss: 0.4408, Accuracy: 89.01%, Total Time: 7.43m

📊 Epoch 219 - Evaluation Completed.


🚀 Epoch 220 - Training Started...

python(47699) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47701) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47703) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47705) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 220, Batch 100, Loss: 0.0355, Accuracy: 98.28%, Time Passed: 5.88m
Epoch 220, Batch 200, Loss: 0.0382, Accuracy: 98.22%, Time Passed: 10.88m
Epoch 220, Batch 300, Loss: 0.0413, Accuracy: 98.10%, Time Passed: 15.80m
Epoch 220, Batch 400, Loss: 0.0418, Accuracy: 98.00%, Time Passed: 20.46m
Epoch 220, Batch 500, Loss: 0.0426, Accuracy: 97.96%, Time Passed: 24.83m
Epoch 220 Completed - Average Loss: 0.0431, Accuracy: 97.93%, Epoch Time: 28.47m
Training Complete Epoch 220 - Total Time: 28.47m

✅ Epoch 220 - Training Completed. Starting Evaluation...

python(47967) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47970) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47973) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(47976) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.4464, Accuracy: 88.44%, Time Passed: 4.13m
Evaluation Complete - Loss: 0.4387, Accuracy: 88.95%, Total Time: 7.38m

📊 Epoch 220 - Evaluation Completed.

In [73]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_top_30_{start_epoch}_{end_epoch}.pkl')

## **full_web_lowest_30_dataset**

### Step 1

In [46]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[1])

✅ Random seed set to 1234 (MPS available: True)

In [77]:
training_states = joblib.load(WORKSPACE_DIR /
                              "Phase 1/mobilenetv2/training_states/training_states_121_130.pkl")
 
mobilenetv2_stageF_lowest_30 = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes)) 
device = torch.device("mps") 
mobilenetv2_stageF_lowest_30.to(device)
mobilenetv2_stageF_lowest_30.load_state_dict(training_states[127]["model_state_dict"])
del training_states

### the following method divide the other class weights by 2

In [48]:
norm_sqrt_inv_weights_train = compute_class_weights(train_dataset, method="sqrt_inverse", normalize=True)
norm_sqrt_inv_weights_train_lowest_30 = compute_class_weights(web_lowest_30_dataset, method="sqrt_inverse", normalize=True)   
norm_sqrt_inv_weights_train_lowest_30[-1] = 0 # handel other class

In [49]:
norm_sqrt_inv_weights = (norm_sqrt_inv_weights_train + (2*norm_sqrt_inv_weights_train_lowest_30))/2

In [50]:
norm_sqrt_inv_weights

tensor([1.0964, 1.1421, 1.5081, 1.2170, 1.1522, 1.2750, 1.5694, 1.9039, 2.3485,
        1.0524, 1.6564, 2.0909, 1.0611, 0.9941, 1.0207, 1.4491, 2.7100, 1.5648,
        1.1239, 0.9281, 0.9572, 1.5909, 1.1301, 0.8475, 1.2812, 1.0702, 1.4472,
        1.1048, 0.8819, 1.2444, 1.6734, 2.6062, 0.4783], device='mps:0')

In [51]:
norm_sqrt_inv_criterion = nn.CrossEntropyLoss(weight=norm_sqrt_inv_weights)
stageF_optimizer = torch.optim.AdamW(mobilenetv2_stageF_lowest_30.parameters(), lr=1e-5,
                            weight_decay=1e-4, betas=(0.9, 0.999))

In [52]:
start_epoch = 128
end_epoch = 140
start_epoch, end_epoch

(128, 140)

In [53]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_lowest_30, full_web_lowest_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_lowest_30', save_dir = 'Training outputs',
                         class_weights='norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 128 - Training Started...

Epoch 128, Batch 100, Loss: 1.0329, Accuracy: 85.28%, Time Passed: 3.85m
Epoch 128, Batch 200, Loss: 0.9729, Accuracy: 85.67%, Time Passed: 7.84m
Epoch 128, Batch 300, Loss: 0.9540, Accuracy: 85.36%, Time Passed: 11.84m
Epoch 128, Batch 400, Loss: 0.9084, Accuracy: 85.72%, Time Passed: 16.27m
Epoch 128, Batch 500, Loss: 0.8916, Accuracy: 85.62%, Time Passed: 20.44m
Epoch 128 Completed - Average Loss: 0.8734, Accuracy: 85.70%, Epoch Time: 23.53m
Training Complete Epoch 128 - Total Time: 23.53m

✅ Epoch 128 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7620, Accuracy: 79.69%, Time Passed: 4.26m
Evaluation Complete - Loss: 0.7217, Accuracy: 82.05%, Total Time: 7.63m

📊 Epoch 128 - Evaluation Completed.


🚀 Epoch 129 - Training Started...

Epoch 129, Batch 100, Loss: 0.6852, Accuracy: 85.97%, Time Passed: 4.31m
Epoch 129, Batch 200, Loss: 0.6766, Accuracy: 86.11%, Time Passed: 8.85m
Epoch 129, Batch 300, Loss: 0.6557, Accuracy: 86.31%, Time Passed: 13.90m
Epoch 129, Batch 400, Loss: 0.6596, Accuracy: 86.19%, Time Passed: 18.41m
Epoch 129, Batch 500, Loss: 0.6611, Accuracy: 86.12%, Time Passed: 22.75m
Epoch 129 Completed - Average Loss: 0.6492, Accuracy: 86.44%, Epoch Time: 25.99m
Training Complete Epoch 129 - Total Time: 25.99m

✅ Epoch 129 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7491, Accuracy: 79.66%, Time Passed: 4.25m
Evaluation Complete - Loss: 0.7045, Accuracy: 82.50%, Total Time: 7.49m

📊 Epoch 129 - Evaluation Completed.


🚀 Epoch 130 - Training Started...

Epoch 130, Batch 100, Loss: 0.5488, Accuracy: 87.28%, Time Passed: 4.21m
Epoch 130, Batch 200, Loss: 0.5477, Accuracy: 87.45%, Time Passed: 8.55m
Epoch 130, Batch 300, Loss: 0.5624, Accuracy: 87.10%, Time Passed: 12.75m
Epoch 130, Batch 400, Loss: 0.5544, Accuracy: 87.13%, Time Passed: 17.06m
Epoch 130, Batch 500, Loss: 0.5546, Accuracy: 86.96%, Time Passed: 21.45m
Epoch 130 Completed - Average Loss: 0.5588, Accuracy: 86.82%, Epoch Time: 24.58m
Training Complete Epoch 130 - Total Time: 24.58m

✅ Epoch 130 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7682, Accuracy: 79.38%, Time Passed: 4.26m
Evaluation Complete - Loss: 0.7174, Accuracy: 82.18%, Total Time: 7.61m

📊 Epoch 130 - Evaluation Completed.


🚀 Epoch 131 - Training Started...

Epoch 131, Batch 100, Loss: 0.4818, Accuracy: 87.16%, Time Passed: 4.50m
Epoch 131, Batch 200, Loss: 0.4928, Accuracy: 87.45%, Time Passed: 8.98m
Epoch 131, Batch 300, Loss: 0.5050, Accuracy: 86.99%, Time Passed: 13.37m
Epoch 131, Batch 400, Loss: 0.5080, Accuracy: 87.08%, Time Passed: 18.05m
Epoch 131, Batch 500, Loss: 0.5073, Accuracy: 87.16%, Time Passed: 22.65m
Epoch 131 Completed - Average Loss: 0.5056, Accuracy: 87.18%, Epoch Time: 25.90m
Training Complete Epoch 131 - Total Time: 25.90m

✅ Epoch 131 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7133, Accuracy: 79.97%, Time Passed: 4.31m
Evaluation Complete - Loss: 0.6582, Accuracy: 82.91%, Total Time: 7.67m

📊 Epoch 131 - Evaluation Completed.


🚀 Epoch 132 - Training Started...

Epoch 132, Batch 100, Loss: 0.4331, Accuracy: 88.50%, Time Passed: 4.41m
Epoch 132, Batch 200, Loss: 0.4398, Accuracy: 88.42%, Time Passed: 8.80m
Epoch 132, Batch 300, Loss: 0.4503, Accuracy: 88.30%, Time Passed: 13.12m
Epoch 132, Batch 400, Loss: 0.4590, Accuracy: 87.95%, Time Passed: 17.39m
Epoch 132, Batch 500, Loss: 0.4548, Accuracy: 88.09%, Time Passed: 21.69m
Epoch 132 Completed - Average Loss: 0.4569, Accuracy: 87.96%, Epoch Time: 24.92m
Training Complete Epoch 132 - Total Time: 24.92m

✅ Epoch 132 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6590, Accuracy: 81.28%, Time Passed: 4.14m
Evaluation Complete - Loss: 0.6247, Accuracy: 83.84%, Total Time: 7.41m

📊 Epoch 132 - Evaluation Completed.


🚀 Epoch 133 - Training Started...

Epoch 133, Batch 100, Loss: 0.4689, Accuracy: 87.41%, Time Passed: 4.10m
Epoch 133, Batch 200, Loss: 0.4635, Accuracy: 87.48%, Time Passed: 8.38m
Epoch 133, Batch 300, Loss: 0.4605, Accuracy: 87.74%, Time Passed: 12.64m
Epoch 133, Batch 400, Loss: 0.4563, Accuracy: 87.95%, Time Passed: 16.85m
Epoch 133, Batch 500, Loss: 0.4489, Accuracy: 88.11%, Time Passed: 21.19m
Epoch 133 Completed - Average Loss: 0.4468, Accuracy: 88.16%, Epoch Time: 24.48m
Training Complete Epoch 133 - Total Time: 24.48m

✅ Epoch 133 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6665, Accuracy: 80.59%, Time Passed: 4.15m
Evaluation Complete - Loss: 0.6355, Accuracy: 83.28%, Total Time: 7.37m

📊 Epoch 133 - Evaluation Completed.


🚀 Epoch 134 - Training Started...

Epoch 134, Batch 100, Loss: 0.4282, Accuracy: 88.53%, Time Passed: 4.19m
Epoch 134, Batch 200, Loss: 0.4206, Accuracy: 88.42%, Time Passed: 8.55m
Epoch 134, Batch 300, Loss: 0.4294, Accuracy: 88.14%, Time Passed: 12.90m
Epoch 134, Batch 400, Loss: 0.4295, Accuracy: 88.27%, Time Passed: 17.25m
Epoch 134, Batch 500, Loss: 0.4245, Accuracy: 88.43%, Time Passed: 21.52m
Epoch 134 Completed - Average Loss: 0.4247, Accuracy: 88.59%, Epoch Time: 24.60m
Training Complete Epoch 134 - Total Time: 24.60m

✅ Epoch 134 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6701, Accuracy: 80.22%, Time Passed: 4.17m
Evaluation Complete - Loss: 0.5988, Accuracy: 83.50%, Total Time: 7.44m

📊 Epoch 134 - Evaluation Completed.


🚀 Epoch 135 - Training Started...

Epoch 135, Batch 100, Loss: 0.4175, Accuracy: 88.94%, Time Passed: 4.06m
Epoch 135, Batch 200, Loss: 0.4016, Accuracy: 89.06%, Time Passed: 8.43m
Epoch 135, Batch 300, Loss: 0.4194, Accuracy: 88.65%, Time Passed: 12.74m
Epoch 135, Batch 400, Loss: 0.4133, Accuracy: 88.99%, Time Passed: 17.13m
Epoch 135, Batch 500, Loss: 0.4164, Accuracy: 88.78%, Time Passed: 21.48m
Epoch 135 Completed - Average Loss: 0.4182, Accuracy: 88.75%, Epoch Time: 24.56m
Training Complete Epoch 135 - Total Time: 24.56m

✅ Epoch 135 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6467, Accuracy: 80.81%, Time Passed: 4.14m
Evaluation Complete - Loss: 0.6006, Accuracy: 83.61%, Total Time: 7.36m

📊 Epoch 135 - Evaluation Completed.


🚀 Epoch 136 - Training Started...

Epoch 136, Batch 100, Loss: 0.3833, Accuracy: 89.22%, Time Passed: 4.17m
Epoch 136, Batch 200, Loss: 0.3977, Accuracy: 88.80%, Time Passed: 8.45m
Epoch 136, Batch 300, Loss: 0.3941, Accuracy: 88.86%, Time Passed: 12.67m
Epoch 136, Batch 400, Loss: 0.3920, Accuracy: 88.88%, Time Passed: 16.97m
Epoch 136, Batch 500, Loss: 0.3911, Accuracy: 88.92%, Time Passed: 21.19m
Epoch 136 Completed - Average Loss: 0.3922, Accuracy: 88.82%, Epoch Time: 24.30m
Training Complete Epoch 136 - Total Time: 24.30m

✅ Epoch 136 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5951, Accuracy: 82.31%, Time Passed: 4.15m
Evaluation Complete - Loss: 0.5525, Accuracy: 84.77%, Total Time: 7.48m

📊 Epoch 136 - Evaluation Completed.


🚀 Epoch 137 - Training Started...

Epoch 137, Batch 100, Loss: 0.3780, Accuracy: 89.22%, Time Passed: 4.11m
Epoch 137, Batch 200, Loss: 0.3869, Accuracy: 89.06%, Time Passed: 8.42m
Epoch 137, Batch 300, Loss: 0.3805, Accuracy: 89.12%, Time Passed: 12.74m
Epoch 137, Batch 400, Loss: 0.3780, Accuracy: 89.37%, Time Passed: 17.06m
Epoch 137, Batch 500, Loss: 0.3828, Accuracy: 89.35%, Time Passed: 21.43m
Epoch 137 Completed - Average Loss: 0.3857, Accuracy: 89.26%, Epoch Time: 24.57m
Training Complete Epoch 137 - Total Time: 24.57m

✅ Epoch 137 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6253, Accuracy: 81.62%, Time Passed: 4.13m
Evaluation Complete - Loss: 0.5670, Accuracy: 84.56%, Total Time: 7.42m

📊 Epoch 137 - Evaluation Completed.


🚀 Epoch 138 - Training Started...

Epoch 138, Batch 100, Loss: 0.3675, Accuracy: 89.88%, Time Passed: 4.16m
Epoch 138, Batch 200, Loss: 0.3715, Accuracy: 89.75%, Time Passed: 8.46m
Epoch 138, Batch 300, Loss: 0.3812, Accuracy: 89.38%, Time Passed: 12.66m
Epoch 138, Batch 400, Loss: 0.3778, Accuracy: 89.40%, Time Passed: 16.87m
Epoch 138, Batch 500, Loss: 0.3750, Accuracy: 89.44%, Time Passed: 21.09m
Epoch 138 Completed - Average Loss: 0.3706, Accuracy: 89.55%, Epoch Time: 24.25m
Training Complete Epoch 138 - Total Time: 24.25m

✅ Epoch 138 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5881, Accuracy: 82.47%, Time Passed: 4.15m
Evaluation Complete - Loss: 0.5426, Accuracy: 84.91%, Total Time: 7.39m

📊 Epoch 138 - Evaluation Completed.


🚀 Epoch 139 - Training Started...

Epoch 139, Batch 100, Loss: 0.3439, Accuracy: 90.50%, Time Passed: 4.15m
Epoch 139, Batch 200, Loss: 0.3469, Accuracy: 90.50%, Time Passed: 8.49m
Epoch 139, Batch 300, Loss: 0.3514, Accuracy: 90.23%, Time Passed: 12.72m
Epoch 139, Batch 400, Loss: 0.3635, Accuracy: 89.83%, Time Passed: 16.89m
Epoch 139, Batch 500, Loss: 0.3665, Accuracy: 89.68%, Time Passed: 21.11m
Epoch 139 Completed - Average Loss: 0.3697, Accuracy: 89.61%, Epoch Time: 24.20m
Training Complete Epoch 139 - Total Time: 24.20m

✅ Epoch 139 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5728, Accuracy: 83.31%, Time Passed: 4.13m
Evaluation Complete - Loss: 0.5498, Accuracy: 85.27%, Total Time: 7.36m

📊 Epoch 139 - Evaluation Completed.


🚀 Epoch 140 - Training Started...

Epoch 140, Batch 100, Loss: 0.3456, Accuracy: 90.00%, Time Passed: 4.31m
Epoch 140, Batch 200, Loss: 0.3643, Accuracy: 89.27%, Time Passed: 8.53m
Epoch 140, Batch 300, Loss: 0.3578, Accuracy: 89.24%, Time Passed: 12.89m
Epoch 140, Batch 400, Loss: 0.3492, Accuracy: 89.60%, Time Passed: 17.10m
Epoch 140, Batch 500, Loss: 0.3469, Accuracy: 89.77%, Time Passed: 21.29m
Epoch 140 Completed - Average Loss: 0.3496, Accuracy: 89.77%, Epoch Time: 24.29m
Training Complete Epoch 140 - Total Time: 24.29m

✅ Epoch 140 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5732, Accuracy: 83.38%, Time Passed: 4.12m
Evaluation Complete - Loss: 0.5289, Accuracy: 85.66%, Total Time: 7.30m

📊 Epoch 140 - Evaluation Completed.

In [54]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_lowest_30_{start_epoch}_{end_epoch}.pkl')

In [55]:
del training_states

In [56]:
state, generator = setup_reproducibility(continue_run=True, path="Training outputs/rng_state_140.pkl", mode="save", seed=seeds[1], generator=generator)

✅ RNG state saved to Training outputs/rng_state_140.pkl

In [57]:
start_epoch = 141
end_epoch = 150
start_epoch, end_epoch

(141, 150)

In [58]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_lowest_30, full_web_lowest_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_lowest_30', save_dir = 'Training outputs',
                         class_weights='norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 141 - Training Started...

Epoch 141, Batch 100, Loss: 0.3320, Accuracy: 90.41%, Time Passed: 3.80m
Epoch 141, Batch 200, Loss: 0.3550, Accuracy: 89.80%, Time Passed: 7.49m
Epoch 141, Batch 300, Loss: 0.3558, Accuracy: 89.57%, Time Passed: 11.29m
Epoch 141, Batch 400, Loss: 0.3487, Accuracy: 89.71%, Time Passed: 15.15m
Epoch 141, Batch 500, Loss: 0.3496, Accuracy: 89.69%, Time Passed: 19.13m
Epoch 141 Completed - Average Loss: 0.3496, Accuracy: 89.64%, Epoch Time: 22.01m
Training Complete Epoch 141 - Total Time: 22.01m

✅ Epoch 141 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5481, Accuracy: 83.41%, Time Passed: 4.00m
Evaluation Complete - Loss: 0.5127, Accuracy: 85.53%, Total Time: 7.11m

📊 Epoch 141 - Evaluation Completed.


🚀 Epoch 142 - Training Started...

Epoch 142, Batch 100, Loss: 0.2985, Accuracy: 91.56%, Time Passed: 4.49m
Epoch 142, Batch 200, Loss: 0.3256, Accuracy: 90.88%, Time Passed: 8.60m
Epoch 142, Batch 300, Loss: 0.3315, Accuracy: 90.55%, Time Passed: 12.84m
Epoch 142, Batch 400, Loss: 0.3303, Accuracy: 90.61%, Time Passed: 17.20m
Epoch 142, Batch 500, Loss: 0.3283, Accuracy: 90.64%, Time Passed: 21.68m
Epoch 142 Completed - Average Loss: 0.3311, Accuracy: 90.54%, Epoch Time: 25.01m
Training Complete Epoch 142 - Total Time: 25.01m

✅ Epoch 142 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5743, Accuracy: 82.88%, Time Passed: 4.66m
Evaluation Complete - Loss: 0.5384, Accuracy: 85.25%, Total Time: 8.13m

📊 Epoch 142 - Evaluation Completed.


🚀 Epoch 143 - Training Started...

Epoch 143, Batch 100, Loss: 0.3373, Accuracy: 90.50%, Time Passed: 4.40m
Epoch 143, Batch 200, Loss: 0.3361, Accuracy: 90.28%, Time Passed: 9.01m
Epoch 143, Batch 300, Loss: 0.3293, Accuracy: 90.40%, Time Passed: 13.76m
Epoch 143, Batch 400, Loss: 0.3326, Accuracy: 90.35%, Time Passed: 19.32m
Epoch 143, Batch 500, Loss: 0.3334, Accuracy: 90.44%, Time Passed: 24.86m
Epoch 143 Completed - Average Loss: 0.3349, Accuracy: 90.36%, Epoch Time: 29.61m
Training Complete Epoch 143 - Total Time: 29.61m

✅ Epoch 143 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5515, Accuracy: 83.69%, Time Passed: 5.17m
Evaluation Complete - Loss: 0.5419, Accuracy: 85.38%, Total Time: 9.02m

📊 Epoch 143 - Evaluation Completed.


🚀 Epoch 144 - Training Started...

Epoch 144, Batch 100, Loss: 0.3104, Accuracy: 90.69%, Time Passed: 6.48m
Epoch 144, Batch 200, Loss: 0.3214, Accuracy: 90.38%, Time Passed: 12.82m
Epoch 144, Batch 300, Loss: 0.3173, Accuracy: 90.53%, Time Passed: 19.16m
Epoch 144, Batch 400, Loss: 0.3238, Accuracy: 90.34%, Time Passed: 25.00m
Epoch 144, Batch 500, Loss: 0.3250, Accuracy: 90.28%, Time Passed: 32.72m
Epoch 144 Completed - Average Loss: 0.3274, Accuracy: 90.26%, Epoch Time: 36.55m
Training Complete Epoch 144 - Total Time: 36.55m

✅ Epoch 144 - Training Completed. Starting Evaluation...

python(37440) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(37442) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(37444) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(37446) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5724, Accuracy: 83.16%, Time Passed: 4.59m
Evaluation Complete - Loss: 0.5363, Accuracy: 85.44%, Total Time: 7.98m

📊 Epoch 144 - Evaluation Completed.


🚀 Epoch 145 - Training Started...

python(37475) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(37477) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(37479) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(37481) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 145, Batch 100, Loss: 0.3645, Accuracy: 89.69%, Time Passed: 4.94m
Epoch 145, Batch 200, Loss: 0.3480, Accuracy: 89.98%, Time Passed: 10.27m
Epoch 145, Batch 300, Loss: 0.3446, Accuracy: 90.09%, Time Passed: 15.82m
Epoch 145, Batch 400, Loss: 0.3353, Accuracy: 90.23%, Time Passed: 20.97m
Epoch 145, Batch 500, Loss: 0.3317, Accuracy: 90.32%, Time Passed: 26.07m
Epoch 145 Completed - Average Loss: 0.3263, Accuracy: 90.48%, Epoch Time: 29.75m
Training Complete Epoch 145 - Total Time: 29.75m

✅ Epoch 145 - Training Completed. Starting Evaluation...

python(38697) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(38699) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(38701) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(38703) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5369, Accuracy: 84.16%, Time Passed: 4.36m
Evaluation Complete - Loss: 0.5075, Accuracy: 86.09%, Total Time: 7.73m

📊 Epoch 145 - Evaluation Completed.


🚀 Epoch 146 - Training Started...

python(38732) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(38734) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(38736) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(38738) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 146, Batch 100, Loss: 0.3184, Accuracy: 90.25%, Time Passed: 4.52m
Epoch 146, Batch 200, Loss: 0.3109, Accuracy: 90.86%, Time Passed: 9.28m
Epoch 146, Batch 300, Loss: 0.3117, Accuracy: 90.81%, Time Passed: 13.88m
Epoch 146, Batch 400, Loss: 0.3101, Accuracy: 90.72%, Time Passed: 18.46m
Epoch 146, Batch 500, Loss: 0.3150, Accuracy: 90.68%, Time Passed: 22.96m
Epoch 146 Completed - Average Loss: 0.3154, Accuracy: 90.61%, Epoch Time: 26.31m
Training Complete Epoch 146 - Total Time: 26.31m

✅ Epoch 146 - Training Completed. Starting Evaluation...

python(38842) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(38844) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(38846) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(38848) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5722, Accuracy: 82.81%, Time Passed: 4.28m
Evaluation Complete - Loss: 0.5407, Accuracy: 85.03%, Total Time: 7.56m

📊 Epoch 146 - Evaluation Completed.


🚀 Epoch 147 - Training Started...

python(38855) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(38857) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(38859) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(38861) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 147, Batch 100, Loss: 0.2850, Accuracy: 91.50%, Time Passed: 5.10m
Epoch 147, Batch 200, Loss: 0.3036, Accuracy: 90.59%, Time Passed: 11.30m
Epoch 147, Batch 300, Loss: 0.3093, Accuracy: 90.47%, Time Passed: 18.28m
Epoch 147, Batch 400, Loss: 0.3122, Accuracy: 90.54%, Time Passed: 23.49m
Epoch 147, Batch 500, Loss: 0.3179, Accuracy: 90.47%, Time Passed: 29.21m
Epoch 147 Completed - Average Loss: 0.3172, Accuracy: 90.54%, Epoch Time: 32.32m
Training Complete Epoch 147 - Total Time: 32.32m

✅ Epoch 147 - Training Completed. Starting Evaluation...

python(39534) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(39537) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(39540) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(39542) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5561, Accuracy: 83.78%, Time Passed: 4.03m
Evaluation Complete - Loss: 0.5266, Accuracy: 85.66%, Total Time: 7.26m

📊 Epoch 147 - Evaluation Completed.


🚀 Epoch 148 - Training Started...

python(39627) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(39629) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(39631) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(39633) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 148, Batch 100, Loss: 0.3361, Accuracy: 90.62%, Time Passed: 4.37m
Epoch 148, Batch 200, Loss: 0.3156, Accuracy: 90.66%, Time Passed: 8.84m
Epoch 148, Batch 300, Loss: 0.3093, Accuracy: 90.70%, Time Passed: 13.51m
Epoch 148, Batch 400, Loss: 0.3095, Accuracy: 90.65%, Time Passed: 18.27m
Epoch 148, Batch 500, Loss: 0.3094, Accuracy: 90.71%, Time Passed: 23.15m
Epoch 148 Completed - Average Loss: 0.3099, Accuracy: 90.74%, Epoch Time: 26.47m
Training Complete Epoch 148 - Total Time: 26.47m

✅ Epoch 148 - Training Completed. Starting Evaluation...

python(39814) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(39816) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(39818) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(39821) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5427, Accuracy: 84.34%, Time Passed: 4.32m
Evaluation Complete - Loss: 0.5112, Accuracy: 86.09%, Total Time: 7.71m

📊 Epoch 148 - Evaluation Completed.


🚀 Epoch 149 - Training Started...

python(39841) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(39843) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(39845) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(39847) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 149, Batch 100, Loss: 0.3123, Accuracy: 90.47%, Time Passed: 4.77m
Epoch 149, Batch 200, Loss: 0.3035, Accuracy: 90.81%, Time Passed: 9.33m
Epoch 149, Batch 300, Loss: 0.3073, Accuracy: 91.03%, Time Passed: 14.13m
Epoch 149, Batch 400, Loss: 0.3030, Accuracy: 91.12%, Time Passed: 18.94m
Epoch 149, Batch 500, Loss: 0.3004, Accuracy: 91.16%, Time Passed: 23.65m
Epoch 149 Completed - Average Loss: 0.2976, Accuracy: 91.13%, Epoch Time: 26.89m
Training Complete Epoch 149 - Total Time: 26.89m

✅ Epoch 149 - Training Completed. Starting Evaluation...

python(40060) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40064) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40067) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40069) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5872, Accuracy: 82.97%, Time Passed: 4.36m
Evaluation Complete - Loss: 0.5307, Accuracy: 85.27%, Total Time: 7.82m

📊 Epoch 149 - Evaluation Completed.


🚀 Epoch 150 - Training Started...

python(40094) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40096) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40098) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40100) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Epoch 150, Batch 100, Loss: 0.2775, Accuracy: 91.53%, Time Passed: 5.39m
Epoch 150, Batch 200, Loss: 0.2830, Accuracy: 91.56%, Time Passed: 10.00m
Epoch 150, Batch 300, Loss: 0.2885, Accuracy: 91.50%, Time Passed: 14.79m
Epoch 150, Batch 400, Loss: 0.2866, Accuracy: 91.45%, Time Passed: 19.56m
Epoch 150, Batch 500, Loss: 0.2864, Accuracy: 91.47%, Time Passed: 24.33m
Epoch 150 Completed - Average Loss: 0.2887, Accuracy: 91.36%, Epoch Time: 27.68m
Training Complete Epoch 150 - Total Time: 27.68m

✅ Epoch 150 - Training Completed. Starting Evaluation...

python(40171) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40173) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40175) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(40177) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Batch 100, Loss: 0.5543, Accuracy: 83.25%, Time Passed: 4.35m
Evaluation Complete - Loss: 0.5240, Accuracy: 85.34%, Total Time: 7.76m

📊 Epoch 150 - Evaluation Completed.

In [59]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_lowest_30_{start_epoch}_{end_epoch}.pkl')

In [60]:
del training_states

In [51]:
training_states = joblib.load("Training outputs/training_states_lowest_30_141_150.pkl"
)
mobilenetv2_stageF_lowest_30 = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes)) 
device = torch.device("mps") 
mobilenetv2_stageF_lowest_30.to(device)
mobilenetv2_stageF_lowest_30.load_state_dict(training_states[150]["model_state_dict"])
del training_states

norm_sqrt_inv_weights_train = compute_class_weights(train_dataset, method="sqrt_inverse", normalize=True)
norm_sqrt_inv_weights_train_lowest_30 = compute_class_weights(web_lowest_30_dataset, method="sqrt_inverse", normalize=True)   
norm_sqrt_inv_weights_train_lowest_30[-1] = 0 # handel other class
norm_sqrt_inv_weights = (norm_sqrt_inv_weights_train + (2*norm_sqrt_inv_weights_train_lowest_30))/2
norm_sqrt_inv_criterion = nn.CrossEntropyLoss(weight=norm_sqrt_inv_weights)

web_datasets_dict_list = [{'All Web Data': web_dataset},
 {'Web Correctly Classified': web_correctly_classified_dataset},
 {'Web Top 30': web_top_30_dataset}, 
 {'Web Mid_30_70': web_mid_30_70_dataset},
 {'Web Lowest 30': web_lowest_30_dataset}
]

In [52]:
lowest_30_all_results, lowest_30_metrics_summary = evaluate_on_three_sets(
    mobilenetv2_stageF_lowest_30,
    web_datasets_dict_list[4],          
    web_datasets_dict_list[0],        
    [d for i, d in enumerate(web_datasets_dict_list) if i not in (0, 4)],      # list of dicts, each has one dataset
    val_transform,
    "mobilenetv2_stageF_lowest_30",
    norm_sqrt_inv_criterion,
    train_dataset.classes,
    epoch_num=150,
    log_interval=100,
    batch_size=32,
    num_workers=4
)

🔹 Starting evaluation for: Web Lowest 30 (used in training)
Evaluation Complete - Loss: 1.8633, Accuracy: 50.96%, Total Time: 0.55m

🔹 Starting evaluation for: All Web Data
Batch 100, Loss: 1.4624, Accuracy: 59.34%, Time Passed: 0.37m
Evaluation Complete - Loss: 1.3854, Accuracy: 60.73%, Total Time: 0.92m

🔹 Starting evaluation for: Web Correctly Classified
Evaluation Complete - Loss: 7.0380, Accuracy: 28.32%, Total Time: 0.59m

🔹 Starting evaluation for: Web Top 30
Evaluation Complete - Loss: 1.3445, Accuracy: 58.42%, Total Time: 0.54m

🔹 Starting evaluation for: Web Mid_30_70
Evaluation Complete - Loss: 1.9630, Accuracy: 46.81%, Total Time: 0.57m

🔹 Starting evaluation for: Concatenated Remaining Web Data (unseen)
Batch 100, Loss: 4.5967, Accuracy: 41.31%, Time Passed: 0.43m
Evaluation Complete - Loss: 3.7918, Accuracy: 42.56%, Total Time: 0.89m

In [143]:
lowest_30_all_results.to_csv("Training outputs/lowest_30_web_test_150_results.csv", index=False)
lowest_30_metrics_summary.to_csv("Training outputs/lowest_30_web_test_150_metrics.csv", index=False)

### Continue training (Step 2)

In [53]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[2])

✅ Random seed set to 2025 (MPS available: True)

In [54]:
training_states = joblib.load("Training outputs/training_states_lowest_30_141_150.pkl")
mobilenetv2_stageF_lowest_30 = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes)) 
device = torch.device("mps") 
mobilenetv2_stageF_lowest_30.to(device)
mobilenetv2_stageF_lowest_30.load_state_dict(training_states[150]["model_state_dict"])
del training_states

In [55]:
norm_sqrt_inv_weights_train = compute_class_weights(train_dataset, method="sqrt_inverse", normalize=True)
norm_sqrt_inv_weights_train_lowest_30 = compute_class_weights(web_lowest_30_dataset, method="sqrt_inverse", normalize=True)   
norm_sqrt_inv_weights_train_lowest_30[-1] = 0 # handel other class
norm_sqrt_inv_weights = (norm_sqrt_inv_weights_train + (2*norm_sqrt_inv_weights_train_lowest_30))/2


lowest_30_val_results141_150 = pd.read_csv("Training outputs/mobilenetv2_stageF_lowest_30_val_results141_150.csv")

# Step 1: get the subset dataframe
df = lowest_30_val_results141_150[
    (lowest_30_val_results141_150['Species'] != "Average Performance (Macro)") &
    (lowest_30_val_results141_150['Epoch'] == 150)
].copy()

# Step 2: build a mapping from species to recall multiplier
def get_multiplier(recall):
    if recall < 0.6:
        return 10
    elif recall < 0.7:
        return 8
    elif recall < 0.8:
        return 6
    elif recall < 0.9:
        return 4
    elif recall < 1:
        return 2
    else:
        return 1

df['Multiplier'] = df['Recall'].apply(get_multiplier)

# Step 3: make sure class order matches your dataset order
species_to_multiplier = dict(zip(df['Species'], df['Multiplier']))

# Step 4: apply the multipliers to your weight vector
adjusted_weights = norm_sqrt_inv_weights.clone() if hasattr(norm_sqrt_inv_weights, 'clone') else np.copy(norm_sqrt_inv_weights)

for idx, class_name in enumerate(train_dataset.classes):
    if class_name in species_to_multiplier:
        adjusted_weights[idx] *= species_to_multiplier[class_name]

In [56]:
df

,Species,Precision,Recall,F1-score,Epoch,Multiplier
306,Anabasis articulata (Forssk.) Moq.,0.849315,1.000000,0.918519,150,1
307,Anabasis setifera Moq.,0.900000,0.727273,0.804469,150,6
308,Atriplex halimus L.,0.718023,0.879004,0.790400,150,4
309,Calotropis procera,0.916667,0.950617,0.933333,150,2
310,Capparis spinosa L.,0.962617,0.725352,0.827309,150,6
311,Cebatha pendula (J.R.Forst. & G.Forst.) Kuntze,0.932584,0.691667,0.794258,150,8
312,Cenchrus divisus,0.943182,0.954023,0.948571,150,2
313,Deverra tortuosa (Desf.) DC.,0.813953,1.000000,0.897436,150,1
314,Deverra triradiata Hochst. ex Boiss.,0.793651,1.000000,0.884956,150,1
315,Diplotaxis harra (Forssk.) Boiss.,0.827586,0.882353,0.854093,150,4
316,Echinops glaberrimus DC.,0.840517,0.955882,0.894495,150,2
317,Ephedra alata Decne.,0.801762,0.892157,0.844548,150,4
318,Farsetia aegyptia Turra,0.915094,0.524324,0.666667,150,10
319,Gymnocarpos decander Forssk.,0.854167,0.953488,0.901099,150,2
320,Haloxylon salicornicum (Moq.) Bunge ex Boiss.,0.762626,0.888235,0.820652,150,4
321,Heliotropium arbainense Fresen.,0.973545,0.893204,0.931646,150,4
322,Iphiona mucronata (Forssk.) Asch. & Schweinf.,0.936508,0.983333,0.959350,150,2
323,Limonium pruinosum (L.) Chaz.,0.940299,0.707865,0.807692,150,6
324,Lycium shawii Roem. & Schult.,0.875000,0.700000,0.777778,150,6
325,Nitraria retusa (Forssk.) Asch.,0.794118,0.773885,0.783871,150,6
326,Ochradenus baccatus Delile,0.882784,0.967871,0.923372,150,2
327,Peganum harmala L.,0.785714,1.000000,0.880000,150,1
328,Rumex vesicarius L.,0.923913,1.000000,0.960452,150,1
329,Salsola imbricata Forssk.,0.866667,0.990476,0.924444,150,2
330,Stachys aegyptiaca Pers.,0.713514,1.000000,0.832808,150,1
331,Suaeda aegyptiaca (Hasselq.) Zohary,0.795031,0.962406,0.870748,150,2
332,Tamarix nilotica (Ehrenb.) Bunge,0.933333,0.656250,0.770642,150,8
333,Trichodesma africanum (L.) Sm.,0.876190,0.550898,0.676471,150,10
334,Zilla spinosa (L.) Prantl,0.787671,1.000000,0.881226,150,1
335,Zygophyllum arabicum (L.) Christenh. & Byng,0.895833,0.988506,0.939891,150,2
336,Zygophyllum coccineum,0.813084,0.896907,0.852941,150,4
337,Zygophyllum molle (Delile) Christenh. & Byng,0.965812,0.991228,0.978355,150,2
338,others,0.975309,0.790000,0.872928,150,6

In [57]:
adjusted_weights, norm_sqrt_inv_weights

(tensor([ 1.0964,  6.8528,  6.0324,  2.4340,  6.9130, 10.2000,  3.1388,  1.9039,
          2.3485,  4.2096,  3.3128,  8.3636, 10.6105,  1.9881,  4.0826,  5.7964,
          5.4200,  9.3887,  6.7435,  5.5686,  1.9145,  1.5909,  1.1301,  1.6951,
          1.2812,  2.1405, 11.5773, 11.0477,  0.8819,  2.4888,  6.6937,  5.2123,
          2.8695], device='mps:0'),
 tensor([1.0964, 1.1421, 1.5081, 1.2170, 1.1522, 1.2750, 1.5694, 1.9039, 2.3485,
         1.0524, 1.6564, 2.0909, 1.0611, 0.9941, 1.0207, 1.4491, 2.7100, 1.5648,
         1.1239, 0.9281, 0.9572, 1.5909, 1.1301, 0.8475, 1.2812, 1.0702, 1.4472,
         1.1048, 0.8819, 1.2444, 1.6734, 2.6062, 0.4783], device='mps:0'))

In [58]:
norm_sqrt_inv_criterion = nn.CrossEntropyLoss(weight=adjusted_weights)
stageF_optimizer = torch.optim.AdamW(mobilenetv2_stageF_lowest_30.parameters(), lr=1e-5,
                            weight_decay=1e-4, betas=(0.9, 0.999))

In [59]:
start_epoch = 151
end_epoch = 160
start_epoch, end_epoch

(151, 160)

In [60]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_lowest_30, full_web_lowest_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_lowest_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 151 - Training Started...

Epoch 151, Batch 100, Loss: 0.2772, Accuracy: 91.22%, Time Passed: 3.41m
Epoch 151, Batch 200, Loss: 0.2817, Accuracy: 91.08%, Time Passed: 6.91m
Epoch 151, Batch 300, Loss: 0.2726, Accuracy: 91.26%, Time Passed: 10.65m
Epoch 151, Batch 400, Loss: 0.2729, Accuracy: 91.09%, Time Passed: 14.50m
Epoch 151, Batch 500, Loss: 0.2719, Accuracy: 91.01%, Time Passed: 18.43m
Epoch 151 Completed - Average Loss: 0.2730, Accuracy: 90.94%, Epoch Time: 21.13m
Training Complete Epoch 151 - Total Time: 21.13m

✅ Epoch 151 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5077, Accuracy: 85.12%, Time Passed: 4.32m
Evaluation Complete - Loss: 0.4836, Accuracy: 86.81%, Total Time: 7.53m

📊 Epoch 151 - Evaluation Completed.


🚀 Epoch 152 - Training Started...

Epoch 152, Batch 100, Loss: 0.2157, Accuracy: 92.25%, Time Passed: 3.65m
Epoch 152, Batch 200, Loss: 0.2260, Accuracy: 91.73%, Time Passed: 7.42m
Epoch 152, Batch 300, Loss: 0.2389, Accuracy: 91.46%, Time Passed: 11.33m
Epoch 152, Batch 400, Loss: 0.2514, Accuracy: 91.00%, Time Passed: 15.13m
Epoch 152, Batch 500, Loss: 0.2532, Accuracy: 91.01%, Time Passed: 18.92m
Epoch 152 Completed - Average Loss: 0.2579, Accuracy: 91.03%, Epoch Time: 21.63m
Training Complete Epoch 152 - Total Time: 21.63m

✅ Epoch 152 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4666, Accuracy: 86.03%, Time Passed: 4.17m
Evaluation Complete - Loss: 0.4488, Accuracy: 87.50%, Total Time: 7.49m

📊 Epoch 152 - Evaluation Completed.


🚀 Epoch 153 - Training Started...

Epoch 153, Batch 100, Loss: 0.2548, Accuracy: 90.91%, Time Passed: 3.70m
Epoch 153, Batch 200, Loss: 0.2454, Accuracy: 91.05%, Time Passed: 7.68m
Epoch 153, Batch 300, Loss: 0.2505, Accuracy: 90.75%, Time Passed: 11.60m
Epoch 153, Batch 400, Loss: 0.2416, Accuracy: 91.02%, Time Passed: 15.31m
Epoch 153, Batch 500, Loss: 0.2448, Accuracy: 91.11%, Time Passed: 19.06m
Epoch 153 Completed - Average Loss: 0.2521, Accuracy: 90.91%, Epoch Time: 21.63m
Training Complete Epoch 153 - Total Time: 21.63m

✅ Epoch 153 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4593, Accuracy: 86.22%, Time Passed: 4.18m
Evaluation Complete - Loss: 0.4489, Accuracy: 87.63%, Total Time: 7.42m

📊 Epoch 153 - Evaluation Completed.


🚀 Epoch 154 - Training Started...

Epoch 154, Batch 100, Loss: 0.2402, Accuracy: 90.84%, Time Passed: 3.77m
Epoch 154, Batch 200, Loss: 0.2496, Accuracy: 90.70%, Time Passed: 7.44m
Epoch 154, Batch 300, Loss: 0.2501, Accuracy: 90.86%, Time Passed: 11.04m
Epoch 154, Batch 400, Loss: 0.2408, Accuracy: 91.17%, Time Passed: 14.68m
Epoch 154, Batch 500, Loss: 0.2449, Accuracy: 91.17%, Time Passed: 18.24m
Epoch 154 Completed - Average Loss: 0.2469, Accuracy: 91.09%, Epoch Time: 20.95m
Training Complete Epoch 154 - Total Time: 20.95m

✅ Epoch 154 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4897, Accuracy: 85.69%, Time Passed: 4.01m
Evaluation Complete - Loss: 0.4698, Accuracy: 87.28%, Total Time: 7.16m

📊 Epoch 154 - Evaluation Completed.


🚀 Epoch 155 - Training Started...

Epoch 155, Batch 100, Loss: 0.2504, Accuracy: 90.97%, Time Passed: 3.72m
Epoch 155, Batch 200, Loss: 0.2597, Accuracy: 90.91%, Time Passed: 7.31m
Epoch 155, Batch 300, Loss: 0.2496, Accuracy: 90.98%, Time Passed: 10.93m
Epoch 155, Batch 400, Loss: 0.2492, Accuracy: 90.81%, Time Passed: 14.66m
Epoch 155, Batch 500, Loss: 0.2464, Accuracy: 90.89%, Time Passed: 18.31m
Epoch 155 Completed - Average Loss: 0.2451, Accuracy: 90.96%, Epoch Time: 21.05m
Training Complete Epoch 155 - Total Time: 21.05m

✅ Epoch 155 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4636, Accuracy: 86.47%, Time Passed: 4.09m
Evaluation Complete - Loss: 0.4438, Accuracy: 88.00%, Total Time: 7.36m

📊 Epoch 155 - Evaluation Completed.


🚀 Epoch 156 - Training Started...

Epoch 156, Batch 100, Loss: 0.2114, Accuracy: 91.81%, Time Passed: 3.70m
Epoch 156, Batch 200, Loss: 0.2240, Accuracy: 91.69%, Time Passed: 7.45m
Epoch 156, Batch 300, Loss: 0.2493, Accuracy: 91.16%, Time Passed: 11.13m
Epoch 156, Batch 400, Loss: 0.2551, Accuracy: 91.12%, Time Passed: 14.86m
Epoch 156, Batch 500, Loss: 0.2563, Accuracy: 91.06%, Time Passed: 18.66m
Epoch 156 Completed - Average Loss: 0.2547, Accuracy: 91.20%, Epoch Time: 21.57m
Training Complete Epoch 156 - Total Time: 21.57m

✅ Epoch 156 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4507, Accuracy: 86.03%, Time Passed: 4.16m
Evaluation Complete - Loss: 0.4307, Accuracy: 87.67%, Total Time: 7.44m

📊 Epoch 156 - Evaluation Completed.


🚀 Epoch 157 - Training Started...

Epoch 157, Batch 100, Loss: 0.2367, Accuracy: 90.97%, Time Passed: 3.68m
Epoch 157, Batch 200, Loss: 0.2300, Accuracy: 91.16%, Time Passed: 7.55m
Epoch 157, Batch 300, Loss: 0.2419, Accuracy: 91.05%, Time Passed: 11.45m
Epoch 157, Batch 400, Loss: 0.2410, Accuracy: 91.08%, Time Passed: 15.30m
Epoch 157, Batch 500, Loss: 0.2418, Accuracy: 90.95%, Time Passed: 19.08m
Epoch 157 Completed - Average Loss: 0.2385, Accuracy: 91.01%, Epoch Time: 21.90m
Training Complete Epoch 157 - Total Time: 21.90m

✅ Epoch 157 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4740, Accuracy: 85.69%, Time Passed: 4.16m
Evaluation Complete - Loss: 0.4481, Accuracy: 87.30%, Total Time: 7.48m

📊 Epoch 157 - Evaluation Completed.


🚀 Epoch 158 - Training Started...

Epoch 158, Batch 100, Loss: 0.2422, Accuracy: 91.25%, Time Passed: 3.79m
Epoch 158, Batch 200, Loss: 0.2326, Accuracy: 91.31%, Time Passed: 7.59m
Epoch 158, Batch 300, Loss: 0.2402, Accuracy: 91.22%, Time Passed: 11.14m
Epoch 158, Batch 400, Loss: 0.2395, Accuracy: 91.19%, Time Passed: 14.74m
Epoch 158, Batch 500, Loss: 0.2377, Accuracy: 91.28%, Time Passed: 18.38m
Epoch 158 Completed - Average Loss: 0.2392, Accuracy: 91.23%, Epoch Time: 21.07m
Training Complete Epoch 158 - Total Time: 21.07m

✅ Epoch 158 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4944, Accuracy: 84.72%, Time Passed: 3.98m
Evaluation Complete - Loss: 0.4620, Accuracy: 86.92%, Total Time: 7.10m

📊 Epoch 158 - Evaluation Completed.


🚀 Epoch 159 - Training Started...

Epoch 159, Batch 100, Loss: 0.2194, Accuracy: 92.00%, Time Passed: 3.63m
Epoch 159, Batch 200, Loss: 0.2232, Accuracy: 91.55%, Time Passed: 7.32m
Epoch 159, Batch 300, Loss: 0.2330, Accuracy: 91.14%, Time Passed: 11.35m
Epoch 159, Batch 400, Loss: 0.2298, Accuracy: 91.02%, Time Passed: 15.08m
Epoch 159, Batch 500, Loss: 0.2327, Accuracy: 91.19%, Time Passed: 18.86m
Epoch 159 Completed - Average Loss: 0.2336, Accuracy: 91.18%, Epoch Time: 21.65m
Training Complete Epoch 159 - Total Time: 21.65m

✅ Epoch 159 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4811, Accuracy: 86.19%, Time Passed: 3.95m
Evaluation Complete - Loss: 0.4597, Accuracy: 87.57%, Total Time: 7.13m

📊 Epoch 159 - Evaluation Completed.


🚀 Epoch 160 - Training Started...

Epoch 160, Batch 100, Loss: 0.2308, Accuracy: 91.50%, Time Passed: 3.60m
Epoch 160, Batch 200, Loss: 0.2368, Accuracy: 91.39%, Time Passed: 7.18m
Epoch 160, Batch 300, Loss: 0.2282, Accuracy: 91.45%, Time Passed: 10.80m
Epoch 160, Batch 400, Loss: 0.2276, Accuracy: 91.53%, Time Passed: 14.48m
Epoch 160, Batch 500, Loss: 0.2269, Accuracy: 91.54%, Time Passed: 18.15m
Epoch 160 Completed - Average Loss: 0.2263, Accuracy: 91.59%, Epoch Time: 21.10m
Training Complete Epoch 160 - Total Time: 21.10m

✅ Epoch 160 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4579, Accuracy: 86.91%, Time Passed: 4.06m
Evaluation Complete - Loss: 0.4527, Accuracy: 87.83%, Total Time: 7.33m

📊 Epoch 160 - Evaluation Completed.

In [62]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_lowest_30_{start_epoch}_{end_epoch}.pkl')

In [63]:
del training_states

### Continue training

In [57]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[0])

✅ Random seed set to 42 (MPS available: True)

In [58]:
training_states = joblib.load("Training outputs/training_states_lowest_30_151_160.pkl")
mobilenetv2_stageF_lowest_30 = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes)) 
device = torch.device("mps") 
mobilenetv2_stageF_lowest_30.to(device)
mobilenetv2_stageF_lowest_30.load_state_dict(training_states[160]["model_state_dict"])
del training_states

In [59]:
norm_sqrt_inv_weights_train = compute_class_weights(train_dataset, method="sqrt_inverse", normalize=True)
norm_sqrt_inv_weights_train_lowest_30 = compute_class_weights(web_lowest_30_dataset, method="sqrt_inverse", normalize=True)   
norm_sqrt_inv_weights_train_lowest_30[-1] = 0 # handel other class
norm_sqrt_inv_weights = (norm_sqrt_inv_weights_train + (2*norm_sqrt_inv_weights_train_lowest_30))/2


lowest_30_val_results151_160 = pd.read_csv("Training outputs/mobilenetv2_stageF_lowest_30_val_results151_160.csv")

# Step 1: get the subset dataframe
df = lowest_30_val_results151_160[
    (lowest_30_val_results151_160['Species'] != "Average Performance (Macro)") &
    (lowest_30_val_results151_160['Epoch'] == 160)
].copy()

# Step 2: build a mapping from species to recall multiplier
def get_multiplier(recall):
    if recall < 0.6:
        return 10
    elif recall < 0.7:
        return 8
    elif recall < 0.8:
        return 6
    elif recall < 0.9:
        return 4
    elif recall < 1:
        return 2
    else:
        return 1

df['Multiplier'] = df['Recall'].apply(get_multiplier)

# Step 3: make sure class order matches your dataset order
species_to_multiplier = dict(zip(df['Species'], df['Multiplier']))

# Step 4: apply the multipliers to your weight vector
adjusted_weights = norm_sqrt_inv_weights.clone() if hasattr(norm_sqrt_inv_weights, 'clone') else np.copy(norm_sqrt_inv_weights)

for idx, class_name in enumerate(train_dataset.classes):
    if class_name in species_to_multiplier:
        adjusted_weights[idx] *= species_to_multiplier[class_name]

In [60]:
df

,Species,Precision,Recall,F1-score,Epoch,Multiplier
306,Anabasis articulata (Forssk.) Moq.,0.930769,0.975806,0.952756,160,2
307,Anabasis setifera Moq.,0.857923,0.792929,0.824147,160,6
308,Atriplex halimus L.,0.752294,0.875445,0.809211,160,4
309,Calotropis procera,0.962025,0.938272,0.950000,160,2
310,Capparis spinosa L.,0.958333,0.809859,0.877863,160,4
311,Cebatha pendula (J.R.Forst. & G.Forst.) Kuntze,0.856000,0.891667,0.873469,160,4
312,Cenchrus divisus,1.000000,0.977011,0.988372,160,2
313,Deverra tortuosa (Desf.) DC.,0.909091,1.000000,0.952381,160,1
314,Deverra triradiata Hochst. ex Boiss.,0.980392,1.000000,0.990099,160,1
315,Diplotaxis harra (Forssk.) Boiss.,0.846154,0.889706,0.867384,160,4
316,Echinops glaberrimus DC.,0.877828,0.950980,0.912941,160,2
317,Ephedra alata Decne.,0.922280,0.872549,0.896725,160,4
318,Farsetia aegyptia Turra,0.913043,0.681081,0.780186,160,8
319,Gymnocarpos decander Forssk.,0.874074,0.914729,0.893939,160,2
320,Haloxylon salicornicum (Moq.) Bunge ex Boiss.,0.782178,0.929412,0.849462,160,2
321,Heliotropium arbainense Fresen.,0.954545,0.917476,0.935644,160,2
322,Iphiona mucronata (Forssk.) Asch. & Schweinf.,0.909091,1.000000,0.952381,160,1
323,Limonium pruinosum (L.) Chaz.,0.951613,0.662921,0.781457,160,8
324,Lycium shawii Roem. & Schult.,0.784672,0.767857,0.776173,160,6
325,Nitraria retusa (Forssk.) Asch.,0.806061,0.847134,0.826087,160,4
326,Ochradenus baccatus Delile,0.919694,0.965863,0.942214,160,2
327,Peganum harmala L.,0.956522,1.000000,0.977778,160,1
328,Rumex vesicarius L.,0.988372,1.000000,0.994152,160,1
329,Salsola imbricata Forssk.,0.954128,0.990476,0.971963,160,2
330,Stachys aegyptiaca Pers.,0.855263,0.984848,0.915493,160,2
331,Suaeda aegyptiaca (Hasselq.) Zohary,0.881944,0.954887,0.916968,160,2
332,Tamarix nilotica (Ehrenb.) Bunge,0.939655,0.681250,0.789855,160,8
333,Trichodesma africanum (L.) Sm.,0.830508,0.586826,0.687719,160,10
334,Zilla spinosa (L.) Prantl,0.871212,1.000000,0.931174,160,1
335,Zygophyllum arabicum (L.) Christenh. & Byng,0.908127,0.984674,0.944853,160,2
336,Zygophyllum coccineum,0.771552,0.922680,0.840376,160,2
337,Zygophyllum molle (Delile) Christenh. & Byng,0.966102,1.000000,0.982759,160,1
338,others,0.952941,0.810000,0.875676,160,4

In [61]:
adjusted_weights, norm_sqrt_inv_weights

(tensor([ 2.1927,  6.8528,  6.0324,  2.4340,  4.6086,  5.1000,  3.1388,  1.9039,
          2.3485,  4.2096,  3.3128,  8.3636,  8.4884,  1.9881,  2.0413,  2.8982,
          2.7100, 12.5182,  6.7435,  3.7124,  1.9145,  1.5909,  1.1301,  1.6951,
          2.5624,  2.1405, 11.5773, 11.0477,  0.8819,  2.4888,  3.3469,  2.6062,
          1.9130], device='mps:0'),
 tensor([1.0964, 1.1421, 1.5081, 1.2170, 1.1522, 1.2750, 1.5694, 1.9039, 2.3485,
         1.0524, 1.6564, 2.0909, 1.0611, 0.9941, 1.0207, 1.4491, 2.7100, 1.5648,
         1.1239, 0.9281, 0.9572, 1.5909, 1.1301, 0.8475, 1.2812, 1.0702, 1.4472,
         1.1048, 0.8819, 1.2444, 1.6734, 2.6062, 0.4783], device='mps:0'))

In [62]:
norm_sqrt_inv_criterion = nn.CrossEntropyLoss(weight=adjusted_weights)
stageF_optimizer = torch.optim.AdamW(mobilenetv2_stageF_lowest_30.parameters(), lr=1e-5,
                            weight_decay=1e-4, betas=(0.9, 0.999))

In [63]:
start_epoch = 161
end_epoch = 180
start_epoch, end_epoch

(161, 180)

In [64]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_lowest_30, full_web_lowest_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_lowest_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 161 - Training Started...

Epoch 161, Batch 100, Loss: 0.1907, Accuracy: 92.84%, Time Passed: 3.59m
Epoch 161, Batch 200, Loss: 0.2004, Accuracy: 92.45%, Time Passed: 7.22m
Epoch 161, Batch 300, Loss: 0.1940, Accuracy: 92.33%, Time Passed: 10.97m
Epoch 161, Batch 400, Loss: 0.1966, Accuracy: 92.35%, Time Passed: 14.62m
Epoch 161, Batch 500, Loss: 0.1955, Accuracy: 92.38%, Time Passed: 18.40m
Epoch 161 Completed - Average Loss: 0.1972, Accuracy: 92.21%, Epoch Time: 21.24m
Training Complete Epoch 161 - Total Time: 21.24m

✅ Epoch 161 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4929, Accuracy: 86.25%, Time Passed: 4.10m
Evaluation Complete - Loss: 0.4661, Accuracy: 87.52%, Total Time: 7.37m

📊 Epoch 161 - Evaluation Completed.


🚀 Epoch 162 - Training Started...

Epoch 162, Batch 100, Loss: 0.1557, Accuracy: 93.38%, Time Passed: 3.73m
Epoch 162, Batch 200, Loss: 0.1660, Accuracy: 92.88%, Time Passed: 7.70m
Epoch 162, Batch 300, Loss: 0.1764, Accuracy: 92.80%, Time Passed: 11.91m
Epoch 162, Batch 400, Loss: 0.1870, Accuracy: 92.41%, Time Passed: 15.96m
Epoch 162, Batch 500, Loss: 0.1893, Accuracy: 92.43%, Time Passed: 20.02m
Epoch 162 Completed - Average Loss: 0.1914, Accuracy: 92.44%, Epoch Time: 22.86m
Training Complete Epoch 162 - Total Time: 22.86m

✅ Epoch 162 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4760, Accuracy: 85.97%, Time Passed: 4.06m
Evaluation Complete - Loss: 0.4484, Accuracy: 87.59%, Total Time: 7.52m

📊 Epoch 162 - Evaluation Completed.


🚀 Epoch 163 - Training Started...

Epoch 163, Batch 100, Loss: 0.1874, Accuracy: 92.88%, Time Passed: 3.79m
Epoch 163, Batch 200, Loss: 0.1878, Accuracy: 92.72%, Time Passed: 7.62m
Epoch 163, Batch 300, Loss: 0.1894, Accuracy: 92.51%, Time Passed: 11.39m
Epoch 163, Batch 400, Loss: 0.1819, Accuracy: 92.77%, Time Passed: 15.18m
Epoch 163, Batch 500, Loss: 0.1853, Accuracy: 92.76%, Time Passed: 19.16m
Epoch 163 Completed - Average Loss: 0.1892, Accuracy: 92.62%, Epoch Time: 21.97m
Training Complete Epoch 163 - Total Time: 21.97m

✅ Epoch 163 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4732, Accuracy: 86.00%, Time Passed: 4.18m
Evaluation Complete - Loss: 0.4524, Accuracy: 87.69%, Total Time: 7.49m

📊 Epoch 163 - Evaluation Completed.


🚀 Epoch 164 - Training Started...

Epoch 164, Batch 100, Loss: 0.1780, Accuracy: 92.66%, Time Passed: 3.84m
Epoch 164, Batch 200, Loss: 0.1909, Accuracy: 92.23%, Time Passed: 7.53m
Epoch 164, Batch 300, Loss: 0.1905, Accuracy: 92.30%, Time Passed: 11.17m
Epoch 164, Batch 400, Loss: 0.1840, Accuracy: 92.55%, Time Passed: 14.94m
Epoch 164, Batch 500, Loss: 0.1852, Accuracy: 92.46%, Time Passed: 18.65m
Epoch 164 Completed - Average Loss: 0.1867, Accuracy: 92.39%, Epoch Time: 21.39m
Training Complete Epoch 164 - Total Time: 21.39m

✅ Epoch 164 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4974, Accuracy: 85.72%, Time Passed: 4.13m
Evaluation Complete - Loss: 0.4681, Accuracy: 87.41%, Total Time: 7.38m

📊 Epoch 164 - Evaluation Completed.


🚀 Epoch 165 - Training Started...

Epoch 165, Batch 100, Loss: 0.1825, Accuracy: 92.75%, Time Passed: 3.75m
Epoch 165, Batch 200, Loss: 0.1937, Accuracy: 92.50%, Time Passed: 7.35m
Epoch 165, Batch 300, Loss: 0.1856, Accuracy: 92.74%, Time Passed: 11.13m
Epoch 165, Batch 400, Loss: 0.1847, Accuracy: 92.70%, Time Passed: 14.87m
Epoch 165, Batch 500, Loss: 0.1825, Accuracy: 92.70%, Time Passed: 18.62m
Epoch 165 Completed - Average Loss: 0.1819, Accuracy: 92.68%, Epoch Time: 21.37m
Training Complete Epoch 165 - Total Time: 21.37m

✅ Epoch 165 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4862, Accuracy: 86.38%, Time Passed: 4.10m
Evaluation Complete - Loss: 0.4561, Accuracy: 87.87%, Total Time: 7.27m

📊 Epoch 165 - Evaluation Completed.


🚀 Epoch 166 - Training Started...

Epoch 166, Batch 100, Loss: 0.1661, Accuracy: 93.31%, Time Passed: 3.69m
Epoch 166, Batch 200, Loss: 0.1675, Accuracy: 93.33%, Time Passed: 7.48m
Epoch 166, Batch 300, Loss: 0.1863, Accuracy: 92.66%, Time Passed: 11.15m
Epoch 166, Batch 400, Loss: 0.1907, Accuracy: 92.58%, Time Passed: 14.91m
Epoch 166, Batch 500, Loss: 0.1911, Accuracy: 92.59%, Time Passed: 18.76m
Epoch 166 Completed - Average Loss: 0.1891, Accuracy: 92.70%, Epoch Time: 21.62m
Training Complete Epoch 166 - Total Time: 21.62m

✅ Epoch 166 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4824, Accuracy: 85.56%, Time Passed: 4.07m
Evaluation Complete - Loss: 0.4517, Accuracy: 87.44%, Total Time: 7.29m

📊 Epoch 166 - Evaluation Completed.


🚀 Epoch 167 - Training Started...

Epoch 167, Batch 100, Loss: 0.1837, Accuracy: 92.19%, Time Passed: 3.58m
Epoch 167, Batch 200, Loss: 0.1775, Accuracy: 92.53%, Time Passed: 7.29m
Epoch 167, Batch 300, Loss: 0.1836, Accuracy: 92.39%, Time Passed: 11.01m
Epoch 167, Batch 400, Loss: 0.1833, Accuracy: 92.50%, Time Passed: 14.76m
Epoch 167, Batch 500, Loss: 0.1832, Accuracy: 92.48%, Time Passed: 18.40m
Epoch 167 Completed - Average Loss: 0.1803, Accuracy: 92.59%, Epoch Time: 21.18m
Training Complete Epoch 167 - Total Time: 21.18m

✅ Epoch 167 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4891, Accuracy: 85.97%, Time Passed: 4.08m
Evaluation Complete - Loss: 0.4569, Accuracy: 87.57%, Total Time: 7.40m

📊 Epoch 167 - Evaluation Completed.


🚀 Epoch 168 - Training Started...

Epoch 168, Batch 100, Loss: 0.1785, Accuracy: 93.09%, Time Passed: 3.67m
Epoch 168, Batch 200, Loss: 0.1719, Accuracy: 92.80%, Time Passed: 7.33m
Epoch 168, Batch 300, Loss: 0.1759, Accuracy: 92.72%, Time Passed: 11.00m
Epoch 168, Batch 400, Loss: 0.1809, Accuracy: 92.58%, Time Passed: 14.74m
Epoch 168, Batch 500, Loss: 0.1808, Accuracy: 92.56%, Time Passed: 18.48m
Epoch 168 Completed - Average Loss: 0.1811, Accuracy: 92.61%, Epoch Time: 21.32m
Training Complete Epoch 168 - Total Time: 21.32m

✅ Epoch 168 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5090, Accuracy: 84.97%, Time Passed: 4.07m
Evaluation Complete - Loss: 0.4711, Accuracy: 86.90%, Total Time: 7.34m

📊 Epoch 168 - Evaluation Completed.


🚀 Epoch 169 - Training Started...

Epoch 169, Batch 100, Loss: 0.1622, Accuracy: 93.34%, Time Passed: 3.72m
Epoch 169, Batch 200, Loss: 0.1651, Accuracy: 93.05%, Time Passed: 7.33m
Epoch 169, Batch 300, Loss: 0.1703, Accuracy: 92.83%, Time Passed: 11.12m
Epoch 169, Batch 400, Loss: 0.1694, Accuracy: 92.90%, Time Passed: 14.88m
Epoch 169, Batch 500, Loss: 0.1701, Accuracy: 93.04%, Time Passed: 18.69m
Epoch 169 Completed - Average Loss: 0.1712, Accuracy: 93.00%, Epoch Time: 21.44m
Training Complete Epoch 169 - Total Time: 21.44m

✅ Epoch 169 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5119, Accuracy: 85.88%, Time Passed: 4.08m
Evaluation Complete - Loss: 0.4796, Accuracy: 87.46%, Total Time: 7.29m

📊 Epoch 169 - Evaluation Completed.


🚀 Epoch 170 - Training Started...

Epoch 170, Batch 100, Loss: 0.1694, Accuracy: 93.09%, Time Passed: 3.74m
Epoch 170, Batch 200, Loss: 0.1719, Accuracy: 93.14%, Time Passed: 7.39m
Epoch 170, Batch 300, Loss: 0.1666, Accuracy: 93.09%, Time Passed: 11.09m
Epoch 170, Batch 400, Loss: 0.1656, Accuracy: 93.21%, Time Passed: 14.80m
Epoch 170, Batch 500, Loss: 0.1646, Accuracy: 93.26%, Time Passed: 18.42m
Epoch 170 Completed - Average Loss: 0.1666, Accuracy: 93.26%, Epoch Time: 21.20m
Training Complete Epoch 170 - Total Time: 21.20m

✅ Epoch 170 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4897, Accuracy: 86.31%, Time Passed: 4.07m
Evaluation Complete - Loss: 0.4757, Accuracy: 87.35%, Total Time: 7.27m

📊 Epoch 170 - Evaluation Completed.


🚀 Epoch 171 - Training Started...

Epoch 171, Batch 100, Loss: 0.1895, Accuracy: 93.47%, Time Passed: 4.17m
Epoch 171, Batch 200, Loss: 0.1961, Accuracy: 92.77%, Time Passed: 8.30m
Epoch 171, Batch 300, Loss: 0.1935, Accuracy: 92.71%, Time Passed: 12.59m
Epoch 171, Batch 400, Loss: 0.1967, Accuracy: 92.62%, Time Passed: 16.79m
Epoch 171, Batch 500, Loss: 0.1965, Accuracy: 92.45%, Time Passed: 21.02m
Epoch 171 Completed - Average Loss: 0.2006, Accuracy: 92.31%, Epoch Time: 24.10m
Training Complete Epoch 171 - Total Time: 24.10m

✅ Epoch 171 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5206, Accuracy: 85.44%, Time Passed: 4.09m
Evaluation Complete - Loss: 0.4776, Accuracy: 87.02%, Total Time: 7.24m

📊 Epoch 171 - Evaluation Completed.


🚀 Epoch 172 - Training Started...

Epoch 172, Batch 100, Loss: 0.2244, Accuracy: 91.72%, Time Passed: 4.09m
Epoch 172, Batch 200, Loss: 0.2058, Accuracy: 91.94%, Time Passed: 8.44m
Epoch 172, Batch 300, Loss: 0.2021, Accuracy: 92.15%, Time Passed: 12.78m
Epoch 172, Batch 400, Loss: 0.1994, Accuracy: 92.18%, Time Passed: 17.11m
Epoch 172, Batch 500, Loss: 0.1997, Accuracy: 92.11%, Time Passed: 21.26m
Epoch 172 Completed - Average Loss: 0.2037, Accuracy: 91.87%, Epoch Time: 24.48m
Training Complete Epoch 172 - Total Time: 24.48m

✅ Epoch 172 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5020, Accuracy: 85.78%, Time Passed: 4.04m
Evaluation Complete - Loss: 0.4735, Accuracy: 87.37%, Total Time: 7.33m

📊 Epoch 172 - Evaluation Completed.


🚀 Epoch 173 - Training Started...

Epoch 173, Batch 100, Loss: 0.1952, Accuracy: 92.38%, Time Passed: 4.32m
Epoch 173, Batch 200, Loss: 0.2066, Accuracy: 92.27%, Time Passed: 8.54m
Epoch 173, Batch 300, Loss: 0.2064, Accuracy: 92.08%, Time Passed: 12.76m
Epoch 173, Batch 400, Loss: 0.2074, Accuracy: 92.02%, Time Passed: 16.87m
Epoch 173, Batch 500, Loss: 0.2001, Accuracy: 92.18%, Time Passed: 21.10m
Epoch 173 Completed - Average Loss: 0.1989, Accuracy: 92.26%, Epoch Time: 24.23m
Training Complete Epoch 173 - Total Time: 24.23m

✅ Epoch 173 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5027, Accuracy: 85.75%, Time Passed: 4.03m
Evaluation Complete - Loss: 0.4828, Accuracy: 87.17%, Total Time: 7.24m

📊 Epoch 173 - Evaluation Completed.


🚀 Epoch 174 - Training Started...

Epoch 174, Batch 100, Loss: 0.2022, Accuracy: 91.88%, Time Passed: 4.28m
Epoch 174, Batch 200, Loss: 0.1988, Accuracy: 91.97%, Time Passed: 8.43m
Epoch 174, Batch 300, Loss: 0.1963, Accuracy: 92.14%, Time Passed: 12.69m
Epoch 174, Batch 400, Loss: 0.1936, Accuracy: 92.14%, Time Passed: 16.95m
Epoch 174, Batch 500, Loss: 0.1903, Accuracy: 92.29%, Time Passed: 21.17m
Epoch 174 Completed - Average Loss: 0.1915, Accuracy: 92.26%, Epoch Time: 24.47m
Training Complete Epoch 174 - Total Time: 24.47m

✅ Epoch 174 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4698, Accuracy: 86.66%, Time Passed: 4.07m
Evaluation Complete - Loss: 0.4429, Accuracy: 88.00%, Total Time: 7.25m

📊 Epoch 174 - Evaluation Completed.


🚀 Epoch 175 - Training Started...

Epoch 175, Batch 100, Loss: 0.1716, Accuracy: 93.16%, Time Passed: 4.57m
Epoch 175, Batch 200, Loss: 0.1777, Accuracy: 92.95%, Time Passed: 9.08m
Epoch 175, Batch 300, Loss: 0.1774, Accuracy: 92.95%, Time Passed: 13.39m
Epoch 175, Batch 400, Loss: 0.1791, Accuracy: 92.98%, Time Passed: 17.81m
Epoch 175, Batch 500, Loss: 0.1849, Accuracy: 92.79%, Time Passed: 22.41m
Epoch 175 Completed - Average Loss: 0.1832, Accuracy: 92.70%, Epoch Time: 25.65m
Training Complete Epoch 175 - Total Time: 25.65m

✅ Epoch 175 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5000, Accuracy: 85.78%, Time Passed: 4.38m
Evaluation Complete - Loss: 0.4759, Accuracy: 87.03%, Total Time: 7.97m

📊 Epoch 175 - Evaluation Completed.


🚀 Epoch 176 - Training Started...

Epoch 176, Batch 100, Loss: 0.1984, Accuracy: 92.06%, Time Passed: 4.47m
Epoch 176, Batch 200, Loss: 0.1978, Accuracy: 92.33%, Time Passed: 9.17m
Epoch 176, Batch 300, Loss: 0.2010, Accuracy: 92.09%, Time Passed: 13.64m
Epoch 176, Batch 400, Loss: 0.1993, Accuracy: 91.99%, Time Passed: 17.98m
Epoch 176, Batch 500, Loss: 0.1983, Accuracy: 92.14%, Time Passed: 22.27m
Epoch 176 Completed - Average Loss: 0.1948, Accuracy: 92.26%, Epoch Time: 25.43m
Training Complete Epoch 176 - Total Time: 25.43m

✅ Epoch 176 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4875, Accuracy: 85.88%, Time Passed: 4.40m
Evaluation Complete - Loss: 0.4688, Accuracy: 87.41%, Total Time: 7.98m

📊 Epoch 176 - Evaluation Completed.


🚀 Epoch 177 - Training Started...

Epoch 177, Batch 100, Loss: 0.1864, Accuracy: 92.22%, Time Passed: 4.42m
Epoch 177, Batch 200, Loss: 0.1949, Accuracy: 92.05%, Time Passed: 8.70m
Epoch 177, Batch 300, Loss: 0.1895, Accuracy: 92.49%, Time Passed: 13.55m
Epoch 177, Batch 400, Loss: 0.1873, Accuracy: 92.48%, Time Passed: 18.01m
Epoch 177, Batch 500, Loss: 0.1867, Accuracy: 92.41%, Time Passed: 22.31m
Epoch 177 Completed - Average Loss: 0.1870, Accuracy: 92.42%, Epoch Time: 25.55m
Training Complete Epoch 177 - Total Time: 25.55m

✅ Epoch 177 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5021, Accuracy: 85.56%, Time Passed: 4.37m
Evaluation Complete - Loss: 0.4522, Accuracy: 87.50%, Total Time: 7.96m

📊 Epoch 177 - Evaluation Completed.


🚀 Epoch 178 - Training Started...

Epoch 178, Batch 100, Loss: 0.1918, Accuracy: 92.78%, Time Passed: 4.25m
Epoch 178, Batch 200, Loss: 0.1983, Accuracy: 92.72%, Time Passed: 8.64m
Epoch 178, Batch 300, Loss: 0.1885, Accuracy: 92.75%, Time Passed: 13.13m
Epoch 178, Batch 400, Loss: 0.1911, Accuracy: 92.57%, Time Passed: 17.56m
Epoch 178, Batch 500, Loss: 0.1921, Accuracy: 92.53%, Time Passed: 21.95m
Epoch 178 Completed - Average Loss: 0.1923, Accuracy: 92.51%, Epoch Time: 25.34m
Training Complete Epoch 178 - Total Time: 25.34m

✅ Epoch 178 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5193, Accuracy: 85.56%, Time Passed: 4.50m
Evaluation Complete - Loss: 0.4886, Accuracy: 87.43%, Total Time: 7.94m

📊 Epoch 178 - Evaluation Completed.


🚀 Epoch 179 - Training Started...

Epoch 179, Batch 100, Loss: 0.1768, Accuracy: 92.06%, Time Passed: 4.47m
Epoch 179, Batch 200, Loss: 0.1872, Accuracy: 92.28%, Time Passed: 8.83m
Epoch 179, Batch 300, Loss: 0.1825, Accuracy: 92.32%, Time Passed: 13.19m
Epoch 179, Batch 400, Loss: 0.1823, Accuracy: 92.53%, Time Passed: 17.77m
Epoch 179, Batch 500, Loss: 0.1836, Accuracy: 92.42%, Time Passed: 22.11m
Epoch 179 Completed - Average Loss: 0.1855, Accuracy: 92.38%, Epoch Time: 25.29m
Training Complete Epoch 179 - Total Time: 25.29m

✅ Epoch 179 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4975, Accuracy: 85.72%, Time Passed: 4.82m
Evaluation Complete - Loss: 0.4591, Accuracy: 87.41%, Total Time: 8.49m

📊 Epoch 179 - Evaluation Completed.


🚀 Epoch 180 - Training Started...

Epoch 180, Batch 100, Loss: 0.1704, Accuracy: 93.47%, Time Passed: 5.58m
Epoch 180, Batch 200, Loss: 0.1770, Accuracy: 92.70%, Time Passed: 9.89m
Epoch 180, Batch 300, Loss: 0.1818, Accuracy: 92.69%, Time Passed: 14.31m
Epoch 180, Batch 400, Loss: 0.1825, Accuracy: 92.51%, Time Passed: 18.61m
Epoch 180, Batch 500, Loss: 0.1819, Accuracy: 92.44%, Time Passed: 22.90m
Epoch 180 Completed - Average Loss: 0.1808, Accuracy: 92.47%, Epoch Time: 26.08m
Training Complete Epoch 180 - Total Time: 26.08m

✅ Epoch 180 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4956, Accuracy: 86.16%, Time Passed: 4.38m
Evaluation Complete - Loss: 0.4640, Accuracy: 87.54%, Total Time: 7.97m

📊 Epoch 180 - Evaluation Completed.

In [66]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_lowest_30_{start_epoch}_{end_epoch}.pkl')

In [67]:
del training_states

### New Method

In [35]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[2])

✅ Random seed set to 2025 (MPS available: True)

In [36]:
training_states = joblib.load("Training outputs/training_states/training_states_lowest_30_161_180.pkl")
mobilenetv2_stageF_lowest_30 = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes)) 
device = torch.device("mps") 
mobilenetv2_stageF_lowest_30.to(device)
mobilenetv2_stageF_lowest_30.load_state_dict(training_states[180]["model_state_dict"])
del training_states

In [53]:
default_train_transform = build_train_transform(crop_type="random", scale=(0.2, 1.0))
train_dataset.transform = default_train_transform  
web_lowest_30_dataset.transform = default_train_transform
val_dataset.transform = val_transform  
full_web_lowest_30_dataset = ConcatDataset([train_dataset, web_lowest_30_dataset])
train_dataset.transform

Compose(
      ToImage()
      RandomResizedCrop(size=(224, 224), scale=(0.2, 1.0), ratio=(0.75, 1.33), interpolation=InterpolationMode.BILINEAR, antialias=True)
      RandomHorizontalFlip(p=0.5)
      RandomVerticalFlip(p=0.2)
      RandomApply(    RandomRotation(degrees=[-90.0, 90.0], interpolation=InterpolationMode.BILINEAR, expand=False, fill=0))
      ToDtype(scale=True)
      RandomApply(    ColorJitter(brightness=(0.7, 1.3), contrast=(0.85, 1.3), saturation=(0.7, 1.3), hue=(-0.0278, 0.0278)))
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], inplace=False)
)

In [54]:
full_web_lowest_30_loader = DataLoader(
    full_web_lowest_30_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,             # shuffle ensures different order each epoch
    num_workers=4,            # safer on macOS, avoids multiprocessing issues
    pin_memory=True,      
    generator=generator       # ensures reproducible shuffling
)

In [55]:
norm_sqrt_inv_weights_train = compute_class_weights(train_dataset, method="sqrt_inverse", normalize=True)
norm_sqrt_inv_weights_train_lowest_30 = compute_class_weights(web_lowest_30_dataset, method="sqrt_inverse", normalize=True)   
norm_sqrt_inv_weights_train_lowest_30[-1] = 0 # handel other class
norm_sqrt_inv_weights = (norm_sqrt_inv_weights_train + (2*norm_sqrt_inv_weights_train_lowest_30))/2


lowest_30_val_results161_180 = pd.read_csv("Training outputs/lowest_val_results/mobilenetv2_stageF_lowest_30_val_results161_180.csv")

# Step 1: get the subset dataframe
df = lowest_30_val_results161_180[
    (lowest_30_val_results161_180['Species'] != "Average Performance (Macro)") &
    (lowest_30_val_results161_180['Epoch'] == 180)
].copy()

# Step 2: build a mapping from species to recall multiplier
def get_multiplier(recall):
    if recall < 0.6:
        return 10
    elif recall < 0.7:
        return 8
    elif recall < 0.8:
        return 6
    elif recall < 0.9:
        return 4
    elif recall < 1:
        return 2
    else:
        return 1

df['Multiplier'] = df['Recall'].apply(get_multiplier)

# Step 3: make sure class order matches your dataset order
species_to_multiplier = dict(zip(df['Species'], df['Multiplier']))

# Step 4: apply the multipliers to your weight vector
adjusted_weights = norm_sqrt_inv_weights.clone() if hasattr(norm_sqrt_inv_weights, 'clone') else np.copy(norm_sqrt_inv_weights)

for idx, class_name in enumerate(train_dataset.classes):
    if class_name in species_to_multiplier:
        adjusted_weights[idx] *= species_to_multiplier[class_name]

In [56]:
df

,Species,Precision,Recall,F1-score,Epoch,Multiplier
646,Anabasis articulata (Forssk.) Moq.,0.897810,0.991935,0.942529,180,2
647,Anabasis setifera Moq.,0.871345,0.752525,0.807588,180,6
648,Atriplex halimus L.,0.688347,0.903915,0.781538,180,2
649,Calotropis procera,0.938272,0.938272,0.938272,180,2
650,Capparis spinosa L.,0.973214,0.767606,0.858268,180,6
651,Cebatha pendula (J.R.Forst. & G.Forst.) Kuntze,0.857143,0.850000,0.853556,180,4
652,Cenchrus divisus,1.000000,0.977011,0.988372,180,2
653,Deverra tortuosa (Desf.) DC.,0.875000,1.000000,0.933333,180,1
654,Deverra triradiata Hochst. ex Boiss.,0.909091,1.000000,0.952381,180,1
655,Diplotaxis harra (Forssk.) Boiss.,0.909091,0.882353,0.895522,180,4
656,Echinops glaberrimus DC.,0.885321,0.946078,0.914692,180,2
657,Ephedra alata Decne.,0.886598,0.843137,0.864322,180,4
658,Farsetia aegyptia Turra,0.865772,0.697297,0.772455,180,8
659,Gymnocarpos decander Forssk.,0.865248,0.945736,0.903704,180,2
660,Haloxylon salicornicum (Moq.) Bunge ex Boiss.,0.821990,0.923529,0.869806,180,2
661,Heliotropium arbainense Fresen.,0.940299,0.917476,0.928747,180,2
662,Iphiona mucronata (Forssk.) Asch. & Schweinf.,0.983333,0.983333,0.983333,180,2
663,Limonium pruinosum (L.) Chaz.,0.851852,0.775281,0.811765,180,6
664,Lycium shawii Roem. & Schult.,0.842912,0.785714,0.813309,180,6
665,Nitraria retusa (Forssk.) Asch.,0.795380,0.767516,0.781199,180,6
666,Ochradenus baccatus Delile,0.920849,0.957831,0.938976,180,2
667,Peganum harmala L.,1.000000,1.000000,1.000000,180,1
668,Rumex vesicarius L.,0.977011,1.000000,0.988372,180,1
669,Salsola imbricata Forssk.,0.963303,1.000000,0.981308,180,1
670,Stachys aegyptiaca Pers.,0.790419,1.000000,0.882943,180,1
671,Suaeda aegyptiaca (Hasselq.) Zohary,0.811688,0.939850,0.871080,180,2
672,Tamarix nilotica (Ehrenb.) Bunge,0.951965,0.681250,0.794171,180,8
673,Trichodesma africanum (L.) Sm.,0.805970,0.646707,0.717608,180,8
674,Zilla spinosa (L.) Prantl,0.877863,1.000000,0.934959,180,1
675,Zygophyllum arabicum (L.) Christenh. & Byng,0.915194,0.992337,0.952206,180,2
676,Zygophyllum coccineum,0.876847,0.917526,0.896725,180,2
677,Zygophyllum molle (Delile) Christenh. & Byng,0.965812,0.991228,0.978355,180,2
678,others,0.975610,0.800000,0.879121,180,4

In [57]:
adjusted_weights, norm_sqrt_inv_weights

(tensor([ 2.1927,  6.8528,  3.0162,  2.4340,  6.9130,  5.1000,  3.1388,  1.9039,
          2.3485,  4.2096,  3.3128,  8.3636,  8.4884,  1.9881,  2.0413,  2.8982,
          5.4200,  9.3887,  6.7435,  5.5686,  1.9145,  1.5909,  1.1301,  0.8475,
          1.2812,  2.1405, 11.5773,  8.8382,  0.8819,  2.4888,  3.3469,  5.2123,
          1.9130], device='mps:0'),
 tensor([1.0964, 1.1421, 1.5081, 1.2170, 1.1522, 1.2750, 1.5694, 1.9039, 2.3485,
         1.0524, 1.6564, 2.0909, 1.0611, 0.9941, 1.0207, 1.4491, 2.7100, 1.5648,
         1.1239, 0.9281, 0.9572, 1.5909, 1.1301, 0.8475, 1.2812, 1.0702, 1.4472,
         1.1048, 0.8819, 1.2444, 1.6734, 2.6062, 0.4783], device='mps:0'))

In [58]:
norm_sqrt_inv_criterion = nn.CrossEntropyLoss(weight=adjusted_weights)
stageF_optimizer = torch.optim.AdamW(mobilenetv2_stageF_lowest_30.parameters(), lr=1e-5,
                            weight_decay=1e-4, betas=(0.9, 0.999))

In [59]:
start_epoch = 181
end_epoch = 182
start_epoch, end_epoch

(181, 182)

In [60]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_lowest_30, full_web_lowest_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_lowest_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 181 - Training Started...

Epoch 181, Batch 100, Loss: 0.1353, Accuracy: 94.44%, Time Passed: 3.75m
Epoch 181, Batch 200, Loss: 0.1371, Accuracy: 94.59%, Time Passed: 7.71m
Epoch 181, Batch 300, Loss: 0.1291, Accuracy: 94.69%, Time Passed: 11.83m
Epoch 181, Batch 400, Loss: 0.1295, Accuracy: 94.79%, Time Passed: 16.54m
Epoch 181, Batch 500, Loss: 0.1271, Accuracy: 94.92%, Time Passed: 21.59m
Epoch 181 Completed - Average Loss: 0.1260, Accuracy: 94.91%, Epoch Time: 25.27m
Training Complete Epoch 181 - Total Time: 25.27m

✅ Epoch 181 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4938, Accuracy: 86.16%, Time Passed: 5.32m
Evaluation Complete - Loss: 0.4556, Accuracy: 87.52%, Total Time: 9.29m

📊 Epoch 181 - Evaluation Completed.


🚀 Epoch 182 - Training Started...

Epoch 182, Batch 100, Loss: 0.1299, Accuracy: 94.69%, Time Passed: 5.18m
Epoch 182, Batch 200, Loss: 0.1129, Accuracy: 95.14%, Time Passed: 10.85m
Epoch 182, Batch 300, Loss: 0.1116, Accuracy: 95.11%, Time Passed: 16.19m
Epoch 182, Batch 400, Loss: 0.1120, Accuracy: 95.29%, Time Passed: 21.69m
Epoch 182, Batch 500, Loss: 0.1104, Accuracy: 95.37%, Time Passed: 27.51m
Epoch 182 Completed - Average Loss: 0.1106, Accuracy: 95.31%, Epoch Time: 31.49m
Training Complete Epoch 182 - Total Time: 31.49m

✅ Epoch 182 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5152, Accuracy: 85.81%, Time Passed: 5.81m
Evaluation Complete - Loss: 0.4685, Accuracy: 87.24%, Total Time: 10.37m

📊 Epoch 182 - Evaluation Completed.

In [61]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_lowest_30_{start_epoch}_{end_epoch}.pkl')

In [62]:
del training_states

In [64]:
start_epoch = 183
end_epoch = 190
start_epoch, end_epoch

(183, 190)

In [65]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_lowest_30, full_web_lowest_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_lowest_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 183 - Training Started...

Epoch 183, Batch 100, Loss: 0.1011, Accuracy: 95.84%, Time Passed: 3.64m
Epoch 183, Batch 200, Loss: 0.1064, Accuracy: 95.48%, Time Passed: 7.59m
Epoch 183, Batch 300, Loss: 0.1080, Accuracy: 95.52%, Time Passed: 11.64m
Epoch 183, Batch 400, Loss: 0.1120, Accuracy: 95.34%, Time Passed: 16.18m
Epoch 183, Batch 500, Loss: 0.1055, Accuracy: 95.58%, Time Passed: 20.68m
Epoch 183 Completed - Average Loss: 0.1032, Accuracy: 95.60%, Epoch Time: 23.67m
Training Complete Epoch 183 - Total Time: 23.67m

✅ Epoch 183 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4816, Accuracy: 86.19%, Time Passed: 4.26m
Evaluation Complete - Loss: 0.4273, Accuracy: 88.02%, Total Time: 7.74m

📊 Epoch 183 - Evaluation Completed.


🚀 Epoch 184 - Training Started...

Epoch 184, Batch 100, Loss: 0.0992, Accuracy: 95.78%, Time Passed: 4.03m
Epoch 184, Batch 200, Loss: 0.1012, Accuracy: 95.39%, Time Passed: 8.30m
Epoch 184, Batch 300, Loss: 0.0988, Accuracy: 95.47%, Time Passed: 12.43m
Epoch 184, Batch 400, Loss: 0.1010, Accuracy: 95.45%, Time Passed: 16.46m
Epoch 184, Batch 500, Loss: 0.0992, Accuracy: 95.53%, Time Passed: 20.48m
Epoch 184 Completed - Average Loss: 0.1009, Accuracy: 95.51%, Epoch Time: 23.53m
Training Complete Epoch 184 - Total Time: 23.53m

✅ Epoch 184 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4609, Accuracy: 86.44%, Time Passed: 4.21m
Evaluation Complete - Loss: 0.4214, Accuracy: 88.23%, Total Time: 7.55m

📊 Epoch 184 - Evaluation Completed.


🚀 Epoch 185 - Training Started...

Epoch 185, Batch 100, Loss: 0.1135, Accuracy: 95.12%, Time Passed: 3.90m
Epoch 185, Batch 200, Loss: 0.1037, Accuracy: 95.53%, Time Passed: 7.89m
Epoch 185, Batch 300, Loss: 0.1008, Accuracy: 95.76%, Time Passed: 11.97m
Epoch 185, Batch 400, Loss: 0.0988, Accuracy: 95.66%, Time Passed: 15.89m
Epoch 185, Batch 500, Loss: 0.0991, Accuracy: 95.63%, Time Passed: 19.80m
Epoch 185 Completed - Average Loss: 0.0985, Accuracy: 95.70%, Epoch Time: 22.72m
Training Complete Epoch 185 - Total Time: 22.72m

✅ Epoch 185 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4667, Accuracy: 86.84%, Time Passed: 4.20m
Evaluation Complete - Loss: 0.4362, Accuracy: 88.11%, Total Time: 7.65m

📊 Epoch 185 - Evaluation Completed.


🚀 Epoch 186 - Training Started...

Epoch 186, Batch 100, Loss: 0.1121, Accuracy: 95.03%, Time Passed: 3.88m
Epoch 186, Batch 200, Loss: 0.1013, Accuracy: 95.56%, Time Passed: 7.79m
Epoch 186, Batch 300, Loss: 0.0996, Accuracy: 95.60%, Time Passed: 11.86m
Epoch 186, Batch 400, Loss: 0.1039, Accuracy: 95.52%, Time Passed: 15.84m
Epoch 186, Batch 500, Loss: 0.1016, Accuracy: 95.58%, Time Passed: 19.95m
Epoch 186 Completed - Average Loss: 0.1018, Accuracy: 95.60%, Epoch Time: 22.99m
Training Complete Epoch 186 - Total Time: 22.99m

✅ Epoch 186 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4882, Accuracy: 86.31%, Time Passed: 4.56m
Evaluation Complete - Loss: 0.4560, Accuracy: 87.50%, Total Time: 7.98m

📊 Epoch 186 - Evaluation Completed.


🚀 Epoch 187 - Training Started...

Epoch 187, Batch 100, Loss: 0.0925, Accuracy: 96.09%, Time Passed: 4.42m
Epoch 187, Batch 200, Loss: 0.0934, Accuracy: 95.98%, Time Passed: 9.06m
Epoch 187, Batch 300, Loss: 0.0907, Accuracy: 96.01%, Time Passed: 13.73m
Epoch 187, Batch 400, Loss: 0.0882, Accuracy: 96.06%, Time Passed: 18.15m
Epoch 187, Batch 500, Loss: 0.0927, Accuracy: 95.86%, Time Passed: 22.71m
Epoch 187 Completed - Average Loss: 0.0942, Accuracy: 95.75%, Epoch Time: 26.34m
Training Complete Epoch 187 - Total Time: 26.34m

✅ Epoch 187 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4771, Accuracy: 86.97%, Time Passed: 5.19m
Evaluation Complete - Loss: 0.4355, Accuracy: 88.17%, Total Time: 9.27m

📊 Epoch 187 - Evaluation Completed.


🚀 Epoch 188 - Training Started...

Epoch 188, Batch 100, Loss: 0.0827, Accuracy: 96.28%, Time Passed: 4.99m
Epoch 188, Batch 200, Loss: 0.0880, Accuracy: 95.97%, Time Passed: 9.82m
Epoch 188, Batch 300, Loss: 0.0923, Accuracy: 95.74%, Time Passed: 14.59m
Epoch 188, Batch 400, Loss: 0.0921, Accuracy: 95.85%, Time Passed: 20.16m
Epoch 188, Batch 500, Loss: 0.0926, Accuracy: 95.79%, Time Passed: 25.64m
Epoch 188 Completed - Average Loss: 0.0946, Accuracy: 95.70%, Epoch Time: 29.03m
Training Complete Epoch 188 - Total Time: 29.03m

✅ Epoch 188 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4727, Accuracy: 86.69%, Time Passed: 4.54m
Evaluation Complete - Loss: 0.4234, Accuracy: 88.23%, Total Time: 8.07m

📊 Epoch 188 - Evaluation Completed.


🚀 Epoch 189 - Training Started...

Epoch 189, Batch 100, Loss: 0.0983, Accuracy: 95.81%, Time Passed: 3.97m
Epoch 189, Batch 200, Loss: 0.0944, Accuracy: 95.97%, Time Passed: 7.99m
Epoch 189, Batch 300, Loss: 0.0917, Accuracy: 95.98%, Time Passed: 11.89m
Epoch 189, Batch 400, Loss: 0.0913, Accuracy: 95.91%, Time Passed: 16.84m
Epoch 189, Batch 500, Loss: 0.0914, Accuracy: 95.79%, Time Passed: 21.33m
Epoch 189 Completed - Average Loss: 0.0908, Accuracy: 95.84%, Epoch Time: 24.65m
Training Complete Epoch 189 - Total Time: 24.65m

✅ Epoch 189 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4955, Accuracy: 86.22%, Time Passed: 4.36m
Evaluation Complete - Loss: 0.4516, Accuracy: 87.78%, Total Time: 7.62m

📊 Epoch 189 - Evaluation Completed.


🚀 Epoch 190 - Training Started...

Epoch 190, Batch 100, Loss: 0.0844, Accuracy: 95.78%, Time Passed: 4.82m
Epoch 190, Batch 200, Loss: 0.0892, Accuracy: 95.91%, Time Passed: 9.05m
Epoch 190, Batch 300, Loss: 0.0890, Accuracy: 95.74%, Time Passed: 13.02m
Epoch 190, Batch 400, Loss: 0.0905, Accuracy: 95.66%, Time Passed: 17.16m
Epoch 190, Batch 500, Loss: 0.0908, Accuracy: 95.68%, Time Passed: 21.22m
Epoch 190 Completed - Average Loss: 0.0900, Accuracy: 95.77%, Epoch Time: 24.24m
Training Complete Epoch 190 - Total Time: 24.24m

✅ Epoch 190 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4690, Accuracy: 86.97%, Time Passed: 4.31m
Evaluation Complete - Loss: 0.4476, Accuracy: 88.10%, Total Time: 7.63m

📊 Epoch 190 - Evaluation Completed.

In [66]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_lowest_30_{start_epoch}_{end_epoch}.pkl')

In [67]:
del training_states

In [69]:
start_epoch = 191
end_epoch = 200
start_epoch, end_epoch

(191, 200)

In [70]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_lowest_30, full_web_lowest_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_lowest_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 191 - Training Started...

Epoch 191, Batch 100, Loss: 0.0930, Accuracy: 95.31%, Time Passed: 3.97m
Epoch 191, Batch 200, Loss: 0.0937, Accuracy: 95.55%, Time Passed: 7.88m
Epoch 191, Batch 300, Loss: 0.0908, Accuracy: 95.76%, Time Passed: 11.80m
Epoch 191, Batch 400, Loss: 0.0921, Accuracy: 95.78%, Time Passed: 15.71m
Epoch 191, Batch 500, Loss: 0.0883, Accuracy: 95.86%, Time Passed: 19.82m
Epoch 191 Completed - Average Loss: 0.0894, Accuracy: 95.82%, Epoch Time: 22.63m
Training Complete Epoch 191 - Total Time: 22.63m

✅ Epoch 191 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4650, Accuracy: 86.78%, Time Passed: 4.14m
Evaluation Complete - Loss: 0.4287, Accuracy: 88.19%, Total Time: 7.61m

📊 Epoch 191 - Evaluation Completed.


🚀 Epoch 192 - Training Started...

Epoch 192, Batch 100, Loss: 0.0824, Accuracy: 95.53%, Time Passed: 4.31m
Epoch 192, Batch 200, Loss: 0.0859, Accuracy: 95.86%, Time Passed: 8.56m
Epoch 192, Batch 300, Loss: 0.0876, Accuracy: 95.91%, Time Passed: 12.75m
Epoch 192, Batch 400, Loss: 0.0888, Accuracy: 95.91%, Time Passed: 17.01m
Epoch 192, Batch 500, Loss: 0.0873, Accuracy: 95.99%, Time Passed: 21.32m
Epoch 192 Completed - Average Loss: 0.0867, Accuracy: 96.01%, Epoch Time: 24.61m
Training Complete Epoch 192 - Total Time: 24.61m

✅ Epoch 192 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4901, Accuracy: 86.34%, Time Passed: 4.44m
Evaluation Complete - Loss: 0.4521, Accuracy: 87.95%, Total Time: 7.99m

📊 Epoch 192 - Evaluation Completed.


🚀 Epoch 193 - Training Started...

Epoch 193, Batch 100, Loss: 0.0690, Accuracy: 96.22%, Time Passed: 4.47m
Epoch 193, Batch 200, Loss: 0.0835, Accuracy: 95.81%, Time Passed: 8.90m
Epoch 193, Batch 300, Loss: 0.0825, Accuracy: 96.05%, Time Passed: 13.90m
Epoch 193, Batch 400, Loss: 0.0858, Accuracy: 96.01%, Time Passed: 17.96m
Epoch 193, Batch 500, Loss: 0.0835, Accuracy: 96.05%, Time Passed: 22.36m
Epoch 193 Completed - Average Loss: 0.0863, Accuracy: 96.01%, Epoch Time: 25.40m
Training Complete Epoch 193 - Total Time: 25.40m

✅ Epoch 193 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4954, Accuracy: 86.62%, Time Passed: 4.23m
Evaluation Complete - Loss: 0.4588, Accuracy: 88.06%, Total Time: 7.65m

📊 Epoch 193 - Evaluation Completed.


🚀 Epoch 194 - Training Started...

Epoch 194, Batch 100, Loss: 0.0878, Accuracy: 96.06%, Time Passed: 4.07m
Epoch 194, Batch 200, Loss: 0.0861, Accuracy: 96.14%, Time Passed: 8.21m
Epoch 194, Batch 300, Loss: 0.0867, Accuracy: 96.18%, Time Passed: 12.32m
Epoch 194, Batch 400, Loss: 0.0848, Accuracy: 96.20%, Time Passed: 16.44m
Epoch 194, Batch 500, Loss: 0.0852, Accuracy: 96.15%, Time Passed: 20.57m
Epoch 194 Completed - Average Loss: 0.0838, Accuracy: 96.16%, Epoch Time: 23.44m
Training Complete Epoch 194 - Total Time: 23.44m

✅ Epoch 194 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4806, Accuracy: 85.72%, Time Passed: 4.20m
Evaluation Complete - Loss: 0.4517, Accuracy: 87.26%, Total Time: 7.65m

📊 Epoch 194 - Evaluation Completed.


🚀 Epoch 195 - Training Started...

Epoch 195, Batch 100, Loss: 0.0713, Accuracy: 96.75%, Time Passed: 3.81m
Epoch 195, Batch 200, Loss: 0.0815, Accuracy: 96.38%, Time Passed: 7.68m
Epoch 195, Batch 300, Loss: 0.0807, Accuracy: 96.42%, Time Passed: 11.72m
Epoch 195, Batch 400, Loss: 0.0843, Accuracy: 96.20%, Time Passed: 15.65m
Epoch 195, Batch 500, Loss: 0.0834, Accuracy: 96.25%, Time Passed: 20.40m
Epoch 195 Completed - Average Loss: 0.0829, Accuracy: 96.27%, Epoch Time: 23.43m
Training Complete Epoch 195 - Total Time: 23.43m

✅ Epoch 195 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4529, Accuracy: 86.97%, Time Passed: 4.22m
Evaluation Complete - Loss: 0.4335, Accuracy: 88.19%, Total Time: 7.65m

📊 Epoch 195 - Evaluation Completed.


🚀 Epoch 196 - Training Started...

Epoch 196, Batch 100, Loss: 0.0800, Accuracy: 96.09%, Time Passed: 4.00m
Epoch 196, Batch 200, Loss: 0.0812, Accuracy: 96.27%, Time Passed: 8.26m
Epoch 196, Batch 300, Loss: 0.0790, Accuracy: 96.36%, Time Passed: 12.55m
Epoch 196, Batch 400, Loss: 0.0786, Accuracy: 96.37%, Time Passed: 16.44m
Epoch 196, Batch 500, Loss: 0.0786, Accuracy: 96.41%, Time Passed: 21.33m
Epoch 196 Completed - Average Loss: 0.0793, Accuracy: 96.40%, Epoch Time: 24.24m
Training Complete Epoch 196 - Total Time: 24.24m

✅ Epoch 196 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4337, Accuracy: 87.31%, Time Passed: 4.48m
Evaluation Complete - Loss: 0.4046, Accuracy: 88.90%, Total Time: 8.35m

📊 Epoch 196 - Evaluation Completed.


🚀 Epoch 197 - Training Started...

Epoch 197, Batch 100, Loss: 0.0820, Accuracy: 96.09%, Time Passed: 5.04m
Epoch 197, Batch 200, Loss: 0.0766, Accuracy: 96.31%, Time Passed: 9.84m
Epoch 197, Batch 300, Loss: 0.0795, Accuracy: 96.15%, Time Passed: 14.12m
Epoch 197, Batch 400, Loss: 0.0805, Accuracy: 96.25%, Time Passed: 18.36m
Epoch 197, Batch 500, Loss: 0.0777, Accuracy: 96.30%, Time Passed: 22.68m
Epoch 197 Completed - Average Loss: 0.0775, Accuracy: 96.29%, Epoch Time: 25.81m
Training Complete Epoch 197 - Total Time: 25.81m

✅ Epoch 197 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4788, Accuracy: 87.06%, Time Passed: 4.08m
Evaluation Complete - Loss: 0.4372, Accuracy: 88.39%, Total Time: 7.48m

📊 Epoch 197 - Evaluation Completed.


🚀 Epoch 198 - Training Started...

Epoch 198, Batch 100, Loss: 0.0632, Accuracy: 97.03%, Time Passed: 4.37m
Epoch 198, Batch 200, Loss: 0.0692, Accuracy: 96.78%, Time Passed: 8.44m
Epoch 198, Batch 300, Loss: 0.0744, Accuracy: 96.56%, Time Passed: 12.11m
Epoch 198, Batch 400, Loss: 0.0779, Accuracy: 96.38%, Time Passed: 15.77m
Epoch 198, Batch 500, Loss: 0.0782, Accuracy: 96.39%, Time Passed: 19.69m
Epoch 198 Completed - Average Loss: 0.0777, Accuracy: 96.48%, Epoch Time: 22.52m
Training Complete Epoch 198 - Total Time: 22.52m

✅ Epoch 198 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4792, Accuracy: 86.12%, Time Passed: 4.00m
Evaluation Complete - Loss: 0.4473, Accuracy: 87.72%, Total Time: 7.25m

📊 Epoch 198 - Evaluation Completed.


🚀 Epoch 199 - Training Started...

Epoch 199, Batch 100, Loss: 0.0747, Accuracy: 96.44%, Time Passed: 3.97m
Epoch 199, Batch 200, Loss: 0.0782, Accuracy: 96.23%, Time Passed: 8.09m
Epoch 199, Batch 300, Loss: 0.0781, Accuracy: 96.31%, Time Passed: 12.30m
Epoch 199, Batch 400, Loss: 0.0763, Accuracy: 96.38%, Time Passed: 16.95m
Epoch 199, Batch 500, Loss: 0.0774, Accuracy: 96.39%, Time Passed: 21.79m
Epoch 199 Completed - Average Loss: 0.0763, Accuracy: 96.43%, Epoch Time: 25.44m
Training Complete Epoch 199 - Total Time: 25.44m

✅ Epoch 199 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4510, Accuracy: 87.16%, Time Passed: 4.70m
Evaluation Complete - Loss: 0.4302, Accuracy: 88.41%, Total Time: 8.39m

📊 Epoch 199 - Evaluation Completed.


🚀 Epoch 200 - Training Started...

Epoch 200, Batch 100, Loss: 0.0800, Accuracy: 96.69%, Time Passed: 4.98m
Epoch 200, Batch 200, Loss: 0.0777, Accuracy: 96.31%, Time Passed: 10.10m
Epoch 200, Batch 300, Loss: 0.0786, Accuracy: 96.47%, Time Passed: 15.20m
Epoch 200, Batch 400, Loss: 0.0772, Accuracy: 96.47%, Time Passed: 20.25m
Epoch 200, Batch 500, Loss: 0.0753, Accuracy: 96.50%, Time Passed: 25.46m
Epoch 200 Completed - Average Loss: 0.0749, Accuracy: 96.56%, Epoch Time: 29.23m
Training Complete Epoch 200 - Total Time: 29.23m

✅ Epoch 200 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4778, Accuracy: 86.97%, Time Passed: 4.90m
Evaluation Complete - Loss: 0.4456, Accuracy: 88.21%, Total Time: 8.66m

📊 Epoch 200 - Evaluation Completed.

In [71]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_lowest_30_{start_epoch}_{end_epoch}.pkl')

In [72]:
del training_states

In [73]:
start_epoch = 201
end_epoch = 220
start_epoch, end_epoch

(201, 220)

In [74]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_lowest_30, full_web_lowest_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_lowest_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 201 - Training Started...

Epoch 201, Batch 100, Loss: 0.0700, Accuracy: 96.53%, Time Passed: 4.02m
Epoch 201, Batch 200, Loss: 0.0704, Accuracy: 96.62%, Time Passed: 7.84m
Epoch 201, Batch 300, Loss: 0.0720, Accuracy: 96.71%, Time Passed: 11.67m
Epoch 201, Batch 400, Loss: 0.0754, Accuracy: 96.47%, Time Passed: 15.63m
Epoch 201, Batch 500, Loss: 0.0740, Accuracy: 96.46%, Time Passed: 19.68m
Epoch 201 Completed - Average Loss: 0.0748, Accuracy: 96.48%, Epoch Time: 22.56m
Training Complete Epoch 201 - Total Time: 22.56m

✅ Epoch 201 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4801, Accuracy: 86.91%, Time Passed: 4.23m
Evaluation Complete - Loss: 0.4437, Accuracy: 88.28%, Total Time: 7.74m

📊 Epoch 201 - Evaluation Completed.


🚀 Epoch 202 - Training Started...

Epoch 202, Batch 100, Loss: 0.0761, Accuracy: 96.16%, Time Passed: 4.39m
Epoch 202, Batch 200, Loss: 0.0711, Accuracy: 96.64%, Time Passed: 9.09m
Epoch 202, Batch 300, Loss: 0.0738, Accuracy: 96.48%, Time Passed: 13.59m
Epoch 202, Batch 400, Loss: 0.0738, Accuracy: 96.52%, Time Passed: 18.02m
Epoch 202, Batch 500, Loss: 0.0711, Accuracy: 96.62%, Time Passed: 22.69m
Epoch 202 Completed - Average Loss: 0.0692, Accuracy: 96.69%, Epoch Time: 26.00m
Training Complete Epoch 202 - Total Time: 26.00m

✅ Epoch 202 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4804, Accuracy: 86.94%, Time Passed: 4.50m
Evaluation Complete - Loss: 0.4495, Accuracy: 88.36%, Total Time: 8.08m

📊 Epoch 202 - Evaluation Completed.


🚀 Epoch 203 - Training Started...

Epoch 203, Batch 100, Loss: 0.0759, Accuracy: 96.19%, Time Passed: 4.58m
Epoch 203, Batch 200, Loss: 0.0719, Accuracy: 96.41%, Time Passed: 9.42m
Epoch 203, Batch 300, Loss: 0.0713, Accuracy: 96.47%, Time Passed: 14.13m
Epoch 203, Batch 400, Loss: 0.0717, Accuracy: 96.52%, Time Passed: 18.96m
Epoch 203, Batch 500, Loss: 0.0731, Accuracy: 96.46%, Time Passed: 23.56m
Epoch 203 Completed - Average Loss: 0.0723, Accuracy: 96.52%, Epoch Time: 27.18m
Training Complete Epoch 203 - Total Time: 27.18m

✅ Epoch 203 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4620, Accuracy: 87.09%, Time Passed: 4.58m
Evaluation Complete - Loss: 0.4264, Accuracy: 88.63%, Total Time: 8.19m

📊 Epoch 203 - Evaluation Completed.


🚀 Epoch 204 - Training Started...

Epoch 204, Batch 100, Loss: 0.0787, Accuracy: 96.25%, Time Passed: 4.42m
Epoch 204, Batch 200, Loss: 0.0757, Accuracy: 96.50%, Time Passed: 8.98m
Epoch 204, Batch 300, Loss: 0.0706, Accuracy: 96.70%, Time Passed: 13.52m
Epoch 204, Batch 400, Loss: 0.0717, Accuracy: 96.66%, Time Passed: 18.00m
Epoch 204, Batch 500, Loss: 0.0708, Accuracy: 96.66%, Time Passed: 22.43m
Epoch 204 Completed - Average Loss: 0.0705, Accuracy: 96.73%, Epoch Time: 25.72m
Training Complete Epoch 204 - Total Time: 25.72m

✅ Epoch 204 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4988, Accuracy: 86.72%, Time Passed: 4.55m
Evaluation Complete - Loss: 0.4560, Accuracy: 88.24%, Total Time: 8.06m

📊 Epoch 204 - Evaluation Completed.


🚀 Epoch 205 - Training Started...

Epoch 205, Batch 100, Loss: 0.0759, Accuracy: 96.84%, Time Passed: 4.31m
Epoch 205, Batch 200, Loss: 0.0743, Accuracy: 96.58%, Time Passed: 8.82m
Epoch 205, Batch 300, Loss: 0.0746, Accuracy: 96.35%, Time Passed: 13.43m
Epoch 205, Batch 400, Loss: 0.0709, Accuracy: 96.55%, Time Passed: 18.05m
Epoch 205, Batch 500, Loss: 0.0687, Accuracy: 96.69%, Time Passed: 22.70m
Epoch 205 Completed - Average Loss: 0.0682, Accuracy: 96.76%, Epoch Time: 26.25m
Training Complete Epoch 205 - Total Time: 26.25m

✅ Epoch 205 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4575, Accuracy: 87.09%, Time Passed: 4.67m
Evaluation Complete - Loss: 0.4433, Accuracy: 88.26%, Total Time: 8.21m

📊 Epoch 205 - Evaluation Completed.


🚀 Epoch 206 - Training Started...

Epoch 206, Batch 100, Loss: 0.0772, Accuracy: 96.69%, Time Passed: 4.67m
Epoch 206, Batch 200, Loss: 0.0769, Accuracy: 96.41%, Time Passed: 9.52m
Epoch 206, Batch 300, Loss: 0.0783, Accuracy: 96.43%, Time Passed: 14.13m
Epoch 206, Batch 400, Loss: 0.0735, Accuracy: 96.56%, Time Passed: 18.79m
Epoch 206, Batch 500, Loss: 0.0704, Accuracy: 96.71%, Time Passed: 23.43m
Epoch 206 Completed - Average Loss: 0.0715, Accuracy: 96.72%, Epoch Time: 26.88m
Training Complete Epoch 206 - Total Time: 26.88m

✅ Epoch 206 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4868, Accuracy: 86.44%, Time Passed: 4.45m
Evaluation Complete - Loss: 0.4422, Accuracy: 88.30%, Total Time: 8.02m

📊 Epoch 206 - Evaluation Completed.


🚀 Epoch 207 - Training Started...

Epoch 207, Batch 100, Loss: 0.0536, Accuracy: 97.34%, Time Passed: 4.38m
Epoch 207, Batch 200, Loss: 0.0628, Accuracy: 96.98%, Time Passed: 8.74m
Epoch 207, Batch 300, Loss: 0.0636, Accuracy: 96.98%, Time Passed: 13.20m
Epoch 207, Batch 400, Loss: 0.0669, Accuracy: 96.87%, Time Passed: 17.72m
Epoch 207, Batch 500, Loss: 0.0651, Accuracy: 96.93%, Time Passed: 22.12m
Epoch 207 Completed - Average Loss: 0.0659, Accuracy: 96.96%, Epoch Time: 25.45m
Training Complete Epoch 207 - Total Time: 25.45m

✅ Epoch 207 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4639, Accuracy: 86.84%, Time Passed: 4.51m
Evaluation Complete - Loss: 0.4284, Accuracy: 88.43%, Total Time: 7.99m

📊 Epoch 207 - Evaluation Completed.


🚀 Epoch 208 - Training Started...

Epoch 208, Batch 100, Loss: 0.0707, Accuracy: 96.50%, Time Passed: 4.30m
Epoch 208, Batch 200, Loss: 0.0706, Accuracy: 96.53%, Time Passed: 8.74m
Epoch 208, Batch 300, Loss: 0.0712, Accuracy: 96.51%, Time Passed: 13.28m
Epoch 208, Batch 400, Loss: 0.0681, Accuracy: 96.62%, Time Passed: 17.83m
Epoch 208, Batch 500, Loss: 0.0683, Accuracy: 96.64%, Time Passed: 22.29m
Epoch 208 Completed - Average Loss: 0.0683, Accuracy: 96.60%, Epoch Time: 25.55m
Training Complete Epoch 208 - Total Time: 25.55m

✅ Epoch 208 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5051, Accuracy: 86.28%, Time Passed: 4.44m
Evaluation Complete - Loss: 0.4539, Accuracy: 88.23%, Total Time: 8.00m

📊 Epoch 208 - Evaluation Completed.


🚀 Epoch 209 - Training Started...

Epoch 209, Batch 100, Loss: 0.0682, Accuracy: 96.53%, Time Passed: 4.38m
Epoch 209, Batch 200, Loss: 0.0660, Accuracy: 96.67%, Time Passed: 8.88m
Epoch 209, Batch 300, Loss: 0.0643, Accuracy: 96.73%, Time Passed: 13.49m
Epoch 209, Batch 400, Loss: 0.0648, Accuracy: 96.81%, Time Passed: 18.05m
Epoch 209, Batch 500, Loss: 0.0654, Accuracy: 96.78%, Time Passed: 22.54m
Epoch 209 Completed - Average Loss: 0.0645, Accuracy: 96.84%, Epoch Time: 25.85m
Training Complete Epoch 209 - Total Time: 25.85m

✅ Epoch 209 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5031, Accuracy: 86.16%, Time Passed: 4.43m
Evaluation Complete - Loss: 0.4471, Accuracy: 88.13%, Total Time: 7.87m

📊 Epoch 209 - Evaluation Completed.


🚀 Epoch 210 - Training Started...

Epoch 210, Batch 100, Loss: 0.0659, Accuracy: 96.50%, Time Passed: 4.45m
Epoch 210, Batch 200, Loss: 0.0620, Accuracy: 96.72%, Time Passed: 8.97m
Epoch 210, Batch 300, Loss: 0.0651, Accuracy: 96.85%, Time Passed: 13.57m
Epoch 210, Batch 400, Loss: 0.0655, Accuracy: 96.93%, Time Passed: 18.13m
Epoch 210, Batch 500, Loss: 0.0650, Accuracy: 96.97%, Time Passed: 22.58m
Epoch 210 Completed - Average Loss: 0.0665, Accuracy: 96.90%, Epoch Time: 26.12m
Training Complete Epoch 210 - Total Time: 26.12m

✅ Epoch 210 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4687, Accuracy: 86.88%, Time Passed: 4.43m
Evaluation Complete - Loss: 0.4597, Accuracy: 88.06%, Total Time: 7.99m

📊 Epoch 210 - Evaluation Completed.


🚀 Epoch 211 - Training Started...

Epoch 211, Batch 100, Loss: 0.0637, Accuracy: 97.22%, Time Passed: 4.49m
Epoch 211, Batch 200, Loss: 0.0675, Accuracy: 96.78%, Time Passed: 9.17m
Epoch 211, Batch 300, Loss: 0.0654, Accuracy: 96.80%, Time Passed: 13.89m
Epoch 211, Batch 400, Loss: 0.0679, Accuracy: 96.69%, Time Passed: 18.60m
Epoch 211, Batch 500, Loss: 0.0656, Accuracy: 96.79%, Time Passed: 23.35m
Epoch 211 Completed - Average Loss: 0.0630, Accuracy: 96.94%, Epoch Time: 26.84m
Training Complete Epoch 211 - Total Time: 26.84m

✅ Epoch 211 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4705, Accuracy: 86.88%, Time Passed: 4.48m
Evaluation Complete - Loss: 0.4397, Accuracy: 88.21%, Total Time: 7.97m

📊 Epoch 211 - Evaluation Completed.


🚀 Epoch 212 - Training Started...

Epoch 212, Batch 100, Loss: 0.0619, Accuracy: 96.75%, Time Passed: 4.56m
Epoch 212, Batch 200, Loss: 0.0603, Accuracy: 97.00%, Time Passed: 9.32m
Epoch 212, Batch 300, Loss: 0.0594, Accuracy: 96.85%, Time Passed: 14.21m
Epoch 212, Batch 400, Loss: 0.0597, Accuracy: 96.92%, Time Passed: 18.93m
Epoch 212, Batch 500, Loss: 0.0583, Accuracy: 97.00%, Time Passed: 23.56m
Epoch 212 Completed - Average Loss: 0.0587, Accuracy: 96.99%, Epoch Time: 26.87m
Training Complete Epoch 212 - Total Time: 26.87m

✅ Epoch 212 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4848, Accuracy: 87.03%, Time Passed: 4.52m
Evaluation Complete - Loss: 0.4570, Accuracy: 88.24%, Total Time: 8.03m

📊 Epoch 212 - Evaluation Completed.


🚀 Epoch 213 - Training Started...

Epoch 213, Batch 100, Loss: 0.0698, Accuracy: 96.94%, Time Passed: 4.42m
Epoch 213, Batch 200, Loss: 0.0644, Accuracy: 96.91%, Time Passed: 8.88m
Epoch 213, Batch 300, Loss: 0.0639, Accuracy: 96.85%, Time Passed: 13.42m
Epoch 213, Batch 400, Loss: 0.0650, Accuracy: 96.79%, Time Passed: 17.88m
Epoch 213, Batch 500, Loss: 0.0612, Accuracy: 97.02%, Time Passed: 22.43m
Epoch 213 Completed - Average Loss: 0.0611, Accuracy: 96.94%, Epoch Time: 25.70m
Training Complete Epoch 213 - Total Time: 25.70m

✅ Epoch 213 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4853, Accuracy: 86.72%, Time Passed: 4.50m
Evaluation Complete - Loss: 0.4422, Accuracy: 88.15%, Total Time: 7.99m

📊 Epoch 213 - Evaluation Completed.


🚀 Epoch 214 - Training Started...

Epoch 214, Batch 100, Loss: 0.0623, Accuracy: 96.59%, Time Passed: 4.42m
Epoch 214, Batch 200, Loss: 0.0615, Accuracy: 96.80%, Time Passed: 8.91m
Epoch 214, Batch 300, Loss: 0.0651, Accuracy: 96.72%, Time Passed: 13.75m
Epoch 214, Batch 400, Loss: 0.0649, Accuracy: 96.70%, Time Passed: 18.41m
Epoch 214, Batch 500, Loss: 0.0646, Accuracy: 96.75%, Time Passed: 22.99m
Epoch 214 Completed - Average Loss: 0.0634, Accuracy: 96.80%, Epoch Time: 26.32m
Training Complete Epoch 214 - Total Time: 26.32m

✅ Epoch 214 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4573, Accuracy: 86.59%, Time Passed: 4.48m
Evaluation Complete - Loss: 0.4396, Accuracy: 88.15%, Total Time: 7.97m

📊 Epoch 214 - Evaluation Completed.


🚀 Epoch 215 - Training Started...

Epoch 215, Batch 100, Loss: 0.0637, Accuracy: 96.69%, Time Passed: 4.52m
Epoch 215, Batch 200, Loss: 0.0612, Accuracy: 96.98%, Time Passed: 9.08m
Epoch 215, Batch 300, Loss: 0.0591, Accuracy: 96.99%, Time Passed: 13.72m
Epoch 215, Batch 400, Loss: 0.0618, Accuracy: 96.98%, Time Passed: 18.75m
Epoch 215, Batch 500, Loss: 0.0618, Accuracy: 96.99%, Time Passed: 23.94m
Epoch 215 Completed - Average Loss: 0.0629, Accuracy: 96.90%, Epoch Time: 27.45m
Training Complete Epoch 215 - Total Time: 27.45m

✅ Epoch 215 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4569, Accuracy: 87.19%, Time Passed: 4.60m
Evaluation Complete - Loss: 0.4245, Accuracy: 88.65%, Total Time: 8.21m

📊 Epoch 215 - Evaluation Completed.


🚀 Epoch 216 - Training Started...

Epoch 216, Batch 100, Loss: 0.0638, Accuracy: 97.22%, Time Passed: 4.36m
Epoch 216, Batch 200, Loss: 0.0615, Accuracy: 97.08%, Time Passed: 9.27m
Epoch 216, Batch 300, Loss: 0.0607, Accuracy: 97.09%, Time Passed: 14.01m
Epoch 216, Batch 400, Loss: 0.0601, Accuracy: 97.02%, Time Passed: 18.76m
Epoch 216, Batch 500, Loss: 0.0602, Accuracy: 96.99%, Time Passed: 23.37m
Epoch 216 Completed - Average Loss: 0.0591, Accuracy: 97.02%, Epoch Time: 27.17m
Training Complete Epoch 216 - Total Time: 27.17m

✅ Epoch 216 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4408, Accuracy: 87.38%, Time Passed: 4.64m
Evaluation Complete - Loss: 0.4384, Accuracy: 88.32%, Total Time: 8.28m

📊 Epoch 216 - Evaluation Completed.


🚀 Epoch 217 - Training Started...

Epoch 217, Batch 100, Loss: 0.0639, Accuracy: 97.22%, Time Passed: 4.65m
Epoch 217, Batch 200, Loss: 0.0575, Accuracy: 97.39%, Time Passed: 9.48m
Epoch 217, Batch 300, Loss: 0.0594, Accuracy: 97.36%, Time Passed: 14.38m
Epoch 217, Batch 400, Loss: 0.0579, Accuracy: 97.25%, Time Passed: 18.51m
Epoch 217, Batch 500, Loss: 0.0594, Accuracy: 97.17%, Time Passed: 22.26m
Epoch 217 Completed - Average Loss: 0.0592, Accuracy: 97.15%, Epoch Time: 25.17m
Training Complete Epoch 217 - Total Time: 25.17m

✅ Epoch 217 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4703, Accuracy: 87.25%, Time Passed: 4.16m
Evaluation Complete - Loss: 0.4543, Accuracy: 88.41%, Total Time: 7.47m

📊 Epoch 217 - Evaluation Completed.


🚀 Epoch 218 - Training Started...

Epoch 218, Batch 100, Loss: 0.0761, Accuracy: 96.44%, Time Passed: 3.98m
Epoch 218, Batch 200, Loss: 0.0669, Accuracy: 96.70%, Time Passed: 7.84m
Epoch 218, Batch 300, Loss: 0.0616, Accuracy: 96.83%, Time Passed: 11.75m
Epoch 218, Batch 400, Loss: 0.0600, Accuracy: 96.95%, Time Passed: 15.84m
Epoch 218, Batch 500, Loss: 0.0578, Accuracy: 97.14%, Time Passed: 19.78m
Epoch 218 Completed - Average Loss: 0.0589, Accuracy: 97.11%, Epoch Time: 22.72m
Training Complete Epoch 218 - Total Time: 22.72m

✅ Epoch 218 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5012, Accuracy: 86.41%, Time Passed: 4.22m
Evaluation Complete - Loss: 0.4647, Accuracy: 88.08%, Total Time: 7.63m

📊 Epoch 218 - Evaluation Completed.


🚀 Epoch 219 - Training Started...

Epoch 219, Batch 100, Loss: 0.0423, Accuracy: 98.09%, Time Passed: 3.93m
Epoch 219, Batch 200, Loss: 0.0507, Accuracy: 97.66%, Time Passed: 7.80m
Epoch 219, Batch 300, Loss: 0.0529, Accuracy: 97.49%, Time Passed: 11.86m
Epoch 219, Batch 400, Loss: 0.0567, Accuracy: 97.29%, Time Passed: 15.71m
Epoch 219, Batch 500, Loss: 0.0566, Accuracy: 97.21%, Time Passed: 19.76m
Epoch 219 Completed - Average Loss: 0.0576, Accuracy: 97.18%, Epoch Time: 22.74m
Training Complete Epoch 219 - Total Time: 22.74m

✅ Epoch 219 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4600, Accuracy: 87.06%, Time Passed: 4.21m
Evaluation Complete - Loss: 0.4481, Accuracy: 88.19%, Total Time: 7.49m

📊 Epoch 219 - Evaluation Completed.


🚀 Epoch 220 - Training Started...

Epoch 220, Batch 100, Loss: 0.0662, Accuracy: 96.84%, Time Passed: 3.95m
Epoch 220, Batch 200, Loss: 0.0657, Accuracy: 96.86%, Time Passed: 7.87m
Epoch 220, Batch 300, Loss: 0.0614, Accuracy: 96.99%, Time Passed: 11.83m
Epoch 220, Batch 400, Loss: 0.0596, Accuracy: 97.07%, Time Passed: 15.81m
Epoch 220, Batch 500, Loss: 0.0590, Accuracy: 97.09%, Time Passed: 19.77m
Epoch 220 Completed - Average Loss: 0.0584, Accuracy: 97.12%, Epoch Time: 22.79m
Training Complete Epoch 220 - Total Time: 22.79m

✅ Epoch 220 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4611, Accuracy: 87.19%, Time Passed: 4.24m
Evaluation Complete - Loss: 0.4236, Accuracy: 88.60%, Total Time: 7.58m

📊 Epoch 220 - Evaluation Completed.

In [75]:
if training_states:
    joblib.dump(training_states, f'Training outputs/training_states_lowest_30_{start_epoch}_{end_epoch}.pkl')

In [76]:
del training_states

### final step

In [104]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[0])

✅ Random seed set to 42 (MPS available: True)

In [105]:
training_states = joblib.load("Training outputs/training_states_lowest_30_201_220.pkl")
mobilenetv2_stageF_lowest_30 = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes)) 
device = torch.device("mps") 
mobilenetv2_stageF_lowest_30.to(device)
mobilenetv2_stageF_lowest_30.load_state_dict(training_states[215]["model_state_dict"])
del training_states

In [106]:
default_train_transform = build_train_transform(crop_type="random", scale=(0.2, 1.0))
train_dataset.transform = default_train_transform  
web_lowest_30_dataset.transform = default_train_transform
val_dataset.transform = val_transform  
full_web_lowest_30_dataset = ConcatDataset([train_dataset, web_lowest_30_dataset])
train_dataset.transform

Compose(
      ToImage()
      RandomResizedCrop(size=(224, 224), scale=(0.2, 1.0), ratio=(0.75, 1.33), interpolation=InterpolationMode.BILINEAR, antialias=True)
      RandomHorizontalFlip(p=0.5)
      RandomVerticalFlip(p=0.2)
      RandomApply(    RandomRotation(degrees=[-90.0, 90.0], interpolation=InterpolationMode.BILINEAR, expand=False, fill=0))
      ToDtype(scale=True)
      RandomApply(    ColorJitter(brightness=(0.7, 1.3), contrast=(0.85, 1.3), saturation=(0.7, 1.3), hue=(-0.0278, 0.0278)))
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], inplace=False)
)

In [107]:
full_web_lowest_30_loader = DataLoader(
    full_web_lowest_30_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,             # shuffle ensures different order each epoch
    num_workers=4,            # safer on macOS, avoids multiprocessing issues
    pin_memory=True,      
    generator=generator       # ensures reproducible shuffling
)

In [108]:
norm_sqrt_inv_weights_train = compute_class_weights(train_dataset, method="sqrt_inverse", normalize=True)
norm_sqrt_inv_weights_train_lowest_30 = compute_class_weights(web_lowest_30_dataset, method="sqrt_inverse", normalize=True)   
norm_sqrt_inv_weights_train_lowest_30[-1] = 0 # handel other class
norm_sqrt_inv_weights = (norm_sqrt_inv_weights_train + (2*norm_sqrt_inv_weights_train_lowest_30))/2


lowest_30_val_results201_220 = pd.read_csv("Training outputs/mobilenetv2_stageF_lowest_30_val_results201_220.csv")

# Step 1: get the subset dataframe
df = lowest_30_val_results201_220[
    (lowest_30_val_results201_220['Species'] != "Average Performance (Macro)") &
    (lowest_30_val_results201_220['Epoch'] == 215)
].copy()

# Step 2: build a mapping from species to recall multiplier
def get_multiplier(recall):
    if recall < 0.6:
        return 10
    elif recall < 0.7:
        return 8
    elif recall < 0.8:
        return 6
    elif recall < 0.9:
        return 4
    elif recall < 1:
        return 2
    else:
        return 1

df['Multiplier'] = df['Recall'].apply(get_multiplier)

# Step 3: make sure class order matches your dataset order
species_to_multiplier = dict(zip(df['Species'], df['Multiplier']))

# Step 4: apply the multipliers to your weight vector
adjusted_weights = norm_sqrt_inv_weights.clone() if hasattr(norm_sqrt_inv_weights, 'clone') else np.copy(norm_sqrt_inv_weights)

for idx, class_name in enumerate(train_dataset.classes):
    if class_name in species_to_multiplier:
        adjusted_weights[idx] *= species_to_multiplier[class_name]

In [109]:
df

,Species,Precision,Recall,F1-score,Epoch,Multiplier
476,Anabasis articulata (Forssk.) Moq.,0.885714,1.000000,0.939394,215,1
477,Anabasis setifera Moq.,0.902703,0.843434,0.872063,215,4
478,Atriplex halimus L.,0.773292,0.886121,0.825871,215,4
479,Calotropis procera,0.950000,0.938272,0.944099,215,2
480,Capparis spinosa L.,0.926829,0.802817,0.860377,215,4
481,Cebatha pendula (J.R.Forst. & G.Forst.) Kuntze,0.935185,0.841667,0.885965,215,4
482,Cenchrus divisus,0.976471,0.954023,0.965116,215,2
483,Deverra tortuosa (Desf.) DC.,0.909091,1.000000,0.952381,215,1
484,Deverra triradiata Hochst. ex Boiss.,0.859649,0.980000,0.915888,215,2
485,Diplotaxis harra (Forssk.) Boiss.,0.887218,0.867647,0.877323,215,4
486,Echinops glaberrimus DC.,0.870690,0.990196,0.926606,215,2
487,Ephedra alata Decne.,0.912371,0.867647,0.889447,215,4
488,Farsetia aegyptia Turra,0.913333,0.740541,0.817910,215,6
489,Gymnocarpos decander Forssk.,0.883212,0.937984,0.909774,215,2
490,Haloxylon salicornicum (Moq.) Bunge ex Boiss.,0.836957,0.905882,0.870056,215,2
491,Heliotropium arbainense Fresen.,0.968750,0.902913,0.934673,215,2
492,Iphiona mucronata (Forssk.) Asch. & Schweinf.,0.966667,0.966667,0.966667,215,2
493,Limonium pruinosum (L.) Chaz.,0.875000,0.707865,0.782609,215,6
494,Lycium shawii Roem. & Schult.,0.820717,0.735714,0.775895,215,6
495,Nitraria retusa (Forssk.) Asch.,0.731507,0.850318,0.786451,215,4
496,Ochradenus baccatus Delile,0.913043,0.969880,0.940604,215,2
497,Peganum harmala L.,0.956522,1.000000,0.977778,215,1
498,Rumex vesicarius L.,0.988372,1.000000,0.994152,215,1
499,Salsola imbricata Forssk.,0.954545,1.000000,0.976744,215,1
500,Stachys aegyptiaca Pers.,0.873333,0.992424,0.929078,215,2
501,Suaeda aegyptiaca (Hasselq.) Zohary,0.911111,0.924812,0.917910,215,2
502,Tamarix nilotica (Ehrenb.) Bunge,0.972973,0.675000,0.797048,215,8
503,Trichodesma africanum (L.) Sm.,0.836478,0.796407,0.815951,215,6
504,Zilla spinosa (L.) Prantl,0.905512,1.000000,0.950413,215,1
505,Zygophyllum arabicum (L.) Christenh. & Byng,0.921147,0.984674,0.951852,215,2
506,Zygophyllum coccineum,0.864734,0.922680,0.892768,215,2
507,Zygophyllum molle (Delile) Christenh. & Byng,0.957983,1.000000,0.978541,215,1
508,others,0.975904,0.810000,0.885246,215,4

In [110]:
adjusted_weights, norm_sqrt_inv_weights

(tensor([ 1.0964,  4.5686,  6.0324,  2.4340,  4.6086,  5.1000,  3.1388,  1.9039,
          4.6970,  4.2096,  3.3128,  8.3636,  6.3663,  1.9881,  2.0413,  2.8982,
          5.4200,  9.3887,  6.7435,  3.7124,  1.9145,  1.5909,  1.1301,  0.8475,
          2.5624,  2.1405, 11.5773,  6.6286,  0.8819,  2.4888,  3.3469,  2.6062,
          1.9130], device='mps:0'),
 tensor([1.0964, 1.1421, 1.5081, 1.2170, 1.1522, 1.2750, 1.5694, 1.9039, 2.3485,
         1.0524, 1.6564, 2.0909, 1.0611, 0.9941, 1.0207, 1.4491, 2.7100, 1.5648,
         1.1239, 0.9281, 0.9572, 1.5909, 1.1301, 0.8475, 1.2812, 1.0702, 1.4472,
         1.1048, 0.8819, 1.2444, 1.6734, 2.6062, 0.4783], device='mps:0'))

In [111]:
norm_sqrt_inv_criterion = nn.CrossEntropyLoss(weight=adjusted_weights)
stageF_optimizer = torch.optim.AdamW(mobilenetv2_stageF_lowest_30.parameters(), lr=5e-6,
                            weight_decay=1e-4, betas=(0.9, 0.999))

In [74]:
start_epoch = 216
end_epoch = 220
start_epoch, end_epoch

(216, 220)

In [113]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageF_lowest_30, full_web_lowest_30_loader, val_loader, norm_sqrt_inv_criterion, stageF_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageF_lowest_30', save_dir = 'Training outputs',
                         class_weights='adjusted_norm_sqrt_inv', log_interval=100, evaluate=True)

🚀 Epoch 216 - Training Started...

Epoch 216, Batch 100, Loss: 0.0558, Accuracy: 96.91%, Time Passed: 3.70m
Epoch 216, Batch 200, Loss: 0.0636, Accuracy: 96.94%, Time Passed: 7.37m
Epoch 216, Batch 300, Loss: 0.0651, Accuracy: 96.95%, Time Passed: 11.76m
Epoch 216, Batch 400, Loss: 0.0660, Accuracy: 96.90%, Time Passed: 16.07m
Epoch 216, Batch 500, Loss: 0.0641, Accuracy: 97.01%, Time Passed: 20.41m
Epoch 216 Completed - Average Loss: 0.0629, Accuracy: 97.05%, Epoch Time: 23.45m
Training Complete Epoch 216 - Total Time: 23.45m

✅ Epoch 216 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4612, Accuracy: 87.44%, Time Passed: 4.44m
Evaluation Complete - Loss: 0.4328, Accuracy: 88.84%, Total Time: 7.88m

📊 Epoch 216 - Evaluation Completed.


🚀 Epoch 217 - Training Started...

Epoch 217, Batch 100, Loss: 0.0550, Accuracy: 97.28%, Time Passed: 4.53m
Epoch 217, Batch 200, Loss: 0.0555, Accuracy: 97.28%, Time Passed: 8.75m
Epoch 217, Batch 300, Loss: 0.0601, Accuracy: 97.18%, Time Passed: 12.70m
Epoch 217, Batch 400, Loss: 0.0578, Accuracy: 97.27%, Time Passed: 16.72m
Epoch 217, Batch 500, Loss: 0.0593, Accuracy: 97.19%, Time Passed: 20.75m
Epoch 217 Completed - Average Loss: 0.0588, Accuracy: 97.19%, Epoch Time: 23.72m
Training Complete Epoch 217 - Total Time: 23.72m

✅ Epoch 217 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4726, Accuracy: 87.16%, Time Passed: 4.26m
Evaluation Complete - Loss: 0.4473, Accuracy: 88.65%, Total Time: 7.58m

📊 Epoch 217 - Evaluation Completed.


🚀 Epoch 218 - Training Started...

Epoch 218, Batch 100, Loss: 0.0559, Accuracy: 97.25%, Time Passed: 4.06m
Epoch 218, Batch 200, Loss: 0.0572, Accuracy: 97.14%, Time Passed: 8.24m
Epoch 218, Batch 300, Loss: 0.0582, Accuracy: 97.15%, Time Passed: 12.83m
Epoch 218, Batch 400, Loss: 0.0574, Accuracy: 97.12%, Time Passed: 17.18m
Epoch 218, Batch 500, Loss: 0.0590, Accuracy: 97.03%, Time Passed: 21.32m
Epoch 218 Completed - Average Loss: 0.0577, Accuracy: 97.10%, Epoch Time: 24.54m
Training Complete Epoch 218 - Total Time: 24.54m

✅ Epoch 218 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5154, Accuracy: 86.62%, Time Passed: 4.12m
Evaluation Complete - Loss: 0.4715, Accuracy: 88.37%, Total Time: 7.31m

📊 Epoch 218 - Evaluation Completed.


🚀 Epoch 219 - Training Started...

Epoch 219, Batch 100, Loss: 0.0609, Accuracy: 97.31%, Time Passed: 3.91m
Epoch 219, Batch 200, Loss: 0.0562, Accuracy: 97.34%, Time Passed: 8.10m
Epoch 219, Batch 300, Loss: 0.0610, Accuracy: 97.21%, Time Passed: 11.90m
Epoch 219, Batch 400, Loss: 0.0572, Accuracy: 97.24%, Time Passed: 15.78m
Epoch 219, Batch 500, Loss: 0.0600, Accuracy: 97.19%, Time Passed: 19.53m
Epoch 219 Completed - Average Loss: 0.0595, Accuracy: 97.21%, Epoch Time: 22.47m
Training Complete Epoch 219 - Total Time: 22.47m

✅ Epoch 219 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4826, Accuracy: 86.94%, Time Passed: 5.31m
Evaluation Complete - Loss: 0.4642, Accuracy: 88.10%, Total Time: 9.02m

📊 Epoch 219 - Evaluation Completed.


🚀 Epoch 220 - Training Started...

Epoch 220, Batch 100, Loss: 0.0586, Accuracy: 96.88%, Time Passed: 5.37m
Epoch 220, Batch 200, Loss: 0.0565, Accuracy: 96.95%, Time Passed: 10.39m
Epoch 220, Batch 300, Loss: 0.0549, Accuracy: 97.21%, Time Passed: 15.02m
Epoch 220, Batch 400, Loss: 0.0541, Accuracy: 97.29%, Time Passed: 19.89m
Epoch 220, Batch 500, Loss: 0.0554, Accuracy: 97.28%, Time Passed: 24.88m
Epoch 220 Completed - Average Loss: 0.0563, Accuracy: 97.24%, Epoch Time: 28.26m
Training Complete Epoch 220 - Total Time: 28.26m

✅ Epoch 220 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.4906, Accuracy: 86.75%, Time Passed: 4.23m
Evaluation Complete - Loss: 0.4451, Accuracy: 88.60%, Total Time: 7.71m

📊 Epoch 220 - Evaluation Completed.

In [75]:
if training_states:
    joblib.dump(
        training_states,
        f"Training outputs/training_states_lowest_30_{start_epoch}_{end_epoch}.pkl"
    )