# **<center>1. Imports</center>**

In [1]:
# ============================================================
# 1. Imports and Environment Information
# ============================================================

# ----------------------------
# Standard libraries
# ----------------------------
import os
import sys
import re
import copy
import time
import random
import shutil
import math
import platform
import importlib.metadata

from pathlib import Path
from collections import Counter, defaultdict


# ----------------------------
# Data handling
# ----------------------------
import pandas as pd
import numpy as np
import scipy
from scipy.stats import skew
import joblib


# ----------------------------
# Visualization and image handling
# ----------------------------
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

import PIL
from PIL import Image
import pillow_heif


# ----------------------------
# Scikit-learn
# ----------------------------
import sklearn

from sklearn.model_selection import (
    train_test_split,
    StratifiedShuffleSplit,
)

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)


# ----------------------------
# PyTorch and TorchVision
# ----------------------------
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision

from torch.utils.data import (
    DataLoader,
    Subset,
    random_split,
    ConcatDataset,
)

from torchvision import (
    datasets,
    models,
    transforms,
)

import torchvision.transforms.v2 as v2


# ----------------------------
# Enable HEIF / HEIC support
# ----------------------------
pillow_heif.register_heif_opener()


# ============================================================
# Environment logging
# ============================================================

print("=== Environment Info ===")

# System information
print(f"Platform: {platform.platform()}")
print(f"System: {platform.system()}")
print(f"Machine: {platform.machine()}")
print(f"Processor: {platform.processor() or 'Not reported'}")

# Software versions
print(f"Python: {sys.version}")
print(f"PyTorch: {torch.__version__}")
print(f"TorchVision: {torchvision.__version__}")
print(f"NumPy: {np.__version__}")
print(f"Pandas: {pd.__version__}")
print(f"SciPy: {scipy.__version__}")
print(f"Scikit-learn: {sklearn.__version__}")
print(f"Pillow: {PIL.__version__}")
print(f"Joblib: {joblib.__version__}")
print(f"Matplotlib: {matplotlib.__version__}")
print(f"Seaborn: {sns.__version__}")

try:
    print(f"pillow-heif: {importlib.metadata.version('pillow-heif')}")
except importlib.metadata.PackageNotFoundError:
    print("pillow-heif: Not installed")

# Apple Metal Performance Shaders
if hasattr(torch.backends, "mps"):
    print(f"MPS built: {torch.backends.mps.is_built()}")
    print(f"MPS available: {torch.backends.mps.is_available()}")
else:
    print("MPS built: Not supported by this PyTorch build")
    print("MPS available: No")

=== Environment Info ===
Platform: macOS-14.5-arm64-arm-64bit
System: Darwin
Machine: arm64
Processor: arm
Python: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ]
PyTorch: 2.5.1
TorchVision: 0.20.1
NumPy: 1.26.4
Pandas: 2.2.2
SciPy: 1.13.1
Scikit-learn: 1.5.1
Pillow: 10.4.0
Joblib: 1.4.2
Matplotlib: 3.9.2
Seaborn: 0.13.2
pillow-heif: 0.21.0
MPS built: True
MPS available: True

In [2]:
# ============================================================
# Project / Dataset Paths
# ============================================================

from dotenv import load_dotenv

# Permanent private configuration
CONFIG_FILE = Path.home() / ".wadidegla.env"

if not CONFIG_FILE.exists():
    raise FileNotFoundError(
        "Local WadiDegla configuration file was not found."
    )

load_dotenv(CONFIG_FILE)


DATA_DIR = Path(os.environ["WADIDEGLA_DATA_DIR"])
TRAIN_DIR = DATA_DIR / "Train"
VAL_DIR = DATA_DIR / "Validation"

WORKSPACE_DIR = Path(os.environ["WADIDEGLA_WORKSPACE_DIR"])

if not DATA_DIR.exists():
    raise FileNotFoundError(
        "The configured WadiDegla dataset directory does not exist."
    )

if not WORKSPACE_DIR.exists():
    raise FileNotFoundError(
        "The configured WadiDegla experimental workspace directory does not exist."
    )

print("WadiDegla dataset configuration loaded successfully.")
print("WadiDegla experimental workspace configuration loaded successfully.")

WadiDegla dataset configuration loaded successfully.
WadiDegla experimental workspace configuration loaded successfully.

# **<center>2. Reproducibility Setup for Mac M1/MPS</center>**

In [3]:
def set_seed(seed: int, deterministic: bool = True):
    """
    Initialize all RNG seeds for reproducibility on Apple Silicon M1.
    Optimized for MPS backend.

    Returns:
        start_rng_state (dict): RNG states captured immediately after seeding.
        generator (torch.Generator): Torch generator initialized with the same seed.
    """
    os.environ['PYTHONHASHSEED'] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.backends.mps.is_available():
        torch.mps.manual_seed(seed)
    if deterministic:
        torch.use_deterministic_algorithms(True)

    generator = torch.Generator()
    generator.manual_seed(seed)

    rng_state = {
        'seed': seed,
        'rng_python': random.getstate(),
        'rng_numpy': np.random.get_state(),
        'rng_torch': torch.get_rng_state(),
        'rng_torch_mps': torch.mps.get_rng_state() if torch.backends.mps.is_available() else None,
        'deterministic': deterministic,
        'generator_state': generator.get_state()
    }
    print(f"✅ Random seed set to {seed} (MPS available: {torch.backends.mps.is_available()})")
    return rng_state, generator

In [4]:
def get_rng_state(seed: int, generator: torch.Generator, deterministic: bool = True):
    """
    Capture the CURRENT RNG states for Python, NumPy, and PyTorch (CPU + MPS if available).

    Returns:
        (dict, torch.Generator): RNG state dict and the generator.
    """
    rng_state = {
        'seed': seed,
        'rng_python': random.getstate(),
        'rng_numpy': np.random.get_state(),
        'rng_torch': torch.get_rng_state(),
        'rng_torch_mps': torch.mps.get_rng_state() if torch.backends.mps.is_available() else None,
        'deterministic': deterministic,
        'generator_state': generator.get_state()
    }
    return rng_state, generator

In [5]:
def manage_rng_state(path: str, mode: str, seed: int = None, generator: torch.Generator = None, deterministic: bool = True):
    """
    Save or load RNG state for Python, NumPy, and PyTorch (CPU + MPS).

    Returns:
        (dict, torch.Generator): RNG state dict and the generator.
    """
    if mode == 'load':
        rng_state = joblib.load(path)

        random.setstate(rng_state['rng_python'])
        np.random.set_state(rng_state['rng_numpy'])
        torch.set_rng_state(rng_state['rng_torch'])
        if torch.backends.mps.is_available() and rng_state.get('rng_torch_mps') is not None:
            torch.mps.set_rng_state(rng_state['rng_torch_mps'])
        torch.use_deterministic_algorithms(rng_state.get('deterministic', False))

        generator = torch.Generator()
        if 'generator_state' in rng_state:
            generator.set_state(rng_state['generator_state'])
        elif seed is not None:
            generator.manual_seed(seed)

        print(f"✅ RNG state loaded from {path}")
        return rng_state, generator

    elif mode == 'save':
        if generator is None:
            generator = torch.Generator().manual_seed(seed)
        rng_state, generator = get_rng_state(seed, generator, deterministic)
        joblib.dump(rng_state, path)
        print(f"✅ RNG state saved to {path}")
        return rng_state, generator

    else:
        raise ValueError("mode must be either 'save' or 'load'")

In [6]:
def setup_reproducibility(start_fresh: bool = False,
                          seed: int = None,
                          deterministic: bool = True,
                          continue_run: bool = False,
                          path: str = None,
                          mode: str = None,
                          generator: torch.Generator = None):
    """
    Wrapper for reproducibility setup:
      - Optionally set RNG seeds.
      - Optionally save/load RNG states.

    Returns:
        (dict, torch.Generator)
    """
    if start_fresh:
        if seed is None:
            raise ValueError("`seed` must be provided when start_fresh=True.")
        return set_seed(seed=seed, deterministic=deterministic)

    if continue_run:
        if path is None or mode is None:
            raise ValueError("Both `path` and `mode` must be provided when continue_run=True.")
        return manage_rng_state(path=path, mode=mode, seed=seed, generator=generator, deterministic=deterministic)

**Start fresh with a new seed**

In [7]:
seeds = [42, 1234, 2025]

In [8]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[0])

✅ Random seed set to 42 (MPS available: True)

**Save current RNG state**

In [10]:
state, generator = setup_reproducibility(continue_run=True, path="mobilenetv2/rng_state.pkl", mode="save", seed=seeds[0], generator=generator)

✅ RNG state saved to mobilenetv2/rng_state.pkl

**Load previously saved RNG state**

In [11]:
state, generator = setup_reproducibility(continue_run=True, path="mobilenetv2/rng_state.pkl", mode="load")

✅ RNG state loaded from mobilenetv2/rng_state.pkl

# <center>**Input Pipeline Setup (Dataset Loading & Transformations)**</center>

## **1. Experiment Configuration**

In [12]:
BATCH_SIZE = 32
NUM_CLASSES = sum(1 for d in (DATA_DIR/'Train').iterdir() if d.is_dir())
NUM_CLASSES

33

## **2. Define Data Augmentation & Preprocessing Pipeline**

**Resize then Augment**
- **When working with plant images of varying sizes, the recommended order is: resize first, then augment.**


1. **Consistency:** Resizing first ensures all images share the same dimensions, leading to consistent transformation behavior during augmentation.

2. **Computational Efficiency:** Augmentation is faster on smaller, uniform images, while large images use more memory and slow training.
  
3. **Avoids Distortion Cascading:** Resizing first provides a clean base, preventing amplified artifacts (blur, aliasing, edge blanks) that occur when resizing after augmentation.

In [13]:
def build_train_transform(
    crop_type="random",
    scale=(0.2, 1.0),
    crop_size=224,
    ratio=(0.75, 1.33),
    color_jitter=True,
    jitter_prob=0.8,
    always_jitter=False,
    hflip_prob=0.5,
    vflip_prob=0.2,
    rotate_prob=0.5,
    rotation_degrees=(-90, 90),
    brightness=(0.7, 1.3),
    contrast=(0.85, 1.3),
    saturation=(0.7, 1.3),
    hue=(-0.0278, 0.0278),
    mean=None,
    std=None,
    normalize=True
):
    """
    Build a training transform pipeline with customizable augmentations.
    ...
    """
    mean = mean or [0.485, 0.456, 0.406]
    std = std or [0.229, 0.224, 0.225]
    
    # Stage 1: Input Preparation & Spatial Augmentations
    transforms_list = [v2.ToImage()]

    if crop_type == "random":
        transforms_list.append(
            v2.RandomResizedCrop(
                size=(crop_size, crop_size),
                scale=scale,
                ratio=ratio,
                antialias=True
            )
        )
    elif crop_type == "center":
        transforms_list.extend([
            v2.Resize(256),
            v2.CenterCrop(crop_size)
        ])
    else:
        raise ValueError(f"Unknown crop_type: {crop_type}. Use 'random' or 'center'")

    transforms_list.extend([
        v2.RandomHorizontalFlip(p=hflip_prob),
        v2.RandomVerticalFlip(p=vflip_prob),
        v2.RandomApply([
            v2.RandomRotation(degrees=rotation_degrees, interpolation=v2.InterpolationMode.BILINEAR)
        ], p=rotate_prob)
    ])

    # Stage 2: Color Operations
    transforms_list.append(v2.ToDtype(torch.float32, scale=True)) # Convert to [0,1] float32

    if color_jitter:
        jitter = v2.ColorJitter(
            brightness=brightness, contrast=contrast,
            saturation=saturation, hue=hue
        )
        transforms_list.append(jitter if always_jitter else v2.RandomApply([jitter], p=jitter_prob)) # Apply color jitter jitter_prob of the time, identity (1 - jitter_prob)

    # Stage 3: Normalization (CRUCIAL for training)
    if normalize:
        transforms_list.append(v2.Normalize(mean=mean, std=std))

    return v2.Compose(transforms_list)

In [14]:
default_train_transform = build_train_transform(crop_type="random", scale=(0.2, 1.0))
# crop_50_train_transform = build_train_transform(crop_type="random", scale=(0.5, 1.0))
# crop_80_train_transform = build_train_transform(crop_type="random", scale=(0.8, 1.0))
# center_crop_train_transform = build_train_transform(crop_type="center")
# hard_train_transform = build_train_transform(crop_type="random", scale=(0.08, 1.0), always_jitter=True)

In [15]:
default_train_transform

Compose(
      ToImage()
      RandomResizedCrop(size=(224, 224), scale=(0.2, 1.0), ratio=(0.75, 1.33), interpolation=InterpolationMode.BILINEAR, antialias=True)
      RandomHorizontalFlip(p=0.5)
      RandomVerticalFlip(p=0.2)
      RandomApply(    RandomRotation(degrees=[-90.0, 90.0], interpolation=InterpolationMode.BILINEAR, expand=False, fill=0))
      ToDtype(scale=True)
      RandomApply(    ColorJitter(brightness=(0.7, 1.3), contrast=(0.85, 1.3), saturation=(0.7, 1.3), hue=(-0.0278, 0.0278)))
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], inplace=False)
)

**In validation, it is best to first resize the image so that its shorter side is 256 pixels—whether by upscaling or downscaling—and then apply a center crop of 224×224 to obtain a well-centered, standardized region.**

In [16]:
# Validation transforms (no augmentation)
val_transform = v2.Compose([
    v2.ToImage(),
    # Resize the image so its shorter side is 256 pixels, preserving aspect ratio (i.e., the proportion between width and height stays the same)
    v2.Resize(256),
    # Extract a 224x224 patch from the center of the resized image
    v2.CenterCrop(224),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

## **3. Dataset Construction**

### **3.1 File Extension Validation**

In [17]:
def count_extensions(root_dir):
    extension_counter = defaultdict(int)
    c = 0
    for foldername, subfolders, filenames in os.walk(root_dir):
      
            
        for filename in filenames:
            # Extract extension and convert to lowercase
            ext = os.path.splitext(filename)[1].lower()
            if ext == '':
                continue
            # Count extension (even if empty)
            extension_counter[ext] += 1
    
    return dict(extension_counter)

# Usage
extension_counts = count_extensions(DATA_DIR)

print("Extension counts:")
for ext, count in extension_counts.items():
    print(f"{ext}: {count}")
print(f'Total: {sum(extension_counts.values())}')

Extension counts:
.jpg: 21042
.jpeg: 1522
Total: 22564

### **3.2 Dataset creation**

In [18]:
# Create Dataset objects for training and validation sets

train_dataset = datasets.ImageFolder(
    root=DATA_DIR / "Train"  # Path to the training directory
)


val_dataset = datasets.ImageFolder(
    root=DATA_DIR / "Validation"  # Path to the validation directory
)

print(f"Training dataset size: {len(train_dataset)} images")
print(f"Validation dataset size: {len(val_dataset)} images")

Training dataset size: 17364 images
Validation dataset size: 5200 images

In [60]:
print(f'Number of model classes: {len(train_dataset.classes)}')
print(f'Number of images: {len(train_dataset.targets)+len(val_dataset.targets)}')

Number of model classes: 33
Number of images: 22564

In [20]:
train_dataset.transform =default_train_transform  # Apply the aggressive augmentation pipeline
val_dataset.transform   = val_transform    # Apply the deterministic preprocessing pipeline

In [21]:
train_dataset.transform

Compose(
      ToImage()
      RandomResizedCrop(size=(224, 224), scale=(0.2, 1.0), ratio=(0.75, 1.33), interpolation=InterpolationMode.BILINEAR, antialias=True)
      RandomHorizontalFlip(p=0.5)
      RandomVerticalFlip(p=0.2)
      RandomApply(    RandomRotation(degrees=[-90.0, 90.0], interpolation=InterpolationMode.BILINEAR, expand=False, fill=0))
      ToDtype(scale=True)
      RandomApply(    ColorJitter(brightness=(0.7, 1.3), contrast=(0.85, 1.3), saturation=(0.7, 1.3), hue=(-0.0278, 0.0278)))
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], inplace=False)
)

In [22]:
val_dataset.transform

Compose(
      ToImage()
      Resize(size=[256], interpolation=InterpolationMode.BILINEAR, antialias=True)
      CenterCrop(size=(224, 224))
      ToDtype(scale=True)
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], inplace=False)
)

## **4. DataLoader Configuration**

**This is where we wrap the datasets into DataLoaders for batching, shuffling, and parallel loading.**

In [23]:
# Detect if CUDA is available; on M1 we expect only MPS/CPU
use_cuda = torch.cuda.is_available()

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,             # shuffle ensures different order each epoch
    num_workers=4,            # safer on macOS, avoids multiprocessing issues
    pin_memory=True,     
    generator=generator       # ensures reproducible shuffling
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,            # no need to shuffle validation
    num_workers=4,            # same note for macOS
    pin_memory=True,
    generator=generator
)

In [24]:
# Verify the loaders
print(f"Training batches: {len(train_loader)}")
print(f"Validation batches: {len(val_loader)}")

Training batches: 543
Validation batches: 163

# <center>**Utility Functions for Model Training & Evaluation**</center>

## **1. Compute Class Weights**

In [29]:
def compute_class_weights(dataset, method="inverse_frequency", normalize=False):
    """
    Compute class weights based on the chosen method, with optional normalization.

    Args:
        dataset: A dataset object with a 'targets' attribute containing class labels.
        method (str): Method for computing class weights. Options:
            - "inverse_frequency": total_samples / count
            - "balanced": total_samples / (count * num_classes)
            - "sqrt_inverse": 1 / np.sqrt(count)
            - "scaled_sqrt_inverse": (1 / np.sqrt(count)) * 100
        normalize (bool): If True, rescale weights so that their mean = 1.

    Returns:
        torch.Tensor: Class weights tensor on the appropriate device.
    """
    # Compute class frequencies
    class_counts = Counter(dataset.targets)
    total_samples = sum(class_counts.values())
    num_classes = len(class_counts)

    # Select weight calculation method
    if method == "inverse_frequency":
        class_weights = {cls: total_samples / count for cls, count in class_counts.items()}
    elif method == "balanced":
        class_weights = {cls: total_samples / (count * num_classes) for cls, count in class_counts.items()}
    elif method == "sqrt_inverse":
        class_weights = {cls: 1 / np.sqrt(count) for cls, count in class_counts.items()}
    elif method == "scaled_sqrt_inverse":
        class_weights = {cls: (1 / np.sqrt(count)) * 100 for cls, count in class_counts.items()}
    else:
        raise ValueError("Invalid method. Choose from 'inverse_frequency', 'balanced', 'sqrt_inverse', 'scaled_sqrt_inverse'.")

    # Convert to tensor
    class_weights_tensor = torch.tensor([class_weights[i] for i in range(num_classes)], dtype=torch.float32)

    #  Normalize weights to have an average of 1.0 → divide by mean 
    if normalize:
        class_weights_tensor = class_weights_tensor / class_weights_tensor.mean()

    # Move weights to MPS (Apple GPU) if available
    device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
    return class_weights_tensor.to(device)

In [30]:
class_index_count = {train_dataset.classes[i]:sorted(Counter(train_dataset.targets).items())[i] for i in range(len(train_dataset.classes))}
print(class_index_count)

{'Anabasis articulata (Forssk.) Moq.': (0, 299), 'Anabasis setifera Moq.': (1, 865), 'Atriplex halimus L.': (2, 957), 'Calotropis procera (Aiton) W.T.Aiton': (3, 266), 'Capparis spinosa L.': (4, 515), 'Cebatha pendula (J.R.Forst. & G.Forst.) Kuntze': (5, 368), 'Cenchrus divisus (J.F.Gmel.) Verloove, Govaerts & Buttler': (6, 205), 'Deverra tortuosa (Desf.) DC.': (7, 156), 'Deverra triradiata Hochst. ex Boiss.': (8, 148), 'Diplotaxis harra (Forssk.) Boiss.': (9, 415), 'Echinops glaberrimus DC.': (10, 734), 'Ephedra alata Decne.': (11, 860), 'Farsetia aegyptia Turra': (12, 419), 'Gymnocarpos decander Forssk.': (13, 571), 'Haloxylon salicornicum (Moq.) Bunge ex Boiss.': (14, 672), 'Heliotropium arbainense Fresen.': (15, 674), 'Iphiona mucronata (Forssk.) Asch. & Schweinf.': (16, 110), 'Limonium pruinosum (L.) Chaz.': (17, 307), 'Lycium shawii Roem. & Schult.': (18, 1073), 'Nitraria retusa (Forssk.) Asch.': (19, 704), 'Ochradenus baccatus Delile': (20, 1396), 'Peganum harmala L.': (21, 85), 'Rumex vesicarius L.': (22, 340), 'Salsola imbricata Forssk.': (23, 407), 'Stachys aegyptiaca Pers.': (24, 391), 'Suaeda aegyptiaca (Hasselq.) Zohary': (25, 426), 'Tamarix nilotica (Ehrenb.) Bunge': (26, 1074), 'Trichodesma africanum (L.) Sm.': (27, 323), 'Zilla spinosa (L.) Prantl': (28, 456), 'Zygophyllum arabicum (L.) Christenh. & Byng': (29, 878), 'Zygophyllum coccineum L.': (30, 668), 'Zygophyllum molle (Delile) Christenh. & Byng': (31, 202), 'others': (32, 400)}

In [31]:
inverse_frequency_class_weights = compute_class_weights(train_dataset, method="inverse_frequency")
normalized_inverse_frequency_class_weights = compute_class_weights(train_dataset, method="inverse_frequency", normalize=True)

In [32]:
print(f"Inverse frequency class weights: {[round(v, 2) for v in inverse_frequency_class_weights.cpu().numpy().tolist()]}")
print(f"Inverse frequency class weights: {round(inverse_frequency_class_weights.mean().item(), 2)}")

Inverse frequency class weights: [58.07, 20.07, 18.14, 65.28, 33.72, 47.18, 84.7, 111.31, 117.32, 41.84, 23.66, 20.19, 41.44, 30.41, 25.84, 25.76, 157.85, 56.56, 16.18, 24.66, 12.44, 204.28, 51.07, 42.66, 44.41, 40.76, 16.17, 53.76, 38.08, 19.78, 25.99, 85.96, 43.41]
Inverse frequency class weights: 51.48

In [33]:
print(f"Normalized Inverse frequency class weights: {[round(v, 2) for v in normalized_inverse_frequency_class_weights.cpu().numpy().tolist()]}")
print(f"Normalized Inverse frequency class weights: {round(normalized_inverse_frequency_class_weights.mean().item(), 2)}")

Normalized Inverse frequency class weights: [1.13, 0.39, 0.35, 1.27, 0.65, 0.92, 1.65, 2.16, 2.28, 0.81, 0.46, 0.39, 0.8, 0.59, 0.5, 0.5, 3.07, 1.1, 0.31, 0.48, 0.24, 3.97, 0.99, 0.83, 0.86, 0.79, 0.31, 1.04, 0.74, 0.38, 0.5, 1.67, 0.84]
Normalized Inverse frequency class weights: 1.0

In [34]:
def compute_inverse_metric_tensor(
    metric_dict, 
    class_to_idx, 
    normalize=True, 
    power=1.0, 
    eps=1e-8,
    clip = False,
    clip_min=0.5, 
    clip_max=3.0
):
    """
    Compute inverse metric-based class weights and return as a PyTorch tensor.

    Parameters
    ----------
    metric_dict : dict
        {class_name: metric_value}, e.g. recall, precision, or F1-score.
    class_to_idx : dict
        Mapping of {class_name: class_index} from the dataset.
    normalize : bool, optional
        Normalize class_weights_tensor to mean 1. Default True.
    power : float, optional
        Exponent controlling the scaling. Default 1.0.
    eps : float, optional
        Small constant to avoid division by zero.
    clip_min, clip_max : float
        Minimum and maximum clipping values for stability.

    Returns
    -------
    torch.Tensor
        Tensor of class weights ordered by class index, dtype=torch.float32.
    """
    # Compute inverse weights in the correct class order
    inv_weights = []
    for cls, idx in class_to_idx.items():
        metric = metric_dict.get(cls)
        inv_w = (1.0 / (metric + eps)) ** power
        inv_weights.append(inv_w)

    # Convert to tensor
    class_weights_tensor = torch.tensor(inv_weights, dtype=torch.float32)

    # Clip weights to avoid extremes
    if clip:
        class_weights_tensor = torch.clamp(class_weights_tensor, min=clip_min, max=clip_max)

    # Normalize (mean = 1)
    if normalize:
        class_weights_tensor = class_weights_tensor / class_weights_tensor.mean()

    # Move to device
    device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
    return class_weights_tensor.to(device)

## **2. Candidate Models Configuration**

### **1. mobilenet_v2**

In [35]:
def configure_mobilenetv2_training(
    model: nn.Module,
    num_classes: int,
    stage_a: bool = False,
    intermediate: bool = False,
    intermediate_blocks: list[int] | None = None,
    final_stage: bool = False,
    prev_unfrozen: int | None = None,
):
    """
    Configure MobileNetV2 model for staged training (Stage A, Intermediate, Final).

    Args:
        model (nn.Module): MobileNetV2 model instance (fresh or from previous stage).
        num_classes (int): Number of output classes for the dataset.
        stage_a (bool): If True, reinitialize classifier head and freeze backbone.
        intermediate (bool): If True, progressively unfreeze backbone blocks.
        intermediate_blocks (list[int] | None): [prev_unfrozen, new_unfrozen].
            Example: [1, 3] → model had 1 block unfrozen before, now unfreeze 3.
        final_stage (bool): If True, unfreeze the entire backbone.
        prev_unfrozen (int | None): Number of previously unfrozen blocks (for final stage).

    Returns:
        nn.Module: Model with updated training configuration.

    Prints:
        - Trainable layers count and % of total layers
        - Trainable parameters count and % of total parameters
        - Which backbone blocks are trainable
    """

    # ---- Stage A: train only classifier head ----
    if stage_a:
        in_features = model.classifier[1].in_features
        model.classifier[1] = nn.Linear(in_features, num_classes)

        # Kaiming normal init
        nn.init.kaiming_normal_(model.classifier[1].weight, nonlinearity="relu")
        if model.classifier[1].bias is not None:
            nn.init.zeros_(model.classifier[1].bias)

        # Freeze everything
        for param in model.parameters():
            param.requires_grad = False
        
        # Unfreeze the entire classifier
        for param in model.classifier.parameters():
            param.requires_grad = True  
        print("🟢 Stage A → Classifier head is trainable, backbone frozen.")
            

    # ---- Intermediate stage: progressively unfreeze ----
    if intermediate:
        assert intermediate_blocks is not None and len(intermediate_blocks) == 2, \
            "intermediate_blocks must be [prev_unfrozen, new_unfrozen]."

        prev_unfrozen, new_unfrozen = intermediate_blocks
        assert new_unfrozen >= prev_unfrozen, \
            "New unfrozen count must be >= previous unfrozen count."

   
    
        # Unfreeze last `new_unfrozen` blocks
        total_blocks = len(model.features)
        prev_frozen_blocks = total_blocks - prev_unfrozen
        new_frozen_blocks = total_blocks - new_unfrozen

        unfrozen_indices = []
        
        for i in range(total_blocks):
            for param in model.features[i].parameters():
                param.requires_grad = False            
        for i in range(new_frozen_blocks, prev_frozen_blocks): # note that the blocks has zero indexing
            for param in model.features[i].parameters():
                param.requires_grad = True
            unfrozen_indices.append(i)
        print(f"🟢 Intermediate stage → Newly unfrozen blocks: {unfrozen_indices}")

    # ---- Final stage: unfreeze entire backbone ----
    if final_stage:
        assert prev_unfrozen is not None, \
            "prev_unfrozen must be provided for final stage."
    
        total_blocks = len(model.features)

        prev_frozen_blocks = total_blocks - prev_unfrozen
        unfrozen_indices = list(range(prev_frozen_blocks))

        for i in unfrozen_indices:
            for param in model.features[i].parameters():
                param.requires_grad = True

        print(f"🟢 Final stage → Entire backbone unfrozen (blocks {unfrozen_indices})")

    # ---- Report trainable stats ----
    total_layers = sum(1 for p in model.parameters())
    trainable_layers = sum(1 for p in model.parameters() if p.requires_grad)

    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

    print(f"✅ Trainable layers: {trainable_layers}/{total_layers} "
          f"({trainable_layers/total_layers*100:.2f}%)")
    print(f"✅ Trainable params: {trainable_params:,}/{total_params:,} "
          f"({trainable_params/total_params*100:.2f}%)")

    return model

In [36]:
def summarize_mobilenetv2_blocks(model: nn.Module):
    """
    Summarize blocks in a MobileNetV2 model.
    
    Returns:
        pd.DataFrame: block-level summary with counts, percentages, and cumulative stats.
    """

    # ---- Collect blocks: features + classifier ----
    blocks = []
    if hasattr(model, "features"):
        for i, block in enumerate(model.features):
            blocks.append((f"{block.__class__.__name__}_{i+1}", block, "features"))
    if hasattr(model, "classifier"):
        blocks.append((f"{model.classifier.__class__.__name__}", model.classifier, "classifier"))

    # ---- Helper functions ----
    def count_layers(module: nn.Module):
        # Count atomic submodules (ignore containers)
        return sum(1 for m in module.modules() if not isinstance(m, nn.Sequential))

    def count_params(module: nn.Module):
        return sum(p.numel() for p in module.parameters())

    def count_trainable_params(module: nn.Module):
        return sum(p.numel() for p in module.parameters() if p.requires_grad)

    # ---- Build dataframe rows ----
    rows = []
    for order, (name, block, module_name) in enumerate(blocks, 1):
        n_layers = count_layers(block)
        n_params = count_params(block)
        n_trainable = count_trainable_params(block)
        rows.append({
            "Block": name,
            "Order": order,
            "Module": module_name,
            "Layers (#)": n_layers,
            "Params (#)": n_params,
            "Trainable Params (#)": n_trainable,
        })

    df = pd.DataFrame(rows)

    # ---- Totals for whole model ----
    total_layers_model = df["Layers (#)"].sum()
    total_params_model = df["Params (#)"].sum()
    total_trainable_params_model = df["Trainable Params (#)"].sum()

    # Per-model percentages
    df["% Layers (Model)"] = df["Layers (#)"] / total_layers_model * 100
    df["% Params (Model)"] = df["Params (#)"] / total_params_model * 100
    df["% Trainable Params (Model)"] = df["Trainable Params (#)"] / total_params_model * 100

    # Accumulative (start from deepest → reverse order)
    df["Cumulative Layers (Model)"] = df["Layers (#)"][::-1].cumsum()[::-1]
    df["Cumulative % Layers (Model)"] = df["Cumulative Layers (Model)"] / total_layers_model * 100
    df["Cumulative Params (Model)"] = df["Params (#)"][::-1].cumsum()[::-1]
    df["Cumulative % Params (Model)"] = df["Cumulative Params (Model)"] / total_params_model * 100
    # ---- Per-module stats ----
    module_stats = []
    for module_name in df["Module"].unique():
        sub = df[df["Module"] == module_name]
        total_layers_mod = sub["Layers (#)"].sum()
        total_params_mod = sub["Params (#)"].sum()
        total_trainable_mod = sub["Trainable Params (#)"].sum()
        for idx in sub.index:
            module_stats.append({
                "Layers (Module %)": df.loc[idx, "Layers (#)"] / total_layers_mod * 100,
                "Params (Module %)": df.loc[idx, "Params (#)"] / total_params_mod * 100,
                "Trainable Params (Module %)": df.loc[idx, "Trainable Params (#)"] / total_trainable_mod * 100 if total_trainable_mod > 0 else 0,
                "Cumulative Layers (Module)": sub["Layers (#)"][::-1].cumsum()[::-1].loc[idx],
                "Cumulative % Layers (Module)": sub["Layers (#)"][::-1].cumsum()[::-1].loc[idx] / total_layers_mod * 100,
                "Cumulative Params (Module)": sub["Params (#)"][::-1].cumsum()[::-1].loc[idx],
                "Cumulative % Params (Module)": sub["Params (#)"][::-1].cumsum()[::-1].loc[idx] / total_params_mod * 100,
            })
    module_df = pd.DataFrame(module_stats, index=df.index)

    # Combine
    df = pd.concat([df, module_df], axis=1)

    return df

## 3. Model Training

In [37]:
def train_model(model, train_loader, criterion, optimizer, class_names, epoch_num=1, log_interval=100):
    start_time = time.time()  # Start tracking time
    device = torch.device("cuda" if torch.cuda.is_available() else "mps")  # Use GPU if available on Mac

    # Dictionary to store per-class metrics
    class_metrics = defaultdict(lambda: {"correct": 0, "total": 0, "y_true": [], "y_pred": []})

    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    epoch_start_time = time.time()  # Track epoch time

    for batch_idx, (images, labels) in enumerate(train_loader, 1):  # Start index from 1
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        # Compute accuracy
        _, predicted = outputs.max(1)
        correct += (predicted == labels).sum().item()
        total += labels.size(0)
        accuracy = 100 * correct / total

        # Store predictions for per-class metrics
        for label, pred in zip(labels.cpu().numpy(), predicted.cpu().numpy()):
            class_metrics[label]["correct"] += (label == pred)
            class_metrics[label]["total"] += 1
            class_metrics[label]["y_true"].append(label)
            class_metrics[label]["y_pred"].append(pred)

        # Print loss and accuracy every 100 batches
        if batch_idx % log_interval == 0:
            elapsed_time = (time.time() - start_time)/60
            print(f"Epoch {epoch_num}, Batch {batch_idx}, Loss: {running_loss/batch_idx:.4f}, "
                  f"Accuracy: {accuracy:.2f}%, Time Passed: {elapsed_time:.2f}m")

    epoch_time = (time.time() - epoch_start_time)/60
    print(f"Epoch {epoch_num} Completed - Average Loss: {running_loss/len(train_loader):.4f}, "
          f"Accuracy: {accuracy:.2f}%, Epoch Time: {epoch_time:.2f}m")
    overall_accuracy = 100 * correct / total

    total_time = (time.time() - start_time)/60
    print(f"Training Complete Epoch {epoch_num} - Total Time: {total_time:.2f}m")

    # Calculate per-class accuracy, precision, recall, and F1-score
    all_y_true = []
    all_y_pred = []
    
    for class_idx in sorted(class_metrics.keys()):
        all_y_true.extend(class_metrics[class_idx]["y_true"])
        all_y_pred.extend(class_metrics[class_idx]["y_pred"])
    
    # Compute per-class precision, recall, and F1-score
    unique_classes = sorted(set(all_y_true))  # Get all unique classes
    per_class_metrics = {
        "precision": precision_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0),
        "recall": recall_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0),
        "f1_score": f1_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0)
    }

    # Store per-class results in alignment with unique_classes
    class_results = []
    for class_idx in unique_classes:
        class_results.append([
            class_names[class_idx],
            per_class_metrics["precision"][unique_classes.index(class_idx)]*100,
            per_class_metrics["recall"][unique_classes.index(class_idx)]*100,
            per_class_metrics["f1_score"][unique_classes.index(class_idx)]*100
        ])

    # Create a DataFrame with per-class accuracy, precision, recall, and F1-score
    df_results = pd.DataFrame(class_results, columns=["Species", "Precision", "Recall", "F1-score"])

    # Append overall metrics (Macro) as the last row
    macro_precision = per_class_metrics["precision"].mean()*100
    macro_recall = per_class_metrics["recall"].mean()*100
    macro_f1 = per_class_metrics["f1_score"].mean()*100

    df_results.loc[len(df_results)] = ["Average Performance (Macro)", macro_precision, macro_recall, macro_f1]

    df_results['Epoch'] = epoch_num
    avg_loss = running_loss / len(train_loader)

    return {
    'model': model,
    'optimizer': optimizer,
    'metrics_df': df_results,
    'overall_accuracy': overall_accuracy,
    'total_loss': running_loss,
    'avg_loss': avg_loss,
    'epoch_time': epoch_time
            }

## 4. Model Evaluation

In [38]:
def evaluate_model(model, val_loader, criterion, class_names, epoch_num=1, log_interval=100):
    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "mps")
    
    start_time = time.time()  # Track evaluation time

    # Dictionary to store per-class metrics
    class_metrics = defaultdict(lambda: {"correct": 0, "total": 0, "y_true": [], "y_pred": []})
    all_y_true = []
    all_y_pred = []
    correct = 0
    total = 0
    running_loss = 0.0

    with torch.no_grad():
        for batch_idx, (images, labels) in enumerate(val_loader, 1):  # Start index from 1
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)

            # Compute loss
            loss = criterion(outputs, labels)
            running_loss += loss.item()
            
            _, preds = torch.max(outputs, 1)

            all_y_true.extend(labels.cpu().numpy())
            all_y_pred.extend(preds.cpu().numpy())

            # Compute accuracy
            correct += (preds == labels).sum().item()
            total += labels.size(0)
            accuracy = 100 * correct / total

            # Store per-class metrics
            for label, pred in zip(labels.cpu().numpy(), preds.cpu().numpy()):
                class_metrics[label]["correct"] += (label == pred)
                class_metrics[label]["total"] += 1
                class_metrics[label]["y_true"].append(label)
                class_metrics[label]["y_pred"].append(pred)

            # Print progress every 100 batches
            if batch_idx % log_interval == 0:
                elapsed_time = (time.time() - start_time)/60
                avg_loss = running_loss / batch_idx
                print(f"Batch {batch_idx}, Loss: {avg_loss:.4f}, "
                      f"Accuracy: {accuracy:.2f}%, Time Passed: {elapsed_time:.2f}m")

    total_time = (time.time() - start_time)/60
    avg_loss = running_loss / len(val_loader)
    print(f"Evaluation Complete - Loss: {avg_loss:.4f}, Accuracy: {accuracy:.2f}%, Total Time: {total_time:.2f}m")
    overall_accuracy = 100 * correct / total

    # Compute per-class accuracy
    class_results = []
    for class_idx in sorted(class_metrics.keys()):
        metrics = class_metrics[class_idx]
        class_results.append([class_names[class_idx]])

    # Compute per-class precision, recall, and F1-score
    unique_classes = sorted(set(all_y_true))  # Get all unique classes
    per_class_metrics = {
        "precision": precision_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0),
        "recall": recall_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0),
        "f1_score": f1_score(all_y_true, all_y_pred, labels=unique_classes, average=None, zero_division=0)
    }

    # Store per-class metrics
    for idx, class_label in enumerate(unique_classes):
        class_results[idx].extend([
            per_class_metrics["precision"][idx],
            per_class_metrics["recall"][idx],
            per_class_metrics["f1_score"][idx]
        ])

    # Create a DataFrame with per-class accuracy, precision, recall, and F1-score
    df_results = pd.DataFrame(class_results, columns=["Species", "Precision", "Recall", "F1-score"])

    # Append overall metrics (Macro) as the last row
    macro_precision = per_class_metrics["precision"].mean()
    macro_recall = per_class_metrics["recall"].mean()
    macro_f1 = per_class_metrics["f1_score"].mean()

    df_results.loc[len(df_results)] = ["Average Performance (Macro)", macro_precision, macro_recall, macro_f1]

    df_results['Epoch'] = epoch_num
    return {
    'metrics_df': df_results,
    'overall_accuracy': overall_accuracy,
    'avg_loss': avg_loss,
    'epoch_time': total_time
            }

## 5. Create performance summary

In [39]:
def create_performance_summary(df, micro_accuracy, avg_loss, model_name, train_val, class_weights, time_taken, epoch):
    # Extract macro metrics from the last row
    
    macro_row = df[df['Species'] == 'Average Performance (Macro)']
    precision_macro = macro_row['Precision'].values[0]
    recall_macro = macro_row['Recall'].values[0]
    f1_macro = macro_row['F1-score'].values[0]


    # Exclude the last row to analyze per-class accuracies
    class_accuracies = df[df['Species'] != 'Average Performance (Macro)'].copy()

    # Identify best and worst class based on accuracy
    best_class = class_accuracies.loc[class_accuracies['F1-score'].idxmax(), 'Species']
    worst_class = class_accuracies.loc[class_accuracies['F1-score'].idxmin(), 'Species']

    # Compute the median accuracy and find the nearest class
    median_f1_macro = class_accuracies['F1-score'].median()
    class_accuracies['Abs_Diff'] = (class_accuracies['F1-score'] - median_f1_macro).abs()
    median_class = class_accuracies.loc[class_accuracies['Abs_Diff'].idxmin(), 'Species']

    # Compute the number of classes above micro and macro accuracy averages
    num_classes_above_f1_macro_avg = (class_accuracies['F1-score'] > f1_macro).sum()
    num_classes_above_f1_macro_median = (class_accuracies['F1-score'] > median_f1_macro).sum()

    # Create the final summary DataFrame
    performance_summary = pd.DataFrame({
        "Model": [model_name],
        "Train & Validation": [train_val],
        "Accuracy (micro)": [micro_accuracy],
        "Precision (macro)": [precision_macro],
        "Recall (macro)": [recall_macro],
        "F1 (macro)": [f1_macro],
        "Loss": [avg_loss],
        "Class_weights": [class_weights],
        "Best_class": [best_class],
        "Median_class": [median_class],
        "Worst_class": [worst_class],
        "num_classes_above_f1_macro_avg": [num_classes_above_f1_macro_avg],
        "num_classes_above_f1_macro_median": [num_classes_above_f1_macro_median],
        "Time Taken (mins)": [time_taken],
        "Epoch": [epoch]
    })


    return performance_summary

## 6. Model Training & Evaluation Loop

In [40]:
def train_and_evaluate_model(
    model: nn.Module,
    train_loader,
    val_loader,
    criterion,
    optimizer,
    class_names,
    start_epoch: int,
    end_epoch: int,
    model_name: str,
    save_dir: str,
    class_weights: str,
    log_interval: int,
    evaluate = True
):
    """
    Train and evaluate a model, storing per-epoch metrics, summaries, and states.

    Returns:
        dict: {
            'epoch_states': {epoch_num: {'model_state': ..., 'optimizer_state': ..., 'train_metrics': ..., 'val_metrics': ...}},
            'train_results_df': pd.DataFrame,
            'train_summary_df': pd.DataFrame,
            'val_results_df': pd.DataFrame,
            'val_summary_df': pd.DataFrame
        }
    """
    device = torch.device("mps")
    model.to(device)  # Move model to MPS

    # Initialize storage
    epoch_states = {}
    train_results_list, train_summary_list = [], []
    val_results_list, val_summary_list = [], []


    for epoch in range(start_epoch, end_epoch + 1):
        print(f"\n🚀 Epoch {epoch} - Training Started...\n")
        
        # ---- Training ----
        training_result = train_model(
            model, train_loader, criterion, optimizer, class_names, epoch_num=epoch, log_interval=log_interval
        )
        train_summary = create_performance_summary(
            training_result['metrics_df'],
            training_result['overall_accuracy'],
            training_result['avg_loss'],
            model_name=model_name,
            train_val='Train',
            class_weights=class_weights,
            time_taken=training_result['epoch_time'],
            epoch = epoch
        )
        
        train_results_list.append(training_result['metrics_df'])
        train_summary_list.append(train_summary)
        if evaluate:

            print(f"\n✅ Epoch {epoch} - Training Completed. Starting Evaluation...\n")
    
            # ---- Validation ----
            val_result = evaluate_model(
                model, val_loader, criterion, class_names, epoch_num=epoch, log_interval=log_interval
            )
            val_summary = create_performance_summary(
                val_result['metrics_df'],
                val_result['overall_accuracy'],
                val_result['avg_loss'],
                model_name=model_name,
                train_val='Validation',
                class_weights=class_weights,
                time_taken=val_result['epoch_time'],
                epoch = epoch
            )
    
            val_results_list.append(val_result['metrics_df'])
            val_summary_list.append(val_summary)
            print(f"\n📊 Epoch {epoch} - Evaluation Completed.\n")

        else:
            print(f"\n✅ Epoch {epoch} - Training Completed (No Evaluation).\n")

        # ---- Save model + optimizer state for this epoch ----
        epoch_states[epoch] = {
            'model_state_dict': copy.deepcopy(model.state_dict()),
            'optimizer_state_dict': copy.deepcopy(optimizer.state_dict())
        }

        

    # ---- Combine DataFrames ----
    train_results_df = pd.concat(train_results_list, ignore_index=True)
    train_summary_df = pd.concat(train_summary_list, ignore_index=True)
    if evaluate:
        val_results_df = pd.concat(val_results_list, ignore_index=True)
        val_summary_df = pd.concat(val_summary_list, ignore_index=True)

    else:
        val_results_df, val_summary_df = None, None

    # Optionally save to CSV (you can remove if not needed)
    train_results_df.to_csv(f"{save_dir}/{model_name}_train_results{start_epoch}_{end_epoch}.csv", index=False)
    train_summary_df.to_csv(f"{save_dir}/{model_name}_train_summary{start_epoch}_{end_epoch}.csv", index=False)
    if evaluate:
        val_results_df.to_csv(f"{save_dir}/{model_name}_val_results{start_epoch}_{end_epoch}.csv", index=False)
        val_summary_df.to_csv(f"{save_dir}/{model_name}_val_summary{start_epoch}_{end_epoch}.csv", index=False)

    return epoch_states, {
        'train_results_df': train_results_df,
        'train_summary_df': train_summary_df,
        'val_results_df': val_results_df,
        'val_summary_df': val_summary_df
    }

# <center>**MobileNetV2 staged training**</center>

## **Stage A**

In [42]:
mobilenetv2_stageA = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.DEFAULT)
mobilenetv2_stageA = configure_mobilenetv2_training(mobilenetv2_stageA,
    NUM_CLASSES,
    stage_a = True)
df_summary = summarize_mobilenetv2_blocks(mobilenetv2_stageA)
df_summary

🟢 Stage A → Classifier head is trainable, backbone frozen.
✅ Trainable layers: 2/158 (1.27%)
✅ Trainable params: 42,273/2,266,145 (1.87%)

,Block,Order,Module,Layers (#),Params (#),Trainable Params (#),% Layers (Model),% Params (Model),% Trainable Params (Model),Cumulative Layers (Model),Cumulative % Layers (Model),Cumulative Params (Model),Cumulative % Params (Model),Layers (Module %),Params (Module %),Trainable Params (Module %),Cumulative Layers (Module),Cumulative % Layers (Module),Cumulative Params (Module),Cumulative % Params (Module)
0,Conv2dNormActivation_1,1,features,3,928,0,1.898734,0.040951,0.000000,158,100.000000,2266145,100.000000,1.923077,0.041729,0.0,156,100.000000,2223872,100.000000
1,InvertedResidual_2,2,features,6,896,0,3.797468,0.039539,0.000000,155,98.101266,2265217,99.959049,3.846154,0.040290,0.0,153,98.076923,2222944,99.958271
2,InvertedResidual_3,3,features,9,5136,0,5.696203,0.226640,0.000000,149,94.303797,2264321,99.919511,5.769231,0.230949,0.0,147,94.230769,2222048,99.917981
3,InvertedResidual_4,4,features,9,8832,0,5.696203,0.389737,0.000000,140,88.607595,2259185,99.692870,5.769231,0.397145,0.0,138,88.461538,2216912,99.687032
4,InvertedResidual_5,5,features,9,10000,0,5.696203,0.441278,0.000000,131,82.911392,2250353,99.303134,5.769231,0.449666,0.0,129,82.692308,2208080,99.289887
5,InvertedResidual_6,6,features,9,14848,0,5.696203,0.655210,0.000000,122,77.215190,2240353,98.861856,5.769231,0.667664,0.0,120,76.923077,2198080,98.840221
6,InvertedResidual_7,7,features,9,14848,0,5.696203,0.655210,0.000000,113,71.518987,2225505,98.206646,5.769231,0.667664,0.0,111,71.153846,2183232,98.172557
7,InvertedResidual_8,8,features,9,21056,0,5.696203,0.929155,0.000000,104,65.822785,2210657,97.551436,5.769231,0.946817,0.0,102,65.384615,2168384,97.504892
8,InvertedResidual_9,9,features,9,54272,0,5.696203,2.394904,0.000000,95,60.126582,2189601,96.622281,5.769231,2.440428,0.0,93,59.615385,2147328,96.558075
9,InvertedResidual_10,10,features,9,54272,0,5.696203,2.394904,0.000000,86,54.430380,2135329,94.227377,5.769231,2.440428,0.0,84,53.846154,2093056,94.117647
10,InvertedResidual_11,11,features,9,54272,0,5.696203,2.394904,0.000000,77,48.734177,2081057,91.832473,5.769231,2.440428,0.0,75,48.076923,2038784,91.677219
11,InvertedResidual_12,12,features,9,66624,0,5.696203,2.939971,0.000000,68,43.037975,2026785,89.437569,5.769231,2.995856,0.0,66,42.307692,1984512,89.236791
12,InvertedResidual_13,13,features,9,118272,0,5.696203,5.219084,0.000000,59,37.341772,1960161,86.497598,5.769231,5.318292,0.0,57,36.538462,1917888,86.240935
13,InvertedResidual_14,14,features,9,118272,0,5.696203,5.219084,0.000000,50,31.645570,1841889,81.278515,5.769231,5.318292,0.0,48,30.769231,1799616,80.922643
14,InvertedResidual_15,15,features,9,155264,0,5.696203,6.851459,0.000000,41,25.949367,1723617,76.059431,5.769231,6.981697,0.0,39,25.000000,1681344,75.604351
15,InvertedResidual_16,16,features,9,320000,0,5.696203,14.120897,0.000000,32,20.253165,1568353,69.207972,5.769231,14.389317,0.0,30,19.230769,1526080,68.622655
16,InvertedResidual_17,17,features,9,320000,0,5.696203,14.120897,0.000000,23,14.556962,1248353,55.087075,5.769231,14.389317,0.0,21,13.461538,1206080,54.233337
17,InvertedResidual_18,18,features,9,473920,0,5.696203,20.913048,0.000000,14,8.860759,928353,40.966178,5.769231,21.310579,0.0,12,7.692308,886080,39.844020
18,Conv2dNormActivation_19,19,features,3,412160,0,1.898734,18.187715,0.000000,5,3.164557,454433,20.053130,1.923077,18.533441,0.0,3,1.923077,412160,18.533441
19,Sequential,20,classifier,2,42273,42273,1.265823,1.865415,1.865415,2,1.265823,42273,1.865415,100.000000,100.000000,100.0,2,100.000000,42273,100.000000

In [43]:
inverse_frequency_weights = compute_class_weights(train_dataset, method="inverse_frequency", normalize=False)
inverse_frequency_criterion = nn.CrossEntropyLoss(weight=inverse_frequency_weights)
stageA_optimizer = torch.optim.AdamW(mobilenetv2_stageA.parameters(), lr=1e-3,
                            weight_decay=1e-4, betas=(0.9, 0.999))
display(train_dataset.transform)
val_dataset.transform

Compose(
      ToImage()
      RandomResizedCrop(size=(224, 224), scale=(0.2, 1.0), ratio=(0.75, 1.33), interpolation=InterpolationMode.BILINEAR, antialias=True)
      RandomHorizontalFlip(p=0.5)
      RandomVerticalFlip(p=0.2)
      RandomApply(    RandomRotation(degrees=[-90.0, 90.0], interpolation=InterpolationMode.BILINEAR, expand=False, fill=0))
      ToDtype(scale=True)
      RandomApply(    ColorJitter(brightness=(0.7, 1.3), contrast=(0.85, 1.3), saturation=(0.7, 1.3), hue=(-0.0278, 0.0278)))
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], inplace=False)
)

Compose(
      ToImage()
      Resize(size=[256], interpolation=InterpolationMode.BILINEAR, antialias=True)
      CenterCrop(size=(224, 224))
      ToDtype(scale=True)
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], inplace=False)
)

In [39]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageA, train_loader, val_loader, inverse_frequency_criterion, stageA_optimizer, train_dataset.classes,
                         start_epoch = 1, end_epoch = 5, model_name = 'mobilenetv2_stageA', save_dir = 'mobilenetv2',
                         class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 1 - Training Started...

Epoch 1, Batch 100, Loss: 2.9786, Accuracy: 24.62%, Time Passed: 2.87m
Epoch 1, Batch 200, Loss: 2.5948, Accuracy: 36.22%, Time Passed: 5.87m
Epoch 1, Batch 300, Loss: 2.3455, Accuracy: 42.00%, Time Passed: 8.87m
Epoch 1, Batch 400, Loss: 2.1701, Accuracy: 46.20%, Time Passed: 11.87m
Epoch 1, Batch 500, Loss: 2.0355, Accuracy: 49.11%, Time Passed: 14.91m
Epoch 1 Completed - Average Loss: 1.9867, Accuracy: 50.11%, Epoch Time: 16.18m
Training Complete Epoch 1 - Total Time: 16.18m

✅ Epoch 1 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.8591, Accuracy: 44.31%, Time Passed: 3.71m
Evaluation Complete - Loss: 1.7239, Accuracy: 50.75%, Total Time: 6.65m

📊 Epoch 1 - Evaluation Completed.


🚀 Epoch 2 - Training Started...

Epoch 2, Batch 100, Loss: 1.3919, Accuracy: 61.94%, Time Passed: 3.11m
Epoch 2, Batch 200, Loss: 1.3456, Accuracy: 63.41%, Time Passed: 6.17m
Epoch 2, Batch 300, Loss: 1.3183, Accuracy: 64.14%, Time Passed: 9.23m
Epoch 2, Batch 400, Loss: 1.2930, Accuracy: 64.58%, Time Passed: 12.33m
Epoch 2, Batch 500, Loss: 1.2653, Accuracy: 64.92%, Time Passed: 15.36m
Epoch 2 Completed - Average Loss: 1.2566, Accuracy: 64.98%, Epoch Time: 16.67m
Training Complete Epoch 2 - Total Time: 16.67m

✅ Epoch 2 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.6011, Accuracy: 50.66%, Time Passed: 3.77m
Evaluation Complete - Loss: 1.4711, Accuracy: 56.67%, Total Time: 6.48m

📊 Epoch 2 - Evaluation Completed.


🚀 Epoch 3 - Training Started...

Epoch 3, Batch 100, Loss: 1.1590, Accuracy: 66.06%, Time Passed: 3.13m
Epoch 3, Batch 200, Loss: 1.1225, Accuracy: 66.83%, Time Passed: 6.20m
Epoch 3, Batch 300, Loss: 1.1294, Accuracy: 67.05%, Time Passed: 9.29m
Epoch 3, Batch 400, Loss: 1.1172, Accuracy: 67.42%, Time Passed: 12.35m
Epoch 3, Batch 500, Loss: 1.0995, Accuracy: 67.88%, Time Passed: 15.42m
Epoch 3 Completed - Average Loss: 1.0870, Accuracy: 68.28%, Epoch Time: 16.75m
Training Complete Epoch 3 - Total Time: 16.75m

✅ Epoch 3 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.5805, Accuracy: 50.44%, Time Passed: 3.83m
Evaluation Complete - Loss: 1.4629, Accuracy: 56.25%, Total Time: 6.58m

📊 Epoch 3 - Evaluation Completed.


🚀 Epoch 4 - Training Started...

Epoch 4, Batch 100, Loss: 0.9992, Accuracy: 70.78%, Time Passed: 3.15m
Epoch 4, Batch 200, Loss: 0.9918, Accuracy: 70.83%, Time Passed: 6.28m
Epoch 4, Batch 300, Loss: 1.0056, Accuracy: 70.45%, Time Passed: 9.46m
Epoch 4, Batch 400, Loss: 0.9986, Accuracy: 70.45%, Time Passed: 12.65m
Epoch 4, Batch 500, Loss: 0.9967, Accuracy: 70.54%, Time Passed: 15.83m
Epoch 4 Completed - Average Loss: 0.9924, Accuracy: 70.59%, Epoch Time: 17.18m
Training Complete Epoch 4 - Total Time: 17.18m

✅ Epoch 4 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.4811, Accuracy: 53.72%, Time Passed: 3.94m
Evaluation Complete - Loss: 1.3826, Accuracy: 57.87%, Total Time: 6.64m

📊 Epoch 4 - Evaluation Completed.


🚀 Epoch 5 - Training Started...

Epoch 5, Batch 100, Loss: 0.9363, Accuracy: 72.75%, Time Passed: 3.05m
Epoch 5, Batch 200, Loss: 0.9469, Accuracy: 72.45%, Time Passed: 6.08m
Epoch 5, Batch 300, Loss: 0.9302, Accuracy: 72.71%, Time Passed: 9.17m
Epoch 5, Batch 400, Loss: 0.9335, Accuracy: 72.47%, Time Passed: 12.23m
Epoch 5, Batch 500, Loss: 0.9315, Accuracy: 72.25%, Time Passed: 15.30m
Epoch 5 Completed - Average Loss: 0.9262, Accuracy: 72.36%, Epoch Time: 16.61m
Training Complete Epoch 5 - Total Time: 16.61m

✅ Epoch 5 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.4715, Accuracy: 55.84%, Time Passed: 3.86m
Evaluation Complete - Loss: 1.2901, Accuracy: 61.60%, Total Time: 6.61m

📊 Epoch 5 - Evaluation Completed.

In [40]:
start_epoch = 1
end_epoch = 5

In [41]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [42]:
del training_states

In [45]:
start_epoch = 6
end_epoch = 10
start_epoch, end_epoch

(6, 10)

In [46]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageA, train_loader, val_loader, inverse_frequency_criterion, stageA_optimizer, train_dataset.classes,
                         start_epoch = start_epoch, end_epoch = end_epoch, model_name = 'mobilenetv2_stageA', save_dir = 'mobilenetv2',
                         class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 6 - Training Started...

Epoch 6, Batch 100, Loss: 0.9055, Accuracy: 71.47%, Time Passed: 2.88m
Epoch 6, Batch 200, Loss: 0.9044, Accuracy: 72.17%, Time Passed: 5.96m
Epoch 6, Batch 300, Loss: 0.9023, Accuracy: 72.15%, Time Passed: 9.18m
Epoch 6, Batch 400, Loss: 0.9054, Accuracy: 72.05%, Time Passed: 12.39m
Epoch 6, Batch 500, Loss: 0.9067, Accuracy: 72.06%, Time Passed: 15.65m
Epoch 6 Completed - Average Loss: 0.9035, Accuracy: 72.16%, Epoch Time: 17.08m
Training Complete Epoch 6 - Total Time: 17.08m

✅ Epoch 6 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.4349, Accuracy: 55.66%, Time Passed: 4.49m
Evaluation Complete - Loss: 1.2934, Accuracy: 60.77%, Total Time: 8.03m

📊 Epoch 6 - Evaluation Completed.


🚀 Epoch 7 - Training Started...

Epoch 7, Batch 100, Loss: 0.9111, Accuracy: 72.28%, Time Passed: 4.07m
Epoch 7, Batch 200, Loss: 0.8960, Accuracy: 72.17%, Time Passed: 8.02m
Epoch 7, Batch 300, Loss: 0.8808, Accuracy: 72.42%, Time Passed: 11.87m
Epoch 7, Batch 400, Loss: 0.8753, Accuracy: 72.51%, Time Passed: 15.90m
Epoch 7, Batch 500, Loss: 0.8736, Accuracy: 72.39%, Time Passed: 19.58m
Epoch 7 Completed - Average Loss: 0.8685, Accuracy: 72.43%, Epoch Time: 21.07m
Training Complete Epoch 7 - Total Time: 21.07m

✅ Epoch 7 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.3969, Accuracy: 56.59%, Time Passed: 4.55m
Evaluation Complete - Loss: 1.2449, Accuracy: 62.27%, Total Time: 7.77m

📊 Epoch 7 - Evaluation Completed.


🚀 Epoch 8 - Training Started...

Epoch 8, Batch 100, Loss: 0.8241, Accuracy: 73.28%, Time Passed: 3.60m
Epoch 8, Batch 200, Loss: 0.8405, Accuracy: 73.44%, Time Passed: 6.96m
Epoch 8, Batch 300, Loss: 0.8442, Accuracy: 73.19%, Time Passed: 10.42m
Epoch 8, Batch 400, Loss: 0.8414, Accuracy: 73.17%, Time Passed: 14.11m
Epoch 8, Batch 500, Loss: 0.8349, Accuracy: 73.31%, Time Passed: 17.75m
Epoch 8 Completed - Average Loss: 0.8381, Accuracy: 73.32%, Epoch Time: 19.21m
Training Complete Epoch 8 - Total Time: 19.21m

✅ Epoch 8 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.3697, Accuracy: 57.41%, Time Passed: 4.43m
Evaluation Complete - Loss: 1.2217, Accuracy: 62.85%, Total Time: 7.54m

📊 Epoch 8 - Evaluation Completed.


🚀 Epoch 9 - Training Started...

Epoch 9, Batch 100, Loss: 0.8014, Accuracy: 74.81%, Time Passed: 3.58m
Epoch 9, Batch 200, Loss: 0.8049, Accuracy: 74.69%, Time Passed: 7.17m
Epoch 9, Batch 300, Loss: 0.8107, Accuracy: 74.48%, Time Passed: 10.77m
Epoch 9, Batch 400, Loss: 0.8177, Accuracy: 74.07%, Time Passed: 14.44m
Epoch 9, Batch 500, Loss: 0.8233, Accuracy: 74.01%, Time Passed: 18.09m
Epoch 9 Completed - Average Loss: 0.8219, Accuracy: 74.06%, Epoch Time: 19.60m
Training Complete Epoch 9 - Total Time: 19.60m

✅ Epoch 9 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.3618, Accuracy: 57.81%, Time Passed: 4.51m
Evaluation Complete - Loss: 1.2352, Accuracy: 62.38%, Total Time: 7.55m

📊 Epoch 9 - Evaluation Completed.


🚀 Epoch 10 - Training Started...

Epoch 10, Batch 100, Loss: 0.8231, Accuracy: 74.38%, Time Passed: 3.57m
Epoch 10, Batch 200, Loss: 0.8186, Accuracy: 74.31%, Time Passed: 7.33m
Epoch 10, Batch 300, Loss: 0.8196, Accuracy: 73.98%, Time Passed: 11.03m
Epoch 10, Batch 400, Loss: 0.8255, Accuracy: 74.01%, Time Passed: 14.78m
Epoch 10, Batch 500, Loss: 0.8228, Accuracy: 74.08%, Time Passed: 18.52m
Epoch 10 Completed - Average Loss: 0.8209, Accuracy: 74.06%, Epoch Time: 20.04m
Training Complete Epoch 10 - Total Time: 20.04m

✅ Epoch 10 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.3274, Accuracy: 59.53%, Time Passed: 4.43m
Evaluation Complete - Loss: 1.1726, Accuracy: 64.35%, Total Time: 7.45m

📊 Epoch 10 - Evaluation Completed.

In [49]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [52]:
del training_states

In [53]:
start_epoch = 11
end_epoch = 20
start_epoch, end_epoch

(11, 20)

In [54]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageA, train_loader, val_loader, inverse_frequency_criterion, stageA_optimizer, train_dataset.classes,
                         start_epoch = start_epoch, end_epoch = end_epoch, model_name = 'mobilenetv2_stageA', save_dir = 'mobilenetv2',
                         class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 11 - Training Started...

Epoch 11, Batch 100, Loss: 0.7804, Accuracy: 74.62%, Time Passed: 3.20m
Epoch 11, Batch 200, Loss: 0.8043, Accuracy: 74.05%, Time Passed: 6.42m
Epoch 11, Batch 300, Loss: 0.8107, Accuracy: 73.97%, Time Passed: 10.14m
Epoch 11, Batch 400, Loss: 0.8074, Accuracy: 74.05%, Time Passed: 13.33m
Epoch 11, Batch 500, Loss: 0.7952, Accuracy: 74.28%, Time Passed: 16.55m
Epoch 11 Completed - Average Loss: 0.7952, Accuracy: 74.30%, Epoch Time: 17.83m
Training Complete Epoch 11 - Total Time: 17.83m

✅ Epoch 11 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.3170, Accuracy: 59.59%, Time Passed: 4.02m
Evaluation Complete - Loss: 1.1785, Accuracy: 64.25%, Total Time: 7.10m

📊 Epoch 11 - Evaluation Completed.


🚀 Epoch 12 - Training Started...

Epoch 12, Batch 100, Loss: 0.7754, Accuracy: 75.25%, Time Passed: 3.73m
Epoch 12, Batch 200, Loss: 0.7696, Accuracy: 75.45%, Time Passed: 7.91m
Epoch 12, Batch 300, Loss: 0.7790, Accuracy: 75.07%, Time Passed: 11.78m
Epoch 12, Batch 400, Loss: 0.7860, Accuracy: 74.80%, Time Passed: 15.72m
Epoch 12, Batch 500, Loss: 0.7808, Accuracy: 74.96%, Time Passed: 19.65m
Epoch 12 Completed - Average Loss: 0.7733, Accuracy: 75.18%, Epoch Time: 21.28m
Training Complete Epoch 12 - Total Time: 21.28m

✅ Epoch 12 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.3543, Accuracy: 58.53%, Time Passed: 4.83m
Evaluation Complete - Loss: 1.1955, Accuracy: 64.33%, Total Time: 8.13m

📊 Epoch 12 - Evaluation Completed.


🚀 Epoch 13 - Training Started...

Epoch 13, Batch 100, Loss: 0.7725, Accuracy: 75.66%, Time Passed: 3.79m
Epoch 13, Batch 200, Loss: 0.7847, Accuracy: 75.00%, Time Passed: 7.76m
Epoch 13, Batch 300, Loss: 0.7773, Accuracy: 74.85%, Time Passed: 11.74m
Epoch 13, Batch 400, Loss: 0.7742, Accuracy: 74.92%, Time Passed: 15.86m
Epoch 13, Batch 500, Loss: 0.7733, Accuracy: 74.95%, Time Passed: 19.94m
Epoch 13 Completed - Average Loss: 0.7717, Accuracy: 74.92%, Epoch Time: 21.61m
Training Complete Epoch 13 - Total Time: 21.61m

✅ Epoch 13 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.4104, Accuracy: 56.81%, Time Passed: 5.01m
Evaluation Complete - Loss: 1.2176, Accuracy: 63.38%, Total Time: 8.37m

📊 Epoch 13 - Evaluation Completed.


🚀 Epoch 14 - Training Started...

Epoch 14, Batch 100, Loss: 0.7762, Accuracy: 74.59%, Time Passed: 4.14m
Epoch 14, Batch 200, Loss: 0.7666, Accuracy: 74.91%, Time Passed: 8.41m
Epoch 14, Batch 300, Loss: 0.7624, Accuracy: 75.15%, Time Passed: 12.58m
Epoch 14, Batch 400, Loss: 0.7596, Accuracy: 75.05%, Time Passed: 16.75m
Epoch 14, Batch 500, Loss: 0.7612, Accuracy: 75.05%, Time Passed: 20.91m
Epoch 14 Completed - Average Loss: 0.7582, Accuracy: 75.13%, Epoch Time: 22.66m
Training Complete Epoch 14 - Total Time: 22.66m

✅ Epoch 14 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.4166, Accuracy: 56.91%, Time Passed: 5.29m
Evaluation Complete - Loss: 1.2762, Accuracy: 62.31%, Total Time: 8.85m

📊 Epoch 14 - Evaluation Completed.


🚀 Epoch 15 - Training Started...

Epoch 15, Batch 100, Loss: 0.7534, Accuracy: 75.75%, Time Passed: 4.05m
Epoch 15, Batch 200, Loss: 0.7378, Accuracy: 75.86%, Time Passed: 8.13m
Epoch 15, Batch 300, Loss: 0.7426, Accuracy: 75.51%, Time Passed: 12.30m
Epoch 15, Batch 400, Loss: 0.7456, Accuracy: 75.59%, Time Passed: 16.42m
Epoch 15, Batch 500, Loss: 0.7486, Accuracy: 75.54%, Time Passed: 20.52m
Epoch 15 Completed - Average Loss: 0.7479, Accuracy: 75.46%, Epoch Time: 22.19m
Training Complete Epoch 15 - Total Time: 22.19m

✅ Epoch 15 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.3438, Accuracy: 59.09%, Time Passed: 4.88m
Evaluation Complete - Loss: 1.1815, Accuracy: 64.38%, Total Time: 8.13m

📊 Epoch 15 - Evaluation Completed.


🚀 Epoch 16 - Training Started...

Epoch 16, Batch 100, Loss: 0.7156, Accuracy: 75.94%, Time Passed: 3.84m
Epoch 16, Batch 200, Loss: 0.7334, Accuracy: 76.06%, Time Passed: 7.80m
Epoch 16, Batch 300, Loss: 0.7296, Accuracy: 76.32%, Time Passed: 11.84m
Epoch 16, Batch 400, Loss: 0.7373, Accuracy: 76.12%, Time Passed: 15.94m
Epoch 16, Batch 500, Loss: 0.7460, Accuracy: 75.72%, Time Passed: 19.92m
Epoch 16 Completed - Average Loss: 0.7536, Accuracy: 75.58%, Epoch Time: 21.54m
Training Complete Epoch 16 - Total Time: 21.54m

✅ Epoch 16 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.3405, Accuracy: 60.22%, Time Passed: 4.77m
Evaluation Complete - Loss: 1.1875, Accuracy: 65.00%, Total Time: 8.05m

📊 Epoch 16 - Evaluation Completed.


🚀 Epoch 17 - Training Started...

Epoch 17, Batch 100, Loss: 0.7268, Accuracy: 75.03%, Time Passed: 3.87m
Epoch 17, Batch 200, Loss: 0.7492, Accuracy: 74.20%, Time Passed: 7.80m
Epoch 17, Batch 300, Loss: 0.7505, Accuracy: 74.83%, Time Passed: 11.98m
Epoch 17, Batch 400, Loss: 0.7484, Accuracy: 74.96%, Time Passed: 15.80m
Epoch 17, Batch 500, Loss: 0.7485, Accuracy: 74.92%, Time Passed: 19.56m
Epoch 17 Completed - Average Loss: 0.7509, Accuracy: 74.93%, Epoch Time: 21.09m
Training Complete Epoch 17 - Total Time: 21.09m

✅ Epoch 17 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.3491, Accuracy: 58.94%, Time Passed: 4.56m
Evaluation Complete - Loss: 1.1934, Accuracy: 64.08%, Total Time: 7.73m

📊 Epoch 17 - Evaluation Completed.


🚀 Epoch 18 - Training Started...

Epoch 18, Batch 100, Loss: 0.7349, Accuracy: 76.00%, Time Passed: 3.67m
Epoch 18, Batch 200, Loss: 0.7335, Accuracy: 76.42%, Time Passed: 7.55m
Epoch 18, Batch 300, Loss: 0.7420, Accuracy: 75.99%, Time Passed: 11.33m
Epoch 18, Batch 400, Loss: 0.7420, Accuracy: 76.05%, Time Passed: 15.05m
Epoch 18, Batch 500, Loss: 0.7473, Accuracy: 75.96%, Time Passed: 18.83m
Epoch 18 Completed - Average Loss: 0.7445, Accuracy: 76.02%, Epoch Time: 20.39m
Training Complete Epoch 18 - Total Time: 20.39m

✅ Epoch 18 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.2895, Accuracy: 60.78%, Time Passed: 4.91m
Evaluation Complete - Loss: 1.1875, Accuracy: 64.63%, Total Time: 8.32m

📊 Epoch 18 - Evaluation Completed.


🚀 Epoch 19 - Training Started...

Epoch 19, Batch 100, Loss: 0.7639, Accuracy: 75.38%, Time Passed: 3.98m
Epoch 19, Batch 200, Loss: 0.7472, Accuracy: 75.33%, Time Passed: 7.86m
Epoch 19, Batch 300, Loss: 0.7292, Accuracy: 75.95%, Time Passed: 11.75m
Epoch 19, Batch 400, Loss: 0.7304, Accuracy: 75.84%, Time Passed: 15.53m
Epoch 19, Batch 500, Loss: 0.7307, Accuracy: 75.79%, Time Passed: 19.23m
Epoch 19 Completed - Average Loss: 0.7256, Accuracy: 75.84%, Epoch Time: 20.76m
Training Complete Epoch 19 - Total Time: 20.76m

✅ Epoch 19 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.3927, Accuracy: 58.72%, Time Passed: 4.48m
Evaluation Complete - Loss: 1.2172, Accuracy: 64.42%, Total Time: 7.56m

📊 Epoch 19 - Evaluation Completed.


🚀 Epoch 20 - Training Started...

Epoch 20, Batch 100, Loss: 0.7267, Accuracy: 76.25%, Time Passed: 3.54m
Epoch 20, Batch 200, Loss: 0.7237, Accuracy: 76.11%, Time Passed: 7.19m
Epoch 20, Batch 300, Loss: 0.7370, Accuracy: 75.73%, Time Passed: 10.78m
Epoch 20, Batch 400, Loss: 0.7316, Accuracy: 75.80%, Time Passed: 14.60m
Epoch 20, Batch 500, Loss: 0.7391, Accuracy: 75.62%, Time Passed: 18.35m
Epoch 20 Completed - Average Loss: 0.7384, Accuracy: 75.52%, Epoch Time: 19.90m
Training Complete Epoch 20 - Total Time: 19.90m

✅ Epoch 20 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.3040, Accuracy: 59.81%, Time Passed: 4.59m
Evaluation Complete - Loss: 1.1793, Accuracy: 64.56%, Total Time: 7.66m

📊 Epoch 20 - Evaluation Completed.

In [55]:
start_epoch, end_epoch

(11, 20)

In [56]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [57]:
del training_states

## **Stage B**

In [58]:
mobilenetv2_stageB = configure_mobilenetv2_training(
                                                    mobilenetv2_stageA,
                                                    NUM_CLASSES, intermediate=True,
                                                    intermediate_blocks = [0, 2]
                                                   )
df_summary = summarize_mobilenetv2_blocks(mobilenetv2_stageB)
df_summary

🟢 Intermediate stage → Newly unfrozen blocks: [17, 18]
✅ Trainable layers: 14/158 (8.86%)
✅ Trainable params: 928,353/2,266,145 (40.97%)

,Block,Order,Module,Layers (#),Params (#),Trainable Params (#),% Layers (Model),% Params (Model),% Trainable Params (Model),Cumulative Layers (Model),Cumulative % Layers (Model),Cumulative Params (Model),Cumulative % Params (Model),Layers (Module %),Params (Module %),Trainable Params (Module %),Cumulative Layers (Module),Cumulative % Layers (Module),Cumulative Params (Module),Cumulative % Params (Module)
0,Conv2dNormActivation_1,1,features,3,928,0,1.898734,0.040951,0.000000,158,100.000000,2266145,100.000000,1.923077,0.041729,0.000000,156,100.000000,2223872,100.000000
1,InvertedResidual_2,2,features,6,896,0,3.797468,0.039539,0.000000,155,98.101266,2265217,99.959049,3.846154,0.040290,0.000000,153,98.076923,2222944,99.958271
2,InvertedResidual_3,3,features,9,5136,0,5.696203,0.226640,0.000000,149,94.303797,2264321,99.919511,5.769231,0.230949,0.000000,147,94.230769,2222048,99.917981
3,InvertedResidual_4,4,features,9,8832,0,5.696203,0.389737,0.000000,140,88.607595,2259185,99.692870,5.769231,0.397145,0.000000,138,88.461538,2216912,99.687032
4,InvertedResidual_5,5,features,9,10000,0,5.696203,0.441278,0.000000,131,82.911392,2250353,99.303134,5.769231,0.449666,0.000000,129,82.692308,2208080,99.289887
5,InvertedResidual_6,6,features,9,14848,0,5.696203,0.655210,0.000000,122,77.215190,2240353,98.861856,5.769231,0.667664,0.000000,120,76.923077,2198080,98.840221
6,InvertedResidual_7,7,features,9,14848,0,5.696203,0.655210,0.000000,113,71.518987,2225505,98.206646,5.769231,0.667664,0.000000,111,71.153846,2183232,98.172557
7,InvertedResidual_8,8,features,9,21056,0,5.696203,0.929155,0.000000,104,65.822785,2210657,97.551436,5.769231,0.946817,0.000000,102,65.384615,2168384,97.504892
8,InvertedResidual_9,9,features,9,54272,0,5.696203,2.394904,0.000000,95,60.126582,2189601,96.622281,5.769231,2.440428,0.000000,93,59.615385,2147328,96.558075
9,InvertedResidual_10,10,features,9,54272,0,5.696203,2.394904,0.000000,86,54.430380,2135329,94.227377,5.769231,2.440428,0.000000,84,53.846154,2093056,94.117647
10,InvertedResidual_11,11,features,9,54272,0,5.696203,2.394904,0.000000,77,48.734177,2081057,91.832473,5.769231,2.440428,0.000000,75,48.076923,2038784,91.677219
11,InvertedResidual_12,12,features,9,66624,0,5.696203,2.939971,0.000000,68,43.037975,2026785,89.437569,5.769231,2.995856,0.000000,66,42.307692,1984512,89.236791
12,InvertedResidual_13,13,features,9,118272,0,5.696203,5.219084,0.000000,59,37.341772,1960161,86.497598,5.769231,5.318292,0.000000,57,36.538462,1917888,86.240935
13,InvertedResidual_14,14,features,9,118272,0,5.696203,5.219084,0.000000,50,31.645570,1841889,81.278515,5.769231,5.318292,0.000000,48,30.769231,1799616,80.922643
14,InvertedResidual_15,15,features,9,155264,0,5.696203,6.851459,0.000000,41,25.949367,1723617,76.059431,5.769231,6.981697,0.000000,39,25.000000,1681344,75.604351
15,InvertedResidual_16,16,features,9,320000,0,5.696203,14.120897,0.000000,32,20.253165,1568353,69.207972,5.769231,14.389317,0.000000,30,19.230769,1526080,68.622655
16,InvertedResidual_17,17,features,9,320000,0,5.696203,14.120897,0.000000,23,14.556962,1248353,55.087075,5.769231,14.389317,0.000000,21,13.461538,1206080,54.233337
17,InvertedResidual_18,18,features,9,473920,473920,5.696203,20.913048,20.913048,14,8.860759,928353,40.966178,5.769231,21.310579,53.485013,12,7.692308,886080,39.844020
18,Conv2dNormActivation_19,19,features,3,412160,412160,1.898734,18.187715,18.187715,5,3.164557,454433,20.053130,1.923077,18.533441,46.514987,3,1.923077,412160,18.533441
19,Sequential,20,classifier,2,42273,42273,1.265823,1.865415,1.865415,2,1.265823,42273,1.865415,100.000000,100.000000,100.000000,2,100.000000,42273,100.000000

In [46]:
stageB_optimizer = torch.optim.AdamW(mobilenetv2_stageB.parameters(), lr=1e-4,
                            weight_decay=1e-4, betas=(0.9, 0.999))

In [60]:
start_epoch = 21
end_epoch = 25
start_epoch, end_epoch

(21, 25)

In [61]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageB, train_loader, val_loader, inverse_frequency_criterion, stageB_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageB', save_dir = 'mobilenetv2',
                         class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 21 - Training Started...

Epoch 21, Batch 100, Loss: 0.6929, Accuracy: 77.09%, Time Passed: 2.96m
Epoch 21, Batch 200, Loss: 0.6839, Accuracy: 76.98%, Time Passed: 6.03m
Epoch 21, Batch 300, Loss: 0.6725, Accuracy: 77.69%, Time Passed: 9.20m
Epoch 21, Batch 400, Loss: 0.6658, Accuracy: 77.76%, Time Passed: 12.35m
Epoch 21, Batch 500, Loss: 0.6623, Accuracy: 77.83%, Time Passed: 15.62m
Epoch 21 Completed - Average Loss: 0.6580, Accuracy: 78.05%, Epoch Time: 17.01m
Training Complete Epoch 21 - Total Time: 17.01m

✅ Epoch 21 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.2619, Accuracy: 62.09%, Time Passed: 3.99m
Evaluation Complete - Loss: 1.1210, Accuracy: 66.79%, Total Time: 6.84m

📊 Epoch 21 - Evaluation Completed.


🚀 Epoch 22 - Training Started...

Epoch 22, Batch 100, Loss: 0.6043, Accuracy: 79.84%, Time Passed: 3.45m
Epoch 22, Batch 200, Loss: 0.5884, Accuracy: 80.45%, Time Passed: 7.20m
Epoch 22, Batch 300, Loss: 0.5781, Accuracy: 80.65%, Time Passed: 10.97m
Epoch 22, Batch 400, Loss: 0.5775, Accuracy: 80.78%, Time Passed: 14.78m
Epoch 22, Batch 500, Loss: 0.5723, Accuracy: 80.89%, Time Passed: 18.59m
Epoch 22 Completed - Average Loss: 0.5704, Accuracy: 80.95%, Epoch Time: 20.21m
Training Complete Epoch 22 - Total Time: 20.21m

✅ Epoch 22 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.2520, Accuracy: 62.94%, Time Passed: 4.56m
Evaluation Complete - Loss: 1.0781, Accuracy: 68.44%, Total Time: 7.61m

📊 Epoch 22 - Evaluation Completed.


🚀 Epoch 23 - Training Started...

Epoch 23, Batch 100, Loss: 0.5576, Accuracy: 81.38%, Time Passed: 3.65m
Epoch 23, Batch 200, Loss: 0.5248, Accuracy: 82.48%, Time Passed: 7.50m
Epoch 23, Batch 300, Loss: 0.5137, Accuracy: 83.05%, Time Passed: 11.39m
Epoch 23, Batch 400, Loss: 0.5092, Accuracy: 83.25%, Time Passed: 15.25m
Epoch 23, Batch 500, Loss: 0.5089, Accuracy: 83.16%, Time Passed: 19.06m
Epoch 23 Completed - Average Loss: 0.5063, Accuracy: 83.28%, Epoch Time: 20.72m
Training Complete Epoch 23 - Total Time: 20.72m

✅ Epoch 23 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.1452, Accuracy: 66.56%, Time Passed: 4.98m
Evaluation Complete - Loss: 1.0221, Accuracy: 70.54%, Total Time: 8.47m

📊 Epoch 23 - Evaluation Completed.


🚀 Epoch 24 - Training Started...

Epoch 24, Batch 100, Loss: 0.5203, Accuracy: 82.56%, Time Passed: 4.01m
Epoch 24, Batch 200, Loss: 0.4828, Accuracy: 83.28%, Time Passed: 8.10m
Epoch 24, Batch 300, Loss: 0.4814, Accuracy: 83.36%, Time Passed: 12.17m
Epoch 24, Batch 400, Loss: 0.4798, Accuracy: 83.66%, Time Passed: 16.35m
Epoch 24, Batch 500, Loss: 0.4717, Accuracy: 83.81%, Time Passed: 20.58m
Epoch 24 Completed - Average Loss: 0.4713, Accuracy: 83.87%, Epoch Time: 22.33m
Training Complete Epoch 24 - Total Time: 22.33m

✅ Epoch 24 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.1081, Accuracy: 67.62%, Time Passed: 5.04m
Evaluation Complete - Loss: 0.9513, Accuracy: 72.27%, Total Time: 8.42m

📊 Epoch 24 - Evaluation Completed.


🚀 Epoch 25 - Training Started...

Epoch 25, Batch 100, Loss: 0.4500, Accuracy: 84.69%, Time Passed: 3.98m
Epoch 25, Batch 200, Loss: 0.4343, Accuracy: 85.02%, Time Passed: 8.15m
Epoch 25, Batch 300, Loss: 0.4371, Accuracy: 85.04%, Time Passed: 12.29m
Epoch 25, Batch 400, Loss: 0.4378, Accuracy: 85.05%, Time Passed: 16.29m
Epoch 25, Batch 500, Loss: 0.4378, Accuracy: 85.00%, Time Passed: 20.19m
Epoch 25 Completed - Average Loss: 0.4370, Accuracy: 85.00%, Epoch Time: 21.69m
Training Complete Epoch 25 - Total Time: 21.69m

✅ Epoch 25 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.1376, Accuracy: 67.22%, Time Passed: 4.74m
Evaluation Complete - Loss: 0.9864, Accuracy: 71.85%, Total Time: 7.93m

📊 Epoch 25 - Evaluation Completed.

In [62]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [63]:
del training_states

In [64]:
start_epoch = 26
end_epoch = 31
start_epoch, end_epoch

(26, 31)

In [65]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageB, train_loader, val_loader, inverse_frequency_criterion, stageB_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageB', save_dir = 'mobilenetv2',
                         class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 26 - Training Started...

Epoch 26, Batch 100, Loss: 0.3965, Accuracy: 86.25%, Time Passed: 3.47m
Epoch 26, Batch 200, Loss: 0.3977, Accuracy: 86.34%, Time Passed: 6.82m
Epoch 26, Batch 300, Loss: 0.4017, Accuracy: 86.11%, Time Passed: 10.35m
Epoch 26, Batch 400, Loss: 0.4015, Accuracy: 85.95%, Time Passed: 14.09m
Epoch 26, Batch 500, Loss: 0.4003, Accuracy: 85.94%, Time Passed: 17.66m
Epoch 26 Completed - Average Loss: 0.4037, Accuracy: 85.75%, Epoch Time: 19.14m
Training Complete Epoch 26 - Total Time: 19.14m

✅ Epoch 26 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.1000, Accuracy: 67.69%, Time Passed: 4.72m
Evaluation Complete - Loss: 0.9549, Accuracy: 72.46%, Total Time: 7.92m

📊 Epoch 26 - Evaluation Completed.


🚀 Epoch 27 - Training Started...

Epoch 27, Batch 100, Loss: 0.3599, Accuracy: 86.78%, Time Passed: 3.67m
Epoch 27, Batch 200, Loss: 0.3541, Accuracy: 87.38%, Time Passed: 7.10m
Epoch 27, Batch 300, Loss: 0.3687, Accuracy: 87.01%, Time Passed: 10.76m
Epoch 27, Batch 400, Loss: 0.3795, Accuracy: 86.63%, Time Passed: 14.60m
Epoch 27, Batch 500, Loss: 0.3818, Accuracy: 86.59%, Time Passed: 18.34m
Epoch 27 Completed - Average Loss: 0.3811, Accuracy: 86.71%, Epoch Time: 19.96m
Training Complete Epoch 27 - Total Time: 19.96m

✅ Epoch 27 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.0823, Accuracy: 68.00%, Time Passed: 4.46m
Evaluation Complete - Loss: 0.9631, Accuracy: 72.44%, Total Time: 7.52m

📊 Epoch 27 - Evaluation Completed.


🚀 Epoch 28 - Training Started...

Epoch 28, Batch 100, Loss: 0.3915, Accuracy: 87.06%, Time Passed: 3.76m
Epoch 28, Batch 200, Loss: 0.3812, Accuracy: 87.00%, Time Passed: 7.49m
Epoch 28, Batch 300, Loss: 0.3698, Accuracy: 87.28%, Time Passed: 10.92m
Epoch 28, Batch 400, Loss: 0.3674, Accuracy: 87.27%, Time Passed: 14.66m
Epoch 28, Batch 500, Loss: 0.3692, Accuracy: 87.21%, Time Passed: 18.15m
Epoch 28 Completed - Average Loss: 0.3684, Accuracy: 87.30%, Epoch Time: 19.61m
Training Complete Epoch 28 - Total Time: 19.61m

✅ Epoch 28 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.0670, Accuracy: 69.06%, Time Passed: 4.54m
Evaluation Complete - Loss: 0.9578, Accuracy: 72.83%, Total Time: 7.63m

📊 Epoch 28 - Evaluation Completed.


🚀 Epoch 29 - Training Started...

Epoch 29, Batch 100, Loss: 0.3429, Accuracy: 88.19%, Time Passed: 3.63m
Epoch 29, Batch 200, Loss: 0.3477, Accuracy: 88.00%, Time Passed: 7.25m
Epoch 29, Batch 300, Loss: 0.3459, Accuracy: 88.20%, Time Passed: 10.79m
Epoch 29, Batch 400, Loss: 0.3535, Accuracy: 88.08%, Time Passed: 14.42m
Epoch 29, Batch 500, Loss: 0.3526, Accuracy: 88.00%, Time Passed: 17.92m
Epoch 29 Completed - Average Loss: 0.3496, Accuracy: 88.13%, Epoch Time: 19.41m
Training Complete Epoch 29 - Total Time: 19.41m

✅ Epoch 29 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.0712, Accuracy: 68.97%, Time Passed: 4.51m
Evaluation Complete - Loss: 0.9390, Accuracy: 73.62%, Total Time: 7.62m

📊 Epoch 29 - Evaluation Completed.


🚀 Epoch 30 - Training Started...

Epoch 30, Batch 100, Loss: 0.3291, Accuracy: 88.34%, Time Passed: 3.63m
Epoch 30, Batch 200, Loss: 0.3263, Accuracy: 88.20%, Time Passed: 7.92m
Epoch 30, Batch 300, Loss: 0.3167, Accuracy: 88.74%, Time Passed: 11.73m
Epoch 30, Batch 400, Loss: 0.3143, Accuracy: 88.80%, Time Passed: 15.43m
Epoch 30, Batch 500, Loss: 0.3180, Accuracy: 88.71%, Time Passed: 19.19m
Epoch 30 Completed - Average Loss: 0.3175, Accuracy: 88.77%, Epoch Time: 21.08m
Training Complete Epoch 30 - Total Time: 21.08m

✅ Epoch 30 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9686, Accuracy: 71.06%, Time Passed: 4.93m
Evaluation Complete - Loss: 0.8706, Accuracy: 74.92%, Total Time: 8.19m

📊 Epoch 30 - Evaluation Completed.


🚀 Epoch 31 - Training Started...

Epoch 31, Batch 100, Loss: 0.2905, Accuracy: 89.19%, Time Passed: 4.22m
Epoch 31, Batch 200, Loss: 0.3127, Accuracy: 88.69%, Time Passed: 8.27m
Epoch 31, Batch 300, Loss: 0.3132, Accuracy: 88.78%, Time Passed: 12.39m
Epoch 31, Batch 400, Loss: 0.3119, Accuracy: 88.95%, Time Passed: 16.33m
Epoch 31, Batch 500, Loss: 0.3125, Accuracy: 88.96%, Time Passed: 20.70m
Epoch 31 Completed - Average Loss: 0.3131, Accuracy: 89.00%, Epoch Time: 22.71m
Training Complete Epoch 31 - Total Time: 22.71m

✅ Epoch 31 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.0554, Accuracy: 69.50%, Time Passed: 5.77m
Evaluation Complete - Loss: 0.8982, Accuracy: 74.33%, Total Time: 9.60m

📊 Epoch 31 - Evaluation Completed.

In [69]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [70]:
del training_states

In [77]:
start_epoch = 32
end_epoch = 35
start_epoch, end_epoch

(32, 35)

In [78]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageB, train_loader, val_loader, inverse_frequency_criterion, stageB_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageB', save_dir = 'mobilenetv2',
                         class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 32 - Training Started...

Epoch 32, Batch 100, Loss: 0.3357, Accuracy: 88.59%, Time Passed: 3.02m
Epoch 32, Batch 200, Loss: 0.3120, Accuracy: 89.44%, Time Passed: 6.13m
Epoch 32, Batch 300, Loss: 0.3022, Accuracy: 89.60%, Time Passed: 9.37m
Epoch 32, Batch 400, Loss: 0.3065, Accuracy: 89.45%, Time Passed: 12.67m
Epoch 32, Batch 500, Loss: 0.3046, Accuracy: 89.47%, Time Passed: 16.01m
Epoch 32 Completed - Average Loss: 0.3027, Accuracy: 89.50%, Epoch Time: 17.52m
Training Complete Epoch 32 - Total Time: 17.52m

✅ Epoch 32 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9411, Accuracy: 72.44%, Time Passed: 4.26m
Evaluation Complete - Loss: 0.8768, Accuracy: 75.77%, Total Time: 7.20m

📊 Epoch 32 - Evaluation Completed.


🚀 Epoch 33 - Training Started...

Epoch 33, Batch 100, Loss: 0.3132, Accuracy: 89.22%, Time Passed: 3.69m
Epoch 33, Batch 200, Loss: 0.3026, Accuracy: 89.52%, Time Passed: 7.41m
Epoch 33, Batch 300, Loss: 0.2970, Accuracy: 89.77%, Time Passed: 10.88m
Epoch 33, Batch 400, Loss: 0.2962, Accuracy: 89.69%, Time Passed: 14.45m
Epoch 33, Batch 500, Loss: 0.2917, Accuracy: 89.86%, Time Passed: 18.02m
Epoch 33 Completed - Average Loss: 0.2911, Accuracy: 89.83%, Epoch Time: 19.54m
Training Complete Epoch 33 - Total Time: 19.54m

✅ Epoch 33 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9437, Accuracy: 72.81%, Time Passed: 4.03m
Evaluation Complete - Loss: 0.8467, Accuracy: 76.31%, Total Time: 6.84m

📊 Epoch 33 - Evaluation Completed.


🚀 Epoch 34 - Training Started...

Epoch 34, Batch 100, Loss: 0.2664, Accuracy: 90.31%, Time Passed: 3.21m
Epoch 34, Batch 200, Loss: 0.2647, Accuracy: 90.42%, Time Passed: 6.55m
Epoch 34, Batch 300, Loss: 0.2671, Accuracy: 90.50%, Time Passed: 10.01m
Epoch 34, Batch 400, Loss: 0.2726, Accuracy: 90.33%, Time Passed: 13.24m
Epoch 34, Batch 500, Loss: 0.2698, Accuracy: 90.49%, Time Passed: 16.58m
Epoch 34 Completed - Average Loss: 0.2695, Accuracy: 90.56%, Epoch Time: 17.95m
Training Complete Epoch 34 - Total Time: 17.95m

✅ Epoch 34 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.0096, Accuracy: 70.78%, Time Passed: 3.96m
Evaluation Complete - Loss: 0.9027, Accuracy: 74.83%, Total Time: 6.73m

📊 Epoch 34 - Evaluation Completed.


🚀 Epoch 35 - Training Started...

Epoch 35, Batch 100, Loss: 0.2711, Accuracy: 90.44%, Time Passed: 3.55m
Epoch 35, Batch 200, Loss: 0.2808, Accuracy: 90.12%, Time Passed: 6.94m
Epoch 35, Batch 300, Loss: 0.2867, Accuracy: 90.08%, Time Passed: 10.96m
Epoch 35, Batch 400, Loss: 0.2807, Accuracy: 90.30%, Time Passed: 14.62m
Epoch 35, Batch 500, Loss: 0.2785, Accuracy: 90.19%, Time Passed: 18.20m
Epoch 35 Completed - Average Loss: 0.2786, Accuracy: 90.13%, Epoch Time: 19.74m
Training Complete Epoch 35 - Total Time: 19.74m

✅ Epoch 35 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9604, Accuracy: 71.28%, Time Passed: 4.26m
Evaluation Complete - Loss: 0.8514, Accuracy: 75.62%, Total Time: 7.12m

📊 Epoch 35 - Evaluation Completed.

In [79]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [84]:
start_epoch = 36
end_epoch = 40
start_epoch, end_epoch

(36, 40)

In [85]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageB, train_loader, val_loader, inverse_frequency_criterion, stageB_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageB', save_dir = 'mobilenetv2',
                         class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 36 - Training Started...

Epoch 36, Batch 100, Loss: 0.2493, Accuracy: 90.78%, Time Passed: 2.96m
Epoch 36, Batch 200, Loss: 0.2590, Accuracy: 90.78%, Time Passed: 6.00m
Epoch 36, Batch 300, Loss: 0.2525, Accuracy: 90.99%, Time Passed: 9.17m
Epoch 36, Batch 400, Loss: 0.2605, Accuracy: 90.71%, Time Passed: 12.46m
Epoch 36, Batch 500, Loss: 0.2638, Accuracy: 90.69%, Time Passed: 15.76m
Epoch 36 Completed - Average Loss: 0.2628, Accuracy: 90.66%, Epoch Time: 17.24m
Training Complete Epoch 36 - Total Time: 17.24m

✅ Epoch 36 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.0056, Accuracy: 71.03%, Time Passed: 4.06m
Evaluation Complete - Loss: 0.9070, Accuracy: 75.12%, Total Time: 6.90m

📊 Epoch 36 - Evaluation Completed.


🚀 Epoch 37 - Training Started...

Epoch 37, Batch 100, Loss: 0.2430, Accuracy: 91.22%, Time Passed: 3.28m
Epoch 37, Batch 200, Loss: 0.2551, Accuracy: 90.59%, Time Passed: 6.53m
Epoch 37, Batch 300, Loss: 0.2553, Accuracy: 90.60%, Time Passed: 9.92m
Epoch 37, Batch 400, Loss: 0.2532, Accuracy: 90.83%, Time Passed: 13.32m
Epoch 37, Batch 500, Loss: 0.2515, Accuracy: 90.88%, Time Passed: 16.75m
Epoch 37 Completed - Average Loss: 0.2516, Accuracy: 90.92%, Epoch Time: 18.22m
Training Complete Epoch 37 - Total Time: 18.22m

✅ Epoch 37 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9578, Accuracy: 72.75%, Time Passed: 4.19m
Evaluation Complete - Loss: 0.8693, Accuracy: 76.19%, Total Time: 7.05m

📊 Epoch 37 - Evaluation Completed.


🚀 Epoch 38 - Training Started...

Epoch 38, Batch 100, Loss: 0.2369, Accuracy: 91.84%, Time Passed: 3.52m
Epoch 38, Batch 200, Loss: 0.2486, Accuracy: 91.47%, Time Passed: 7.33m
Epoch 38, Batch 300, Loss: 0.2476, Accuracy: 91.68%, Time Passed: 11.13m
Epoch 38, Batch 400, Loss: 0.2498, Accuracy: 91.46%, Time Passed: 15.06m
Epoch 38, Batch 500, Loss: 0.2502, Accuracy: 91.42%, Time Passed: 19.08m
Epoch 38 Completed - Average Loss: 0.2490, Accuracy: 91.49%, Epoch Time: 20.72m
Training Complete Epoch 38 - Total Time: 20.72m

✅ Epoch 38 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9584, Accuracy: 72.97%, Time Passed: 4.69m
Evaluation Complete - Loss: 0.8420, Accuracy: 76.77%, Total Time: 7.87m

📊 Epoch 38 - Evaluation Completed.


🚀 Epoch 39 - Training Started...

Epoch 39, Batch 100, Loss: 0.2127, Accuracy: 91.78%, Time Passed: 3.70m
Epoch 39, Batch 200, Loss: 0.2318, Accuracy: 91.52%, Time Passed: 7.81m
Epoch 39, Batch 300, Loss: 0.2342, Accuracy: 91.46%, Time Passed: 11.97m
Epoch 39, Batch 400, Loss: 0.2333, Accuracy: 91.56%, Time Passed: 16.14m
Epoch 39, Batch 500, Loss: 0.2335, Accuracy: 91.44%, Time Passed: 20.42m
Epoch 39 Completed - Average Loss: 0.2307, Accuracy: 91.59%, Epoch Time: 22.17m
Training Complete Epoch 39 - Total Time: 22.17m

✅ Epoch 39 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9590, Accuracy: 72.50%, Time Passed: 4.88m
Evaluation Complete - Loss: 0.8577, Accuracy: 76.37%, Total Time: 8.20m

📊 Epoch 39 - Evaluation Completed.


🚀 Epoch 40 - Training Started...

Epoch 40, Batch 100, Loss: 0.2362, Accuracy: 91.72%, Time Passed: 3.82m
Epoch 40, Batch 200, Loss: 0.2335, Accuracy: 91.77%, Time Passed: 7.67m
Epoch 40, Batch 300, Loss: 0.2311, Accuracy: 91.67%, Time Passed: 11.58m
Epoch 40, Batch 400, Loss: 0.2315, Accuracy: 91.68%, Time Passed: 15.48m
Epoch 40, Batch 500, Loss: 0.2291, Accuracy: 91.79%, Time Passed: 19.56m
Epoch 40 Completed - Average Loss: 0.2301, Accuracy: 91.79%, Epoch Time: 21.28m
Training Complete Epoch 40 - Total Time: 21.28m

✅ Epoch 40 - Training Completed. Starting Evaluation...

Batch 100, Loss: 1.0639, Accuracy: 70.12%, Time Passed: 4.82m
Evaluation Complete - Loss: 0.9516, Accuracy: 74.54%, Total Time: 8.09m

📊 Epoch 40 - Evaluation Completed.

In [87]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

## **Stage C**

### **Checkpoint Validation**

In [89]:
mobilenetv2_stageC = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes))

# Send it to device
device = torch.device("mps")
mobilenetv2_stageC.to(device)
mobilenetv2_stageC.load_state_dict(training_states[39]["model_state_dict"])

In [91]:
_ = evaluate_model(
            mobilenetv2_stageC, val_loader, inverse_frequency_criterion, train_dataset.classes, epoch_num=39, log_interval=100)

Batch 100, Loss: 0.9590, Accuracy: 72.50%, Time Passed: 3.60m
Evaluation Complete - Loss: 0.8577, Accuracy: 76.37%, Total Time: 6.31m

In [92]:
del training_states

### **Training**

In [95]:
mobilenetv2_stageC = configure_mobilenetv2_training(
                                                    mobilenetv2_stageC,
                                                    NUM_CLASSES, intermediate=True,
                                                    intermediate_blocks = [0, 4]
                                                   )
df_summary = summarize_mobilenetv2_blocks(mobilenetv2_stageC)
df_summary

🟢 Intermediate stage → Newly unfrozen blocks: [15, 16, 17, 18]
✅ Trainable layers: 32/158 (20.25%)
✅ Trainable params: 1,568,353/2,266,145 (69.21%)

,Block,Order,Module,Layers (#),Params (#),Trainable Params (#),% Layers (Model),% Params (Model),% Trainable Params (Model),Cumulative Layers (Model),Cumulative % Layers (Model),Cumulative Params (Model),Cumulative % Params (Model),Layers (Module %),Params (Module %),Trainable Params (Module %),Cumulative Layers (Module),Cumulative % Layers (Module),Cumulative Params (Module),Cumulative % Params (Module)
0,Conv2dNormActivation_1,1,features,3,928,0,1.898734,0.040951,0.000000,158,100.000000,2266145,100.000000,1.923077,0.041729,0.000000,156,100.000000,2223872,100.000000
1,InvertedResidual_2,2,features,6,896,0,3.797468,0.039539,0.000000,155,98.101266,2265217,99.959049,3.846154,0.040290,0.000000,153,98.076923,2222944,99.958271
2,InvertedResidual_3,3,features,9,5136,0,5.696203,0.226640,0.000000,149,94.303797,2264321,99.919511,5.769231,0.230949,0.000000,147,94.230769,2222048,99.917981
3,InvertedResidual_4,4,features,9,8832,0,5.696203,0.389737,0.000000,140,88.607595,2259185,99.692870,5.769231,0.397145,0.000000,138,88.461538,2216912,99.687032
4,InvertedResidual_5,5,features,9,10000,0,5.696203,0.441278,0.000000,131,82.911392,2250353,99.303134,5.769231,0.449666,0.000000,129,82.692308,2208080,99.289887
5,InvertedResidual_6,6,features,9,14848,0,5.696203,0.655210,0.000000,122,77.215190,2240353,98.861856,5.769231,0.667664,0.000000,120,76.923077,2198080,98.840221
6,InvertedResidual_7,7,features,9,14848,0,5.696203,0.655210,0.000000,113,71.518987,2225505,98.206646,5.769231,0.667664,0.000000,111,71.153846,2183232,98.172557
7,InvertedResidual_8,8,features,9,21056,0,5.696203,0.929155,0.000000,104,65.822785,2210657,97.551436,5.769231,0.946817,0.000000,102,65.384615,2168384,97.504892
8,InvertedResidual_9,9,features,9,54272,0,5.696203,2.394904,0.000000,95,60.126582,2189601,96.622281,5.769231,2.440428,0.000000,93,59.615385,2147328,96.558075
9,InvertedResidual_10,10,features,9,54272,0,5.696203,2.394904,0.000000,86,54.430380,2135329,94.227377,5.769231,2.440428,0.000000,84,53.846154,2093056,94.117647
10,InvertedResidual_11,11,features,9,54272,0,5.696203,2.394904,0.000000,77,48.734177,2081057,91.832473,5.769231,2.440428,0.000000,75,48.076923,2038784,91.677219
11,InvertedResidual_12,12,features,9,66624,0,5.696203,2.939971,0.000000,68,43.037975,2026785,89.437569,5.769231,2.995856,0.000000,66,42.307692,1984512,89.236791
12,InvertedResidual_13,13,features,9,118272,0,5.696203,5.219084,0.000000,59,37.341772,1960161,86.497598,5.769231,5.318292,0.000000,57,36.538462,1917888,86.240935
13,InvertedResidual_14,14,features,9,118272,0,5.696203,5.219084,0.000000,50,31.645570,1841889,81.278515,5.769231,5.318292,0.000000,48,30.769231,1799616,80.922643
14,InvertedResidual_15,15,features,9,155264,0,5.696203,6.851459,0.000000,41,25.949367,1723617,76.059431,5.769231,6.981697,0.000000,39,25.000000,1681344,75.604351
15,InvertedResidual_16,16,features,9,320000,320000,5.696203,14.120897,14.120897,32,20.253165,1568353,69.207972,5.769231,14.389317,20.968757,30,19.230769,1526080,68.622655
16,InvertedResidual_17,17,features,9,320000,320000,5.696203,14.120897,14.120897,23,14.556962,1248353,55.087075,5.769231,14.389317,20.968757,21,13.461538,1206080,54.233337
17,InvertedResidual_18,18,features,9,473920,473920,5.696203,20.913048,20.913048,14,8.860759,928353,40.966178,5.769231,21.310579,31.054728,12,7.692308,886080,39.844020
18,Conv2dNormActivation_19,19,features,3,412160,412160,1.898734,18.187715,18.187715,5,3.164557,454433,20.053130,1.923077,18.533441,27.007758,3,1.923077,412160,18.533441
19,Sequential,20,classifier,2,42273,42273,1.265823,1.865415,1.865415,2,1.265823,42273,1.865415,100.000000,100.000000,100.000000,2,100.000000,42273,100.000000

In [98]:
stageC_optimizer = torch.optim.AdamW(mobilenetv2_stageC.parameters(), lr=5e-5,
                            weight_decay=1e-4, betas=(0.9, 0.999))

In [99]:
start_epoch = 40
end_epoch = 50
start_epoch, end_epoch

(40, 50)

In [100]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageC, train_loader, val_loader, inverse_frequency_criterion, stageC_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageC', save_dir = 'mobilenetv2',
                         class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 40 - Training Started...

Epoch 40, Batch 100, Loss: 0.2234, Accuracy: 91.50%, Time Passed: 3.97m
Epoch 40, Batch 200, Loss: 0.2143, Accuracy: 91.75%, Time Passed: 7.83m
Epoch 40, Batch 300, Loss: 0.2161, Accuracy: 91.92%, Time Passed: 11.52m
Epoch 40, Batch 400, Loss: 0.2180, Accuracy: 91.93%, Time Passed: 14.87m
Epoch 40, Batch 500, Loss: 0.2165, Accuracy: 92.14%, Time Passed: 18.24m
Epoch 40 Completed - Average Loss: 0.2165, Accuracy: 92.15%, Epoch Time: 19.64m
Training Complete Epoch 40 - Total Time: 19.64m

✅ Epoch 40 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9449, Accuracy: 73.09%, Time Passed: 4.22m
Evaluation Complete - Loss: 0.8368, Accuracy: 77.25%, Total Time: 7.06m

📊 Epoch 40 - Evaluation Completed.


🚀 Epoch 41 - Training Started...

Epoch 41, Batch 100, Loss: 0.1948, Accuracy: 93.16%, Time Passed: 3.40m
Epoch 41, Batch 200, Loss: 0.2027, Accuracy: 92.88%, Time Passed: 6.82m
Epoch 41, Batch 300, Loss: 0.2186, Accuracy: 92.41%, Time Passed: 10.42m
Epoch 41, Batch 400, Loss: 0.2149, Accuracy: 92.42%, Time Passed: 14.12m
Epoch 41, Batch 500, Loss: 0.2137, Accuracy: 92.53%, Time Passed: 17.98m
Epoch 41 Completed - Average Loss: 0.2154, Accuracy: 92.45%, Epoch Time: 19.55m
Training Complete Epoch 41 - Total Time: 19.55m

✅ Epoch 41 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9115, Accuracy: 74.53%, Time Passed: 4.44m
Evaluation Complete - Loss: 0.8361, Accuracy: 77.69%, Total Time: 7.47m

📊 Epoch 41 - Evaluation Completed.


🚀 Epoch 42 - Training Started...

Epoch 42, Batch 100, Loss: 0.2155, Accuracy: 92.31%, Time Passed: 3.57m
Epoch 42, Batch 200, Loss: 0.2114, Accuracy: 92.34%, Time Passed: 7.03m
Epoch 42, Batch 300, Loss: 0.2073, Accuracy: 92.49%, Time Passed: 10.67m
Epoch 42, Batch 400, Loss: 0.2074, Accuracy: 92.62%, Time Passed: 14.22m
Epoch 42, Batch 500, Loss: 0.2079, Accuracy: 92.50%, Time Passed: 17.84m
Epoch 42 Completed - Average Loss: 0.2058, Accuracy: 92.53%, Epoch Time: 19.37m
Training Complete Epoch 42 - Total Time: 19.37m

✅ Epoch 42 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9335, Accuracy: 73.50%, Time Passed: 4.58m
Evaluation Complete - Loss: 0.8316, Accuracy: 77.25%, Total Time: 7.68m

📊 Epoch 42 - Evaluation Completed.


🚀 Epoch 43 - Training Started...

Epoch 43, Batch 100, Loss: 0.1831, Accuracy: 93.47%, Time Passed: 3.52m
Epoch 43, Batch 200, Loss: 0.1915, Accuracy: 93.05%, Time Passed: 7.53m
Epoch 43, Batch 300, Loss: 0.1946, Accuracy: 93.00%, Time Passed: 11.20m
Epoch 43, Batch 400, Loss: 0.1902, Accuracy: 93.17%, Time Passed: 14.88m
Epoch 43, Batch 500, Loss: 0.1916, Accuracy: 93.03%, Time Passed: 18.43m
Epoch 43 Completed - Average Loss: 0.1904, Accuracy: 93.04%, Epoch Time: 19.87m
Training Complete Epoch 43 - Total Time: 19.87m

✅ Epoch 43 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9493, Accuracy: 73.44%, Time Passed: 4.21m
Evaluation Complete - Loss: 0.8485, Accuracy: 77.06%, Total Time: 7.18m

📊 Epoch 43 - Evaluation Completed.


🚀 Epoch 44 - Training Started...

Epoch 44, Batch 100, Loss: 0.2097, Accuracy: 93.06%, Time Passed: 3.36m
Epoch 44, Batch 200, Loss: 0.2015, Accuracy: 93.14%, Time Passed: 7.09m
Epoch 44, Batch 300, Loss: 0.1990, Accuracy: 93.16%, Time Passed: 11.18m
Epoch 44, Batch 400, Loss: 0.1961, Accuracy: 93.02%, Time Passed: 15.15m
Epoch 44, Batch 500, Loss: 0.1948, Accuracy: 93.03%, Time Passed: 19.12m
Epoch 44 Completed - Average Loss: 0.1965, Accuracy: 92.92%, Epoch Time: 20.73m
Training Complete Epoch 44 - Total Time: 20.73m

✅ Epoch 44 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9295, Accuracy: 73.84%, Time Passed: 5.17m
Evaluation Complete - Loss: 0.8102, Accuracy: 77.92%, Total Time: 8.77m

📊 Epoch 44 - Evaluation Completed.


🚀 Epoch 45 - Training Started...

Epoch 45, Batch 100, Loss: 0.1560, Accuracy: 94.00%, Time Passed: 4.62m
Epoch 45, Batch 200, Loss: 0.1744, Accuracy: 93.58%, Time Passed: 8.31m
Epoch 45, Batch 300, Loss: 0.1714, Accuracy: 93.64%, Time Passed: 12.18m
Epoch 45, Batch 400, Loss: 0.1702, Accuracy: 93.73%, Time Passed: 16.46m
Epoch 45, Batch 500, Loss: 0.1760, Accuracy: 93.68%, Time Passed: 21.02m
Epoch 45 Completed - Average Loss: 0.1747, Accuracy: 93.69%, Epoch Time: 23.08m
Training Complete Epoch 45 - Total Time: 23.08m

✅ Epoch 45 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8784, Accuracy: 75.88%, Time Passed: 5.57m
Evaluation Complete - Loss: 0.7965, Accuracy: 79.04%, Total Time: 8.88m

📊 Epoch 45 - Evaluation Completed.


🚀 Epoch 46 - Training Started...

Epoch 46, Batch 100, Loss: 0.1843, Accuracy: 93.22%, Time Passed: 3.91m
Epoch 46, Batch 200, Loss: 0.1891, Accuracy: 92.95%, Time Passed: 7.90m
Epoch 46, Batch 300, Loss: 0.1838, Accuracy: 93.25%, Time Passed: 12.26m
Epoch 46, Batch 400, Loss: 0.1798, Accuracy: 93.59%, Time Passed: 16.00m
Epoch 46, Batch 500, Loss: 0.1794, Accuracy: 93.61%, Time Passed: 19.65m
Epoch 46 Completed - Average Loss: 0.1800, Accuracy: 93.60%, Epoch Time: 21.07m
Training Complete Epoch 46 - Total Time: 21.07m

✅ Epoch 46 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8686, Accuracy: 75.53%, Time Passed: 4.45m
Evaluation Complete - Loss: 0.8007, Accuracy: 78.92%, Total Time: 7.40m

📊 Epoch 46 - Evaluation Completed.


🚀 Epoch 47 - Training Started...

Epoch 47, Batch 100, Loss: 0.1786, Accuracy: 93.50%, Time Passed: 3.82m
Epoch 47, Batch 200, Loss: 0.1621, Accuracy: 93.81%, Time Passed: 7.59m
Epoch 47, Batch 300, Loss: 0.1619, Accuracy: 94.00%, Time Passed: 11.36m
Epoch 47, Batch 400, Loss: 0.1661, Accuracy: 93.91%, Time Passed: 15.03m
Epoch 47, Batch 500, Loss: 0.1644, Accuracy: 94.03%, Time Passed: 18.69m
Epoch 47 Completed - Average Loss: 0.1634, Accuracy: 94.09%, Epoch Time: 20.29m
Training Complete Epoch 47 - Total Time: 20.29m

✅ Epoch 47 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8911, Accuracy: 75.19%, Time Passed: 4.33m
Evaluation Complete - Loss: 0.7955, Accuracy: 78.65%, Total Time: 7.33m

📊 Epoch 47 - Evaluation Completed.


🚀 Epoch 48 - Training Started...

Epoch 48, Batch 100, Loss: 0.1518, Accuracy: 94.12%, Time Passed: 3.60m
Epoch 48, Batch 200, Loss: 0.1671, Accuracy: 93.88%, Time Passed: 7.16m
Epoch 48, Batch 300, Loss: 0.1657, Accuracy: 93.80%, Time Passed: 10.67m
Epoch 48, Batch 400, Loss: 0.1721, Accuracy: 93.65%, Time Passed: 14.30m
Epoch 48, Batch 500, Loss: 0.1712, Accuracy: 93.72%, Time Passed: 18.10m
Epoch 48 Completed - Average Loss: 0.1693, Accuracy: 93.80%, Epoch Time: 19.76m
Training Complete Epoch 48 - Total Time: 19.76m

✅ Epoch 48 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8941, Accuracy: 74.72%, Time Passed: 4.33m
Evaluation Complete - Loss: 0.8090, Accuracy: 78.50%, Total Time: 7.45m

📊 Epoch 48 - Evaluation Completed.


🚀 Epoch 49 - Training Started...

Epoch 49, Batch 100, Loss: 0.1513, Accuracy: 94.00%, Time Passed: 4.21m
Epoch 49, Batch 200, Loss: 0.1614, Accuracy: 93.77%, Time Passed: 7.92m
Epoch 49, Batch 300, Loss: 0.1644, Accuracy: 93.93%, Time Passed: 11.61m
Epoch 49, Batch 400, Loss: 0.1628, Accuracy: 94.02%, Time Passed: 15.49m
Epoch 49, Batch 500, Loss: 0.1627, Accuracy: 94.03%, Time Passed: 19.16m
Epoch 49 Completed - Average Loss: 0.1627, Accuracy: 94.06%, Epoch Time: 20.61m
Training Complete Epoch 49 - Total Time: 20.61m

✅ Epoch 49 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8514, Accuracy: 75.97%, Time Passed: 4.35m
Evaluation Complete - Loss: 0.7894, Accuracy: 78.96%, Total Time: 7.46m

📊 Epoch 49 - Evaluation Completed.


🚀 Epoch 50 - Training Started...

Epoch 50, Batch 100, Loss: 0.1589, Accuracy: 93.78%, Time Passed: 4.27m
Epoch 50, Batch 200, Loss: 0.1557, Accuracy: 93.83%, Time Passed: 8.44m
Epoch 50, Batch 300, Loss: 0.1544, Accuracy: 93.93%, Time Passed: 12.28m
Epoch 50, Batch 400, Loss: 0.1508, Accuracy: 94.10%, Time Passed: 16.25m
Epoch 50, Batch 500, Loss: 0.1561, Accuracy: 94.08%, Time Passed: 20.11m
Epoch 50 Completed - Average Loss: 0.1551, Accuracy: 94.08%, Epoch Time: 21.61m
Training Complete Epoch 50 - Total Time: 21.61m

✅ Epoch 50 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8791, Accuracy: 75.59%, Time Passed: 4.52m
Evaluation Complete - Loss: 0.7836, Accuracy: 79.23%, Total Time: 7.58m

📊 Epoch 50 - Evaluation Completed.

In [103]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [104]:
del training_states

In [106]:
start_epoch = 51
end_epoch = 52
start_epoch, end_epoch

(51, 52)

In [107]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageC, train_loader, val_loader, inverse_frequency_criterion, stageC_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageC', save_dir = 'mobilenetv2',
                         class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 51 - Training Started...

Epoch 51, Batch 100, Loss: 0.1609, Accuracy: 94.59%, Time Passed: 3.51m
Epoch 51, Batch 200, Loss: 0.1530, Accuracy: 94.59%, Time Passed: 7.09m
Epoch 51, Batch 300, Loss: 0.1527, Accuracy: 94.51%, Time Passed: 10.70m
Epoch 51, Batch 400, Loss: 0.1574, Accuracy: 94.37%, Time Passed: 14.09m
Epoch 51, Batch 500, Loss: 0.1557, Accuracy: 94.41%, Time Passed: 17.53m
Epoch 51 Completed - Average Loss: 0.1543, Accuracy: 94.48%, Epoch Time: 18.99m
Training Complete Epoch 51 - Total Time: 18.99m

✅ Epoch 51 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8368, Accuracy: 76.47%, Time Passed: 4.24m
Evaluation Complete - Loss: 0.7574, Accuracy: 80.00%, Total Time: 7.14m

📊 Epoch 51 - Evaluation Completed.


🚀 Epoch 52 - Training Started...

Epoch 52, Batch 100, Loss: 0.1514, Accuracy: 94.53%, Time Passed: 3.51m
Epoch 52, Batch 200, Loss: 0.1476, Accuracy: 94.80%, Time Passed: 7.05m
Epoch 52, Batch 300, Loss: 0.1413, Accuracy: 94.90%, Time Passed: 10.61m
Epoch 52, Batch 400, Loss: 0.1458, Accuracy: 94.69%, Time Passed: 14.21m
Epoch 52, Batch 500, Loss: 0.1440, Accuracy: 94.76%, Time Passed: 17.73m
Epoch 52 Completed - Average Loss: 0.1462, Accuracy: 94.71%, Epoch Time: 19.16m
Training Complete Epoch 52 - Total Time: 19.16m

✅ Epoch 52 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8072, Accuracy: 77.06%, Time Passed: 4.28m
Evaluation Complete - Loss: 0.7670, Accuracy: 80.08%, Total Time: 7.22m

📊 Epoch 52 - Evaluation Completed.

In [108]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [109]:
del training_states

In [112]:
start_epoch = 53
end_epoch = 60
start_epoch, end_epoch

(53, 60)

In [113]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageC, train_loader, val_loader, inverse_frequency_criterion, stageC_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageC', save_dir = 'mobilenetv2',
                         class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 53 - Training Started...

Epoch 53, Batch 100, Loss: 0.1444, Accuracy: 94.06%, Time Passed: 3.32m
Epoch 53, Batch 200, Loss: 0.1500, Accuracy: 94.47%, Time Passed: 6.71m
Epoch 53, Batch 300, Loss: 0.1403, Accuracy: 94.73%, Time Passed: 10.21m
Epoch 53, Batch 400, Loss: 0.1411, Accuracy: 94.73%, Time Passed: 13.76m
Epoch 53, Batch 500, Loss: 0.1438, Accuracy: 94.83%, Time Passed: 17.51m
Epoch 53 Completed - Average Loss: 0.1432, Accuracy: 94.83%, Epoch Time: 18.93m
Training Complete Epoch 53 - Total Time: 18.93m

✅ Epoch 53 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9112, Accuracy: 75.31%, Time Passed: 4.32m
Evaluation Complete - Loss: 0.8244, Accuracy: 78.87%, Total Time: 7.31m

📊 Epoch 53 - Evaluation Completed.


🚀 Epoch 54 - Training Started...

Epoch 54, Batch 100, Loss: 0.1340, Accuracy: 94.91%, Time Passed: 3.74m
Epoch 54, Batch 200, Loss: 0.1368, Accuracy: 94.92%, Time Passed: 7.58m
Epoch 54, Batch 300, Loss: 0.1387, Accuracy: 94.85%, Time Passed: 11.36m
Epoch 54, Batch 400, Loss: 0.1355, Accuracy: 95.00%, Time Passed: 14.88m
Epoch 54, Batch 500, Loss: 0.1367, Accuracy: 95.08%, Time Passed: 18.57m
Epoch 54 Completed - Average Loss: 0.1382, Accuracy: 94.99%, Epoch Time: 20.15m
Training Complete Epoch 54 - Total Time: 20.15m

✅ Epoch 54 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8646, Accuracy: 76.00%, Time Passed: 4.18m
Evaluation Complete - Loss: 0.7935, Accuracy: 79.46%, Total Time: 7.10m

📊 Epoch 54 - Evaluation Completed.


🚀 Epoch 55 - Training Started...

Epoch 55, Batch 100, Loss: 0.1471, Accuracy: 94.41%, Time Passed: 3.48m
Epoch 55, Batch 200, Loss: 0.1514, Accuracy: 94.48%, Time Passed: 7.16m
Epoch 55, Batch 300, Loss: 0.1438, Accuracy: 94.86%, Time Passed: 10.78m
Epoch 55, Batch 400, Loss: 0.1470, Accuracy: 94.74%, Time Passed: 14.38m
Epoch 55, Batch 500, Loss: 0.1465, Accuracy: 94.82%, Time Passed: 17.97m
Epoch 55 Completed - Average Loss: 0.1457, Accuracy: 94.82%, Epoch Time: 19.34m
Training Complete Epoch 55 - Total Time: 19.34m

✅ Epoch 55 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8107, Accuracy: 78.16%, Time Passed: 4.31m
Evaluation Complete - Loss: 0.7482, Accuracy: 81.13%, Total Time: 7.34m

📊 Epoch 55 - Evaluation Completed.


🚀 Epoch 56 - Training Started...

Epoch 56, Batch 100, Loss: 0.1279, Accuracy: 95.19%, Time Passed: 3.49m
Epoch 56, Batch 200, Loss: 0.1301, Accuracy: 95.16%, Time Passed: 6.98m
Epoch 56, Batch 300, Loss: 0.1271, Accuracy: 95.31%, Time Passed: 10.64m
Epoch 56, Batch 400, Loss: 0.1306, Accuracy: 95.24%, Time Passed: 14.59m
Epoch 56, Batch 500, Loss: 0.1314, Accuracy: 95.12%, Time Passed: 18.36m
Epoch 56 Completed - Average Loss: 0.1338, Accuracy: 95.10%, Epoch Time: 19.93m
Training Complete Epoch 56 - Total Time: 19.93m

✅ Epoch 56 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8353, Accuracy: 77.34%, Time Passed: 4.32m
Evaluation Complete - Loss: 0.7471, Accuracy: 80.58%, Total Time: 7.33m

📊 Epoch 56 - Evaluation Completed.


🚀 Epoch 57 - Training Started...

Epoch 57, Batch 100, Loss: 0.1344, Accuracy: 95.03%, Time Passed: 3.69m
Epoch 57, Batch 200, Loss: 0.1393, Accuracy: 95.12%, Time Passed: 7.45m
Epoch 57, Batch 300, Loss: 0.1353, Accuracy: 95.24%, Time Passed: 11.12m
Epoch 57, Batch 400, Loss: 0.1359, Accuracy: 95.19%, Time Passed: 14.70m
Epoch 57, Batch 500, Loss: 0.1328, Accuracy: 95.21%, Time Passed: 18.22m
Epoch 57 Completed - Average Loss: 0.1330, Accuracy: 95.16%, Epoch Time: 19.70m
Training Complete Epoch 57 - Total Time: 19.70m

✅ Epoch 57 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8453, Accuracy: 77.12%, Time Passed: 4.17m
Evaluation Complete - Loss: 0.7900, Accuracy: 79.79%, Total Time: 7.10m

📊 Epoch 57 - Evaluation Completed.


🚀 Epoch 58 - Training Started...

Epoch 58, Batch 100, Loss: 0.1370, Accuracy: 95.22%, Time Passed: 3.57m
Epoch 58, Batch 200, Loss: 0.1320, Accuracy: 95.44%, Time Passed: 7.16m
Epoch 58, Batch 300, Loss: 0.1372, Accuracy: 95.42%, Time Passed: 11.00m
Epoch 58, Batch 400, Loss: 0.1374, Accuracy: 95.29%, Time Passed: 14.84m
Epoch 58, Batch 500, Loss: 0.1359, Accuracy: 95.26%, Time Passed: 18.69m
Epoch 58 Completed - Average Loss: 0.1352, Accuracy: 95.29%, Epoch Time: 20.32m
Training Complete Epoch 58 - Total Time: 20.32m

✅ Epoch 58 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.9384, Accuracy: 74.38%, Time Passed: 4.33m
Evaluation Complete - Loss: 0.8461, Accuracy: 78.54%, Total Time: 7.37m

📊 Epoch 58 - Evaluation Completed.


🚀 Epoch 59 - Training Started...

Epoch 59, Batch 100, Loss: 0.1362, Accuracy: 94.81%, Time Passed: 3.97m
Epoch 59, Batch 200, Loss: 0.1392, Accuracy: 94.75%, Time Passed: 8.11m
Epoch 59, Batch 300, Loss: 0.1422, Accuracy: 94.80%, Time Passed: 12.08m
Epoch 59, Batch 400, Loss: 0.1368, Accuracy: 95.00%, Time Passed: 16.09m
Epoch 59, Batch 500, Loss: 0.1322, Accuracy: 95.03%, Time Passed: 20.35m
Epoch 59 Completed - Average Loss: 0.1323, Accuracy: 95.04%, Epoch Time: 22.08m
Training Complete Epoch 59 - Total Time: 22.08m

✅ Epoch 59 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8669, Accuracy: 75.47%, Time Passed: 4.62m
Evaluation Complete - Loss: 0.7978, Accuracy: 79.27%, Total Time: 7.87m

📊 Epoch 59 - Evaluation Completed.


🚀 Epoch 60 - Training Started...

Epoch 60, Batch 100, Loss: 0.1253, Accuracy: 95.41%, Time Passed: 4.21m
Epoch 60, Batch 200, Loss: 0.1225, Accuracy: 95.50%, Time Passed: 8.26m
Epoch 60, Batch 300, Loss: 0.1193, Accuracy: 95.73%, Time Passed: 12.24m
Epoch 60, Batch 400, Loss: 0.1226, Accuracy: 95.57%, Time Passed: 16.38m
Epoch 60, Batch 500, Loss: 0.1232, Accuracy: 95.47%, Time Passed: 20.52m
Epoch 60 Completed - Average Loss: 0.1245, Accuracy: 95.39%, Epoch Time: 22.20m
Training Complete Epoch 60 - Total Time: 22.20m

✅ Epoch 60 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8466, Accuracy: 76.75%, Time Passed: 4.78m
Evaluation Complete - Loss: 0.7716, Accuracy: 80.10%, Total Time: 7.79m

📊 Epoch 60 - Evaluation Completed.

In [114]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [115]:
del training_states

In [116]:
start_epoch = 61
end_epoch = 65
start_epoch, end_epoch

(61, 65)

In [117]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageC, train_loader, val_loader, inverse_frequency_criterion, stageC_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageC', save_dir = 'mobilenetv2',
                         class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 61 - Training Started...

Epoch 61, Batch 100, Loss: 0.1081, Accuracy: 96.47%, Time Passed: 4.06m
Epoch 61, Batch 200, Loss: 0.1235, Accuracy: 95.70%, Time Passed: 8.46m
Epoch 61, Batch 300, Loss: 0.1173, Accuracy: 95.77%, Time Passed: 12.49m
Epoch 61, Batch 400, Loss: 0.1238, Accuracy: 95.64%, Time Passed: 16.33m
Epoch 61, Batch 500, Loss: 0.1212, Accuracy: 95.64%, Time Passed: 19.99m
Epoch 61 Completed - Average Loss: 0.1216, Accuracy: 95.59%, Epoch Time: 21.46m
Training Complete Epoch 61 - Total Time: 21.46m

✅ Epoch 61 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8957, Accuracy: 75.31%, Time Passed: 4.79m
Evaluation Complete - Loss: 0.7894, Accuracy: 79.23%, Total Time: 7.88m

📊 Epoch 61 - Evaluation Completed.


🚀 Epoch 62 - Training Started...

Epoch 62, Batch 100, Loss: 0.1010, Accuracy: 96.16%, Time Passed: 3.87m
Epoch 62, Batch 200, Loss: 0.1142, Accuracy: 95.69%, Time Passed: 7.74m
Epoch 62, Batch 300, Loss: 0.1150, Accuracy: 95.85%, Time Passed: 11.61m
Epoch 62, Batch 400, Loss: 0.1151, Accuracy: 95.73%, Time Passed: 15.35m
Epoch 62, Batch 500, Loss: 0.1171, Accuracy: 95.68%, Time Passed: 19.07m
Epoch 62 Completed - Average Loss: 0.1192, Accuracy: 95.59%, Epoch Time: 20.68m
Training Complete Epoch 62 - Total Time: 20.68m

✅ Epoch 62 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8298, Accuracy: 77.16%, Time Passed: 4.36m
Evaluation Complete - Loss: 0.7382, Accuracy: 80.83%, Total Time: 7.39m

📊 Epoch 62 - Evaluation Completed.


🚀 Epoch 63 - Training Started...

Epoch 63, Batch 100, Loss: 0.1194, Accuracy: 95.62%, Time Passed: 3.78m
Epoch 63, Batch 200, Loss: 0.1243, Accuracy: 95.55%, Time Passed: 7.54m
Epoch 63, Batch 300, Loss: 0.1252, Accuracy: 95.56%, Time Passed: 11.37m
Epoch 63, Batch 400, Loss: 0.1230, Accuracy: 95.63%, Time Passed: 15.40m
Epoch 63, Batch 500, Loss: 0.1198, Accuracy: 95.67%, Time Passed: 19.41m
Epoch 63 Completed - Average Loss: 0.1194, Accuracy: 95.67%, Epoch Time: 20.95m
Training Complete Epoch 63 - Total Time: 20.95m

✅ Epoch 63 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8585, Accuracy: 77.50%, Time Passed: 4.56m
Evaluation Complete - Loss: 0.8024, Accuracy: 80.23%, Total Time: 7.73m

📊 Epoch 63 - Evaluation Completed.


🚀 Epoch 64 - Training Started...

Epoch 64, Batch 100, Loss: 0.1327, Accuracy: 95.31%, Time Passed: 3.69m
Epoch 64, Batch 200, Loss: 0.1188, Accuracy: 95.69%, Time Passed: 7.34m
Epoch 64, Batch 300, Loss: 0.1201, Accuracy: 95.52%, Time Passed: 11.25m
Epoch 64, Batch 400, Loss: 0.1242, Accuracy: 95.43%, Time Passed: 15.35m
Epoch 64, Batch 500, Loss: 0.1246, Accuracy: 95.37%, Time Passed: 19.33m
Epoch 64 Completed - Average Loss: 0.1231, Accuracy: 95.47%, Epoch Time: 20.97m
Training Complete Epoch 64 - Total Time: 20.97m

✅ Epoch 64 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8570, Accuracy: 76.75%, Time Passed: 4.50m
Evaluation Complete - Loss: 0.7665, Accuracy: 80.27%, Total Time: 7.55m

📊 Epoch 64 - Evaluation Completed.


🚀 Epoch 65 - Training Started...

Epoch 65, Batch 100, Loss: 0.1091, Accuracy: 96.12%, Time Passed: 3.70m
Epoch 65, Batch 200, Loss: 0.1180, Accuracy: 95.73%, Time Passed: 7.49m
Epoch 65, Batch 300, Loss: 0.1173, Accuracy: 95.82%, Time Passed: 11.39m
Epoch 65, Batch 400, Loss: 0.1162, Accuracy: 95.76%, Time Passed: 15.36m
Epoch 65, Batch 500, Loss: 0.1174, Accuracy: 95.64%, Time Passed: 18.97m
Epoch 65 Completed - Average Loss: 0.1161, Accuracy: 95.62%, Epoch Time: 20.48m
Training Complete Epoch 65 - Total Time: 20.48m

✅ Epoch 65 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7736, Accuracy: 79.16%, Time Passed: 4.24m
Evaluation Complete - Loss: 0.7406, Accuracy: 81.37%, Total Time: 7.26m

📊 Epoch 65 - Evaluation Completed.

In [118]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [44]:
del training_states

### **Checkpoint Validation**

In [48]:
inverse_frequency_weights = compute_class_weights(train_dataset, method="inverse_frequency", normalize=False)
inverse_frequency_criterion = nn.CrossEntropyLoss(weight=inverse_frequency_weights)

In [46]:
training_states = joblib.load(f'mobilenetv2/training_states_{61}_{65}.pkl')

In [42]:
mobilenetv2_stageC = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes))

# Send it to device
device = torch.device("mps")
mobilenetv2_stageC.to(device)
mobilenetv2_stageC.load_state_dict(training_states[65]["model_state_dict"])

In [43]:
mobilenetv2_stageC = configure_mobilenetv2_training(
                                                    mobilenetv2_stageC,
                                                    NUM_CLASSES, intermediate=True,
                                                    intermediate_blocks = [0, 4]
                                                   )
df_summary = summarize_mobilenetv2_blocks(mobilenetv2_stageC)
df_summary

🟢 Intermediate stage → Newly unfrozen blocks: [15, 16, 17, 18]
✅ Trainable layers: 32/158 (20.25%)
✅ Trainable params: 1,568,353/2,266,145 (69.21%)

,Block,Order,Module,Layers (#),Params (#),Trainable Params (#),% Layers (Model),% Params (Model),% Trainable Params (Model),Cumulative Layers (Model),Cumulative % Layers (Model),Cumulative Params (Model),Cumulative % Params (Model),Layers (Module %),Params (Module %),Trainable Params (Module %),Cumulative Layers (Module),Cumulative % Layers (Module),Cumulative Params (Module),Cumulative % Params (Module)
0,Conv2dNormActivation_1,1,features,3,928,0,1.898734,0.040951,0.000000,158,100.000000,2266145,100.000000,1.923077,0.041729,0.000000,156,100.000000,2223872,100.000000
1,InvertedResidual_2,2,features,6,896,0,3.797468,0.039539,0.000000,155,98.101266,2265217,99.959049,3.846154,0.040290,0.000000,153,98.076923,2222944,99.958271
2,InvertedResidual_3,3,features,9,5136,0,5.696203,0.226640,0.000000,149,94.303797,2264321,99.919511,5.769231,0.230949,0.000000,147,94.230769,2222048,99.917981
3,InvertedResidual_4,4,features,9,8832,0,5.696203,0.389737,0.000000,140,88.607595,2259185,99.692870,5.769231,0.397145,0.000000,138,88.461538,2216912,99.687032
4,InvertedResidual_5,5,features,9,10000,0,5.696203,0.441278,0.000000,131,82.911392,2250353,99.303134,5.769231,0.449666,0.000000,129,82.692308,2208080,99.289887
5,InvertedResidual_6,6,features,9,14848,0,5.696203,0.655210,0.000000,122,77.215190,2240353,98.861856,5.769231,0.667664,0.000000,120,76.923077,2198080,98.840221
6,InvertedResidual_7,7,features,9,14848,0,5.696203,0.655210,0.000000,113,71.518987,2225505,98.206646,5.769231,0.667664,0.000000,111,71.153846,2183232,98.172557
7,InvertedResidual_8,8,features,9,21056,0,5.696203,0.929155,0.000000,104,65.822785,2210657,97.551436,5.769231,0.946817,0.000000,102,65.384615,2168384,97.504892
8,InvertedResidual_9,9,features,9,54272,0,5.696203,2.394904,0.000000,95,60.126582,2189601,96.622281,5.769231,2.440428,0.000000,93,59.615385,2147328,96.558075
9,InvertedResidual_10,10,features,9,54272,0,5.696203,2.394904,0.000000,86,54.430380,2135329,94.227377,5.769231,2.440428,0.000000,84,53.846154,2093056,94.117647
10,InvertedResidual_11,11,features,9,54272,0,5.696203,2.394904,0.000000,77,48.734177,2081057,91.832473,5.769231,2.440428,0.000000,75,48.076923,2038784,91.677219
11,InvertedResidual_12,12,features,9,66624,0,5.696203,2.939971,0.000000,68,43.037975,2026785,89.437569,5.769231,2.995856,0.000000,66,42.307692,1984512,89.236791
12,InvertedResidual_13,13,features,9,118272,0,5.696203,5.219084,0.000000,59,37.341772,1960161,86.497598,5.769231,5.318292,0.000000,57,36.538462,1917888,86.240935
13,InvertedResidual_14,14,features,9,118272,0,5.696203,5.219084,0.000000,50,31.645570,1841889,81.278515,5.769231,5.318292,0.000000,48,30.769231,1799616,80.922643
14,InvertedResidual_15,15,features,9,155264,0,5.696203,6.851459,0.000000,41,25.949367,1723617,76.059431,5.769231,6.981697,0.000000,39,25.000000,1681344,75.604351
15,InvertedResidual_16,16,features,9,320000,320000,5.696203,14.120897,14.120897,32,20.253165,1568353,69.207972,5.769231,14.389317,20.968757,30,19.230769,1526080,68.622655
16,InvertedResidual_17,17,features,9,320000,320000,5.696203,14.120897,14.120897,23,14.556962,1248353,55.087075,5.769231,14.389317,20.968757,21,13.461538,1206080,54.233337
17,InvertedResidual_18,18,features,9,473920,473920,5.696203,20.913048,20.913048,14,8.860759,928353,40.966178,5.769231,21.310579,31.054728,12,7.692308,886080,39.844020
18,Conv2dNormActivation_19,19,features,3,412160,412160,1.898734,18.187715,18.187715,5,3.164557,454433,20.053130,1.923077,18.533441,27.007758,3,1.923077,412160,18.533441
19,Sequential,20,classifier,2,42273,42273,1.265823,1.865415,1.865415,2,1.265823,42273,1.865415,100.000000,100.000000,100.000000,2,100.000000,42273,100.000000

In [45]:
_ = evaluate_model(
            mobilenetv2_stageC, val_loader, inverse_frequency_criterion, train_dataset.classes, epoch_num=65, log_interval=100)

Batch 100, Loss: 0.7736, Accuracy: 79.16%, Time Passed: 3.71m
Evaluation Complete - Loss: 0.7406, Accuracy: 81.37%, Total Time: 6.46m

### **Continue Training**

In [48]:
# Recreate the optimizer with the same settings as before
stageC_optimizer = torch.optim.AdamW(mobilenetv2_stageC.parameters(), lr=5e-5, weight_decay=1e-4,
                                     betas=(0.9, 0.999))

# Load the saved optimizer state
stageC_optimizer.load_state_dict(training_states[65]["optimizer_state_dict"])

In [51]:
start_epoch = 66
end_epoch = 70
start_epoch, end_epoch

(66, 70)

In [52]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageC, train_loader, val_loader, inverse_frequency_criterion, stageC_optimizer, train_dataset.classes,
                         start_epoch, end_epoch, model_name = 'mobilenetv2_stageC', save_dir = 'mobilenetv2',
                         class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 66 - Training Started...

Epoch 66, Batch 100, Loss: 0.1151, Accuracy: 95.69%, Time Passed: 2.96m
Epoch 66, Batch 200, Loss: 0.1178, Accuracy: 95.39%, Time Passed: 5.98m
Epoch 66, Batch 300, Loss: 0.1198, Accuracy: 95.49%, Time Passed: 9.09m
Epoch 66, Batch 400, Loss: 0.1155, Accuracy: 95.55%, Time Passed: 12.24m
Epoch 66, Batch 500, Loss: 0.1158, Accuracy: 95.59%, Time Passed: 15.46m
Epoch 66 Completed - Average Loss: 0.1139, Accuracy: 95.69%, Epoch Time: 16.85m
Training Complete Epoch 66 - Total Time: 16.85m

✅ Epoch 66 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8414, Accuracy: 76.91%, Time Passed: 4.01m
Evaluation Complete - Loss: 0.7586, Accuracy: 80.42%, Total Time: 6.83m

📊 Epoch 66 - Evaluation Completed.


🚀 Epoch 67 - Training Started...

Epoch 67, Batch 100, Loss: 0.1267, Accuracy: 95.56%, Time Passed: 3.26m
Epoch 67, Batch 200, Loss: 0.1270, Accuracy: 95.41%, Time Passed: 6.91m
Epoch 67, Batch 300, Loss: 0.1287, Accuracy: 95.31%, Time Passed: 10.69m
Epoch 67, Batch 400, Loss: 0.1249, Accuracy: 95.42%, Time Passed: 14.53m
Epoch 67, Batch 500, Loss: 0.1208, Accuracy: 95.53%, Time Passed: 18.42m
Epoch 67 Completed - Average Loss: 0.1211, Accuracy: 95.55%, Epoch Time: 19.90m
Training Complete Epoch 67 - Total Time: 19.90m

✅ Epoch 67 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8909, Accuracy: 76.28%, Time Passed: 4.36m
Evaluation Complete - Loss: 0.7933, Accuracy: 80.13%, Total Time: 7.35m

📊 Epoch 67 - Evaluation Completed.


🚀 Epoch 68 - Training Started...

Epoch 68, Batch 100, Loss: 0.1051, Accuracy: 96.00%, Time Passed: 3.75m
Epoch 68, Batch 200, Loss: 0.1135, Accuracy: 95.86%, Time Passed: 7.70m
Epoch 68, Batch 300, Loss: 0.1131, Accuracy: 95.80%, Time Passed: 11.52m
Epoch 68, Batch 400, Loss: 0.1103, Accuracy: 95.91%, Time Passed: 15.06m
Epoch 68, Batch 500, Loss: 0.1124, Accuracy: 95.88%, Time Passed: 18.69m
Epoch 68 Completed - Average Loss: 0.1120, Accuracy: 95.93%, Epoch Time: 20.21m
Training Complete Epoch 68 - Total Time: 20.21m

✅ Epoch 68 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8361, Accuracy: 77.44%, Time Passed: 4.17m
Evaluation Complete - Loss: 0.7505, Accuracy: 80.73%, Total Time: 7.09m

📊 Epoch 68 - Evaluation Completed.


🚀 Epoch 69 - Training Started...

Epoch 69, Batch 100, Loss: 0.1030, Accuracy: 95.78%, Time Passed: 3.37m
Epoch 69, Batch 200, Loss: 0.1148, Accuracy: 95.66%, Time Passed: 6.70m
Epoch 69, Batch 300, Loss: 0.1149, Accuracy: 95.81%, Time Passed: 10.09m
Epoch 69, Batch 400, Loss: 0.1172, Accuracy: 95.62%, Time Passed: 13.55m
Epoch 69, Batch 500, Loss: 0.1153, Accuracy: 95.72%, Time Passed: 16.97m
Epoch 69 Completed - Average Loss: 0.1146, Accuracy: 95.72%, Epoch Time: 18.40m
Training Complete Epoch 69 - Total Time: 18.40m

✅ Epoch 69 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8840, Accuracy: 75.88%, Time Passed: 4.17m
Evaluation Complete - Loss: 0.8007, Accuracy: 79.38%, Total Time: 7.33m

📊 Epoch 69 - Evaluation Completed.


🚀 Epoch 70 - Training Started...

Epoch 70, Batch 100, Loss: 0.1070, Accuracy: 96.00%, Time Passed: 3.66m
Epoch 70, Batch 200, Loss: 0.1005, Accuracy: 96.08%, Time Passed: 7.81m
Epoch 70, Batch 300, Loss: 0.1044, Accuracy: 95.98%, Time Passed: 12.13m
Epoch 70, Batch 400, Loss: 0.1068, Accuracy: 95.97%, Time Passed: 16.44m
Epoch 70, Batch 500, Loss: 0.1071, Accuracy: 95.95%, Time Passed: 21.10m
Epoch 70 Completed - Average Loss: 0.1083, Accuracy: 95.96%, Epoch Time: 22.84m
Training Complete Epoch 70 - Total Time: 22.84m

✅ Epoch 70 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8638, Accuracy: 76.19%, Time Passed: 4.44m
Evaluation Complete - Loss: 0.7674, Accuracy: 79.87%, Total Time: 7.33m

📊 Epoch 70 - Evaluation Completed.

## **Stage D**

### **Checkpoint Validation**

In [55]:
training_states = joblib.load(f'mobilenetv2/training_states_{61}_{65}.pkl')

In [42]:
mobilenetv2_stageD = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes))

# Send it to device
device = torch.device("mps")
mobilenetv2_stageD.to(device)
mobilenetv2_stageD.load_state_dict(training_states[65]["model_state_dict"])

In [44]:
mobilenetv2_stageD = configure_mobilenetv2_training(
                                                    mobilenetv2_stageD,
                                                    NUM_CLASSES, intermediate=True,
                                                    intermediate_blocks = [0, 6]
                                                   )
df_summary = summarize_mobilenetv2_blocks(mobilenetv2_stageD)
df_summary

🟢 Intermediate stage → Newly unfrozen blocks: [13, 14, 15, 16, 17, 18]
✅ Trainable layers: 50/158 (31.65%)
✅ Trainable params: 1,841,889/2,266,145 (81.28%)

,Block,Order,Module,Layers (#),Params (#),Trainable Params (#),% Layers (Model),% Params (Model),% Trainable Params (Model),Cumulative Layers (Model),Cumulative % Layers (Model),Cumulative Params (Model),Cumulative % Params (Model),Layers (Module %),Params (Module %),Trainable Params (Module %),Cumulative Layers (Module),Cumulative % Layers (Module),Cumulative Params (Module),Cumulative % Params (Module)
0,Conv2dNormActivation_1,1,features,3,928,0,1.898734,0.040951,0.000000,158,100.000000,2266145,100.000000,1.923077,0.041729,0.000000,156,100.000000,2223872,100.000000
1,InvertedResidual_2,2,features,6,896,0,3.797468,0.039539,0.000000,155,98.101266,2265217,99.959049,3.846154,0.040290,0.000000,153,98.076923,2222944,99.958271
2,InvertedResidual_3,3,features,9,5136,0,5.696203,0.226640,0.000000,149,94.303797,2264321,99.919511,5.769231,0.230949,0.000000,147,94.230769,2222048,99.917981
3,InvertedResidual_4,4,features,9,8832,0,5.696203,0.389737,0.000000,140,88.607595,2259185,99.692870,5.769231,0.397145,0.000000,138,88.461538,2216912,99.687032
4,InvertedResidual_5,5,features,9,10000,0,5.696203,0.441278,0.000000,131,82.911392,2250353,99.303134,5.769231,0.449666,0.000000,129,82.692308,2208080,99.289887
5,InvertedResidual_6,6,features,9,14848,0,5.696203,0.655210,0.000000,122,77.215190,2240353,98.861856,5.769231,0.667664,0.000000,120,76.923077,2198080,98.840221
6,InvertedResidual_7,7,features,9,14848,0,5.696203,0.655210,0.000000,113,71.518987,2225505,98.206646,5.769231,0.667664,0.000000,111,71.153846,2183232,98.172557
7,InvertedResidual_8,8,features,9,21056,0,5.696203,0.929155,0.000000,104,65.822785,2210657,97.551436,5.769231,0.946817,0.000000,102,65.384615,2168384,97.504892
8,InvertedResidual_9,9,features,9,54272,0,5.696203,2.394904,0.000000,95,60.126582,2189601,96.622281,5.769231,2.440428,0.000000,93,59.615385,2147328,96.558075
9,InvertedResidual_10,10,features,9,54272,0,5.696203,2.394904,0.000000,86,54.430380,2135329,94.227377,5.769231,2.440428,0.000000,84,53.846154,2093056,94.117647
10,InvertedResidual_11,11,features,9,54272,0,5.696203,2.394904,0.000000,77,48.734177,2081057,91.832473,5.769231,2.440428,0.000000,75,48.076923,2038784,91.677219
11,InvertedResidual_12,12,features,9,66624,0,5.696203,2.939971,0.000000,68,43.037975,2026785,89.437569,5.769231,2.995856,0.000000,66,42.307692,1984512,89.236791
12,InvertedResidual_13,13,features,9,118272,0,5.696203,5.219084,0.000000,59,37.341772,1960161,86.497598,5.769231,5.318292,0.000000,57,36.538462,1917888,86.240935
13,InvertedResidual_14,14,features,9,118272,118272,5.696203,5.219084,5.219084,50,31.645570,1841889,81.278515,5.769231,5.318292,6.572069,48,30.769231,1799616,80.922643
14,InvertedResidual_15,15,features,9,155264,155264,5.696203,6.851459,6.851459,41,25.949367,1723617,76.059431,5.769231,6.981697,8.627618,39,25.000000,1681344,75.604351
15,InvertedResidual_16,16,features,9,320000,320000,5.696203,14.120897,14.120897,32,20.253165,1568353,69.207972,5.769231,14.389317,17.781571,30,19.230769,1526080,68.622655
16,InvertedResidual_17,17,features,9,320000,320000,5.696203,14.120897,14.120897,23,14.556962,1248353,55.087075,5.769231,14.389317,17.781571,21,13.461538,1206080,54.233337
17,InvertedResidual_18,18,features,9,473920,473920,5.696203,20.913048,20.913048,14,8.860759,928353,40.966178,5.769231,21.310579,26.334507,12,7.692308,886080,39.844020
18,Conv2dNormActivation_19,19,features,3,412160,412160,1.898734,18.187715,18.187715,5,3.164557,454433,20.053130,1.923077,18.533441,22.902664,3,1.923077,412160,18.533441
19,Sequential,20,classifier,2,42273,42273,1.265823,1.865415,1.865415,2,1.265823,42273,1.865415,100.000000,100.000000,100.000000,2,100.000000,42273,100.000000

In [59]:
_ = evaluate_model(
            mobilenetv2_stageD, val_loader, inverse_frequency_criterion, train_dataset.classes, epoch_num=65, log_interval=100)

Batch 100, Loss: 0.7736, Accuracy: 79.16%, Time Passed: 3.77m
Evaluation Complete - Loss: 0.7406, Accuracy: 81.37%, Total Time: 6.55m

### **Continue Training**

In [45]:
stageD_optimizer = torch.optim.AdamW(
    mobilenetv2_stageD.parameters(),
    lr=3e-5,    # even smaller LR, since more params unfrozen
    weight_decay=1e-4,
    betas=(0.9, 0.999)
)

In [66]:
start_epoch = 66
end_epoch = 70
start_epoch, end_epoch

(66, 70)

In [67]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageD, train_loader, val_loader, inverse_frequency_criterion, stageD_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageD',
                                                          save_dir = 'mobilenetv2', class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 66 - Training Started...

Epoch 66, Batch 100, Loss: 0.1146, Accuracy: 95.84%, Time Passed: 3.30m
Epoch 66, Batch 200, Loss: 0.1142, Accuracy: 95.81%, Time Passed: 6.71m
Epoch 66, Batch 300, Loss: 0.1078, Accuracy: 96.09%, Time Passed: 10.13m
Epoch 66, Batch 400, Loss: 0.1066, Accuracy: 96.12%, Time Passed: 13.61m
Epoch 66, Batch 500, Loss: 0.1107, Accuracy: 95.99%, Time Passed: 17.09m
Epoch 66 Completed - Average Loss: 0.1128, Accuracy: 95.91%, Epoch Time: 18.61m
Training Complete Epoch 66 - Total Time: 18.61m

✅ Epoch 66 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8173, Accuracy: 77.78%, Time Passed: 4.03m
Evaluation Complete - Loss: 0.7495, Accuracy: 80.77%, Total Time: 6.88m

📊 Epoch 66 - Evaluation Completed.


🚀 Epoch 67 - Training Started...

Epoch 67, Batch 100, Loss: 0.1160, Accuracy: 96.00%, Time Passed: 3.39m
Epoch 67, Batch 200, Loss: 0.1068, Accuracy: 96.41%, Time Passed: 6.80m
Epoch 67, Batch 300, Loss: 0.1103, Accuracy: 96.20%, Time Passed: 10.44m
Epoch 67, Batch 400, Loss: 0.1141, Accuracy: 96.09%, Time Passed: 14.02m
Epoch 67, Batch 500, Loss: 0.1153, Accuracy: 96.04%, Time Passed: 17.50m
Epoch 67 Completed - Average Loss: 0.1151, Accuracy: 96.01%, Epoch Time: 18.96m
Training Complete Epoch 67 - Total Time: 18.96m

✅ Epoch 67 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8191, Accuracy: 77.09%, Time Passed: 4.13m
Evaluation Complete - Loss: 0.7509, Accuracy: 80.38%, Total Time: 7.30m

📊 Epoch 67 - Evaluation Completed.


🚀 Epoch 68 - Training Started...

Epoch 68, Batch 100, Loss: 0.1121, Accuracy: 96.16%, Time Passed: 4.54m
Epoch 68, Batch 200, Loss: 0.1176, Accuracy: 95.59%, Time Passed: 11.16m
Epoch 68, Batch 300, Loss: 0.1157, Accuracy: 95.68%, Time Passed: 17.07m
Epoch 68, Batch 400, Loss: 0.1150, Accuracy: 95.58%, Time Passed: 23.61m
Epoch 68, Batch 500, Loss: 0.1124, Accuracy: 95.67%, Time Passed: 29.60m
Epoch 68 Completed - Average Loss: 0.1111, Accuracy: 95.72%, Epoch Time: 31.40m
Training Complete Epoch 68 - Total Time: 31.40m

✅ Epoch 68 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8382, Accuracy: 77.38%, Time Passed: 3.94m
Evaluation Complete - Loss: 0.7620, Accuracy: 80.44%, Total Time: 6.83m

📊 Epoch 68 - Evaluation Completed.


🚀 Epoch 69 - Training Started...

Epoch 69, Batch 100, Loss: 0.0950, Accuracy: 96.66%, Time Passed: 3.50m
Epoch 69, Batch 200, Loss: 0.0992, Accuracy: 96.45%, Time Passed: 7.07m
Epoch 69, Batch 300, Loss: 0.1016, Accuracy: 96.39%, Time Passed: 10.66m
Epoch 69, Batch 400, Loss: 0.1023, Accuracy: 96.23%, Time Passed: 14.20m
Epoch 69, Batch 500, Loss: 0.1020, Accuracy: 96.28%, Time Passed: 17.64m
Epoch 69 Completed - Average Loss: 0.1021, Accuracy: 96.26%, Epoch Time: 19.07m
Training Complete Epoch 69 - Total Time: 19.07m

✅ Epoch 69 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8427, Accuracy: 77.06%, Time Passed: 4.08m
Evaluation Complete - Loss: 0.7731, Accuracy: 80.15%, Total Time: 6.84m

📊 Epoch 69 - Evaluation Completed.


🚀 Epoch 70 - Training Started...

Epoch 70, Batch 100, Loss: 0.1032, Accuracy: 96.31%, Time Passed: 3.20m
Epoch 70, Batch 200, Loss: 0.1070, Accuracy: 95.88%, Time Passed: 6.40m
Epoch 70, Batch 300, Loss: 0.1034, Accuracy: 96.01%, Time Passed: 9.66m
Epoch 70, Batch 400, Loss: 0.1022, Accuracy: 96.03%, Time Passed: 13.04m
Epoch 70, Batch 500, Loss: 0.1027, Accuracy: 96.00%, Time Passed: 16.37m
Epoch 70 Completed - Average Loss: 0.1042, Accuracy: 95.95%, Epoch Time: 17.80m
Training Complete Epoch 70 - Total Time: 17.80m

✅ Epoch 70 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7504, Accuracy: 79.88%, Time Passed: 4.04m
Evaluation Complete - Loss: 0.7136, Accuracy: 82.15%, Total Time: 6.83m

📊 Epoch 70 - Evaluation Completed.

In [70]:
end_epoch

70

In [71]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}DDDD.pkl')

In [72]:
del training_states

In [74]:
start_epoch = 71
end_epoch = 72
start_epoch, end_epoch

(71, 72)

In [75]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageD, train_loader, val_loader, inverse_frequency_criterion, stageD_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageD',
                                                          save_dir = 'mobilenetv2', class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 71 - Training Started...

Epoch 71, Batch 100, Loss: 0.1129, Accuracy: 95.84%, Time Passed: 3.24m
Epoch 71, Batch 200, Loss: 0.1020, Accuracy: 96.33%, Time Passed: 6.72m
Epoch 71, Batch 300, Loss: 0.0957, Accuracy: 96.34%, Time Passed: 10.15m
Epoch 71, Batch 400, Loss: 0.0998, Accuracy: 96.21%, Time Passed: 13.73m
Epoch 71, Batch 500, Loss: 0.1006, Accuracy: 96.16%, Time Passed: 17.24m
Epoch 71 Completed - Average Loss: 0.1009, Accuracy: 96.15%, Epoch Time: 18.64m
Training Complete Epoch 71 - Total Time: 18.64m

✅ Epoch 71 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7871, Accuracy: 78.97%, Time Passed: 3.98m
Evaluation Complete - Loss: 0.7560, Accuracy: 81.19%, Total Time: 6.74m

📊 Epoch 71 - Evaluation Completed.


🚀 Epoch 72 - Training Started...

Epoch 72, Batch 100, Loss: 0.1007, Accuracy: 96.56%, Time Passed: 3.27m
Epoch 72, Batch 200, Loss: 0.0985, Accuracy: 96.62%, Time Passed: 6.52m
Epoch 72, Batch 300, Loss: 0.0940, Accuracy: 96.56%, Time Passed: 9.84m
Epoch 72, Batch 400, Loss: 0.0930, Accuracy: 96.55%, Time Passed: 13.11m
Epoch 72, Batch 500, Loss: 0.0949, Accuracy: 96.41%, Time Passed: 16.49m
Epoch 72 Completed - Average Loss: 0.0934, Accuracy: 96.49%, Epoch Time: 17.92m
Training Complete Epoch 72 - Total Time: 17.92m

✅ Epoch 72 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8265, Accuracy: 78.06%, Time Passed: 3.98m
Evaluation Complete - Loss: 0.7339, Accuracy: 81.58%, Total Time: 6.73m

📊 Epoch 72 - Evaluation Completed.

In [76]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}DDDD.pkl')

- The DDDD suffix was used as an internal filename marker to distinguish Stage D checkpoints from Stage C checkpoints covering the same epoch range.

In [77]:
del training_states

In [52]:
start_epoch = 73
end_epoch = 80
start_epoch, end_epoch

(73, 80)

In [53]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageD, train_loader, val_loader, inverse_frequency_criterion, stageD_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageD',
                                                          save_dir = 'mobilenetv2', class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 73 - Training Started...

Epoch 73, Batch 100, Loss: 0.0853, Accuracy: 96.84%, Time Passed: 3.10m
Epoch 73, Batch 200, Loss: 0.0963, Accuracy: 96.44%, Time Passed: 6.39m
Epoch 73, Batch 300, Loss: 0.0934, Accuracy: 96.62%, Time Passed: 9.59m
Epoch 73, Batch 400, Loss: 0.0968, Accuracy: 96.47%, Time Passed: 12.80m
Epoch 73, Batch 500, Loss: 0.0962, Accuracy: 96.45%, Time Passed: 16.11m
Epoch 73 Completed - Average Loss: 0.0955, Accuracy: 96.43%, Epoch Time: 17.65m
Training Complete Epoch 73 - Total Time: 17.65m

✅ Epoch 73 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8855, Accuracy: 76.88%, Time Passed: 4.38m
Evaluation Complete - Loss: 0.8127, Accuracy: 79.92%, Total Time: 7.32m

📊 Epoch 73 - Evaluation Completed.


🚀 Epoch 74 - Training Started...

Epoch 74, Batch 100, Loss: 0.0913, Accuracy: 96.53%, Time Passed: 3.33m
Epoch 74, Batch 200, Loss: 0.0919, Accuracy: 96.56%, Time Passed: 6.57m
Epoch 74, Batch 300, Loss: 0.0958, Accuracy: 96.40%, Time Passed: 9.79m
Epoch 74, Batch 400, Loss: 0.0933, Accuracy: 96.45%, Time Passed: 13.02m
Epoch 74, Batch 500, Loss: 0.0982, Accuracy: 96.29%, Time Passed: 16.29m
Epoch 74 Completed - Average Loss: 0.0970, Accuracy: 96.36%, Epoch Time: 17.70m
Training Complete Epoch 74 - Total Time: 17.70m

✅ Epoch 74 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7737, Accuracy: 79.03%, Time Passed: 3.88m
Evaluation Complete - Loss: 0.6973, Accuracy: 82.04%, Total Time: 6.60m

📊 Epoch 74 - Evaluation Completed.


🚀 Epoch 75 - Training Started...

Epoch 75, Batch 100, Loss: 0.0853, Accuracy: 96.81%, Time Passed: 3.13m
Epoch 75, Batch 200, Loss: 0.0907, Accuracy: 96.64%, Time Passed: 6.33m
Epoch 75, Batch 300, Loss: 0.0887, Accuracy: 96.75%, Time Passed: 9.58m
Epoch 75, Batch 400, Loss: 0.0896, Accuracy: 96.75%, Time Passed: 12.81m
Epoch 75, Batch 500, Loss: 0.0889, Accuracy: 96.78%, Time Passed: 16.01m
Epoch 75 Completed - Average Loss: 0.0883, Accuracy: 96.77%, Epoch Time: 17.39m
Training Complete Epoch 75 - Total Time: 17.39m

✅ Epoch 75 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8282, Accuracy: 77.91%, Time Passed: 3.86m
Evaluation Complete - Loss: 0.7581, Accuracy: 81.08%, Total Time: 6.58m

📊 Epoch 75 - Evaluation Completed.


🚀 Epoch 76 - Training Started...

Epoch 76, Batch 100, Loss: 0.0869, Accuracy: 96.75%, Time Passed: 3.11m
Epoch 76, Batch 200, Loss: 0.0901, Accuracy: 96.58%, Time Passed: 6.24m
Epoch 76, Batch 300, Loss: 0.0912, Accuracy: 96.52%, Time Passed: 9.41m
Epoch 76, Batch 400, Loss: 0.0931, Accuracy: 96.41%, Time Passed: 12.82m
Epoch 76, Batch 500, Loss: 0.0942, Accuracy: 96.40%, Time Passed: 16.18m
Epoch 76 Completed - Average Loss: 0.0931, Accuracy: 96.40%, Epoch Time: 17.59m
Training Complete Epoch 76 - Total Time: 17.59m

✅ Epoch 76 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8194, Accuracy: 78.62%, Time Passed: 3.96m
Evaluation Complete - Loss: 0.7519, Accuracy: 81.58%, Total Time: 6.74m

📊 Epoch 76 - Evaluation Completed.


🚀 Epoch 77 - Training Started...

Epoch 77, Batch 100, Loss: 0.0873, Accuracy: 96.69%, Time Passed: 3.25m
Epoch 77, Batch 200, Loss: 0.0970, Accuracy: 96.34%, Time Passed: 6.43m
Epoch 77, Batch 300, Loss: 0.0934, Accuracy: 96.49%, Time Passed: 9.76m
Epoch 77, Batch 400, Loss: 0.0916, Accuracy: 96.49%, Time Passed: 13.02m
Epoch 77, Batch 500, Loss: 0.0898, Accuracy: 96.59%, Time Passed: 16.32m
Epoch 77 Completed - Average Loss: 0.0891, Accuracy: 96.63%, Epoch Time: 17.65m
Training Complete Epoch 77 - Total Time: 17.65m

✅ Epoch 77 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8163, Accuracy: 78.44%, Time Passed: 3.96m
Evaluation Complete - Loss: 0.7443, Accuracy: 81.33%, Total Time: 6.76m

📊 Epoch 77 - Evaluation Completed.


🚀 Epoch 78 - Training Started...

Epoch 78, Batch 100, Loss: 0.0907, Accuracy: 96.88%, Time Passed: 3.27m
Epoch 78, Batch 200, Loss: 0.0886, Accuracy: 96.81%, Time Passed: 6.59m
Epoch 78, Batch 300, Loss: 0.0887, Accuracy: 96.86%, Time Passed: 9.93m
Epoch 78, Batch 400, Loss: 0.0870, Accuracy: 96.78%, Time Passed: 13.45m
Epoch 78, Batch 500, Loss: 0.0886, Accuracy: 96.76%, Time Passed: 16.92m
Epoch 78 Completed - Average Loss: 0.0890, Accuracy: 96.72%, Epoch Time: 18.38m
Training Complete Epoch 78 - Total Time: 18.38m

✅ Epoch 78 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7852, Accuracy: 78.66%, Time Passed: 4.08m
Evaluation Complete - Loss: 0.7556, Accuracy: 81.25%, Total Time: 6.97m

📊 Epoch 78 - Evaluation Completed.


🚀 Epoch 79 - Training Started...

Epoch 79, Batch 100, Loss: 0.0837, Accuracy: 96.81%, Time Passed: 3.28m
Epoch 79, Batch 200, Loss: 0.0838, Accuracy: 96.73%, Time Passed: 6.64m
Epoch 79, Batch 300, Loss: 0.0833, Accuracy: 96.88%, Time Passed: 10.12m
Epoch 79, Batch 400, Loss: 0.0808, Accuracy: 96.93%, Time Passed: 13.68m
Epoch 79, Batch 500, Loss: 0.0800, Accuracy: 96.94%, Time Passed: 17.07m
Epoch 79 Completed - Average Loss: 0.0795, Accuracy: 96.96%, Epoch Time: 18.40m
Training Complete Epoch 79 - Total Time: 18.40m

✅ Epoch 79 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8148, Accuracy: 78.62%, Time Passed: 3.94m
Evaluation Complete - Loss: 0.7445, Accuracy: 81.48%, Total Time: 6.80m

📊 Epoch 79 - Evaluation Completed.


🚀 Epoch 80 - Training Started...

Epoch 80, Batch 100, Loss: 0.0760, Accuracy: 97.22%, Time Passed: 3.39m
Epoch 80, Batch 200, Loss: 0.0801, Accuracy: 97.11%, Time Passed: 7.03m
Epoch 80, Batch 300, Loss: 0.0873, Accuracy: 96.89%, Time Passed: 10.60m
Epoch 80, Batch 400, Loss: 0.0842, Accuracy: 96.96%, Time Passed: 14.17m
Epoch 80, Batch 500, Loss: 0.0835, Accuracy: 97.03%, Time Passed: 17.64m
Epoch 80 Completed - Average Loss: 0.0827, Accuracy: 97.03%, Epoch Time: 19.06m
Training Complete Epoch 80 - Total Time: 19.06m

✅ Epoch 80 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7759, Accuracy: 79.47%, Time Passed: 4.10m
Evaluation Complete - Loss: 0.7199, Accuracy: 81.98%, Total Time: 6.98m

📊 Epoch 80 - Evaluation Completed.

In [54]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [55]:
del training_states

In [57]:
start_epoch = 81
end_epoch = 83
start_epoch, end_epoch

(81, 83)

In [58]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageD, train_loader, val_loader, inverse_frequency_criterion, stageD_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageD',
                                                          save_dir = 'mobilenetv2', class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 81 - Training Started...

Epoch 81, Batch 100, Loss: 0.0758, Accuracy: 97.16%, Time Passed: 3.25m
Epoch 81, Batch 200, Loss: 0.0744, Accuracy: 97.09%, Time Passed: 6.61m
Epoch 81, Batch 300, Loss: 0.0812, Accuracy: 96.91%, Time Passed: 10.18m
Epoch 81, Batch 400, Loss: 0.0809, Accuracy: 97.07%, Time Passed: 13.73m
Epoch 81, Batch 500, Loss: 0.0811, Accuracy: 97.03%, Time Passed: 17.43m
Epoch 81 Completed - Average Loss: 0.0812, Accuracy: 97.05%, Epoch Time: 18.93m
Training Complete Epoch 81 - Total Time: 18.93m

✅ Epoch 81 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7886, Accuracy: 78.78%, Time Passed: 4.17m
Evaluation Complete - Loss: 0.6984, Accuracy: 82.10%, Total Time: 7.03m

📊 Epoch 81 - Evaluation Completed.


🚀 Epoch 82 - Training Started...

Epoch 82, Batch 100, Loss: 0.0813, Accuracy: 97.25%, Time Passed: 3.34m
Epoch 82, Batch 200, Loss: 0.0834, Accuracy: 97.02%, Time Passed: 6.61m
Epoch 82, Batch 300, Loss: 0.0863, Accuracy: 96.93%, Time Passed: 9.98m
Epoch 82, Batch 400, Loss: 0.0858, Accuracy: 96.91%, Time Passed: 13.24m
Epoch 82, Batch 500, Loss: 0.0850, Accuracy: 96.97%, Time Passed: 16.58m
Epoch 82 Completed - Average Loss: 0.0841, Accuracy: 97.03%, Epoch Time: 18.00m
Training Complete Epoch 82 - Total Time: 18.00m

✅ Epoch 82 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7733, Accuracy: 78.94%, Time Passed: 3.95m
Evaluation Complete - Loss: 0.6854, Accuracy: 82.21%, Total Time: 6.75m

📊 Epoch 82 - Evaluation Completed.


🚀 Epoch 83 - Training Started...

Epoch 83, Batch 100, Loss: 0.0759, Accuracy: 97.25%, Time Passed: 3.23m
Epoch 83, Batch 200, Loss: 0.0821, Accuracy: 96.94%, Time Passed: 6.50m
Epoch 83, Batch 300, Loss: 0.0768, Accuracy: 97.12%, Time Passed: 9.79m
Epoch 83, Batch 400, Loss: 0.0789, Accuracy: 97.05%, Time Passed: 13.03m
Epoch 83, Batch 500, Loss: 0.0809, Accuracy: 97.04%, Time Passed: 16.39m
Epoch 83 Completed - Average Loss: 0.0799, Accuracy: 97.02%, Epoch Time: 17.79m
Training Complete Epoch 83 - Total Time: 17.79m

✅ Epoch 83 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7898, Accuracy: 79.66%, Time Passed: 3.96m
Evaluation Complete - Loss: 0.7202, Accuracy: 82.56%, Total Time: 6.73m

📊 Epoch 83 - Evaluation Completed.

In [63]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [64]:
del training_states

In [66]:
start_epoch = 84
end_epoch = 90
start_epoch, end_epoch

(84, 90)

In [67]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageD, train_loader, val_loader, inverse_frequency_criterion, stageD_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageD',
                                                          save_dir = 'mobilenetv2', class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 84 - Training Started...

Epoch 84, Batch 100, Loss: 0.0790, Accuracy: 97.38%, Time Passed: 3.11m
Epoch 84, Batch 200, Loss: 0.0744, Accuracy: 97.38%, Time Passed: 6.26m
Epoch 84, Batch 300, Loss: 0.0765, Accuracy: 97.36%, Time Passed: 9.49m
Epoch 84, Batch 400, Loss: 0.0735, Accuracy: 97.39%, Time Passed: 12.85m
Epoch 84, Batch 500, Loss: 0.0759, Accuracy: 97.22%, Time Passed: 16.14m
Epoch 84 Completed - Average Loss: 0.0764, Accuracy: 97.25%, Epoch Time: 17.52m
Training Complete Epoch 84 - Total Time: 17.52m

✅ Epoch 84 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7651, Accuracy: 80.19%, Time Passed: 3.89m
Evaluation Complete - Loss: 0.6739, Accuracy: 83.27%, Total Time: 6.58m

📊 Epoch 84 - Evaluation Completed.


🚀 Epoch 85 - Training Started...

Epoch 85, Batch 100, Loss: 0.0799, Accuracy: 96.53%, Time Passed: 3.11m
Epoch 85, Batch 200, Loss: 0.0844, Accuracy: 96.77%, Time Passed: 6.28m
Epoch 85, Batch 300, Loss: 0.0831, Accuracy: 96.86%, Time Passed: 9.44m
Epoch 85, Batch 400, Loss: 0.0827, Accuracy: 96.88%, Time Passed: 12.62m
Epoch 85, Batch 500, Loss: 0.0802, Accuracy: 96.97%, Time Passed: 15.80m
Epoch 85 Completed - Average Loss: 0.0824, Accuracy: 96.95%, Epoch Time: 17.29m
Training Complete Epoch 85 - Total Time: 17.29m

✅ Epoch 85 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7603, Accuracy: 80.28%, Time Passed: 4.48m
Evaluation Complete - Loss: 0.7023, Accuracy: 82.81%, Total Time: 7.37m

📊 Epoch 85 - Evaluation Completed.


🚀 Epoch 86 - Training Started...

Epoch 86, Batch 100, Loss: 0.0779, Accuracy: 97.19%, Time Passed: 3.79m
Epoch 86, Batch 200, Loss: 0.0850, Accuracy: 97.05%, Time Passed: 7.74m
Epoch 86, Batch 300, Loss: 0.0820, Accuracy: 96.99%, Time Passed: 11.45m
Epoch 86, Batch 400, Loss: 0.0830, Accuracy: 96.95%, Time Passed: 15.11m
Epoch 86, Batch 500, Loss: 0.0828, Accuracy: 97.01%, Time Passed: 18.79m
Epoch 86 Completed - Average Loss: 0.0833, Accuracy: 96.98%, Epoch Time: 20.36m
Training Complete Epoch 86 - Total Time: 20.36m

✅ Epoch 86 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7856, Accuracy: 79.19%, Time Passed: 4.39m
Evaluation Complete - Loss: 0.6947, Accuracy: 82.37%, Total Time: 7.49m

📊 Epoch 86 - Evaluation Completed.


🚀 Epoch 87 - Training Started...

Epoch 87, Batch 100, Loss: 0.0887, Accuracy: 96.84%, Time Passed: 3.40m
Epoch 87, Batch 200, Loss: 0.0831, Accuracy: 96.97%, Time Passed: 6.77m
Epoch 87, Batch 300, Loss: 0.0791, Accuracy: 97.05%, Time Passed: 10.51m
Epoch 87, Batch 400, Loss: 0.0765, Accuracy: 97.15%, Time Passed: 14.17m
Epoch 87, Batch 500, Loss: 0.0751, Accuracy: 97.22%, Time Passed: 17.83m
Epoch 87 Completed - Average Loss: 0.0731, Accuracy: 97.33%, Epoch Time: 19.31m
Training Complete Epoch 87 - Total Time: 19.31m

✅ Epoch 87 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7804, Accuracy: 78.47%, Time Passed: 4.21m
Evaluation Complete - Loss: 0.7143, Accuracy: 81.37%, Total Time: 7.39m

📊 Epoch 87 - Evaluation Completed.


🚀 Epoch 88 - Training Started...

Epoch 88, Batch 100, Loss: 0.0654, Accuracy: 97.41%, Time Passed: 3.85m
Epoch 88, Batch 200, Loss: 0.0657, Accuracy: 97.47%, Time Passed: 7.88m
Epoch 88, Batch 300, Loss: 0.0712, Accuracy: 97.29%, Time Passed: 11.93m
Epoch 88, Batch 400, Loss: 0.0712, Accuracy: 97.38%, Time Passed: 15.83m
Epoch 88, Batch 500, Loss: 0.0717, Accuracy: 97.36%, Time Passed: 19.78m
Epoch 88 Completed - Average Loss: 0.0716, Accuracy: 97.36%, Epoch Time: 21.43m
Training Complete Epoch 88 - Total Time: 21.43m

✅ Epoch 88 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7831, Accuracy: 78.91%, Time Passed: 4.54m
Evaluation Complete - Loss: 0.7133, Accuracy: 81.79%, Total Time: 7.56m

📊 Epoch 88 - Evaluation Completed.


🚀 Epoch 89 - Training Started...

Epoch 89, Batch 100, Loss: 0.0761, Accuracy: 97.25%, Time Passed: 3.75m
Epoch 89, Batch 200, Loss: 0.0791, Accuracy: 97.30%, Time Passed: 7.46m
Epoch 89, Batch 300, Loss: 0.0769, Accuracy: 97.38%, Time Passed: 11.24m
Epoch 89, Batch 400, Loss: 0.0783, Accuracy: 97.27%, Time Passed: 14.97m
Epoch 89, Batch 500, Loss: 0.0777, Accuracy: 97.26%, Time Passed: 18.56m
Epoch 89 Completed - Average Loss: 0.0772, Accuracy: 97.24%, Epoch Time: 20.12m
Training Complete Epoch 89 - Total Time: 20.12m

✅ Epoch 89 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7742, Accuracy: 80.44%, Time Passed: 4.25m
Evaluation Complete - Loss: 0.6870, Accuracy: 83.15%, Total Time: 7.24m

📊 Epoch 89 - Evaluation Completed.


🚀 Epoch 90 - Training Started...

Epoch 90, Batch 100, Loss: 0.0715, Accuracy: 97.81%, Time Passed: 3.59m
Epoch 90, Batch 200, Loss: 0.0751, Accuracy: 97.45%, Time Passed: 7.21m
Epoch 90, Batch 300, Loss: 0.0774, Accuracy: 97.38%, Time Passed: 10.57m
Epoch 90, Batch 400, Loss: 0.0755, Accuracy: 97.40%, Time Passed: 13.92m
Epoch 90, Batch 500, Loss: 0.0758, Accuracy: 97.35%, Time Passed: 17.23m
Epoch 90 Completed - Average Loss: 0.0745, Accuracy: 97.37%, Epoch Time: 18.63m
Training Complete Epoch 90 - Total Time: 18.63m

✅ Epoch 90 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7652, Accuracy: 80.25%, Time Passed: 4.09m
Evaluation Complete - Loss: 0.6796, Accuracy: 82.94%, Total Time: 6.92m

📊 Epoch 90 - Evaluation Completed.

In [71]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [72]:
del training_states

In [74]:
start_epoch = 91
end_epoch = 95
start_epoch, end_epoch

(91, 95)

In [75]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageD, train_loader, val_loader, inverse_frequency_criterion, stageD_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageD',
                                                          save_dir = 'mobilenetv2', class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 91 - Training Started...

Epoch 91, Batch 100, Loss: 0.0604, Accuracy: 97.66%, Time Passed: 3.36m
Epoch 91, Batch 200, Loss: 0.0697, Accuracy: 97.34%, Time Passed: 6.90m
Epoch 91, Batch 300, Loss: 0.0713, Accuracy: 97.24%, Time Passed: 10.42m
Epoch 91, Batch 400, Loss: 0.0702, Accuracy: 97.33%, Time Passed: 13.74m
Epoch 91, Batch 500, Loss: 0.0686, Accuracy: 97.38%, Time Passed: 17.10m
Epoch 91 Completed - Average Loss: 0.0678, Accuracy: 97.39%, Epoch Time: 18.50m
Training Complete Epoch 91 - Total Time: 18.50m

✅ Epoch 91 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7115, Accuracy: 80.94%, Time Passed: 4.01m
Evaluation Complete - Loss: 0.6577, Accuracy: 83.40%, Total Time: 6.82m

📊 Epoch 91 - Evaluation Completed.


🚀 Epoch 92 - Training Started...

Epoch 92, Batch 100, Loss: 0.0710, Accuracy: 97.59%, Time Passed: 3.31m
Epoch 92, Batch 200, Loss: 0.0731, Accuracy: 97.31%, Time Passed: 6.62m
Epoch 92, Batch 300, Loss: 0.0738, Accuracy: 97.34%, Time Passed: 10.07m
Epoch 92, Batch 400, Loss: 0.0723, Accuracy: 97.38%, Time Passed: 13.49m
Epoch 92, Batch 500, Loss: 0.0695, Accuracy: 97.42%, Time Passed: 16.87m
Epoch 92 Completed - Average Loss: 0.0688, Accuracy: 97.45%, Epoch Time: 18.32m
Training Complete Epoch 92 - Total Time: 18.32m

✅ Epoch 92 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7340, Accuracy: 80.25%, Time Passed: 4.05m
Evaluation Complete - Loss: 0.6810, Accuracy: 82.81%, Total Time: 6.90m

📊 Epoch 92 - Evaluation Completed.


🚀 Epoch 93 - Training Started...

Epoch 93, Batch 100, Loss: 0.0681, Accuracy: 97.47%, Time Passed: 3.45m
Epoch 93, Batch 200, Loss: 0.0696, Accuracy: 97.44%, Time Passed: 6.89m
Epoch 93, Batch 300, Loss: 0.0700, Accuracy: 97.41%, Time Passed: 10.51m
Epoch 93, Batch 400, Loss: 0.0693, Accuracy: 97.50%, Time Passed: 14.04m
Epoch 93, Batch 500, Loss: 0.0708, Accuracy: 97.46%, Time Passed: 17.52m
Epoch 93 Completed - Average Loss: 0.0709, Accuracy: 97.43%, Epoch Time: 19.01m
Training Complete Epoch 93 - Total Time: 19.01m

✅ Epoch 93 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7639, Accuracy: 80.38%, Time Passed: 4.14m
Evaluation Complete - Loss: 0.6993, Accuracy: 82.88%, Total Time: 7.06m

📊 Epoch 93 - Evaluation Completed.


🚀 Epoch 94 - Training Started...

Epoch 94, Batch 100, Loss: 0.0553, Accuracy: 97.78%, Time Passed: 3.44m
Epoch 94, Batch 200, Loss: 0.0608, Accuracy: 97.62%, Time Passed: 6.86m
Epoch 94, Batch 300, Loss: 0.0630, Accuracy: 97.59%, Time Passed: 10.42m
Epoch 94, Batch 400, Loss: 0.0641, Accuracy: 97.67%, Time Passed: 13.89m
Epoch 94, Batch 500, Loss: 0.0634, Accuracy: 97.67%, Time Passed: 17.27m
Epoch 94 Completed - Average Loss: 0.0629, Accuracy: 97.66%, Epoch Time: 18.70m
Training Complete Epoch 94 - Total Time: 18.70m

✅ Epoch 94 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7617, Accuracy: 80.16%, Time Passed: 4.11m
Evaluation Complete - Loss: 0.6851, Accuracy: 82.85%, Total Time: 6.92m

📊 Epoch 94 - Evaluation Completed.


🚀 Epoch 95 - Training Started...

Epoch 95, Batch 100, Loss: 0.0669, Accuracy: 97.38%, Time Passed: 3.42m
Epoch 95, Batch 200, Loss: 0.0663, Accuracy: 97.47%, Time Passed: 6.87m
Epoch 95, Batch 300, Loss: 0.0664, Accuracy: 97.51%, Time Passed: 10.43m
Epoch 95, Batch 400, Loss: 0.0657, Accuracy: 97.62%, Time Passed: 14.07m
Epoch 95, Batch 500, Loss: 0.0687, Accuracy: 97.50%, Time Passed: 17.72m
Epoch 95 Completed - Average Loss: 0.0686, Accuracy: 97.49%, Epoch Time: 19.19m
Training Complete Epoch 95 - Total Time: 19.19m

✅ Epoch 95 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8388, Accuracy: 78.28%, Time Passed: 4.15m
Evaluation Complete - Loss: 0.7225, Accuracy: 81.73%, Total Time: 7.10m

📊 Epoch 95 - Evaluation Completed.

In [76]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [77]:
del training_states

In [79]:
start_epoch = 96
end_epoch = 100
start_epoch, end_epoch

(96, 100)

In [80]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageD, train_loader, val_loader, inverse_frequency_criterion, stageD_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageD',
                                                          save_dir = 'mobilenetv2', class_weights='inverse_frequency', log_interval=100)

🚀 Epoch 96 - Training Started...

Epoch 96, Batch 100, Loss: 0.0696, Accuracy: 97.31%, Time Passed: 3.24m
Epoch 96, Batch 200, Loss: 0.0639, Accuracy: 97.66%, Time Passed: 6.52m
Epoch 96, Batch 300, Loss: 0.0680, Accuracy: 97.39%, Time Passed: 9.85m
Epoch 96, Batch 400, Loss: 0.0684, Accuracy: 97.44%, Time Passed: 13.37m
Epoch 96, Batch 500, Loss: 0.0680, Accuracy: 97.47%, Time Passed: 16.81m
Epoch 96 Completed - Average Loss: 0.0671, Accuracy: 97.51%, Epoch Time: 18.22m
Training Complete Epoch 96 - Total Time: 18.22m

✅ Epoch 96 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7531, Accuracy: 79.97%, Time Passed: 3.95m
Evaluation Complete - Loss: 0.6785, Accuracy: 82.79%, Total Time: 6.73m

📊 Epoch 96 - Evaluation Completed.


🚀 Epoch 97 - Training Started...

Epoch 97, Batch 100, Loss: 0.0840, Accuracy: 97.12%, Time Passed: 3.40m
Epoch 97, Batch 200, Loss: 0.0753, Accuracy: 97.45%, Time Passed: 6.90m
Epoch 97, Batch 300, Loss: 0.0737, Accuracy: 97.46%, Time Passed: 10.43m
Epoch 97, Batch 400, Loss: 0.0708, Accuracy: 97.49%, Time Passed: 13.94m
Epoch 97, Batch 500, Loss: 0.0701, Accuracy: 97.52%, Time Passed: 17.47m
Epoch 97 Completed - Average Loss: 0.0694, Accuracy: 97.51%, Epoch Time: 18.99m
Training Complete Epoch 97 - Total Time: 18.99m

✅ Epoch 97 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7312, Accuracy: 81.28%, Time Passed: 4.08m
Evaluation Complete - Loss: 0.6413, Accuracy: 84.06%, Total Time: 6.92m

📊 Epoch 97 - Evaluation Completed.


🚀 Epoch 98 - Training Started...

Epoch 98, Batch 100, Loss: 0.0593, Accuracy: 97.81%, Time Passed: 3.41m
Epoch 98, Batch 200, Loss: 0.0599, Accuracy: 97.75%, Time Passed: 6.74m
Epoch 98, Batch 300, Loss: 0.0602, Accuracy: 97.82%, Time Passed: 10.12m
Epoch 98, Batch 400, Loss: 0.0599, Accuracy: 97.91%, Time Passed: 13.78m
Epoch 98, Batch 500, Loss: 0.0601, Accuracy: 97.85%, Time Passed: 17.49m
Epoch 98 Completed - Average Loss: 0.0600, Accuracy: 97.85%, Epoch Time: 18.97m
Training Complete Epoch 98 - Total Time: 18.97m

✅ Epoch 98 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7510, Accuracy: 80.25%, Time Passed: 4.12m
Evaluation Complete - Loss: 0.6890, Accuracy: 83.10%, Total Time: 7.08m

📊 Epoch 98 - Evaluation Completed.


🚀 Epoch 99 - Training Started...

Epoch 99, Batch 100, Loss: 0.0670, Accuracy: 97.38%, Time Passed: 3.56m
Epoch 99, Batch 200, Loss: 0.0685, Accuracy: 97.31%, Time Passed: 7.02m
Epoch 99, Batch 300, Loss: 0.0644, Accuracy: 97.54%, Time Passed: 10.52m
Epoch 99, Batch 400, Loss: 0.0643, Accuracy: 97.59%, Time Passed: 14.05m
Epoch 99, Batch 500, Loss: 0.0632, Accuracy: 97.58%, Time Passed: 17.56m
Epoch 99 Completed - Average Loss: 0.0644, Accuracy: 97.55%, Epoch Time: 19.02m
Training Complete Epoch 99 - Total Time: 19.02m

✅ Epoch 99 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7952, Accuracy: 79.28%, Time Passed: 4.12m
Evaluation Complete - Loss: 0.7042, Accuracy: 82.46%, Total Time: 6.96m

📊 Epoch 99 - Evaluation Completed.


🚀 Epoch 100 - Training Started...

Epoch 100, Batch 100, Loss: 0.0715, Accuracy: 97.41%, Time Passed: 3.37m
Epoch 100, Batch 200, Loss: 0.0645, Accuracy: 97.67%, Time Passed: 6.96m
Epoch 100, Batch 300, Loss: 0.0645, Accuracy: 97.62%, Time Passed: 10.49m
Epoch 100, Batch 400, Loss: 0.0661, Accuracy: 97.58%, Time Passed: 14.31m
Epoch 100, Batch 500, Loss: 0.0642, Accuracy: 97.64%, Time Passed: 17.93m
Epoch 100 Completed - Average Loss: 0.0653, Accuracy: 97.63%, Epoch Time: 19.35m
Training Complete Epoch 100 - Total Time: 19.35m

✅ Epoch 100 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.8250, Accuracy: 79.06%, Time Passed: 4.04m
Evaluation Complete - Loss: 0.7254, Accuracy: 82.54%, Total Time: 6.90m

📊 Epoch 100 - Evaluation Completed.

In [81]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

## **Stage E**

### **98-110 & Amplified Inverse Recall + Inverse Frequency Combination**

In [56]:
df = pd.read_csv("mobilenetv2/mobilenetv2_stageD_val_results96_100.csv")
df = df[(df['Epoch'] == 97) & (df['Species'] != 'Average Performance (Macro)')]
recall_dict = dict(zip(df['Species'], df['Recall']))
inverse_recall_weights = compute_inverse_metric_tensor(recall_dict, train_dataset.class_to_idx, normalize=False, clip = False)

In [42]:
w = inverse_recall_weights.cpu()

# Compute percentiles
percentiles = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
thresholds = [np.percentile(w.numpy(), p) for p in percentiles]
# Start with multipliers = 1
multipliers = torch.ones_like(w)

# Apply scaling in descending order to avoid overwriting smaller thresholds
rules = list(zip(thresholds, [1, 1, 2, 2, 3, 3, 4, 4, 5, 5]))
for t, m in rules:
    multipliers[w >= t] = m

# Apply the multipliers
amplified = w * multipliers
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
amplified = amplified.to(device)

In [43]:
amplified

tensor([ 2.0541,  5.7810,  4.9735,  2.0769,  4.8547,  2.1239,  3.3038,  1.0000,
         1.0000,  5.1810,  3.2727,  3.6213, 11.5625,  5.1600,  3.4459,  3.4915,
         1.0000,  5.5625,  7.6923,  3.4889,  2.0750,  1.0000,  1.0000,  1.0000,
         1.0000,  1.0000,  7.7295,  8.1068,  1.0087,  2.0964,  3.3837,  1.0000,
         2.0619], device='mps:0')

In [44]:
inverse_frequency_weights = compute_class_weights(train_dataset, method="inverse_frequency", normalize=False)
# Normalize both to z-score
norm_inv_freq = (inverse_frequency_weights - inverse_frequency_weights.mean()) / inverse_frequency_weights.std()
norm_inv_recall = (amplified - amplified.mean()) / amplified.std()

# Combine and shift
combined_weights = norm_inv_freq + norm_inv_recall
combined_weights = combined_weights - combined_weights.min() + 1.0

# Optional: normalize mean to 1
combined_weights = combined_weights / combined_weights.mean()
combined_weights

tensor([2.0624, 2.6081, 2.2515, 2.2402, 2.5710, 1.8339, 3.1689, 2.9047, 3.0458,
        2.8874, 1.7250, 1.7781, 5.3387, 2.6111, 1.8430, 1.8588, 3.9966, 3.3798,
        3.2539, 1.8320, 1.0000, 5.0856, 1.4917, 1.2945, 1.3354, 1.2498, 3.2678,
        4.2951, 1.1903, 1.1804, 1.8226, 2.3101, 1.7214], device='mps:0')

In [153]:
combined_criterion = nn.CrossEntropyLoss(weight=combined_weights)

In [161]:
training_states = joblib.load(f'mobilenetv2/training_states_{96}_{100}.pkl')

In [162]:
mobilenetv2_stageE = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes))

# Send it to device
device = torch.device("mps")
mobilenetv2_stageE.to(device)
mobilenetv2_stageE.load_state_dict(training_states[97]["model_state_dict"])

In [163]:
mobilenetv2_stageE = configure_mobilenetv2_training(
                                                    mobilenetv2_stageE,
                                                    NUM_CLASSES, final_stage=True,
                                                    prev_unfrozen = 0
                                                   )
    
df_summary = summarize_mobilenetv2_blocks(mobilenetv2_stageE)
df_summary

🟢 Final stage → Entire backbone unfrozen (blocks [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])
✅ Trainable layers: 158/158 (100.00%)
✅ Trainable params: 2,266,145/2,266,145 (100.00%)

,Block,Order,Module,Layers (#),Params (#),Trainable Params (#),% Layers (Model),% Params (Model),% Trainable Params (Model),Cumulative Layers (Model),Cumulative % Layers (Model),Cumulative Params (Model),Cumulative % Params (Model),Layers (Module %),Params (Module %),Trainable Params (Module %),Cumulative Layers (Module),Cumulative % Layers (Module),Cumulative Params (Module),Cumulative % Params (Module)
0,Conv2dNormActivation_1,1,features,3,928,928,1.898734,0.040951,0.040951,158,100.000000,2266145,100.000000,1.923077,0.041729,0.041729,156,100.000000,2223872,100.000000
1,InvertedResidual_2,2,features,6,896,896,3.797468,0.039539,0.039539,155,98.101266,2265217,99.959049,3.846154,0.040290,0.040290,153,98.076923,2222944,99.958271
2,InvertedResidual_3,3,features,9,5136,5136,5.696203,0.226640,0.226640,149,94.303797,2264321,99.919511,5.769231,0.230949,0.230949,147,94.230769,2222048,99.917981
3,InvertedResidual_4,4,features,9,8832,8832,5.696203,0.389737,0.389737,140,88.607595,2259185,99.692870,5.769231,0.397145,0.397145,138,88.461538,2216912,99.687032
4,InvertedResidual_5,5,features,9,10000,10000,5.696203,0.441278,0.441278,131,82.911392,2250353,99.303134,5.769231,0.449666,0.449666,129,82.692308,2208080,99.289887
5,InvertedResidual_6,6,features,9,14848,14848,5.696203,0.655210,0.655210,122,77.215190,2240353,98.861856,5.769231,0.667664,0.667664,120,76.923077,2198080,98.840221
6,InvertedResidual_7,7,features,9,14848,14848,5.696203,0.655210,0.655210,113,71.518987,2225505,98.206646,5.769231,0.667664,0.667664,111,71.153846,2183232,98.172557
7,InvertedResidual_8,8,features,9,21056,21056,5.696203,0.929155,0.929155,104,65.822785,2210657,97.551436,5.769231,0.946817,0.946817,102,65.384615,2168384,97.504892
8,InvertedResidual_9,9,features,9,54272,54272,5.696203,2.394904,2.394904,95,60.126582,2189601,96.622281,5.769231,2.440428,2.440428,93,59.615385,2147328,96.558075
9,InvertedResidual_10,10,features,9,54272,54272,5.696203,2.394904,2.394904,86,54.430380,2135329,94.227377,5.769231,2.440428,2.440428,84,53.846154,2093056,94.117647
10,InvertedResidual_11,11,features,9,54272,54272,5.696203,2.394904,2.394904,77,48.734177,2081057,91.832473,5.769231,2.440428,2.440428,75,48.076923,2038784,91.677219
11,InvertedResidual_12,12,features,9,66624,66624,5.696203,2.939971,2.939971,68,43.037975,2026785,89.437569,5.769231,2.995856,2.995856,66,42.307692,1984512,89.236791
12,InvertedResidual_13,13,features,9,118272,118272,5.696203,5.219084,5.219084,59,37.341772,1960161,86.497598,5.769231,5.318292,5.318292,57,36.538462,1917888,86.240935
13,InvertedResidual_14,14,features,9,118272,118272,5.696203,5.219084,5.219084,50,31.645570,1841889,81.278515,5.769231,5.318292,5.318292,48,30.769231,1799616,80.922643
14,InvertedResidual_15,15,features,9,155264,155264,5.696203,6.851459,6.851459,41,25.949367,1723617,76.059431,5.769231,6.981697,6.981697,39,25.000000,1681344,75.604351
15,InvertedResidual_16,16,features,9,320000,320000,5.696203,14.120897,14.120897,32,20.253165,1568353,69.207972,5.769231,14.389317,14.389317,30,19.230769,1526080,68.622655
16,InvertedResidual_17,17,features,9,320000,320000,5.696203,14.120897,14.120897,23,14.556962,1248353,55.087075,5.769231,14.389317,14.389317,21,13.461538,1206080,54.233337
17,InvertedResidual_18,18,features,9,473920,473920,5.696203,20.913048,20.913048,14,8.860759,928353,40.966178,5.769231,21.310579,21.310579,12,7.692308,886080,39.844020
18,Conv2dNormActivation_19,19,features,3,412160,412160,1.898734,18.187715,18.187715,5,3.164557,454433,20.053130,1.923077,18.533441,18.533441,3,1.923077,412160,18.533441
19,Sequential,20,classifier,2,42273,42273,1.265823,1.865415,1.865415,2,1.265823,42273,1.865415,100.000000,100.000000,100.000000,2,100.000000,42273,100.000000

In [95]:
_ = evaluate_model(
            mobilenetv2_stageE, val_loader, inverse_frequency_criterion, train_dataset.classes, epoch_num=97, log_interval=100)

Batch 100, Loss: 0.7312, Accuracy: 81.28%, Time Passed: 3.65m
Evaluation Complete - Loss: 0.6413, Accuracy: 84.06%, Total Time: 6.37m

In [164]:
stageE_optimizer = torch.optim.AdamW(
    mobilenetv2_stageE.parameters(),
    lr=1e-5,    # even smaller LR, since more params unfrozen
    weight_decay=1e-4,
    betas=(0.9, 0.999)
)

In [165]:
del training_states

In [166]:
start_epoch = 98
end_epoch = 102
start_epoch, end_epoch

(98, 102)

In [167]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageE, train_loader, val_loader, combined_criterion, stageE_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageE',
                                                          save_dir = 'mobilenetv2', class_weights='combined', log_interval=100)

🚀 Epoch 98 - Training Started...

Epoch 98, Batch 100, Loss: 0.0721, Accuracy: 97.78%, Time Passed: 3.54m
Epoch 98, Batch 200, Loss: 0.0686, Accuracy: 97.75%, Time Passed: 7.45m
Epoch 98, Batch 300, Loss: 0.0671, Accuracy: 97.81%, Time Passed: 11.11m
Epoch 98, Batch 400, Loss: 0.0689, Accuracy: 97.76%, Time Passed: 14.90m
Epoch 98, Batch 500, Loss: 0.0693, Accuracy: 97.74%, Time Passed: 18.62m
Epoch 98 Completed - Average Loss: 0.0699, Accuracy: 97.71%, Epoch Time: 20.25m
Training Complete Epoch 98 - Total Time: 20.25m

✅ Epoch 98 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7160, Accuracy: 80.97%, Time Passed: 4.03m
Evaluation Complete - Loss: 0.6329, Accuracy: 83.79%, Total Time: 6.87m

📊 Epoch 98 - Evaluation Completed.


🚀 Epoch 99 - Training Started...

Epoch 99, Batch 100, Loss: 0.0615, Accuracy: 97.53%, Time Passed: 4.25m
Epoch 99, Batch 200, Loss: 0.0611, Accuracy: 97.73%, Time Passed: 8.47m
Epoch 99, Batch 300, Loss: 0.0597, Accuracy: 97.79%, Time Passed: 12.73m
Epoch 99, Batch 400, Loss: 0.0594, Accuracy: 97.83%, Time Passed: 16.95m
Epoch 99, Batch 500, Loss: 0.0615, Accuracy: 97.78%, Time Passed: 21.26m
Epoch 99 Completed - Average Loss: 0.0616, Accuracy: 97.78%, Epoch Time: 23.05m
Training Complete Epoch 99 - Total Time: 23.05m

✅ Epoch 99 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7134, Accuracy: 80.91%, Time Passed: 4.32m
Evaluation Complete - Loss: 0.6261, Accuracy: 84.06%, Total Time: 7.34m

📊 Epoch 99 - Evaluation Completed.


🚀 Epoch 100 - Training Started...

Epoch 100, Batch 100, Loss: 0.0577, Accuracy: 97.84%, Time Passed: 4.47m
Epoch 100, Batch 200, Loss: 0.0638, Accuracy: 97.55%, Time Passed: 9.07m
Epoch 100, Batch 300, Loss: 0.0631, Accuracy: 97.69%, Time Passed: 13.81m
Epoch 100, Batch 400, Loss: 0.0639, Accuracy: 97.73%, Time Passed: 18.73m
Epoch 100, Batch 500, Loss: 0.0645, Accuracy: 97.75%, Time Passed: 23.22m
Epoch 100 Completed - Average Loss: 0.0637, Accuracy: 97.75%, Epoch Time: 25.20m
Training Complete Epoch 100 - Total Time: 25.20m

✅ Epoch 100 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.7046, Accuracy: 81.06%, Time Passed: 4.52m
Evaluation Complete - Loss: 0.6566, Accuracy: 83.58%, Total Time: 7.66m

📊 Epoch 100 - Evaluation Completed.


🚀 Epoch 101 - Training Started...

Epoch 101, Batch 100, Loss: 0.0534, Accuracy: 97.97%, Time Passed: 4.56m
Epoch 101, Batch 200, Loss: 0.0567, Accuracy: 97.89%, Time Passed: 9.29m
Epoch 101, Batch 300, Loss: 0.0597, Accuracy: 97.86%, Time Passed: 14.03m
Epoch 101, Batch 400, Loss: 0.0587, Accuracy: 97.91%, Time Passed: 18.55m
Epoch 101, Batch 500, Loss: 0.0591, Accuracy: 97.92%, Time Passed: 22.79m
Epoch 101 Completed - Average Loss: 0.0587, Accuracy: 97.97%, Epoch Time: 24.49m
Training Complete Epoch 101 - Total Time: 24.49m

✅ Epoch 101 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6719, Accuracy: 82.22%, Time Passed: 4.45m
Evaluation Complete - Loss: 0.6367, Accuracy: 84.12%, Total Time: 7.44m

📊 Epoch 101 - Evaluation Completed.


🚀 Epoch 102 - Training Started...

Epoch 102, Batch 100, Loss: 0.0564, Accuracy: 97.97%, Time Passed: 4.28m
Epoch 102, Batch 200, Loss: 0.0543, Accuracy: 98.23%, Time Passed: 8.51m
Epoch 102, Batch 300, Loss: 0.0583, Accuracy: 97.93%, Time Passed: 12.96m
Epoch 102, Batch 400, Loss: 0.0582, Accuracy: 97.91%, Time Passed: 17.24m
Epoch 102, Batch 500, Loss: 0.0571, Accuracy: 97.96%, Time Passed: 21.61m
Epoch 102 Completed - Average Loss: 0.0573, Accuracy: 97.98%, Epoch Time: 23.42m
Training Complete Epoch 102 - Total Time: 23.42m

✅ Epoch 102 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6543, Accuracy: 82.19%, Time Passed: 4.40m
Evaluation Complete - Loss: 0.6170, Accuracy: 84.40%, Total Time: 7.46m

📊 Epoch 102 - Evaluation Completed.

In [169]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [170]:
del training_states

In [173]:
start_epoch = 103
end_epoch = 110
start_epoch, end_epoch

(103, 110)

In [174]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageE, train_loader, val_loader, combined_criterion, stageE_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageE',
                                                          save_dir = 'mobilenetv2', class_weights='combined', log_interval=100)

🚀 Epoch 103 - Training Started...

Epoch 103, Batch 100, Loss: 0.0612, Accuracy: 97.91%, Time Passed: 4.06m
Epoch 103, Batch 200, Loss: 0.0624, Accuracy: 97.92%, Time Passed: 8.58m
Epoch 103, Batch 300, Loss: 0.0631, Accuracy: 97.88%, Time Passed: 13.02m
Epoch 103, Batch 400, Loss: 0.0626, Accuracy: 97.88%, Time Passed: 17.40m
Epoch 103, Batch 500, Loss: 0.0615, Accuracy: 97.91%, Time Passed: 21.78m
Epoch 103 Completed - Average Loss: 0.0613, Accuracy: 97.89%, Epoch Time: 24.01m
Training Complete Epoch 103 - Total Time: 24.01m

✅ Epoch 103 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6675, Accuracy: 82.22%, Time Passed: 4.83m
Evaluation Complete - Loss: 0.6333, Accuracy: 84.35%, Total Time: 7.83m

📊 Epoch 103 - Evaluation Completed.


🚀 Epoch 104 - Training Started...

Epoch 104, Batch 100, Loss: 0.0616, Accuracy: 97.69%, Time Passed: 4.54m
Epoch 104, Batch 200, Loss: 0.0559, Accuracy: 98.03%, Time Passed: 9.04m
Epoch 104, Batch 300, Loss: 0.0545, Accuracy: 98.11%, Time Passed: 13.45m
Epoch 104, Batch 400, Loss: 0.0545, Accuracy: 98.13%, Time Passed: 18.10m
Epoch 104, Batch 500, Loss: 0.0535, Accuracy: 98.16%, Time Passed: 22.52m
Epoch 104 Completed - Average Loss: 0.0557, Accuracy: 98.12%, Epoch Time: 24.35m
Training Complete Epoch 104 - Total Time: 24.35m

✅ Epoch 104 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6725, Accuracy: 82.22%, Time Passed: 4.51m
Evaluation Complete - Loss: 0.6314, Accuracy: 84.23%, Total Time: 7.68m

📊 Epoch 104 - Evaluation Completed.


🚀 Epoch 105 - Training Started...

Epoch 105, Batch 100, Loss: 0.0619, Accuracy: 97.94%, Time Passed: 4.59m
Epoch 105, Batch 200, Loss: 0.0519, Accuracy: 98.30%, Time Passed: 8.87m
Epoch 105, Batch 300, Loss: 0.0508, Accuracy: 98.29%, Time Passed: 13.25m
Epoch 105, Batch 400, Loss: 0.0564, Accuracy: 98.06%, Time Passed: 17.55m
Epoch 105, Batch 500, Loss: 0.0563, Accuracy: 98.04%, Time Passed: 21.76m
Epoch 105 Completed - Average Loss: 0.0569, Accuracy: 98.05%, Epoch Time: 23.59m
Training Complete Epoch 105 - Total Time: 23.59m

✅ Epoch 105 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6387, Accuracy: 82.59%, Time Passed: 4.51m
Evaluation Complete - Loss: 0.6063, Accuracy: 84.79%, Total Time: 7.61m

📊 Epoch 105 - Evaluation Completed.


🚀 Epoch 106 - Training Started...

Epoch 106, Batch 100, Loss: 0.0507, Accuracy: 98.22%, Time Passed: 4.16m
Epoch 106, Batch 200, Loss: 0.0483, Accuracy: 98.23%, Time Passed: 8.92m
Epoch 106, Batch 300, Loss: 0.0508, Accuracy: 98.10%, Time Passed: 13.50m
Epoch 106, Batch 400, Loss: 0.0508, Accuracy: 98.05%, Time Passed: 17.94m
Epoch 106, Batch 500, Loss: 0.0513, Accuracy: 98.07%, Time Passed: 22.38m
Epoch 106 Completed - Average Loss: 0.0515, Accuracy: 98.09%, Epoch Time: 24.21m
Training Complete Epoch 106 - Total Time: 24.21m

✅ Epoch 106 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6346, Accuracy: 83.72%, Time Passed: 4.58m
Evaluation Complete - Loss: 0.6045, Accuracy: 85.35%, Total Time: 7.64m

📊 Epoch 106 - Evaluation Completed.


🚀 Epoch 107 - Training Started...

Epoch 107, Batch 100, Loss: 0.0475, Accuracy: 98.50%, Time Passed: 4.48m
Epoch 107, Batch 200, Loss: 0.0552, Accuracy: 98.22%, Time Passed: 8.79m
Epoch 107, Batch 300, Loss: 0.0570, Accuracy: 98.11%, Time Passed: 13.29m
Epoch 107, Batch 400, Loss: 0.0556, Accuracy: 98.14%, Time Passed: 17.80m
Epoch 107, Batch 500, Loss: 0.0565, Accuracy: 98.09%, Time Passed: 22.39m
Epoch 107 Completed - Average Loss: 0.0557, Accuracy: 98.12%, Epoch Time: 24.35m
Training Complete Epoch 107 - Total Time: 24.35m

✅ Epoch 107 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6365, Accuracy: 83.53%, Time Passed: 4.87m
Evaluation Complete - Loss: 0.5970, Accuracy: 85.25%, Total Time: 8.06m

📊 Epoch 107 - Evaluation Completed.


🚀 Epoch 108 - Training Started...

Epoch 108, Batch 100, Loss: 0.0493, Accuracy: 98.09%, Time Passed: 5.02m
Epoch 108, Batch 200, Loss: 0.0470, Accuracy: 98.20%, Time Passed: 10.22m
Epoch 108, Batch 300, Loss: 0.0482, Accuracy: 98.12%, Time Passed: 14.93m
Epoch 108, Batch 400, Loss: 0.0536, Accuracy: 98.05%, Time Passed: 19.55m
Epoch 108, Batch 500, Loss: 0.0526, Accuracy: 98.11%, Time Passed: 24.25m
Epoch 108 Completed - Average Loss: 0.0521, Accuracy: 98.13%, Epoch Time: 26.06m
Training Complete Epoch 108 - Total Time: 26.06m

✅ Epoch 108 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6273, Accuracy: 83.75%, Time Passed: 4.69m
Evaluation Complete - Loss: 0.6007, Accuracy: 85.31%, Total Time: 7.83m

📊 Epoch 108 - Evaluation Completed.


🚀 Epoch 109 - Training Started...

Epoch 109, Batch 100, Loss: 0.0494, Accuracy: 98.62%, Time Passed: 4.93m
Epoch 109, Batch 200, Loss: 0.0498, Accuracy: 98.42%, Time Passed: 9.85m
Epoch 109, Batch 300, Loss: 0.0521, Accuracy: 98.32%, Time Passed: 14.84m
Epoch 109, Batch 400, Loss: 0.0510, Accuracy: 98.38%, Time Passed: 20.04m
Epoch 109, Batch 500, Loss: 0.0510, Accuracy: 98.40%, Time Passed: 25.01m
Epoch 109 Completed - Average Loss: 0.0519, Accuracy: 98.39%, Epoch Time: 27.12m
Training Complete Epoch 109 - Total Time: 27.12m

✅ Epoch 109 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6386, Accuracy: 83.25%, Time Passed: 4.84m
Evaluation Complete - Loss: 0.6102, Accuracy: 84.94%, Total Time: 8.08m

📊 Epoch 109 - Evaluation Completed.


🚀 Epoch 110 - Training Started...

Epoch 110, Batch 100, Loss: 0.0487, Accuracy: 98.50%, Time Passed: 4.83m
Epoch 110, Batch 200, Loss: 0.0523, Accuracy: 98.30%, Time Passed: 9.68m
Epoch 110, Batch 300, Loss: 0.0510, Accuracy: 98.27%, Time Passed: 14.56m
Epoch 110, Batch 400, Loss: 0.0510, Accuracy: 98.32%, Time Passed: 19.54m
Epoch 110, Batch 500, Loss: 0.0524, Accuracy: 98.30%, Time Passed: 24.20m
Epoch 110 Completed - Average Loss: 0.0517, Accuracy: 98.34%, Epoch Time: 26.06m
Training Complete Epoch 110 - Total Time: 26.06m

✅ Epoch 110 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6754, Accuracy: 82.62%, Time Passed: 4.49m
Evaluation Complete - Loss: 0.6465, Accuracy: 84.40%, Total Time: 7.54m

📊 Epoch 110 - Evaluation Completed.

In [176]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [177]:
del training_states

### **109-120 & Moderately Recall-Weighted Combination (Amplified Inverse Recall + Inverse Frequency, 2.5 : 1/2.5 Ratio)**

In [266]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[0])

✅ Random seed set to 42 (MPS available: True)

In [267]:
df = pd.read_csv("mobilenetv2/mobilenetv2_stageE_val_results103_110.csv")
df = df[(df['Epoch'] == 108) & (df['Species'] != 'Average Performance (Macro)')]

In [268]:
# Compute from recall values
recall_penalty_weights = (1 - df['Recall'].values) * 100

# Convert to tensor
recall_penalty_weights = torch.tensor(recall_penalty_weights, dtype=torch.float32)

# Move to MPS (Apple GPU) if available, otherwise CPU
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
recall_penalty_weights = recall_penalty_weights.to(device)

In [269]:
recall_penalty_weights

tensor([ 2.6316, 23.7374,  9.9644,  4.9383, 18.3099, 13.3333,  8.0460,  0.0000,
         0.0000, 20.5882,  3.4314, 13.2353, 45.9459, 12.4031, 10.5882, 14.0777,
         0.0000, 24.7191, 33.5714, 18.7898,  4.2169,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000, 37.8125, 42.5150,  0.8621,  4.2146, 10.3093,  0.8772,
         3.0000], device='mps:0')

In [270]:
inverse_frequency_weights = compute_class_weights(train_dataset, method="inverse_frequency", normalize=False)
inverse_frequency_criterion = nn.CrossEntropyLoss(weight=inverse_frequency_weights)
inverse_frequency_weights

tensor([ 58.0736,  20.0740,  18.1442,  65.2782,  33.7165,  47.1848,  84.7024,
        111.3077, 117.3243,  41.8410,  23.6567,  20.1907,  41.4415,  30.4098,
         25.8393,  25.7626, 157.8545,  56.5603,  16.1827,  24.6648,  12.4384,
        204.2823,  51.0706,  42.6634,  44.4092,  40.7606,  16.1676,  53.7585,
         38.0789,  19.7768,  25.9940,  85.9604,  43.4100], device='mps:0')

In [271]:
# Normalize both to z-score
norm_inv_freq = (inverse_frequency_weights - inverse_frequency_weights.mean()) / inverse_frequency_weights.std()
norm_recall_penalty = (recall_penalty_weights - recall_penalty_weights.mean()) / recall_penalty_weights.std()

# Combine and shift
new_combined_weights = (norm_inv_freq/2.5) + (2.5*norm_recall_penalty)
new_combined_weights = new_combined_weights - new_combined_weights.min() + 1.0
new_combined_weights

tensor([1.6636, 5.3267, 2.6855, 2.1706, 4.4211, 3.5996, 2.9447, 1.6619, 1.7184,
        4.9312, 1.4930, 3.3277, 9.7569, 3.2651, 2.8765, 3.5404, 2.0987, 5.8560,
        7.1631, 4.4275, 1.5374, 2.5343, 1.0967, 1.0179, 1.0342, 1.0000, 7.9707,
        9.2190, 1.1390, 1.6058, 2.8249, 1.5912, 1.5962], device='mps:0')

In [272]:
new_combined_criterion = nn.CrossEntropyLoss(weight=new_combined_weights)

In [275]:
training_states = joblib.load(f'mobilenetv2/training_states_{103}_{110}.pkl')

In [276]:
mobilenetv2_stageE = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes))

# Send it to device
device = torch.device("mps")
mobilenetv2_stageE.to(device)
mobilenetv2_stageE.load_state_dict(training_states[108]["model_state_dict"])

In [277]:
mobilenetv2_stageE = configure_mobilenetv2_training(
                                                    mobilenetv2_stageE,
                                                    NUM_CLASSES, final_stage=True,
                                                    prev_unfrozen = 0
                                                   )
    
df_summary = summarize_mobilenetv2_blocks(mobilenetv2_stageE)
df_summary

🟢 Final stage → Entire backbone unfrozen (blocks [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])
✅ Trainable layers: 158/158 (100.00%)
✅ Trainable params: 2,266,145/2,266,145 (100.00%)

,Block,Order,Module,Layers (#),Params (#),Trainable Params (#),% Layers (Model),% Params (Model),% Trainable Params (Model),Cumulative Layers (Model),Cumulative % Layers (Model),Cumulative Params (Model),Cumulative % Params (Model),Layers (Module %),Params (Module %),Trainable Params (Module %),Cumulative Layers (Module),Cumulative % Layers (Module),Cumulative Params (Module),Cumulative % Params (Module)
0,Conv2dNormActivation_1,1,features,3,928,928,1.898734,0.040951,0.040951,158,100.000000,2266145,100.000000,1.923077,0.041729,0.041729,156,100.000000,2223872,100.000000
1,InvertedResidual_2,2,features,6,896,896,3.797468,0.039539,0.039539,155,98.101266,2265217,99.959049,3.846154,0.040290,0.040290,153,98.076923,2222944,99.958271
2,InvertedResidual_3,3,features,9,5136,5136,5.696203,0.226640,0.226640,149,94.303797,2264321,99.919511,5.769231,0.230949,0.230949,147,94.230769,2222048,99.917981
3,InvertedResidual_4,4,features,9,8832,8832,5.696203,0.389737,0.389737,140,88.607595,2259185,99.692870,5.769231,0.397145,0.397145,138,88.461538,2216912,99.687032
4,InvertedResidual_5,5,features,9,10000,10000,5.696203,0.441278,0.441278,131,82.911392,2250353,99.303134,5.769231,0.449666,0.449666,129,82.692308,2208080,99.289887
5,InvertedResidual_6,6,features,9,14848,14848,5.696203,0.655210,0.655210,122,77.215190,2240353,98.861856,5.769231,0.667664,0.667664,120,76.923077,2198080,98.840221
6,InvertedResidual_7,7,features,9,14848,14848,5.696203,0.655210,0.655210,113,71.518987,2225505,98.206646,5.769231,0.667664,0.667664,111,71.153846,2183232,98.172557
7,InvertedResidual_8,8,features,9,21056,21056,5.696203,0.929155,0.929155,104,65.822785,2210657,97.551436,5.769231,0.946817,0.946817,102,65.384615,2168384,97.504892
8,InvertedResidual_9,9,features,9,54272,54272,5.696203,2.394904,2.394904,95,60.126582,2189601,96.622281,5.769231,2.440428,2.440428,93,59.615385,2147328,96.558075
9,InvertedResidual_10,10,features,9,54272,54272,5.696203,2.394904,2.394904,86,54.430380,2135329,94.227377,5.769231,2.440428,2.440428,84,53.846154,2093056,94.117647
10,InvertedResidual_11,11,features,9,54272,54272,5.696203,2.394904,2.394904,77,48.734177,2081057,91.832473,5.769231,2.440428,2.440428,75,48.076923,2038784,91.677219
11,InvertedResidual_12,12,features,9,66624,66624,5.696203,2.939971,2.939971,68,43.037975,2026785,89.437569,5.769231,2.995856,2.995856,66,42.307692,1984512,89.236791
12,InvertedResidual_13,13,features,9,118272,118272,5.696203,5.219084,5.219084,59,37.341772,1960161,86.497598,5.769231,5.318292,5.318292,57,36.538462,1917888,86.240935
13,InvertedResidual_14,14,features,9,118272,118272,5.696203,5.219084,5.219084,50,31.645570,1841889,81.278515,5.769231,5.318292,5.318292,48,30.769231,1799616,80.922643
14,InvertedResidual_15,15,features,9,155264,155264,5.696203,6.851459,6.851459,41,25.949367,1723617,76.059431,5.769231,6.981697,6.981697,39,25.000000,1681344,75.604351
15,InvertedResidual_16,16,features,9,320000,320000,5.696203,14.120897,14.120897,32,20.253165,1568353,69.207972,5.769231,14.389317,14.389317,30,19.230769,1526080,68.622655
16,InvertedResidual_17,17,features,9,320000,320000,5.696203,14.120897,14.120897,23,14.556962,1248353,55.087075,5.769231,14.389317,14.389317,21,13.461538,1206080,54.233337
17,InvertedResidual_18,18,features,9,473920,473920,5.696203,20.913048,20.913048,14,8.860759,928353,40.966178,5.769231,21.310579,21.310579,12,7.692308,886080,39.844020
18,Conv2dNormActivation_19,19,features,3,412160,412160,1.898734,18.187715,18.187715,5,3.164557,454433,20.053130,1.923077,18.533441,18.533441,3,1.923077,412160,18.533441
19,Sequential,20,classifier,2,42273,42273,1.265823,1.865415,1.865415,2,1.265823,42273,1.865415,100.000000,100.000000,100.000000,2,100.000000,42273,100.000000

In [279]:
_ = evaluate_model(
            mobilenetv2_stageE, val_loader, new_combined_criterion, train_dataset.classes, epoch_num=108, log_interval=100)

Batch 100, Loss: 0.6301, Accuracy: 83.75%, Time Passed: 3.89m
Evaluation Complete - Loss: 0.6058, Accuracy: 85.31%, Total Time: 6.69m

In [280]:
stageE_optimizer = torch.optim.AdamW(
    mobilenetv2_stageE.parameters(),
    lr=1e-5,    # even smaller LR, since more params unfrozen
    weight_decay=1e-4,
    betas=(0.9, 0.999)
)

In [281]:
start_epoch = 109
end_epoch = 115
start_epoch, end_epoch

(109, 115)

In [282]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageE, train_loader, val_loader, new_combined_criterion, stageE_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageE',
                                                          save_dir = 'mobilenetv2', class_weights='new_combined', log_interval=100)

🚀 Epoch 109 - Training Started...

Epoch 109, Batch 100, Loss: 0.0494, Accuracy: 98.06%, Time Passed: 3.87m
Epoch 109, Batch 200, Loss: 0.0522, Accuracy: 98.03%, Time Passed: 7.65m
Epoch 109, Batch 300, Loss: 0.0502, Accuracy: 98.14%, Time Passed: 11.50m
Epoch 109, Batch 400, Loss: 0.0529, Accuracy: 98.04%, Time Passed: 15.32m
Epoch 109, Batch 500, Loss: 0.0544, Accuracy: 98.02%, Time Passed: 19.12m
Epoch 109 Completed - Average Loss: 0.0548, Accuracy: 98.05%, Epoch Time: 20.64m
Training Complete Epoch 109 - Total Time: 20.64m

✅ Epoch 109 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5957, Accuracy: 84.91%, Time Passed: 4.18m
Evaluation Complete - Loss: 0.5727, Accuracy: 86.12%, Total Time: 7.11m

📊 Epoch 109 - Evaluation Completed.


🚀 Epoch 110 - Training Started...

Epoch 110, Batch 100, Loss: 0.0491, Accuracy: 98.22%, Time Passed: 3.96m
Epoch 110, Batch 200, Loss: 0.0447, Accuracy: 98.28%, Time Passed: 7.91m
Epoch 110, Batch 300, Loss: 0.0522, Accuracy: 98.14%, Time Passed: 11.89m
Epoch 110, Batch 400, Loss: 0.0476, Accuracy: 98.24%, Time Passed: 16.06m
Epoch 110, Batch 500, Loss: 0.0483, Accuracy: 98.26%, Time Passed: 20.09m
Epoch 110 Completed - Average Loss: 0.0475, Accuracy: 98.28%, Epoch Time: 21.79m
Training Complete Epoch 110 - Total Time: 21.79m

✅ Epoch 110 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5929, Accuracy: 84.84%, Time Passed: 4.42m
Evaluation Complete - Loss: 0.5674, Accuracy: 86.27%, Total Time: 7.38m

📊 Epoch 110 - Evaluation Completed.


🚀 Epoch 111 - Training Started...

Epoch 111, Batch 100, Loss: 0.0634, Accuracy: 97.69%, Time Passed: 4.24m
Epoch 111, Batch 200, Loss: 0.0549, Accuracy: 98.06%, Time Passed: 8.27m
Epoch 111, Batch 300, Loss: 0.0525, Accuracy: 98.09%, Time Passed: 12.38m
Epoch 111, Batch 400, Loss: 0.0516, Accuracy: 98.00%, Time Passed: 16.47m
Epoch 111, Batch 500, Loss: 0.0520, Accuracy: 97.97%, Time Passed: 20.53m
Epoch 111 Completed - Average Loss: 0.0516, Accuracy: 98.00%, Epoch Time: 22.15m
Training Complete Epoch 111 - Total Time: 22.15m

✅ Epoch 111 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5808, Accuracy: 84.59%, Time Passed: 4.38m
Evaluation Complete - Loss: 0.5745, Accuracy: 85.87%, Total Time: 7.45m

📊 Epoch 111 - Evaluation Completed.


🚀 Epoch 112 - Training Started...

Epoch 112, Batch 100, Loss: 0.0517, Accuracy: 97.75%, Time Passed: 4.15m
Epoch 112, Batch 200, Loss: 0.0508, Accuracy: 97.88%, Time Passed: 8.15m
Epoch 112, Batch 300, Loss: 0.0466, Accuracy: 98.08%, Time Passed: 12.29m
Epoch 112, Batch 400, Loss: 0.0450, Accuracy: 98.17%, Time Passed: 16.36m
Epoch 112, Batch 500, Loss: 0.0437, Accuracy: 98.22%, Time Passed: 20.61m
Epoch 112 Completed - Average Loss: 0.0450, Accuracy: 98.23%, Epoch Time: 22.37m
Training Complete Epoch 112 - Total Time: 22.37m

✅ Epoch 112 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6110, Accuracy: 83.84%, Time Passed: 4.29m
Evaluation Complete - Loss: 0.5862, Accuracy: 85.56%, Total Time: 7.26m

📊 Epoch 112 - Evaluation Completed.


🚀 Epoch 113 - Training Started...

Epoch 113, Batch 100, Loss: 0.0537, Accuracy: 98.06%, Time Passed: 3.99m
Epoch 113, Batch 200, Loss: 0.0501, Accuracy: 98.17%, Time Passed: 8.16m
Epoch 113, Batch 300, Loss: 0.0500, Accuracy: 98.15%, Time Passed: 12.35m
Epoch 113, Batch 400, Loss: 0.0500, Accuracy: 98.10%, Time Passed: 16.60m
Epoch 113, Batch 500, Loss: 0.0492, Accuracy: 98.10%, Time Passed: 20.79m
Epoch 113 Completed - Average Loss: 0.0488, Accuracy: 98.12%, Epoch Time: 22.64m
Training Complete Epoch 113 - Total Time: 22.64m

✅ Epoch 113 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5723, Accuracy: 84.69%, Time Passed: 4.44m
Evaluation Complete - Loss: 0.5617, Accuracy: 86.08%, Total Time: 7.49m

📊 Epoch 113 - Evaluation Completed.


🚀 Epoch 114 - Training Started...

Epoch 114, Batch 100, Loss: 0.0546, Accuracy: 97.88%, Time Passed: 4.16m
Epoch 114, Batch 200, Loss: 0.0512, Accuracy: 98.00%, Time Passed: 8.48m
Epoch 114, Batch 300, Loss: 0.0505, Accuracy: 98.03%, Time Passed: 12.61m
Epoch 114, Batch 400, Loss: 0.0521, Accuracy: 98.05%, Time Passed: 16.86m
Epoch 114, Batch 500, Loss: 0.0508, Accuracy: 98.04%, Time Passed: 20.97m
Epoch 114 Completed - Average Loss: 0.0495, Accuracy: 98.11%, Epoch Time: 22.73m
Training Complete Epoch 114 - Total Time: 22.73m

✅ Epoch 114 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5872, Accuracy: 84.44%, Time Passed: 4.38m
Evaluation Complete - Loss: 0.5700, Accuracy: 86.21%, Total Time: 7.46m

📊 Epoch 114 - Evaluation Completed.


🚀 Epoch 115 - Training Started...

Epoch 115, Batch 100, Loss: 0.0447, Accuracy: 98.16%, Time Passed: 4.06m
Epoch 115, Batch 200, Loss: 0.0411, Accuracy: 98.27%, Time Passed: 8.28m
Epoch 115, Batch 300, Loss: 0.0425, Accuracy: 98.16%, Time Passed: 12.58m
Epoch 115, Batch 400, Loss: 0.0436, Accuracy: 98.12%, Time Passed: 16.81m
Epoch 115, Batch 500, Loss: 0.0425, Accuracy: 98.21%, Time Passed: 21.06m
Epoch 115 Completed - Average Loss: 0.0421, Accuracy: 98.24%, Epoch Time: 22.90m
Training Complete Epoch 115 - Total Time: 22.90m

✅ Epoch 115 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5934, Accuracy: 84.34%, Time Passed: 4.51m
Evaluation Complete - Loss: 0.5707, Accuracy: 86.04%, Total Time: 7.64m

📊 Epoch 115 - Evaluation Completed.

In [283]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [284]:
del training_states

In [285]:
start_epoch = 116
end_epoch = 118
start_epoch, end_epoch

(116, 118)

In [286]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageE, train_loader, val_loader, new_combined_criterion, stageE_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageE',
                                                          save_dir = 'mobilenetv2', class_weights='new_combined', log_interval=100)

🚀 Epoch 116 - Training Started...

Epoch 116, Batch 100, Loss: 0.0390, Accuracy: 98.59%, Time Passed: 3.82m
Epoch 116, Batch 200, Loss: 0.0428, Accuracy: 98.50%, Time Passed: 7.49m
Epoch 116, Batch 300, Loss: 0.0443, Accuracy: 98.38%, Time Passed: 11.22m
Epoch 116, Batch 400, Loss: 0.0428, Accuracy: 98.30%, Time Passed: 15.00m
Epoch 116, Batch 500, Loss: 0.0441, Accuracy: 98.23%, Time Passed: 18.74m
Epoch 116 Completed - Average Loss: 0.0448, Accuracy: 98.22%, Epoch Time: 20.27m
Training Complete Epoch 116 - Total Time: 20.27m

✅ Epoch 116 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5864, Accuracy: 84.09%, Time Passed: 4.13m
Evaluation Complete - Loss: 0.5572, Accuracy: 85.92%, Total Time: 6.98m

📊 Epoch 116 - Evaluation Completed.


🚀 Epoch 117 - Training Started...

Epoch 117, Batch 100, Loss: 0.0432, Accuracy: 98.31%, Time Passed: 3.93m
Epoch 117, Batch 200, Loss: 0.0412, Accuracy: 98.41%, Time Passed: 7.97m
Epoch 117, Batch 300, Loss: 0.0419, Accuracy: 98.44%, Time Passed: 12.00m
Epoch 117, Batch 400, Loss: 0.0404, Accuracy: 98.53%, Time Passed: 16.27m
Epoch 117, Batch 500, Loss: 0.0413, Accuracy: 98.46%, Time Passed: 20.33m
Epoch 117 Completed - Average Loss: 0.0408, Accuracy: 98.46%, Epoch Time: 22.04m
Training Complete Epoch 117 - Total Time: 22.04m

✅ Epoch 117 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5898, Accuracy: 84.25%, Time Passed: 4.37m
Evaluation Complete - Loss: 0.5644, Accuracy: 86.06%, Total Time: 7.37m

📊 Epoch 117 - Evaluation Completed.


🚀 Epoch 118 - Training Started...

Epoch 118, Batch 100, Loss: 0.0418, Accuracy: 98.06%, Time Passed: 3.93m
Epoch 118, Batch 200, Loss: 0.0407, Accuracy: 98.31%, Time Passed: 7.85m
Epoch 118, Batch 300, Loss: 0.0388, Accuracy: 98.35%, Time Passed: 11.92m
Epoch 118, Batch 400, Loss: 0.0410, Accuracy: 98.27%, Time Passed: 16.00m
Epoch 118, Batch 500, Loss: 0.0410, Accuracy: 98.28%, Time Passed: 20.26m
Epoch 118 Completed - Average Loss: 0.0409, Accuracy: 98.31%, Epoch Time: 22.11m
Training Complete Epoch 118 - Total Time: 22.11m

✅ Epoch 118 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6251, Accuracy: 83.78%, Time Passed: 4.34m
Evaluation Complete - Loss: 0.5850, Accuracy: 85.63%, Total Time: 7.38m

📊 Epoch 118 - Evaluation Completed.

In [287]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')

In [288]:
del training_states

In [290]:
start_epoch = 119
end_epoch = 120
start_epoch, end_epoch

(119, 120)

In [291]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageE, train_loader, val_loader, new_combined_criterion, stageE_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageE',
                                                          save_dir = 'mobilenetv2', class_weights='new_combined', log_interval=100)

🚀 Epoch 119 - Training Started...

Epoch 119, Batch 100, Loss: 0.0315, Accuracy: 98.75%, Time Passed: 3.71m
Epoch 119, Batch 200, Loss: 0.0360, Accuracy: 98.55%, Time Passed: 7.61m
Epoch 119, Batch 300, Loss: 0.0370, Accuracy: 98.46%, Time Passed: 11.45m
Epoch 119, Batch 400, Loss: 0.0389, Accuracy: 98.44%, Time Passed: 15.33m
Epoch 119, Batch 500, Loss: 0.0392, Accuracy: 98.39%, Time Passed: 19.43m
Epoch 119 Completed - Average Loss: 0.0391, Accuracy: 98.41%, Epoch Time: 21.10m
Training Complete Epoch 119 - Total Time: 21.10m

✅ Epoch 119 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5764, Accuracy: 84.97%, Time Passed: 4.33m
Evaluation Complete - Loss: 0.5543, Accuracy: 86.37%, Total Time: 7.30m

📊 Epoch 119 - Evaluation Completed.


🚀 Epoch 120 - Training Started...

Epoch 120, Batch 100, Loss: 0.0328, Accuracy: 98.50%, Time Passed: 4.09m
Epoch 120, Batch 200, Loss: 0.0338, Accuracy: 98.50%, Time Passed: 8.43m
Epoch 120, Batch 300, Loss: 0.0368, Accuracy: 98.41%, Time Passed: 13.08m
Epoch 120, Batch 400, Loss: 0.0385, Accuracy: 98.37%, Time Passed: 17.64m
Epoch 120, Batch 500, Loss: 0.0383, Accuracy: 98.44%, Time Passed: 22.32m
Epoch 120 Completed - Average Loss: 0.0390, Accuracy: 98.42%, Epoch Time: 24.38m
Training Complete Epoch 120 - Total Time: 24.38m

✅ Epoch 120 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5871, Accuracy: 84.34%, Time Passed: 4.81m
Evaluation Complete - Loss: 0.5681, Accuracy: 85.94%, Total Time: 8.08m

📊 Epoch 120 - Evaluation Completed.

In [ ]:
if training_states:
    joblib.dump(
        training_states,
        'mobilenetv2/training_states_119_120.pkl'
    )

### **121-130 & Strong Recall-Weighted Combination (Amplified Inverse Recall + Inverse Frequency, 5 : 1/5 Ratio)**

In [108]:
state, generator = setup_reproducibility(start_fresh=True, seed=seeds[0])

✅ Random seed set to 42 (MPS available: True)

In [102]:
df = pd.read_csv("mobilenetv2/mobilenetv2_stageE_val_results119_120.csv")
df = df[(df['Epoch'] == 120) & (df['Species'] != 'Average Performance (Macro)')]

In [103]:
# Compute from recall values
recall_penalty_weights = (1 - df['Recall'].values) * 100

# Convert to tensor
recall_penalty_weights = torch.tensor(recall_penalty_weights, dtype=torch.float32)

# Move to MPS (Apple GPU) if available, otherwise CPU
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
recall_penalty_weights = recall_penalty_weights.to(device)

In [104]:
recall_penalty_weights

tensor([ 2.6316, 20.7071, 11.7438,  4.9383, 21.1268, 12.5000,  5.7471,  0.0000,
         0.0000, 19.1176,  6.3725, 10.7843, 46.4865, 10.8527, 10.5882, 11.6505,
         0.0000, 25.8427, 27.8571, 20.0637,  3.8153,  0.0000,  0.0000,  0.9524,
         0.0000,  0.0000, 35.0000, 43.1138,  1.7241,  3.0651,  7.7320,  1.7544,
         3.0000], device='mps:0')

In [105]:
inverse_frequency_weights = compute_class_weights(train_dataset, method="inverse_frequency", normalize=False)
inverse_frequency_criterion = nn.CrossEntropyLoss(weight=inverse_frequency_weights)
inverse_frequency_weights

tensor([ 58.0736,  20.0740,  18.1442,  65.2782,  33.7165,  47.1848,  84.7024,
        111.3077, 117.3243,  41.8410,  23.6567,  20.1907,  41.4415,  30.4098,
         25.8393,  25.7626, 157.8545,  56.5603,  16.1827,  24.6648,  12.4384,
        204.2823,  51.0706,  42.6634,  44.4092,  40.7606,  16.1676,  53.7585,
         38.0789,  19.7768,  25.9940,  85.9604,  43.4100], device='mps:0')

In [106]:
# Normalize both to z-score
norm_inv_freq = (inverse_frequency_weights - inverse_frequency_weights.mean()) / inverse_frequency_weights.std()
norm_recall_penalty = (recall_penalty_weights - recall_penalty_weights.mean()) / recall_penalty_weights.std()

# Combine and shift
new_combined_weights = (norm_inv_freq/5) + (5*norm_recall_penalty)
new_combined_weights = new_combined_weights - new_combined_weights.min() + 1.0
new_combined_weights

tensor([ 2.1151,  9.0385,  5.5079,  3.0552,  9.2674,  5.9412,  3.4641,  1.3310,
         1.3592,  8.5161,  3.4234,  5.1405, 19.2671,  5.2153,  5.0900,  5.5069,
         1.5493, 11.2274, 11.8294,  8.8072,  2.3661,  1.7672,  1.0484,  1.3831,
         1.0171,  1.0000, 14.6356, 17.9998,  1.6648,  2.1058,  3.9685,  1.9013,
         2.1911], device='mps:0')

In [107]:
new_combined_criterion = nn.CrossEntropyLoss(weight=new_combined_weights)

In [118]:
training_states = joblib.load(f'mobilenetv2/training_states_{119}_{120}.pkl')

In [119]:
mobilenetv2_stageE = models.mobilenet_v2(weights=None, num_classes=len(train_dataset.classes))

# Send it to device
device = torch.device("mps")
mobilenetv2_stageE.to(device)
mobilenetv2_stageE.load_state_dict(training_states[120]["model_state_dict"])

In [120]:
mobilenetv2_stageE = configure_mobilenetv2_training(
                                                    mobilenetv2_stageE,
                                                    NUM_CLASSES, final_stage=True,
                                                    prev_unfrozen = 0
                                                   )
    
df_summary = summarize_mobilenetv2_blocks(mobilenetv2_stageE)
df_summary

🟢 Final stage → Entire backbone unfrozen (blocks [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])
✅ Trainable layers: 158/158 (100.00%)
✅ Trainable params: 2,266,145/2,266,145 (100.00%)

,Block,Order,Module,Layers (#),Params (#),Trainable Params (#),% Layers (Model),% Params (Model),% Trainable Params (Model),Cumulative Layers (Model),Cumulative % Layers (Model),Cumulative Params (Model),Cumulative % Params (Model),Layers (Module %),Params (Module %),Trainable Params (Module %),Cumulative Layers (Module),Cumulative % Layers (Module),Cumulative Params (Module),Cumulative % Params (Module)
0,Conv2dNormActivation_1,1,features,3,928,928,1.898734,0.040951,0.040951,158,100.000000,2266145,100.000000,1.923077,0.041729,0.041729,156,100.000000,2223872,100.000000
1,InvertedResidual_2,2,features,6,896,896,3.797468,0.039539,0.039539,155,98.101266,2265217,99.959049,3.846154,0.040290,0.040290,153,98.076923,2222944,99.958271
2,InvertedResidual_3,3,features,9,5136,5136,5.696203,0.226640,0.226640,149,94.303797,2264321,99.919511,5.769231,0.230949,0.230949,147,94.230769,2222048,99.917981
3,InvertedResidual_4,4,features,9,8832,8832,5.696203,0.389737,0.389737,140,88.607595,2259185,99.692870,5.769231,0.397145,0.397145,138,88.461538,2216912,99.687032
4,InvertedResidual_5,5,features,9,10000,10000,5.696203,0.441278,0.441278,131,82.911392,2250353,99.303134,5.769231,0.449666,0.449666,129,82.692308,2208080,99.289887
5,InvertedResidual_6,6,features,9,14848,14848,5.696203,0.655210,0.655210,122,77.215190,2240353,98.861856,5.769231,0.667664,0.667664,120,76.923077,2198080,98.840221
6,InvertedResidual_7,7,features,9,14848,14848,5.696203,0.655210,0.655210,113,71.518987,2225505,98.206646,5.769231,0.667664,0.667664,111,71.153846,2183232,98.172557
7,InvertedResidual_8,8,features,9,21056,21056,5.696203,0.929155,0.929155,104,65.822785,2210657,97.551436,5.769231,0.946817,0.946817,102,65.384615,2168384,97.504892
8,InvertedResidual_9,9,features,9,54272,54272,5.696203,2.394904,2.394904,95,60.126582,2189601,96.622281,5.769231,2.440428,2.440428,93,59.615385,2147328,96.558075
9,InvertedResidual_10,10,features,9,54272,54272,5.696203,2.394904,2.394904,86,54.430380,2135329,94.227377,5.769231,2.440428,2.440428,84,53.846154,2093056,94.117647
10,InvertedResidual_11,11,features,9,54272,54272,5.696203,2.394904,2.394904,77,48.734177,2081057,91.832473,5.769231,2.440428,2.440428,75,48.076923,2038784,91.677219
11,InvertedResidual_12,12,features,9,66624,66624,5.696203,2.939971,2.939971,68,43.037975,2026785,89.437569,5.769231,2.995856,2.995856,66,42.307692,1984512,89.236791
12,InvertedResidual_13,13,features,9,118272,118272,5.696203,5.219084,5.219084,59,37.341772,1960161,86.497598,5.769231,5.318292,5.318292,57,36.538462,1917888,86.240935
13,InvertedResidual_14,14,features,9,118272,118272,5.696203,5.219084,5.219084,50,31.645570,1841889,81.278515,5.769231,5.318292,5.318292,48,30.769231,1799616,80.922643
14,InvertedResidual_15,15,features,9,155264,155264,5.696203,6.851459,6.851459,41,25.949367,1723617,76.059431,5.769231,6.981697,6.981697,39,25.000000,1681344,75.604351
15,InvertedResidual_16,16,features,9,320000,320000,5.696203,14.120897,14.120897,32,20.253165,1568353,69.207972,5.769231,14.389317,14.389317,30,19.230769,1526080,68.622655
16,InvertedResidual_17,17,features,9,320000,320000,5.696203,14.120897,14.120897,23,14.556962,1248353,55.087075,5.769231,14.389317,14.389317,21,13.461538,1206080,54.233337
17,InvertedResidual_18,18,features,9,473920,473920,5.696203,20.913048,20.913048,14,8.860759,928353,40.966178,5.769231,21.310579,21.310579,12,7.692308,886080,39.844020
18,Conv2dNormActivation_19,19,features,3,412160,412160,1.898734,18.187715,18.187715,5,3.164557,454433,20.053130,1.923077,18.533441,18.533441,3,1.923077,412160,18.533441
19,Sequential,20,classifier,2,42273,42273,1.265823,1.865415,1.865415,2,1.265823,42273,1.865415,100.000000,100.000000,100.000000,2,100.000000,42273,100.000000

In [121]:
stageE_optimizer = torch.optim.AdamW(
    mobilenetv2_stageE.parameters(),
    lr=1e-5,    # even smaller LR, since more params unfrozen
    weight_decay=1e-4,
    betas=(0.9, 0.999)
)

In [122]:
start_epoch = 121
end_epoch = 130
start_epoch, end_epoch

(121, 130)

In [123]:
training_states, training_logs = train_and_evaluate_model(mobilenetv2_stageE, train_loader, val_loader, new_combined_criterion, stageE_optimizer,
                                                          train_dataset.classes, start_epoch, end_epoch, model_name = 'mobilenetv2_stageE',
                                                          save_dir = 'mobilenetv2', class_weights='new_combined', log_interval=100)

🚀 Epoch 121 - Training Started...

Epoch 121, Batch 100, Loss: 0.0362, Accuracy: 98.41%, Time Passed: 4.29m
Epoch 121, Batch 200, Loss: 0.0354, Accuracy: 98.55%, Time Passed: 8.33m
Epoch 121, Batch 300, Loss: 0.0350, Accuracy: 98.50%, Time Passed: 12.34m
Epoch 121, Batch 400, Loss: 0.0359, Accuracy: 98.45%, Time Passed: 16.53m
Epoch 121, Batch 500, Loss: 0.0378, Accuracy: 98.41%, Time Passed: 20.88m
Epoch 121 Completed - Average Loss: 0.0378, Accuracy: 98.41%, Epoch Time: 22.72m
Training Complete Epoch 121 - Total Time: 22.72m

✅ Epoch 121 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6025, Accuracy: 84.62%, Time Passed: 4.66m
Evaluation Complete - Loss: 0.5854, Accuracy: 85.92%, Total Time: 7.75m

📊 Epoch 121 - Evaluation Completed.


🚀 Epoch 122 - Training Started...

Epoch 122, Batch 100, Loss: 0.0394, Accuracy: 98.34%, Time Passed: 4.26m
Epoch 122, Batch 200, Loss: 0.0411, Accuracy: 98.38%, Time Passed: 8.62m
Epoch 122, Batch 300, Loss: 0.0390, Accuracy: 98.32%, Time Passed: 13.29m
Epoch 122, Batch 400, Loss: 0.0373, Accuracy: 98.40%, Time Passed: 17.87m
Epoch 122, Batch 500, Loss: 0.0372, Accuracy: 98.41%, Time Passed: 22.28m
Epoch 122 Completed - Average Loss: 0.0376, Accuracy: 98.34%, Epoch Time: 23.99m
Training Complete Epoch 122 - Total Time: 23.99m

✅ Epoch 122 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5716, Accuracy: 85.06%, Time Passed: 4.42m
Evaluation Complete - Loss: 0.5684, Accuracy: 86.35%, Total Time: 7.43m

📊 Epoch 122 - Evaluation Completed.


🚀 Epoch 123 - Training Started...

Epoch 123, Batch 100, Loss: 0.0371, Accuracy: 98.25%, Time Passed: 4.16m
Epoch 123, Batch 200, Loss: 0.0346, Accuracy: 98.53%, Time Passed: 8.43m
Epoch 123, Batch 300, Loss: 0.0348, Accuracy: 98.47%, Time Passed: 12.77m
Epoch 123, Batch 400, Loss: 0.0363, Accuracy: 98.41%, Time Passed: 17.02m
Epoch 123, Batch 500, Loss: 0.0355, Accuracy: 98.46%, Time Passed: 21.23m
Epoch 123 Completed - Average Loss: 0.0352, Accuracy: 98.46%, Epoch Time: 23.03m
Training Complete Epoch 123 - Total Time: 23.03m

✅ Epoch 123 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5924, Accuracy: 84.88%, Time Passed: 4.39m
Evaluation Complete - Loss: 0.5965, Accuracy: 85.90%, Total Time: 7.43m

📊 Epoch 123 - Evaluation Completed.


🚀 Epoch 124 - Training Started...

Epoch 124, Batch 100, Loss: 0.0329, Accuracy: 98.66%, Time Passed: 4.10m
Epoch 124, Batch 200, Loss: 0.0328, Accuracy: 98.47%, Time Passed: 8.11m
Epoch 124, Batch 300, Loss: 0.0379, Accuracy: 98.34%, Time Passed: 12.25m
Epoch 124, Batch 400, Loss: 0.0372, Accuracy: 98.38%, Time Passed: 16.44m
Epoch 124, Batch 500, Loss: 0.0360, Accuracy: 98.42%, Time Passed: 20.51m
Epoch 124 Completed - Average Loss: 0.0358, Accuracy: 98.45%, Epoch Time: 22.19m
Training Complete Epoch 124 - Total Time: 22.19m

✅ Epoch 124 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5770, Accuracy: 84.84%, Time Passed: 4.36m
Evaluation Complete - Loss: 0.5698, Accuracy: 86.19%, Total Time: 7.35m

📊 Epoch 124 - Evaluation Completed.


🚀 Epoch 125 - Training Started...

Epoch 125, Batch 100, Loss: 0.0369, Accuracy: 98.28%, Time Passed: 4.02m
Epoch 125, Batch 200, Loss: 0.0350, Accuracy: 98.39%, Time Passed: 8.03m
Epoch 125, Batch 300, Loss: 0.0353, Accuracy: 98.43%, Time Passed: 12.53m
Epoch 125, Batch 400, Loss: 0.0391, Accuracy: 98.33%, Time Passed: 16.70m
Epoch 125, Batch 500, Loss: 0.0384, Accuracy: 98.39%, Time Passed: 20.69m
Epoch 125 Completed - Average Loss: 0.0381, Accuracy: 98.37%, Epoch Time: 22.36m
Training Complete Epoch 125 - Total Time: 22.36m

✅ Epoch 125 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5452, Accuracy: 85.81%, Time Passed: 4.33m
Evaluation Complete - Loss: 0.5484, Accuracy: 86.71%, Total Time: 7.30m

📊 Epoch 125 - Evaluation Completed.


🚀 Epoch 126 - Training Started...

Epoch 126, Batch 100, Loss: 0.0354, Accuracy: 98.53%, Time Passed: 4.00m
Epoch 126, Batch 200, Loss: 0.0374, Accuracy: 98.48%, Time Passed: 8.12m
Epoch 126, Batch 300, Loss: 0.0385, Accuracy: 98.46%, Time Passed: 12.28m
Epoch 126, Batch 400, Loss: 0.0403, Accuracy: 98.41%, Time Passed: 16.37m
Epoch 126, Batch 500, Loss: 0.0395, Accuracy: 98.41%, Time Passed: 20.44m
Epoch 126 Completed - Average Loss: 0.0395, Accuracy: 98.37%, Epoch Time: 22.22m
Training Complete Epoch 126 - Total Time: 22.22m

✅ Epoch 126 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.6178, Accuracy: 83.75%, Time Passed: 4.40m
Evaluation Complete - Loss: 0.6241, Accuracy: 85.17%, Total Time: 7.43m

📊 Epoch 126 - Evaluation Completed.


🚀 Epoch 127 - Training Started...

Epoch 127, Batch 100, Loss: 0.0389, Accuracy: 98.03%, Time Passed: 4.17m
Epoch 127, Batch 200, Loss: 0.0358, Accuracy: 98.27%, Time Passed: 8.16m
Epoch 127, Batch 300, Loss: 0.0347, Accuracy: 98.41%, Time Passed: 12.30m
Epoch 127, Batch 400, Loss: 0.0357, Accuracy: 98.39%, Time Passed: 16.35m
Epoch 127, Batch 500, Loss: 0.0373, Accuracy: 98.39%, Time Passed: 20.39m
Epoch 127 Completed - Average Loss: 0.0364, Accuracy: 98.42%, Epoch Time: 22.21m
Training Complete Epoch 127 - Total Time: 22.21m

✅ Epoch 127 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5782, Accuracy: 85.41%, Time Passed: 4.52m
Evaluation Complete - Loss: 0.5763, Accuracy: 86.42%, Total Time: 7.60m

📊 Epoch 127 - Evaluation Completed.


🚀 Epoch 128 - Training Started...

Epoch 128, Batch 100, Loss: 0.0402, Accuracy: 98.41%, Time Passed: 5.40m
Epoch 128, Batch 200, Loss: 0.0367, Accuracy: 98.39%, Time Passed: 10.71m
Epoch 128, Batch 300, Loss: 0.0356, Accuracy: 98.38%, Time Passed: 15.96m
Epoch 128, Batch 400, Loss: 0.0357, Accuracy: 98.42%, Time Passed: 21.41m
Epoch 128, Batch 500, Loss: 0.0340, Accuracy: 98.53%, Time Passed: 26.82m
Epoch 128 Completed - Average Loss: 0.0345, Accuracy: 98.51%, Epoch Time: 29.07m
Training Complete Epoch 128 - Total Time: 29.07m

✅ Epoch 128 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5895, Accuracy: 84.88%, Time Passed: 5.20m
Evaluation Complete - Loss: 0.6005, Accuracy: 86.00%, Total Time: 8.59m

📊 Epoch 128 - Evaluation Completed.


🚀 Epoch 129 - Training Started...

Epoch 129, Batch 100, Loss: 0.0391, Accuracy: 98.53%, Time Passed: 5.23m
Epoch 129, Batch 200, Loss: 0.0326, Accuracy: 98.75%, Time Passed: 10.73m
Epoch 129, Batch 300, Loss: 0.0351, Accuracy: 98.65%, Time Passed: 16.29m
Epoch 129, Batch 400, Loss: 0.0361, Accuracy: 98.59%, Time Passed: 21.77m
Epoch 129, Batch 500, Loss: 0.0369, Accuracy: 98.49%, Time Passed: 27.30m
Epoch 129 Completed - Average Loss: 0.0368, Accuracy: 98.50%, Epoch Time: 29.46m
Training Complete Epoch 129 - Total Time: 29.46m

✅ Epoch 129 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5705, Accuracy: 85.47%, Time Passed: 4.88m
Evaluation Complete - Loss: 0.5671, Accuracy: 86.44%, Total Time: 8.10m

📊 Epoch 129 - Evaluation Completed.


🚀 Epoch 130 - Training Started...

Epoch 130, Batch 100, Loss: 0.0343, Accuracy: 98.47%, Time Passed: 5.33m
Epoch 130, Batch 200, Loss: 0.0341, Accuracy: 98.48%, Time Passed: 10.86m
Epoch 130, Batch 300, Loss: 0.0347, Accuracy: 98.53%, Time Passed: 16.60m
Epoch 130, Batch 400, Loss: 0.0336, Accuracy: 98.59%, Time Passed: 22.64m
Epoch 130, Batch 500, Loss: 0.0327, Accuracy: 98.61%, Time Passed: 28.23m
Epoch 130 Completed - Average Loss: 0.0328, Accuracy: 98.59%, Epoch Time: 30.48m
Training Complete Epoch 130 - Total Time: 30.48m

✅ Epoch 130 - Training Completed. Starting Evaluation...

Batch 100, Loss: 0.5544, Accuracy: 85.94%, Time Passed: 4.83m
Evaluation Complete - Loss: 0.5803, Accuracy: 86.52%, Total Time: 8.11m

📊 Epoch 130 - Evaluation Completed.

In [124]:
if training_states:
    joblib.dump(training_states, f'mobilenetv2/training_states_{start_epoch}_{end_epoch}.pkl')